# -*- coding: utf-8 -*-
"""B1 inceleme, parti 1 (w01900–w02100): Türkçe karşılık düzeltmeleri.

{id: (beklenen_mevcut_tr, yeni_tr)} — mevcut Türkçe beklenenle birebir
aynı değilse satıra dokunulmaz (kimlik kayması ya da araya giren bir
düzenleme varsa veriyi bozmamak için).
"""

FIXES = {
    # Yanlış ya da yanıltıcı
    'w01940': ('mavi', 'açık mavi'),  # голубой; "mavi" синий
    'w02017': ('kızarmış ekmek (tost)', 'kadeh kaldırma (konuşma) / kızarmış ekmek'),
    'w02022': ('çek', 'fiş / çek'),
    'w01949': ('ceket', 'mont / ceket'),
    'w01910': ('top', 'top (silah)'),
    'w01902': ('gıpta etmek', 'kıskanmak / imrenmek'),
    'w02079': ('göçmek', 'taşınmak / (karşıya) geçmek'),
    'w02093': ('kokmak', 'pis kokmak'),
    'w02071': ('ılık', 'sıcak / ılık'),
    'w02046': ('enli', 'geniş / enli'),
    'w02081': ('hastane', '(askeri) hastane'),
    'w02044': ('gezi', 'doğa yürüyüşü / kamp / sefer'),
    'w01994': ('bayır turpu', 'yaban turpu / (argo) lanet'),
    # Eski / resmi / az bilinen
    'w01967': ('ibare', 'cümle / söz / ifade'),
    'w02054': ('mutabakat', 'onay / rıza / uzlaşma'),
    'w01980': ('müsaade etmek', 'izin vermek / çözmek (sorun)'),
    'w02074': ('fantazi', 'hayal gücü / fantezi'),
    'w02043': ('hiç bir yerde', 'hiçbir yerde'),
    # Ana anlamı eksik
    'w01901': ('mobil', 'mobil / cep (telefonu)'),
    'w01906': ('alçak', 'alçak / şerefsiz (argo)'),
    'w01913': ('varlık', 'varlık / varoluş'),
    'w01914': ('koğuş (hastane)', 'koğuş / (hastane) odası / meclis'),
    'w01916': ('silmek', 'silmek / çıkarmak / uzaklaştırmak'),
    'w01917': ('hayran', 'hayran / taraftar'),
    'w01918': ('tanışıklık', 'tanışma / tanışıklık'),
    'w01919': ('birlik', 'birlik / ittifak'),
    'w01922': ('kir', 'kir / çamur / pislik'),
    'w01923': ('gereksiz', 'fazla / gereksiz'),
    'w01926': ('içinden', 'içinden / arasından'),
    'w01928': ('acemi', 'acemi / yeni gelen / çaylak'),
    'w01931': ('tartışmak', 'tartışmak / iddiaya girmek'),
    'w01933': ('hisse senedi', 'hisse / kampanya (indirim) / eylem'),
    'w01934': ('çakmak (çivi), gol atmak (futbol)', 'çakmak (çivi) / gol atmak / tıkamak'),
    'w01937': ('numara', 'numara / hile / gösteri'),
    'w01942': ('sonuç', 'sonuç / hüküm / hapis'),
    'w01944': ('döndürmek', 'dönmek / döndürmek / çevirmek'),
    'w01945': ('gezinti', 'yürüyüş / gezinti'),
    'w01950': ('gizli sevgili', 'sevgili / gizli sevgili'),
    'w01951': ('dönemeç', 'dönüş / viraj / dönüm noktası'),
    'w01955': ('teşekkür', 'minnettarlık / teşekkür'),
    'w01969': ('çiğ', 'çiğ / nemli / rutubetli'),
    'w01970': ('bırakmak', 'bırakmak / serbest bırakmak / salmak'),
    'w01971': ('toplama', 'toplama / toplanma / ücret (harç)'),
    'w01972': ('yöneltmek', 'yöneltmek / göndermek / yönlendirmek'),
    'w01974': ('sıkı', 'sıkı / katı / sert'),
    'w01975': ('yazı tahtası', 'tahta / yazı tahtası / pano'),
    'w01977': ('tedirginlik', 'endişe / kaygı / rahatsızlık'),
    'w01979': ('yaz', 'yaz (yaza ait) / yazlık'),
    'w01981': ('başka', 'diğer / başka'),
    'w01990': ('dış', 'dış / harici'),
    'w01992': ('bitirmek', 'öldürmek / işini bitirmek'),
    'w01995': ('basit', 'basit / sade / kolay'),
    'w02000': ('giymek', 'giymek / takmak'),
    'w02002': ('zayıflık', 'zayıflık / halsizlik'),
    'w02005': ('arızalanmak', 'kırılmak / bozulmak / arızalanmak'),
    'w02007': ('araştırmak', 'soruşturmak / araştırmak'),
    'w02012': ('yemek tarifi', 'tarif / reçete'),
    'w02013': ('parlak', 'parlak / harika'),
    'w02018': ('takım', 'takım / set / alım (kayıt)'),
    'w02024': ('gezmek', '(araçla) gezmek / kaymak (kayak, paten) / binmek'),
    'w02026': ('sığınak', 'sığınak / sığınma (iltica)'),
    'w02027': ('şık', 'şık / lüks / harika'),
    'w02030': ('kurtuluş', 'kurtuluş / serbest bırakma / özgürleşme'),
    'w02031': ('başlatmak', 'çalıştırmak (motor) / edinmek (arkadaş, hayvan) / başlatmak'),
    'w02036': ('utanç', 'utanç / rezalet'),
    'w02037': ('görüş', 'görüş / vizyon'),
    'w02038': ('bozmak', 'bozmak / mahvetmek'),
    'w02045': ('beceriksiz', 'sakar / beceriksiz / tuhaf (durum)'),
    'w02049': ('utanmak', 'utanmak / çekinmek'),
    'w02060': ('korumak', 'korumak / saklamak / kaydetmek'),
    'w02061': ('çırpınmak', 'dövüşmek / çarpmak (kalp) / çırpınmak / uğraşmak'),
    'w02066': ('alıcı', 'alıcı / müşteri'),
    'w02067': ('düğün', 'düğüne ait / düğün'),
    'w02068': ('ilk olarak', 'önce / ilk olarak'),
    'w02069': ('değişiklik', 'değişiklik / teneffüs'),
    'w02070': ('paylaşmak', 'paylaşmak / bölünmek'),
    'w02075': ('depozito', 'depozito / rehin / kefalet'),
    'w02076': ('et', 'ten / beden / et'),
    'w02080': ('şefkatli', 'şefkatli / yumuşak / narin'),
    'w02082': ('almak', 'elinden almak / (sayı) çıkarmak'),
    'w02090': ('doruk', 'zirve / doruk / tepe'),
    'w02092': ('güven', 'güven / emin olma'),
    'w02096': ('karşısında', 'karşısında / aksine'),
    'w02099': ('yönetim', 'yönetim / kılavuz'),
}
