# -*- coding: utf-8 -*-
"""B1 inceleme, parti 10 (w03725–w03899) — son parti."""

FIXES = {
    # Yanlış / yanıltıcı
    'w03816': ('terapist', 'dahiliyeci / pratisyen hekim / terapist'),  # терапевт önce iç hastalıkları doktoru
    'w03768': ('ilgeç', 'bahane / edat'),
    'w03763': ('düşünceli', 'endişeli / kaygılı'),
    'w03837': ('demlik', 'çaydanlık / su ısıtıcısı / (argo) acemi'),
    'w03865': ('kalkmak', 'iptal edilmek'),
    'w03752': ('tılsım', 'maskot / uğur (tılsım)'),
    'w03843': ('direk', 'doğrudan / içten (samimi)'),
    'w03891': ('bacı', 'kız kardeş (küçük)'),
    'w03874': ('hiç bir yerden', 'hiçbir yerden'),
    'w03757': ('döşek', 'yatak (şilte) / döşek'),
    # Eski / resmi
    'w03760': ('esin vermek', 'ilham vermek'),
    'w03795': ('enteresan', 'sürükleyici / ilginç'),
    'w03853': ('olağandışılık', 'anormallik / anomali'),
    'w03851': ('sıkıca, derin (uykuda)', 'sıkıca / derin (uyku) / sert (içki)'),
    'w03888': ('para, mangır (argo)', 'para / mangır (argo)'),
    'w03879': ('şevk', 'heves / coşku / şevk'),
    # Ana anlamı eksik
    'w03727': ('birim', 'birim / bir (rakam) / en düşük not'),
    'w03728': ('hayret', 'şaşkınlık / hayret'),
    'w03729': ('rahat', 'rahat / sıcacık (ev gibi)'),
    'w03736': ('huy', 'huy / mizaç'),
    'w03738': ('musluk', 'musluk / vinç'),
    'w03739': ('nefes almak', '(nefes) içine çekmek / ilham vermek'),
    'w03743': ('nine', 'nine / yaşlı kadın'),
    'w03746': ('dal', 'dal / (metro) hat'),
    'w03747': ('yetişmek', 'yetişmek / zamanında yapabilmek'),
    'w03748': ('kurtarmak', '(zor durumdan) kurtarmak / (para) kazanmak'),
    'w03749': ('bulunan şey', 'buluntu / keşif'),
    'w03750': ('parça', 'kırık parça / kıymık / şarapnel'),
    'w03758': ('yorum', 'yorum / geri bildirim / referans'),
    'w03775': ('şarkı', 'kısa şarkı / tekerleme'),
    'w03776': ('ince tabaka', 'film (fotoğraf) / ince tabaka / streç film'),
    'w03779': ('memur', '(devlet) memuru / bürokrat'),
    'w03780': ('doruk noktası', 'en hararetli an / tam ortası'),
    'w03784': ('merhamet', 'şefkat / merhamet'),
    'w03785': ('enkaz', '(tren) kazası / batma / çöküş'),
    'w03791': ('muayene etmek', 'gözden geçirmek / muayene etmek / gezmek (görmek)'),
    'w03794': ('orkestra şefi', 'maestro / usta'),
    'w03798': ('ateşli', 'yanan / ateşli'),
    'w03802': ('halk', 'halk (sıfat) / halka ait'),
    'w03806': ('hububat', 'tane / tahıl / çekirdek'),
    'w03811': ('afet', 'felaket / afet'),
    'w03813': ('organize', 'düzenli / organize'),
    'w03814': ('damat', 'damat / enişte'),
    'w03822': ('oturmak', 'oturmak (ikamet) / yaşamak'),
    'w03823': ('su', 'su (sıfat) / sulu'),
    'w03827': ('itiş', 'itiş / sarsıntı (deprem) / ivme'),
    'w03830': ('tahmin etmek', 'fal bakmak / tahmin etmek'),
    'w03833': ('asgari', 'en düşük / asgari'),
    'w03838': ('doğru', 'dürüst / doğru'),
    'w03855': ('ayyaş', 'ayyaş / sarhoş'),
    'w03856': ('iddia', 'iddia / onay (onaylanma)'),
    'w03859': ('sindirmek', 'korkutmak / sindirmek'),
    'w03860': ('artırmak', 'artırmak / yükseltmek / terfi ettirmek'),
    'w03866': ('sürpriz', 'sürpriz / beklenmedik durum'),
    'w03869': ('geçerli', 'geçerli / faal / görevdeki'),
    'w03871': ('acıklı', 'trajik / acıklı'),
    'w03876': ('hava atmak', 'hava atmak / (kendine soru) sormak'),
    'w03878': ('karargâh', 'genel merkez / karargâh'),
    'w03880': ('sallanmak', 'sallanmak / (boş boş) dolaşmak'),
    'w03881': ('fırtına', 'gök gürültülü fırtına'),
    'w03887': ('arzu', 'istek / çaba / arzu'),
    'w03889': ('vahşi', 'vahşi (insan) / yabani'),
    'w03898': ('silmek', '(çizerek) silmek / listeden çıkarmak'),
    'w03899': ('ilkbahar', 'bahar (sıfat) / ilkbahar'),
}
