# -*- coding: utf-8 -*-
"""B1 inceleme, parti 6 (w02912–w03115)."""

FIXES = {
    # Yanlış / yanıltıcı
    'w03022': ('sürüngen', 'alçak / pislik (argo) / sürüngen'),
    'w02947': ('kodaman büyük', 'kozalak / şişlik / (argo) kodaman'),
    'w03006': ('soğan', 'soğan / yay (silah)'),
    'w03027': ('ceviz', 'ceviz / fındık / kuruyemiş'),
    'w03053': ('kaynaşmak', 'arkadaş olmak'),
    'w03087': ('kaynaşmak', 'bir araya gelmek / uyuşmak / anlaşmak'),
    'w02934': ('artist', 'sanatçı / oyuncu'),
    'w02963': ('müstakil', 'bağımsız / kendi başına'),
    'w03080': ('canice', 'suç (sıfat) / suç teşkil eden'),
    'w03108': ('psikolojik', 'ruhsal / zihinsel'),
    'w02932': ('afganistan', 'Afganistan'),
    # Eski / resmi / jargon
    'w03019': ('lahza', 'an'),
    'w03112': ('konjektür', 'tahmin / sezgi'),
    'w03037': ('baştanbaşa', 'tamamen / bütünüyle'),
    'w03039': ('anahtar niteliğinde', 'kilit / anahtar (önemli)'),
    'w03071': ('sanrı', 'halüsinasyon / sanrı'),
    'w02986': ('gereksinim', 'ihtiyaç / gereksinim'),
    'w03082': ('azami', 'en yüksek / maksimum / azami'),
    'w02959': ('eser, çarpım (matematikte)', 'eser / çarpım (matematik)'),
    'w02985': ('parfüm, ruhlar (manevi varlık)', 'parfüm / ruhlar'),
    'w03007': ('er (asker), sıradan', 'er (asker) / sıradan'),
    # Ana anlamı eksik
    'w02912': ('onarım', 'onarım / yeniden inşa / iyileşme'),
    'w02915': ('dönme', 'dönüş / gidişat / ciro'),
    'w02917': ('pati', 'pati / pençe'),
    'w02918': ('incinmek', 'gücenmek / darılmak'),
    'w02919': ('engel', 'engel / parazit (sinyal)'),
    'w02920': ('tırmanmak', 'tırmanmak / (içeri) girmek'),
    'w02923': ('girişmek', 'başlamak / girişmek'),
    'w02924': ('sınır', 'sınır / eşik / yüz (kenar)'),
    'w02925': ('toplamak', 'toplamak / (numara) çevirmek / (kilo) almak'),
    'w02935': ('ok', 'ok (işaret) / ibre'),
    'w02936': ('hizmet', 'servis / hizmet / bakım'),
    'w02937': ('kap kacak', 'bulaşık / kap kacak'),
    'w02939': ('utandırmak', 'utandırmak / kafasını karıştırmak'),
    'w02941': ('izleme', 'izleme / görüntülenme / inceleme'),
    'w02943': ('sermek', 'ortaya koymak / anlatmak / paylaşmak (internete)'),
    'w02949': ('seçkin', 'seçkin / olağanüstü'),
    'w02951': ('gösterim', 'gösterim / defile / gösteri'),
    'w02953': ('ambalaj', 'ambalaj / paket'),
    'w02956': ('görüşme', 'tartışma / görüşme / müzakere'),
    'w02957': ('sızmak', 'sızmak / gizlice girmek'),
    'w02961': ('gaddarlık', 'gaddarlık / zulüm / şiddet'),
    'w02962': ('gar', 'gar / istasyon'),
    'w02966': ('kazanmak', 'fethetmek / kazanmak'),
    'w02970': ('karmaşa', 'karmaşa / dağınıklık / rezalet'),
    'w02978': ('gürültü etmek', 'gürültü yapmak / ses çıkarmak'),
    'w02980': ('başlangıç', 'başlangıç / start / kalkış'),
    'w02981': ('bölge', 'bölge / arazi'),
    'w02988': ('tam olarak', 'tam / tam olarak'),
    'w02994': ('dışarı çıkarmak', 'dışarı çıkarmak / (sonuç) çıkarmak / (leke) çıkarmak'),
    'w03003': ('çağ', 'çağ / dönem'),
    'w03005': ('yağmurluk', 'yağmurluk / pelerin / trençkot'),
    'w03009': ('çarpmak', 'çarpmak (bir yere)'),
    'w03011': ('don', 'külot / don / şort'),
    'w03017': ('ofis', 'büro / ofis'),
    'w03021': ('sürü', 'sürü (kuş, kurt)'),
    'w03024': ('grafik', 'program (takvim) / grafik'),
    'w03028': ('kale', 'kale / sağlamlık / (içki) derecesi'),
    'w03030': ('çengel', 'kanca / çengel / (olta) iğnesi'),
    'w03033': ('not', 'yorum / uyarı / azar'),
    'w03040': ('verici', 'bağışçı / verici (kan, organ)'),
    'w03041': ('büyükbaş hayvan', 'çiftlik hayvanları / sığır'),
    'w03048': ('başarmak', 'başarmak / becermek'),
    'w03049': ('taşımak', 'taşımak / ertelemek / dayanmak'),
    'w03051': ('kaygılandırmak', 'endişelendirmek / umurunda olmak'),
    'w03059': ('ciyaklamak', 'ciyaklamak / bip bip etmek'),
    'w03060': ('kol', 'kol (giysi) / (nehir) kolu'),
    'w03061': ('gerçi', 'gerçi / zaten / bununla birlikte'),
    'w03064': ('otopark', 'otopark / durak / kamp yeri'),
    'w03065': ('yetiştirmek', 'yetiştirmek / eğitmek (terbiye)'),
    'w03070': ('mısra', 'şiir / dize'),
    'w03072': ('üflemek', 'üflemek / esmek (rüzgâr)'),
    'w03086': ('kabuk', '(ağaç) kabuk / (yer) kabuğu'),
    'w03105': ('ayarlamak', 'ayarlamak / akort etmek'),
    'w03106': ('sıkıcı kişi', 'sıkıcı / mızmız (kişi)'),
    'w03109': ('lider', 'lider / önder / reis (kabile)'),
}
