# -*- coding: utf-8 -*-
"""B1 inceleme, parti 3 (w02305–w02505)."""

FIXES = {
    # Yanlış / yanıltıcı
    'w02465': ('yılan', 'uçurtma / ejderha (masal)'),  # змей; yılan змея (w02496)
    'w02497': ('senet', 'yükümlülük / taahhüt'),
    'w02483': ('tek', 'eşsiz / benzersiz'),
    'w02421': ('elmas', 'pırlanta / elmas'),
    'w02397': ('akıl doktoru', 'psikiyatrist'),
    'w02504': ('susamak', 'çok istemek / özlemini çekmek'),
    'w02423': ('isabetsiz', 'başarısız / kötü / talihsiz'),
    'w02469': ('kara yolu', 'otoyol / ana yol'),
    # Eski / resmi
    'w02348': ('zan', 'tahmin / varsayım'),
    'w02384': ('celse', 'oturum / toplantı'),
    'w02420': ('aheste aheste', 'yavaşça / yavaş yavaş'),
    'w02367': ('salıvermek', 'serbest bırakmak / üretmek / yayımlamak'),
    'w02425': ('hayırlı, iyi (yüce anlamda)', 'hayırlı / iyi'),
    'w02464': ('içindekiler/kompozisyon', 'bileşim / içindekiler / kadro'),
    'w02435': ('karargah', 'karargâh / merkez'),
    'w02392': ('güzergah', 'güzergâh / rota'),
    # Ana anlamı eksik
    'w02308': ('maden ocağı', 'maden ocağı / (asansör) boşluğu'),
    'w02309': ('olmak', 'olmak / yapılmak'),
    'w02315': ('işe yaramak', 'işe yaramak / uygun olmak'),
    'w02316': ('enstitü', 'enstitü / üniversite'),
    'w02320': ('içermek', 'içermek / geçindirmek / bulundurmak'),
    'w02326': ('direniş', 'direniş / direnç'),
    'w02327': ('bagaj bölümü', 'bagaj (araba)'),
    'w02329': ('onarım', 'tamir / onarım / tadilat'),
    'w02330': ('ortadan kalkma', 'kaybolma / yok olma'),
    'w02332': ('denemek', 'denemek / yaşamak (duygu) / test etmek'),
    'w02334': ('iletişim', 'iletişim / sohbet'),
    'w02335': ('etrafından dolaşmak', 'etrafından dolaşmak / geçmek / atlatmak'),
    'w02338': ('geri vermek', 'geri vermek / geri getirmek / döndürmek'),
    'w02341': ('giyim', 'kıyafet / (askeri) görev'),
    'w02343': ('böbrek', 'böbrek / tomurcuk'),
    'w02344': ('öge', 'öge / element'),
    'w02356': ('tüy', 'tüy / kalem ucu'),
    'w02362': ('uzağa', 'uzağa / defol!'),
    'w02370': ('düşünmek', 'iyice düşünmek'),
    'w02373': ('değnek', 'sopa / değnek / çubuk'),
    'w02376': ('kare', 'kare (film) / kadro (personel)'),
    'w02377': ('ders', 'ders (üniversite) / konferans'),
    'w02382': ('kınamak', 'kınamak / yargılamak / mahkûm etmek'),
    'w02383': ('düz', 'düz / düzgün / eşit'),
    'w02389': ('tanıklık', 'belge / kanıt / tanıklık'),
    'w02390': ('önemli', 'önemli / büyük (miktar) / kayda değer'),
    'w02391': ('yıldırım', 'şimşek / yıldırım / fermuar'),
    'w02395': ('şerit', 'şerit / çizgi / (uçuş) pisti'),
    'w02406': ('hayati', 'hayat (sıfat) / hayati'),
    'w02407': ('tatil', '(okul) tatili'),
    'w02411': ('battaniye', 'yorgan / battaniye'),
    'w02414': ('vurmak', 'vurmak / (kapıyı) çalmak / ispiyonlamak'),
    'w02417': ('atama', 'atama / amaç / kullanım'),
    'w02424': ('çıkıntı yapmak', 'dışarı çıkmak / dikilip durmak / (argo) takılmak'),
    'w02427': ('kaya', 'kayalık / uçurum / kaya'),
    'w02428': ('ambalaj', 'ambalaj / kap'),
    'w02433': ('kopma', 'kopma / ayrılık / patlama'),
    'w02436': ('bırakmak', 'bırakmak / durdurmak / kesmek'),
    'w02442': ('beslenme', 'beslenme / gıda'),
    'w02443': ('fişek', 'fişek / duy (ampul) / patron'),
    'w02445': ('gövde (ağaç)', 'gövde (ağaç) / namlu'),
    'w02447': ('yatırmak', 'yatırmak (para) / (içine) koymak'),
    'w02449': ('kamu', 'halka açık / kamu'),
    'w02451': ('ateş', 'sıcak / ateş (hastalık) / kor'),
    'w02452': ('meydan', 'meydan / alan (yüzölçümü)'),
    'w02477': ('temsil', 'oyun (tiyatro) / gösteri'),
    'w02481': ('kesim', 'sektör / kesim / bölge'),
    'w02482': ('gösterme', 'talimat / belirtme / işaret'),
    'w02485': ('somut', 'somut / belirli'),
    'w02488': ('oluşturmak', 'oluşturmak / hazırlamak (liste, belge) / (miktar) tutmak'),
    'w02490': ('bağımlılık', 'bağımlılık / (bir şeye) bağlılık'),
    'w02502': ('teslim etmek', 'teslim etmek / (sınav) vermek / kiraya vermek'),
}

DROP = {
    'w02458': 'Вашингтон',  # şehir adı, kart olarak bir şey öğretmiyor
}
