# -*- coding: utf-8 -*-
"""B1 inceleme, parti 5 (w02710–w02911)."""

FIXES = {
    # Yanlış / yanıltıcı / yazım
    'w02811': ('kar', 'kâr / çıkar / fayda'),  # "kar" kar yağışı gibi okunuyor
    'w02731': ('kelebek', 'kelebek / papyon'),  # örnek cümle papyon
    'w02763': ('tekniker', 'teknisyen'),
    'w02808': ('sorgulanamaz', 'şüphesiz / kesin'),
    'w02757': ('sağ', 'sağ / haklı'),
    'w02715': ('klân', 'klan'),
    'w02894': ('ünvan', 'unvan / rütbe'),
    'w02888': ('irak', 'Irak'),
    'w02826': ('avro', 'euro / avro'),
    # Eski / resmi
    'w02742': ('biçare', 'zavallı'),
    'w02884': ('hıyanet', 'ihanet'),
    'w02786': ('alamet', 'işaret / batıl inanç / eşkal'),
    'w02867': ('muhafaza', 'saklama / depolama'),
    'w02834': ('kriminalist', 'adli uzman / kriminolog'),
    'w02882': ('yol ile ilgili', 'yol (sıfat) / trafik'),
    'w02779': ('tortu, berbat (argo)', 'berbat (argo) / tortu'),
    'w02737': ('sağlamak, göstermek (etki)', '(yardım, destek) sağlamak / (etki) göstermek'),
    'w02805': ('paylaşmak, katılmak (bir görüşe)', 'paylaşmak / (görüşe) katılmak / ayırmak'),
    # Ana anlamı eksik
    'w02712': ('gündüzün', 'gündüz / gün içinde'),
    'w02714': ('hükümdar', 'efendi / hükümdar'),
    'w02716': ('esrarengiz', 'gizemli / esrarengiz'),
    'w02719': ('kur yapmak', 'bakmak (bakımını yapmak) / kur yapmak'),
    'w02722': ('araya girmek', 'araya girmek / müdahale etmek'),
    'w02726': ('klasör', 'dosya / klasör'),
    'w02729': ('toprak', 'toprak / zemin'),
    'w02730': ('keskin', 'keskin / sert / ani'),
    'w02736': ('susuzluk', 'susuzluk / tutku (özlem)'),
    'w02738': ('kimlik belgesi', 'belge / kimlik (kartı)'),
    'w02739': ('bulunmamak', 'bulunmamak / yok olmak'),
    'w02745': ('bölmek', 'bölmek / paylaşmak / ayırmak'),
    'w02746': ('birader', 'küçük kardeş / birader'),
    'w02752': ('olay örgüsü', 'konu / olay örgüsü'),
    'w02753': ('kesmek', 'yarıda kesmek / bölmek'),
    'w02754': ('nakliye', 'ulaşım / taşıt / nakliye'),
    'w02761': ('elektrik', 'elektrikli / elektrik'),
    'w02762': ('delikanlı', 'genç (erkek) / delikanlı'),
    'w02771': ('yeğen', 'yeğen (kız)'),
    'w02773': ('bora', 'fırtına / bora'),
    'w02774': ('gelme', 'geliş / varış'),
    'w02778': ('sonuç', 'sonuç / soruşturma'),
    'w02789': ('açmaz', 'çıkmaz (sokak) / açmaz'),
    'w02790': ('bağlı kalmak', 'uymak / korumak / bağlı kalmak'),
    'w02794': ('iç karartıcı', 'kasvetli / karanlık / iç karartıcı'),
    'w02795': ('ilahi', 'ilahi / enfes'),
    'w02797': ('moda', 'moda / modaya uygun / şık'),
    'w02800': ('tahrip', 'yıkım / tahrip'),
    'w02806': ('iyilik', 'iyilik / fayda / nimet'),
    'w02809': ('esrarengiz', 'gizemli / esrarengiz'),
    'w02814': ('yüce', 'yüksek / yüce'),
    'w02815': ('post', 'deri / post'),
    'w02819': ('çevirmek', 'çevirmek (tercüme) / aktarmak / (para) göndermek'),
    'w02822': ('ambar', 'kulübe / ambar'),
    'w02824': ('kucaklama', 'kucaklama / sarılma'),
    'w02825': ('dükkân', 'dükkân / bank (oturak)'),
    'w02829': ('göz', 'göz (şiirsel)'),
    'w02833': ('surat', 'surat / (hayvan) yüzü'),
    'w02836': ('fazlasıyla', 'aşırı / fazlasıyla'),
    'w02838': ('rapor', 'rapor / sunum / bildiri'),
    'w02839': ('vefakâr', 'sadık / vefakâr'),
    'w02852': ('kurt', 'solucan / kurt'),
    'w02853': ('stabil', 'istikrarlı / stabil'),
    'w02855': ('düzeltme', 'düzeltme / değişiklik (yasa) / iyileşme'),
    'w02857': ('böcek', 'böcek (kın kanatlı)'),
    'w02863': ('başlatma', 'başlatma / fırlatma (roket)'),
    'w02886': ('titiz', 'titiz / özenli'),
    'w02892': ('jeton', 'jeton / (argo) özellik, olay'),
    'w02901': ('bakış açısı', 'gelecek (olasılık) / bakış açısı / perspektif'),
    'w02904': ('dürüst olmayan', 'dürüst olmayan / haksız'),
    'w02908': ('pratik', 'uygulama / pratik / staj'),
    'w02911': ('aklamak', 'aklamak / haklı çıkarmak'),
}

# мука: anlamı ve örneği "un" (мука́), ama vurgu "му́ка" (eziyet) diye
# yazılmış; kartta yanlış hece vurgulu çıkıyordu.
FIELDS = {
    'w02869': {'accented': ('му́ка', 'мука́'), 'translit': ('MU-ka', 'mu-KA')},
}
