# -*- coding: utf-8 -*-
"""B1 inceleme, parti 4 (w02506–w02709)."""

FIXES = {
    # Yanlış / yanıltıcı / dil bilgisi
    'w02614': ('dalaveracı', 'dolandırıcı'),
    'w02627': ('dizüstü bilgisayarı', 'dizüstü bilgisayar'),
    'w02606': ('acımak', '(birinin) üzüntüsünü paylaşmak / acımak'),
    'w02652': ('aynı zamanda olan', 'eş zamanlı'),
    'w02698': ('al', 'kırmızı / al'),
    'w02553': ('mars', 'Mars'),
    'w02666': ('garson', 'garson (kadın)'),
    'w02644': ('oturma yeri', 'koltuk / oturak'),
    'w02551': ('yaya', 'yürüyerek / yaya'),
    # Eski / resmi
    'w02576': ('itidal', 'sakinlik / huzur'),
    'w02593': ('safha', 'aşama / etap'),
    'w02630': ('cangıl', 'tropik orman / cangıl'),
    'w02685': ('cemaat', 'topluluk / cemiyet'),
    'w02618': ('icra', 'yerine getirme / icra'),
    'w02628': ('düzen, dizi (askeri saf)', 'düzen (rejim) / sıra (askeri)'),
    'w02669': ('harfi harfine', 'kelimesi kelimesine / resmen'),
    'w02649': ('canlı biçimde', 'canlı / çabuk'),
    # Ana anlamı eksik
    'w02507': ('trafik sıkışıklığı', 'mantar (tıpa) / trafik sıkışıklığı'),
    'w02509': ('gerilim', 'gerilim / voltaj / gerginlik'),
    'w02511': ('ev', 'konut / ev / barınacak yer'),
    'w02512': ('üretmek', 'üretmek / (etki) bırakmak / yapmak'),
    'w02515': ('kemer', 'kemer / kuşak / bel'),
    'w02517': ('gösterim', 'seans / gösterim'),
    'w02518': ('hizmetçi', 'oda görevlisi / hizmetçi'),
    'w02519': ('başarmak', 'elde etmeye çalışmak / peşinde olmak / başarmak'),
    'w02524': ('bitim', 'bitiş / son / (dil bilgisi) çekim eki'),
    'w02526': ('savunucu', 'savunucu / savunma avukatı / defans oyuncusu'),
    'w02529': ('kütle', 'kütle / çok sayıda / kitle'),
    'w02530': ('metres', 'sevgili (kadın) / metres'),
    'w02531': ('amatör', 'meraklı / sever / amatör'),
    'w02532': ('varış', 'geliş / varış / gelir'),
    'w02539': ('güvenmek', 'güvenmek / (-mesi) gerekmek'),
    'w02544': ('kesin', 'kesin / son / nihai'),
    'w02545': ('yüzmek', 'yüzmek / (gemiyle) gitmek / süzülmek'),
    'w02548': ('bozukluk', 'bozukluk / üzüntü'),
    'w02552': ('patika', 'yol / patika / pist'),
    'w02558': ('tel', 'kablo / tel'),
    'w02560': ('saklanmak', 'saklanmak / gözden kaybolmak / kaçmak'),
    'w02561': ('meyve', 'meyve / ürün (sonuç) / cenin'),
    'w02566': ('ceza', 'ceza (hukuku) / cezai'),
    'w02567': ('girmek', 'girmek / tırmanmak / sığmak'),
    'w02568': ('doğrulama', 'onay / doğrulama'),
    'w02570': ('mülk', 'gayrimenkul / emlak'),
    'w02574': ('vesayet', 'vesayet / himaye / bakım'),
    'w02583': ('millet', 'ulus / millet'),
    'w02584': ('ilişkilendirmek', 'bağlamak / ilişkilendirmek'),
    'w02585': ('yıkmak', 'yıkmak / tahrip etmek / mahvetmek'),
    'w02591': ('getirmek', 'teslim etmek / götürmek / (sıkıntı, zevk) vermek'),
    'w02594': ('ganimet', 'av / ganimet / (maden) çıkarma'),
    'w02595': ('yığın', 'küçük yığın / bir avuç (insan)'),
    'w02596': ('sihirbaz', 'büyücü / sihirbaz'),
    'w02598': ('sızlanmak', 'sızlanmak / (ağrı) sızlamak'),
    'w02599': ('memleket', 'vatan / memleket'),
    'w02603': ('çarpışmak', 'çarpışmak / (sorunla) karşılaşmak'),
    'w02609': ('araştırmak', 'araştırmak / incelemek'),
    'w02610': ('hafifleme', 'rahatlama / kolaylaştırma'),
    'w02613': ('sürekli', 'kesintisiz / tamamen'),
    'w02615': ('betimlemek', 'tasvir etmek / canlandırmak / taklit etmek'),
    'w02616': ('taşınmak', '(evden) taşınmak / kaymak / aşağı inmek'),
    'w02621': ('temizlemek', 'temizlemek / fırçalamak / soymak'),
    'w02637': ('mal', 'mal / mülk / eşya'),
    'w02638': ('bulmak', 'kazanmak / edinmek / bulmak'),
    'w02639': ('alet', 'cihaz / alet / (sofra) takımı'),
    'w02648': ('son', 'yakın zamandaki / son'),
    'w02650': ('erişilebilir', 'erişilebilir / uygun (fiyat) / anlaşılır'),
    'w02660': ('kesmek', 'kesip çıkarmak / oymak / kesmek'),
    'w02662': ('ödül', 'ödül / prim / ikramiye'),
    'w02665': ('ballı', 'ballı / bal (sıfat)'),
    'w02667': ('uymak', 'uymak / itaat etmek'),
    'w02668': ('atıcı', 'nişancı / atıcı'),
    'w02670': ('kesmek', 'sözünü kesmek / yarıda kesmek / bölmek'),
    'w02673': ('gezi', 'gezi / tur (rehberli)'),
    'w02682': ('tabii', 'tabii ki / doğal olarak'),
    'w02690': ('değer', 'fiyat / maliyet / değer'),
    'w02693': ('morartı', 'morluk / çürük'),
    'w02694': ('uyluk', 'kalça / uyluk'),
    'w02703': ('bağlılık', 'sadakat / bağlılık'),
    'w02704': ('hitap', 'hitap / başvuru / davranış'),
}
