# -*- coding: utf-8 -*-
"""B1 inceleme, parti 7 (w03116–w03317)."""

FIXES = {
    # Yanlış / yanıltıcı
    'w03198': ('röportaj', 'haber (yerinden) / canlı yayın'),  # röportaj = интервью
    'w03225': ('kalem', 'kurşun kalem'),
    'w03212': ('ciklet', 'sakız'),
    'w03136': ('değerini bilmemek', 'küçümsemek / hafife almak'),
    'w03293': ('tekerlekli sandalye', 'bebek arabası / tekerlekli sandalye'),
    'w03248': ('dost', 'cana yakın / dostça'),
    'w03260': ('araklamak', 'aşırmak / çalmak / çekip indirmek'),
    'w03151': ('moron', 'aptal / geri zekâlı (argo)'),
    'w03251': ('hristiyan', 'Hristiyan'),
    'w03298': ('koca', 'eş (erkek) / koca'),
    # Eski / resmi
    'w03201': ('kurtulmalık', 'fidye'),
    'w03206': ('azletmek', 'işten çıkarmak / kovmak'),
    'w03256': ('muhasip', 'muhasebeci'),
    'w03227': ('yazın', 'edebiyat / literatür'),
    'w03289': ('biçem', 'tarz / üslup / tavır'),
    'w03126': ('berduş', 'serseri / evsiz / berduş'),
    'w03150': ('surat (argo), yılancık', 'surat (argo) / yılancık (hastalık)'),
    'w03140': ('sergilemek, öne sürmek (aday için)', 'sergilemek / dışarı koymak / (aday) göstermek'),
    'w03186': ('taşımak, götürüp getirmek (araçla)', '(araçla) götürmek / taşımak'),
    'w03239': ('ezmek, dövmek (havanda)', '(havanda) dövmek / ezmek'),
    # Ana anlamı eksik
    'w03116': ('dönmek', 'dönmek / döndürmek / çevirmek'),
    'w03119': ('ikna', 'inanç (kanaat) / ikna'),
    'w03120': ('havalanmak', 'havalanmak / kalkmak (uçak)'),
    'w03122': ('uygunluk', 'uygunluk / uyum'),
    'w03124': ('memur', 'çalışan / memur'),
    'w03127': ('dinmek', 'durmak / bırakmak / dinmek'),
    'w03128': ('alay', 'ironi / alay'),
    'w03132': ('kazançlı', 'kârlı / avantajlı / kazançlı'),
    'w03133': ('karmaşıklık', 'zorluk / karmaşıklık'),
    'w03134': ('fark etmek', 'seçmek (görmek) / fark etmek'),
    'w03138': ('akıtmak', 'dökmek / akıtmak'),
    'w03141': ('dul', 'dul (kadın)'),
    'w03149': ('kurmak', 'kurmak / yerleştirmek / belirlemek'),
    'w03153': ('görünmek', 'ortaya çıkmak / çıkagelmek'),
    'w03154': ('deşarj', 'derece (kategori) / boşalma (elektrik)'),
    'w03156': ('sert', 'sert / katı'),
    'w03157': ('örtmek', 'örtmek / kaplamak / (masraf) karşılamak'),
    'w03164': ('araştırma', 'öğrenme / inceleme / araştırma'),
    'w03168': ('düzenli', 'düzenli / özenli / dikkatli'),
    'w03171': ('büyü', 'büyü / sihir'),
    'w03172': ('iki kişi', 'ikisi birlikte / baş başa'),
    'w03175': ('belirtmek', 'kutlamak / belirtmek / işaretlemek'),
    'w03177': ('kap', 'kap / damar (kan)'),
    'w03192': ('hayvan', '(çiftlik) hayvanı / (argo) hayvan herif'),
    'w03193': ('kusursuzluk', 'mükemmellik / kusursuzluk'),
    'w03194': ('katkı', 'katkı / (banka) mevduat'),
    'w03196': ('cinsel', 'cinsel / cinsiyete ait'),
    'w03199': ('etkili', 'etkili / nüfuzlu'),
    'w03203': ('kanun', 'kanun / kurallar bütünü'),
    'w03207': ('güzel koku', 'koku / aroma'),
    'w03208': ('etraf', 'çevre (insanlar) / kuşatma'),
    'w03217': ('lavabo', 'lavabo / deniz kabuğu'),
    'w03219': ('ayarlamak', 'yoluna koymak / (ilişki) kurmak / tamir etmek'),
    'w03224': ('takıma ait', 'takım (sıfat) / komuta (sıfat)'),
    'w03226': ('ilerlemek', 'gelişmek / ilerlemek'),
    'w03228': ('yararsız', 'boşuna / yersiz'),
    'w03229': ('dar', 'dar / sıkışık / yakın (ilişki)'),
    'w03230': ('asalak', 'parazit / asalak'),
    'w03232': ('panayır', 'fuar / panayır'),
    'w03235': ('algılamak', 'algılamak / karşılamak'),
    'w03238': ('geçiş', 'geçiş / (yaya) geçidi'),
    'w03244': ('takım', 'takım (askeri) / müfreze'),
    'w03253': ('kazanmak', 'satın almak / edinmek / kazanmak'),
    'w03258': ('heyecan', 'heyecan / endişe / dalgalanma (deniz)'),
    'w03263': ('tugay', 'ekip / tugay'),
    'w03266': ('oynamak', 'oynamak / (şaka) yapmak / çekiliş yapmak'),
    'w03267': ('tezgah', 'tezgâh / bar / (danışma) masası'),
    'w03269': ('oditoryum', 'dinleyiciler / derslik / oditoryum'),
    'w03270': ('merhum', 'ölmüş / merhum'),
    'w03275': ('ölçme', 'ölçüm / boyut'),
    'w03276': ('eşmek', 'eşelemek / karıştırmak / oyalanmak'),
    'w03279': ('dağılmak', 'dağılmak / ayrılmak / (fikir) ayrışmak'),
    'w03281': ('yetiştirme', 'terbiye / yetiştirme / eğitim'),
    'w03282': ('uygulama', 'uygulama / kullanım'),
    'w03284': ('öğretmen', 'öğretmen / öğretim görevlisi'),
    'w03285': ('indirmek', 'indirmek / (tetiği) çekmek / (su) boşaltmak'),
    'w03295': ('kurulum', 'kurulum / düzenek / tutum (bakış)'),
    'w03302': ('öğrenci', 'öğrenci (kız)'),
    'w03304': ('âlem', 'krallık / saltanat / âlem'),
    'w03305': ('betimlemek', 'anlatmak / tarif etmek / betimlemek'),
    'w03306': ('girişmek', '(işe) girişmek / (elle) tutmak / üstlenmek'),
    'w03307': ('örtmek', 'örtmek / kaplamak / (masraf) karşılamak'),
    'w03309': ('ahşap', 'ahşap / tahta'),
    'w03313': ('uzmanlık', 'bilirkişi incelemesi / ekspertiz'),
    'w03315': ('huy', 'yaradılış / doğa / huy'),
    'w03317': ('ağız', 'ağız (hayvan)'),
}
