# -*- coding: utf-8 -*-
"""B1 inceleme, parti 9 (w03521–w03724)."""

FIXES = {
    # Yanlış / yanıltıcı
    'w03608': ('cirit', 'mızrak'),
    'w03611': ('edepsiz külhanbey', 'serseri / kabadayı / holigan'),
    'w03615': ('ah', 'iç çekme / nefes'),
    'w03668': ('lazımlık', 'saksı / çömlek / lazımlık'),
    'w03682': ('azdırmak', 'uyandırmak (ilgi) / heyecanlandırmak / tahrik etmek'),
    'w03701': ('seksiyon', 'bölüm / kulüp (spor)'),
    'w03689': ('kâbiliyetli', 'becerikli / usta'),
    'w03715': ('parça', 'parça (müzik) / pist'),
    'w03543': ('hiddet', 'öfke / kuduz (hastalık)'),
    'w03582': ('indirim', 'indirimli satış / ucuzluk'),
    'w03676': ('genç', 'ergen / gençlik (sıfat)'),
    # Eski / resmi
    'w03522': ('aldırmaz', 'kayıtsız / umursamaz'),
    'w03706': ('sefer', 'keşif gezisi / sefer'),
    'w03669': ('(tuhaf şeyler) yapmak, çıkarmak', '(tuhaf şeyler) yapmak / marifet yapmak'),
    'w03636': ('çarpmak (araçla), düşürmek', '(araçla) çarpmak / düşürmek / (köpük) çırpmak'),
    'w03535': ('global', 'küresel / global'),
    'w03685': ('inisiyatif', 'girişim / inisiyatif'),
    # Ana anlamı eksik
    'w03524': ('kuruluş', 'kurum / kuruluş'),
    'w03525': ('sıçramak', 'zıplamak / dört nala koşmak'),
    'w03526': ('sıcak', 'sıcak hava / sıcaklık'),
    'w03529': ('topuk', 'topuk (ayakkabı)'),
    'w03530': ('kınamak', 'mahkûm etmek / kınamak'),
    'w03539': ('buluş', 'icat / buluş'),
    'w03541': ('kuşatmak', 'çevrelemek / kuşatmak'),
    'w03542': ('ocak (fırın)', 'ocak / levha (taş)'),
    'w03544': ('gazi', 'gazi / emektar (tecrübeli)'),
    'w03548': ('incinmek', 'gücenmek / darılmak'),
    'w03549': ('denge', 'denge / bakiye'),
    'w03552': ('düşünmek', 'düşünüp taşınmak / kafa yormak'),
    'w03555': ('kabul etme', 'kabul / benimseme / (karar) alma'),
    'w03556': ('hasret', 'hüzün / özlem / can sıkıntısı'),
    'w03557': ('devir', 'döngü / devir / seri'),
    'w03558': ('dürtü', 'dürtü / (sinir) uyarısı / itici güç'),
    'w03561': ('nüsha', 'nüsha / örnek (tek parça)'),
    'w03564': ('azaltma', 'azaltma / kısaltma / (işten) çıkarma'),
    'w03566': ('yoğun', 'yoğun / sık / kalın / doyurucu (yemek)'),
    'w03572': ('yönetmek', 'başında olmak / yönetmek'),
    'w03577': ('sütlü', 'süt (sıfat) / sütlü'),
    'w03587': ('boğulmak', 'nefesi kesilmek / (havasızlıktan) boğulmak'),
    'w03591': ('uzaklık', 'mesafe / parkur'),
    'w03596': ('mal olmak', 'mal olmak / (-sız) idare etmek / davranmak'),
    'w03599': ('taraftar', 'destekçi / taraftar'),
    'w03609': ('lapa', 'lapa (tahıl) / karmaşa (argo)'),
    'w03614': ('içten', 'içten / samimi / ruhsal'),
    'w03617': ('atamak', 'atamak / (ilaç) vermek / (tarih) belirlemek'),
    'w03620': ('düz', 'pürüzsüz / düz'),
    'w03632': ('ödül', 'ödül / ücret'),
    'w03633': ('sancı (doğum)', 'çatışma / dövüş / sancı (doğum)'),
    'w03641': ('tartışma', 'tartışma / anlaşmazlık / iddia (bahis)'),
    'w03642': ('lakap', 'lakap / (hayvan) adı'),
    'w03643': ('kurtarıcı', 'kurtarma görevlisi / cankurtaran'),
    'w03644': ('kaldıraç', 'kol / manivela / kaldıraç'),
    'w03646': ('bağırmak', 'bağırmak / çığlık atmak'),
    'w03648': ('bileşik', 'bileşik / bağlantı / birleşme'),
    'w03649': ('değer biçmek', 'değerlendirmek / değer biçmek'),
    'w03659': ('ladin', 'ladin / çam (Noel ağacı)'),
    'w03660': ('oynamak', '(oyun) oynamak / şaka yapmak / çekilişle vermek'),
    'w03661': ('ganimet', 'ganimet / ödül (kupa)'),
    'w03662': ('sızdırmak', 'dökmek (boşaltmak) / (bilgi) sızdırmak'),
    'w03663': ('ilgilenmek', 'merak salmak / ilgilenmek / kapılmak'),
    'w03665': ('katı', 'sert / katı / kararlı'),
    'w03666': ('nefes almak', '(temiz) hava almak / nefes almak'),
    'w03674': ('madde', 'madde / kumaş'),
    'w03679': ('kiracı', 'kiracı / sakin (oturan)'),
    'w03681': ('kazanmak', 'edinmek / (cesaret) toplamak / (argo) sarhoş olmak'),
    'w03696': ('üstelik', 'üstelik / (при чём) ne alakası var'),
    'w03699': ('hesap', 'hesap / hesaplama / (hesap) ödeme'),
    'w03707': ('direk', 'direk / sütun'),
    'w03719': ('kesin', 'kararlı / kesin'),
    'w03721': ('aile', 'aile / familya (biyoloji)'),
    'w03723': ('denemek', '(giysi) denemek / prova etmek'),
}
