# -*- coding: utf-8 -*-
"""B1 inceleme, parti 8 (w03318–w03520)."""

FIXES = {
    # Yanlış / yanıltıcı
    'w03477': ('fragman', 'parça / bölüm (alıntı)'),  # Türkçede fragman = tanıtım filmi
    'w03319': ('daire', 'kulüp (kurs) / küçük daire'),
    'w03353': ('batarya', 'kalorifer peteği / batarya'),
    'w03355': ('ortaklık', 'dernek / birlik / çağrışım'),
    'w03330': ('sahte', 'yalancı / yalan'),
    'w03331': ('andırmak', 'benzemek / (biraz) dolaşmak'),
    'w03398': ('araklamak', '(araç) çalmak / (uçak) kaçırmak'),
    'w03440': ('dost', 'dostça / arkadaşça'),
    'w03446': ('deli', 'delisi (bir şeyin) / kafayı takmış'),
    'w03382': ('vietnam', 'Vietnam'),
    'w03502': ('kapamak', 'kapatmak'),
    'w03490': ('bıkkınlık', 'can sıkıntısı'),
    'w03458': ('dişi kedi', 'pisi / kedicik'),
    # Eski / resmi
    'w03374': ('istiklal', 'bağımsızlık'),
    'w03387': ('ülkü', 'ideal / ülkü'),
    'w03397': ('tazmin', 'tazminat / telafi'),
    'w03454': ('icra', 'yapma / düzenleme / gerçekleştirme'),
    'w03324': ('madenî', 'metal / metalik'),
    'w03392': ('yakarmak', 'yalvarmak / yakarmak'),
    'w03474': ('şahıs', 'kişi / şahıs'),
    'w03464': ('sömestr', 'dönem (yarıyıl) / sömestr'),
    'w03386': ('ateş (hastalık), telaş', 'ateş (hastalık) / telaş'),
    'w03481': ('nota (müzik/diplomatik)', 'nota (müzik) / nota (diplomatik)'),
    # Ana anlamı eksik
    'w03320': ('anne', 'anne (günlük dil) / teyze (hitap)'),
    'w03321': ('sargı', 'sargı / bandaj'),
    'w03325': ('hasat', 'hasat / ürün (mahsul)'),
    'w03329': ('sataşmak', 'kızdırmak / takılmak / sataşmak'),
    'w03333': ('uzaklaştırmak', 'uzaklaştırmak / görevden almak'),
    'w03337': ('fısıldamak', 'ipucu vermek / hatırlatmak / fısıldamak'),
    'w03338': ('malikane', 'malikâne / arazi'),
    'w03340': ('basmak', 'basmak / (klavyede) yazmak'),
    'w03341': ('musallat olmak', 'rahatsız etmek / asılmak / musallat olmak'),
    'w03347': ('kat', 'katman / kat / (toplum) kesimi'),
    'w03349': ('sokmak', 'sokmak / (veri) girmek / uygulamaya koymak'),
    'w03352': ('uzaktan kumanda', 'kumanda / kontrol paneli'),
    'w03358': ('dikmek / ekmek', 'dikmek / ekmek / oturtmak / hapse atmak'),
    'w03362': ('bulup çıkarmak', 'soruşturup öğrenmek / araştırıp bulmak'),
    'w03363': ('konumlandırma', 'konum / yer / eğilim (sempati)'),
    'w03364': ('fener', 'fener / sokak lambası'),
    'w03371': ('vazgeçmek', '(yerini) vermek / boyun eğmek / taviz vermek'),
    'w03376': ('çalıştırmak', 'antrenman yaptırmak / çalıştırmak'),
    'w03378': ('indirmek', 'indirmek / (mektup) atmak / atlamak'),
    'w03385': ('menteşe', 'ilmek / menteşe'),
    'w03388': ('kabul etmek', 'izin vermek / (olasılığı) kabul etmek / (hata) yapmak'),
    'w03393': ('ikram etmek', 'ikram etmek / ısmarlamak'),
    'w03399': ('ayartmak', 'baştan çıkarmak / ayartmak'),
    'w03403': ('yöneltmek', 'yöneltmek / göndermek / yönlendirmek'),
    'w03404': ('göz atmak', 'göz atmak / gözden geçirmek / izlemek'),
    'w03406': ('rahatsız etmek', 'rahatsız etmek / endişelendirmek'),
    'w03409': ('kazanç', 'kazanç / ikramiye (piyango)'),
    'w03410': ('çağırmak', 'çağırmak / çağrıda bulunmak / askere almak'),
    'w03413': ('zararlı', 'zararlı / huysuz (kişi)'),
    'w03415': ('başörtü', 'başörtüsü / mendil / eşarp'),
    'w03417': ('yıkamak', 'yıkayıp çıkarmak / (dalga) alıp götürmek'),
    'w03420': ('yırtmak', 'yırtmak / koparmak / kusmak'),
    'w03423': ('bir araya getirmek', 'birleştirmek / bir araya getirmek'),
    'w03424': ('çanak', 'kâse / kadeh / çanak'),
    'w03427': ('kuduz', 'kuduz / çılgın / deli gibi (hızlı)'),
    'w03432': ('devlet desteği', 'yardım (ödenek) / ders kitabı (kılavuz)'),
    'w03435': ('afiş', 'afiş / poster'),
    'w03438': ('kırmak', 'kırmak / bölmek'),
    'w03439': ('delip geçme', 'atılım / çığır / (baraj) patlaması'),
    'w03441': ('tehlikeli', 'riskli / tehlikeli'),
    'w03443': ('destekleyici', 'sponsor / destekçi'),
    'w03448': ('rehin vermek', 'rehin vermek / temelini atmak / koymak'),
    'w03450': ('efsane', 'mit / efsane'),
    'w03451': ('yakalamak', 'yakalamak / (hastalık) kapmak / devam ettirmek'),
    'w03453': ('eş', 'eş (kadın) / hanım'),
    'w03460': ('eşarp', 'atkı / eşarp'),
    'w03461': ('kurma', 'sahneleme / (tanı, soru) koyma'),
    'w03465': ('olgu', 'olay / olgu'),
    'w03466': ('gösterim', 'gösteri (yürüyüş) / gösterim'),
    'w03467': ('dürüst', 'dürüst / terbiyeli / epey (miktar)'),
    'w03475': ('parlaklık', 'parlaklık / ışıltı'),
    'w03476': ('sağlama', 'sağlama / güvence / yazılım (programlar)'),
    'w03482': ('ağrılı', 'ağrılı / hastalıklı / acı verici'),
    'w03486': ('fıskiyeli havuz', 'fıskiye / (süs) çeşme'),
    'w03487': ('atlı', 'atlı / binici'),
    'w03491': ('karşı', 'karşı / zıt'),
    'w03493': ('atomik', 'atom / nükleer'),
    'w03499': ('yakmak', 'yakmak / (argo) coşturmak'),
    'w03508': ('başında olmak', 'başına geçmek / önderlik etmek'),
    'w03511': ('okuma', 'öğrenim / eğitim / ders çalışma'),
    'w03512': ('geçit', 'portal / geçit'),
}

DROP = {
    'w03396': 'люцифер',  # özel isim (kayıtta küçük harf)
    'w03408': 'лука',     # "nehir dönemeci"; neredeyse hep лук'un (soğan) hâli olarak görülüyor
}
