# -*- coding: utf-8 -*-
"""B2 inceleme, parti 4."""

FIXES = {
    'w04507': ('mercek', 'mercek / lens'),
    'w04508': ('eksiklik', 'eksiklik / yetersizlik'),
    'w04512': ('çıkarmak', 'silmek / uzaklaştırmak / çıkarmak'),
    'w04513': ('abide', 'anıt / heykel'),
    'w04516': ('soygun', 'soygun / yağma'),
    'w04518': ('uğurlamak', 'yolcu etmek / uğurlamak / eşlik etmek'),
    'w04519': ('kabak', 'balkabağı'),
    'w04520': ('tapmak', 'tapınmak'),
    'w04522': ('alicenap', 'cömert / yüce gönüllü'),
    'w04523': ('özellik', 'özellik / nitelik'),
    'w04524': ('eğer', 'eğer / madem'),
    'w04525': ('dövülmüş', 'dövülmüş / bayat (klişe)'),
    'w04526': ('kuş', 'kuş (sıfat)'),
    'w04527': ('belgesel', 'belgesel / belgeye dayalı'),
    'w04529': ('yakalama', 'gözaltı / yakalama'),
    'w04530': ('arife', 'arife / öncesi'),
    'w04532': ('dizilim', 'sıra / dizi / tutarlılık'),
    'w04533': ('matris', 'matris / kalıp'),
    'w04536': ('dalgın', 'dalgın / dağınık'),
    'w04537': ('ıslatmak; (argo) öldürmek', 'ıslatmak / (argo) öldürmek'),
    'w04539': ('yalnızca', 'yalnızca / son derece'),
    'w04541': ('kurulmak', 'inşa edilmek / sıraya girmek'),
    'w04542': ('mahkûm etmek', 'hüküm vermek / mahkûm etmek'),
    'w04543': ('köknar', 'ladin / yılbaşı ağacı'),
    'w04544': ('parlaklık', 'parıltı / ışıltı'),
    'w04545': ('tuhaf adam', 'tuhaf adam / garip biri'),
    'w04546': ('düpedüz', 'açıkça / samimiyetle'),
    'w04547': ('yırtmak', 'yırtmak / koparmak / bitirmek (ilişki)'),
    'w04548': ('iplik', 'iplik / dikiş ipi'),
    'w04549': ('çözelti', 'çözelti / harç'),
    'w04551': ('işınım', 'ışıma / radyasyon'),
    'w04552': ('kovan', 'kovan / kartuş'),
    'w04553': ('inandırıcı', 'inandırıcı / makul'),
    'w04555': ('hüküm', 'yargı / görüş'),
    'w04556': ('ele geçirmek', 'ele geçirmek / ustalaşmak'),
    'w04557': ('peni', 'peni / pens'),
    'w04560': ('abes', 'saçma / absürt'),
    'w04561': ('birleştirmek', 'birleştirmek / bağlamak'),
    'w04562': ('delmek', 'delmek / sondaj yapmak'),
    'w04563': ('büyücü', 'büyücü / cadı (erkek)'),
    'w04565': ('hasta bakıcı', 'hastabakıcı / sıhhiye'),
    'w04569': ('kara', 'kara / kuraklık'),
    'w04570': ('alt', 'alt / dip'),
    'w04572': ('başarıyla', 'başarıyla / şanslı bir şekilde'),
    'w04573': ('meyve', 'meyve (böğürtlen vb.) / tane'),
    'w04574': ('melez', 'melez / hibrit'),
    'w04575': ('kapıyı çalmak', 'kapıyı çalmak / vurmak'),
    'w04576': ('anket', 'anket / form'),
    'w04579': ('kongre', 'kongre / toplantı / (yoldan) çıkış'),
    'w04582': ('erginleşmek', 'büyümek / yetişkin olmak'),
    'w04583': ('tükürük', 'salya / tükürük'),
    'w04584': ('tanımak', 'tanımak / teşhis etmek'),
    'w04587': ('öne çıkmak', 'öne çıkmak / ayrılmak / salgılanmak'),
    'w04588': ('tembel', 'tembel / işsiz güçsüz'),
    'w04589': ('vade', 'erteleme / ek süre'),
    'w04590': ('sosis', 'sucuk / sosis'),
    'w04591': ('silgi', 'silgi / lastik'),
    'w04592': ('nar', 'nar / bomba (el bombası)'),
    'w04594': ('kramp', 'kramp / spazm'),
    'w04596': ('kazanmak', 'yenmek (oyunda)'),
    'w04597': ('doğuş', 'doğuş / gün doğumu'),
    'w04598': ('karanlık', 'karanlık / kasvet'),
    'w04599': ('entrika', 'entrika / ilginç olay örgüsü'),
    'w04601': ('gaf', 'ıskalama / hata'),
    'w04605': ('endişe', 'endişe / korku'),
    'w04610': ('yüzerek uzaklaşmak', 'yüzerek / gemiyle uzaklaşmak'),
    'w04611': ('anlamak', 'anlamak / kavramak / bir çare bulmak'),
    'w04613': ('artırmak', 'artırmak / büyütmek'),
    'w04614': ('tampon', 'tampon / (tıbbi) tampon'),
    'w04615': ('evlilik', 'evlilik (kadın için)'),
    'w04617': ('bir araya getirmek', 'birleştirmek'),
    'w04620': ('kapatmak', 'kapatmak / devre dışı bırakmak'),
    'w04624': ('içirmek', 'içirmek / su vermek'),
    'w04626': ('sallamak', 'sallamak / pompalamak / indirmek'),
    'w04627': ('ıslah edici', 'ıslah edici / ıslahevi (sıfat)'),
    'w04628': ('çöküş', 'çöküş / iflas'),
    'w04630': ('rezerv', 'yedek / rezerv'),
    'w04631': ('işaret', 'işaret / etiket'),
    'w04632': ('aşçılık', 'mutfakla / yemek pişirmeyle ilgili'),
    'w04633': ('yapıştırmak', 'yapıştırmak'),
    'w04636': ('aldanmak', 'yanılmak / aldanmak'),
    'w04640': ('soruşturmak', 'soru sormak / sorup öğrenmek'),
    'w04642': ('yaratıcılık', 'yaratıcılık / eserler'),
    'w04646': ('hücum', 'hücum / saldırı'),
    'w04647': ('köpek dişi', 'köpek dişi / azı'),
    'w04651': ('doğan', 'doğan / şahin'),
    'w04652': ('prediksiyon', 'tahmin / kehanet'),
    'w04653': ('bozulmak', 'bozulmak / kırılmak'),
    'w04654': ('kirli', 'kirli / temiz olmayan'),
    'w04656': ('sigorta', 'sigorta (elektrik) / emniyet'),
    'w04657': ('özellik', 'özellik / nitelik / referans mektubu'),
    'w04658': ('endüstriyel', 'sanayi (sıfat) / endüstriyel'),
    'w04660': ('ikiye bölünmek', 'yırtılmak / patlamak / bölünmek'),
    'w04661': ('hıyar', 'salatalık'),
    'w04662': ('uygunsuz', 'ayıp / uygunsuz'),
    'w04665': ('emir', 'ferman / kararname'),
    'w04666': ('zafer', 'zafer / muzaffer kazanç'),
    'w04667': ('uğursuz', 'uğursuz / meşum'),
    'w04670': ('dönmek', 'geri dönmek'),
    'w04675': ('çariçe', 'çariçe / kraliçe'),
    'w04676': ('yüksek lisans', 'yüksek lisans (derece) / usta'),
    'w04678': ('muhasebe', 'muhasebe (birimi)'),
    'w04680': ('yansıtmak', 'yansıtmak / savuşturmak'),
    'w04683': ('yuvarlamak', 'yuvarlamak / (araçla) gitmek'),
    'w04684': ('yazılış', 'yazılış / yazım'),
    'w04685': ('tebeşir', 'tebeşir / kireç taşı'),
    'w04691': ('uzmanlık alanı', 'uzmanlık / meslek'),
    'w04692': ('ücret', 'telif / ücret (serbest)'),
    'w04695': ('açık büfe', 'büfe / (mobilya) büfe'),
    'w04696': ('karalama', 'taslak / karalama'),
    'w04700': ('zorla girmek', 'zorla girmek / dalmak'),
    'w04701': ('kızartmak', 'kızartmak / kavurmak'),
    'w04702': ('feragat etmek', 'yol vermek / taviz vermek / geri kalmak'),
    'w04704': ('kafasını karıştırmak', 'karıştırmak / dolaştırmak'),
    'w04705': ('uç', 'uç / ucu'),
    'w04706': ('akıllı', 'makul / sağduyulu'),
    'w04707': ('su birikintisi', 'su birikintisi / gölcük'),
}

DROP = {
    'w04506': 'попа',
}
