# -*- coding: utf-8 -*-
"""B2 inceleme, parti 6."""

FIXES = {
    'w04911': ('katı', 'sıkı / gergin / katı'),
    'w04912': ('av tüfeği', 'av tüfeği / pompalı tüfek'),
    'w04913': ('alay', 'alay / küçümseme'),
    'w04916': ('adi', 'kaba / adi'),
    'w04921': ('suç ortağı', 'suç ortağı / ortak'),
    'w04925': ('borç', 'borç / kredi'),
    'w04928': ('esmer kadın', 'esmer / kara saçlı kadın'),
    'w04931': ('cetvel', 'tablo / çizelge'),
    'w04932': ('perde', 'perde (sahne)'),
    'w04933': ('kaynamak', 'kaynamak / dolu olmak'),
    'w04934': ('şefkat', 'şefkat / okşama / gelincik'),
    'w04935': ('mola', 'mola / soluklanma'),
    'w04936': ('dünden önceki gün', 'evvelsi gün / dünden önceki gün'),
    'w04937': ('soylu', 'asilzade / soylu'),
    'w04939': ('sırt', 'sırt / omurga / dağ silsilesi'),
    'w04942': ('mantıksal', 'mantıksal / mantıklı'),
    'w04943': ('kaydetmek', 'kaydetmek / tescil etmek'),
    'w04944': ('uçurum', 'uçurum / kopma'),
    'w04945': ('onarmak', 'onarmak / yeniden kurmak / eski haline getirmek'),
    'w04946': ('zapt etmek', 'bastırmak / ezmek'),
    'w04947': ('şans', 'şans'),
    'w04948': ('kullanım', 'kullanım / tüketim'),
    'w04951': ('barındırmak', 'barındırmak / sığınak vermek'),
    'w04953': ('pipet', 'pipet / saman çöpü'),
    'w04954': ('torun', 'torun (kız)'),
    'w04955': ('Kanada geyiği, mus (elk)', 'geyik (Avrasya) / mus'),
    'w04957': ('yerleştirmek', 'yerleştirmek / koymak'),
    'w04959': ('yürüyüş', 'yürüyüş / adım'),
    'w04961': ('şifa', 'şifa / iyileşme'),
    'w04963': ('deniz eri', 'gemici / denizci'),
    'w04964': ('cesaret', 'cesaret / yiğitlik'),
    'w04966': ('koparmak', 'koparmak / bozmak (plan)'),
    'w04968': ('çizmek', 'çizmek / tırmalamak'),
    'w04970': ('yer altı', 'zindan / yeraltı'),
    'w04971': ('gereksiz', 'gereksiz / fazla'),
    'w04973': ('müntehir', 'intihar eden kişi'),
    'w04976': ('ırksal', 'ırksal / ırk (sıfat)'),
    'w04978': ('gasp', 'haraç / gasp / şantajla para koparma'),
    'w04980': ('allahlık', 'budala / salak'),
    'w04982': ('bakış', 'bakış / göz'),
    'w04985': ('yapı', 'yapı / tasarım'),
    'w04986': ('deneme', 'deney (sıfat) / deney hayvanı'),
    'w04988': ('yakmak', 'yakmak / körüklemek / tutuşturmak'),
    'w04990': ('ürün', 'ürünler / üretim'),
    'w04991': ('kendine mal etmek', 'kendine mal etmek / (unvan) vermek'),
    'w04995': ('harabe', 'harabe / yıkıntı'),
    'w04997': ('usta', 'usta / üstat'),
    'w04998': ('kenar mahalle', 'kenar mahalle / kenar'),
    'w05000': ('iptal etmek', 'iptal etmek / geçersiz kılmak'),
    'w05001': ('alçak', 'alçak / aşağıda'),
    'w05003': ('neden', 'neden / niçin'),
    'w05004': ('etkileyici', 'sağlam / ciddi / itibarlı'),
    'w05005': ('baston', 'baston / kamış'),
    'w05006': ('birleşme', 'birleşme / birlik / dernek'),
    'w05008': ('gam', 'gam (müzik) / spektrum'),
    'w05009': ('kadeh', 'kadeh'),
    'w05010': ('kukla, korkuluk (bostan korkuluğu)', 'korkuluk / doldurulmuş hayvan'),
    'w05011': ('topçu', 'topçu / topçu birliği'),
    'w05012': ('tüy', 'tüy (yumuşak) / ince tüy'),
    'w05015': ('masraf', 'masraf / harcama'),
    'w05017': ('titreme', 'titreme / ürperti'),
    'w05020': ('sessiz', 'suskun / sessiz'),
    'w05021': ('yırtık', 'yırtık / parçalanmış'),
    'w05022': ('can sıkıcı', 'sinir bozucu / can sıkıcı'),
    'w05023': ('azaltmak', 'azaltmak / düşürmek'),
    'w05024': ('yutmak', 'yutmak / silip süpürmek'),
    'w05025': ('ayarlamak', 'yerleştirmek / sahip olmak'),
    'w05026': ('nötralize etmek', 'etkisiz hale getirmek / nötralize etmek'),
    'w05028': ('dayanmak', 'dayanmak / katlanmak / sınavdan geçmek'),
    'w05029': ('telaşlı', 'huzursuz / telaşlı'),
    'w05031': ('karar', 'karar / kararname'),
    'w05032': ('verimlilik', 'verimlilik / etkililik'),
    'w05037': ('acemi er', 'acemi er / yeni asker'),
    'w05038': ('hayal kırıklığına uğramak', 'hayal kırıklığına uğramak'),
    'w05039': ('kutup', 'kutup (sıfat) / kutupsal'),
    'w05041': ('anlatmak', 'anlatmak / sunmak / yazıya dökmek'),
    'w05042': ('müsamahalı', 'hoşgörülü / alttan alan'),
    'w05043': ('vantilatör', 'vantilatör / fan'),
    'w05044': ('engel', 'güçlük / sıkıntı'),
    'w05045': ('tur', 'tur / turne'),
    'w05046': ('iskele', 'iskele / rıhtım'),
    'w05047': ('havyar, baldır (bağlama göre)', 'havyar / balık yumurtası / baldır'),
    'w05049': ('berbat', 'berbat / değersiz'),
    'w05050': ('gözetlemek', 'gözetlemek / pusuda beklemek'),
    'w05054': ('abartmak', 'abartmak / fazla kaçırmak'),
    'w05055': ('yapı', 'yapı / bina'),
    'w05056': ('göz korkutmak', 'korkutmak / göz korkutmak'),
    'w05058': ('iyilikle', 'iyilikle / kibarca'),
    'w05063': ('döküntü', 'döküntü / kızarıklık'),
    'w05064': ('mızrak; zirve', 'mızrak / (iskambil) maça'),
    'w05065': ('boşluk', 'boşluk / eksiklik'),
    'w05066': ('dökmek, saçmak (taneli madde için)', 'dökmek / saçmak / yağdırmak'),
    'w05067': ('görgü', 'terbiye / edep'),
    'w05069': ('amansız', 'amansız / acımasız'),
    'w05070': ('üçü birlikte', 'üç kişi birlikte'),
    'w05073': ('yumuşakça', 'yumuşakça / midye'),
    'w05075': ('hanım', 'hanımefendi'),
    'w05077': ('koparmak', 'koparmak / ayırmak'),
    'w05078': ('kırıp girmek', 'kırıp açmak / hacklemek'),
    'w05079': ('bozulmak', 'bozulmak / kötüleşmek'),
    'w05081': ('parça', 'küçük parça / kâğıt parçası'),
    'w05082': ('yatmak', 'biraz yatmak'),
    'w05086': ('çöp kutusu, sandık (oy sandığı)', 'çöp kutusu / oy sandığı'),
    'w05087': ('hostes', 'hostes / uçuş görevlisi'),
    'w05088': ('baharat', 'baharat'),
    'w05090': ('yapı', 'yapı / bina'),
    'w05091': ('mebus', 'milletvekili / delege'),
    'w05092': ('cıvata', 'cıvata / (argo) boş ver'),
    'w05093': ('forvet', 'forvet / saldırgan'),
    'w05096': ('aldırmaz', 'kayıtsız / ilgisiz'),
    'w05097': ('arıtmak', 'temizlemek / arıtmak / soymak'),
    'w05099': ('nefes almak', 'iç çekmek / nefes almak'),
    'w05100': ('fırın', 'fırın (ekmek)'),
    'w05101': ('yarık', 'yarık / çatlak / aralık'),
    'w05102': ('bölünme', 'bölünme / ayrılık'),
    'w05103': ('istekli', 'heyecanlı / tutkulu / kendini kaptırmış'),
    'w05104': ('bitiş', 'sona erme / kesilme'),
    'w05106': ('antika', 'antika eşya'),
    'w05107': ('yeterlilik', 'yeterlilik / nitelik'),
    'w05109': ('amaçlı', 'bilinçli / kasıtlı'),
    'w05110': ('borç', 'kredi / borç'),
    'w05111': ('yas tutmak', 'üzülmek / yas tutmak'),
}

DROP = {
    'w04987': 'Неаполь',
    'w05013': 'сирия',
    'w05030': 'мерси',
    'w05053': 'блевать',
}
