# -*- coding: utf-8 -*-
"""B2 inceleme, parti 9."""

FIXES = {
    'w05520': ('kargaşa', 'kargaşa / telaş'),
    'w05521': ('olgunlaşmak', 'olgunlaşmak / pişmek'),
    'w05522': ('deste', 'deste (iskambil) / kütük'),
    'w05523': ('faydasız', 'işe yaramaz / değersiz'),
    'w05524': ('isimsiz', 'isimsiz / adsız'),
    'w05525': ('taban', 'taban / (ayakkabı) tabanı'),
    'w05529': ('azalmak', 'azalmak / alçalmak / düşmek'),
    'w05530': ('yakınlaştırmak', 'yaklaştırmak'),
    'w05531': ('yapım', 'üretim / imal'),
    'w05532': ('girmek', '(araçla) girmek / taşınmak'),
    'w05533': ('toparlamak', 'toparlamak / sonlandırmak / yuvarlaklaşmak'),
    'w05534': ('çekim', 'çekim / cazibe'),
    'w05535': ('zeki', 'zeki / çabuk kavrayan'),
    'w05537': ('ısıtmak', 'ısıtmak (soba) / batırmak / eritmek'),
    'w05538': ('kılıç', 'kılıç (eğri) / kılıç'),
    'w05539': ('uzun boylu', 'iri yarı / uzun boylu'),
    'w05543': ('etyemez', 'vejetaryen'),
    'w05546': ('taklit etmek', 'taklit etmek / örnek almak'),
    'w05547': ('kaynamak', 'kaynamak / köpürmek'),
    'w05550': ('çalışmakla ödemek', 'çalışarak ödemek / (beceri) geliştirmek'),
    'w05552': ('manken', 'manken (vitrin) / model'),
    'w05554': ('iş adamı', 'iş adamı / işbitirici'),
    'w05555': ('eğri', 'eğri / çarpık'),
    'w05559': ('sergilenen eser', 'sergilenen eser / sergi parçası'),
    'w05561': ('çağrı', 'meslek aşkı / çağrı / yetenek'),
    'w05566': ('mezura', 'ruletmasa / şerit metre'),
    'w05568': ('sinirli', 'sinirli / çabuk sinirlenen'),
    'w05569': ('kaside', 'kaside / övgü şiiri'),
    'w05573': ('araçla dolaşmak', 'dolaşmak (araçla) / etrafından geçmek'),
    'w05574': ('idolleştirmek', 'tapmak / hayranlık duymak'),
    'w05575': ('mevsimsiz erken', 'erken / vaktinden önce'),
    'w05579': ('idari', 'idari'),
    'w05580': ('paten', 'paten / at yavrusu / (çatı) mahya'),
    'w05581': ('komutan', 'komutan / yönetici (bina)'),
    'w05582': ('utanmış', 'utanmış / mahcup'),
    'w05584': ('özgül', 'özgün / kendine has'),
    'w05585': ('ortaçağ', 'ortaçağ (sıfat)'),
    'w05586': ('ölçülü', 'ölçülü / kendini tutan'),
    'w05589': ('depo odası', 'kiler / depo odası'),
    'w05590': ('sık sık', 'çoğu zaman / sık sık'),
    'w05591': ('dalgıç elbisesi', 'uzay giysisi / dalgıç elbisesi'),
    'w05592': ('koyulmak', 'koyulmak / başlamak'),
    'w05593': ('ürkek', 'ürkek / çekingen'),
    'w05594': ('kauçuk', 'lastik / kauçuk'),
    'w05596': ('dikkatli', 'dikkatli / sabit (bakış)'),
    'w05597': ('kayınbirader', 'kayınbirader (karının kardeşi)'),
    'w05598': ('kıta', 'kıta / anakara'),
    'w05599': ('takılmak', 'takmak / ilişmek / çengele takmak'),
    'w05600': ('teyp', 'teyp / kaset çalar'),
    'w05602': ('yaratıcı', 'buluşçu / yaratıcı'),
    'w05605': ('çizmek', 'çizmek / plan çizmek'),
    'w05606': ('dinmek', 'sona ermek / dinmek'),
    'w05607': ('batakhane', 'batakhane / sığınak (suç)'),
    'w05608': ('buz pateni sahası, (yol) silindiri', 'buz pateni sahası / yol silindiri'),
    'w05610': ('korumak', 'korumak / biriktirmek'),
    'w05611': ('girişimci', 'girişimci / iş insanı'),
    'w05612': ('üstüne', 'üstüne / üzerinde'),
    'w05613': ('yazma', 'kutsal yazı / yazma'),
    'w05614': ('vatandaşlık', 'vatandaşlık / uyruk'),
    'w05618': ('vergi yükümlüsü', 'vergi mükellefi'),
    'w05619': ('yol arkadaşı', 'yol arkadaşı / eş (kadın)'),
    'w05620': ('kibir', 'kibir / şöhret düşkünlüğü'),
    'w05621': ('dayanmak', 'dayanmak / yaslanmak'),
    'w05622': ('fahri', 'fahri / onur (sıfat)'),
    'w05623': ('genişletmek', 'genişletmek / yaymak'),
    'w05624': ('savmak', 'kovmak / def etmek / savmak'),
    'w05625': ('egoizm', 'bencillik'),
    'w05626': ('imparatorluk', 'Reich / (Alman) devleti'),
    'w05627': ('sorunsuz', 'sorunsuz / huzurlu / rahat'),
    'w05628': ('dümen', 'dümen / direksiyon (gemi, uçak)'),
    'w05629': ('bakımsız', 'bakımsız / ihmal edilmiş'),
    'w05630': ('bereket', 'refah / gelişme'),
    'w05631': ('yahni', 'yahni / güveç'),
    'w05632': ('düşük', 'düşük / çocuk düşürme'),
    'w05635': ('ihmal etmek', 'ihmal etmek / hiçe saymak'),
    'w05636': ('önyargılı', 'önyargılı / tarafgir'),
    'w05637': ('antika', 'antika / antikacılıkla ilgili'),
    'w05638': ('kaygısız', 'kaygısız / tasasız'),
    'w05639': ('saf', 'saf / güvenen'),
    'w05641': ('saga', 'destan / saga'),
    'w05642': ('dürtü', 'dürtü / güdü'),
    'w05643': ('havacılık', 'havacılık / hava kuvvetleri'),
    'w05644': ('kargaşa', 'karmaşa / şaşkınlık'),
    'w05645': ('alçakgönüllülük', 'alçakgönüllülük / mütevazılık'),
    'w05648': ('sırt', 'sırtlık / arka (sandalye)'),
    'w05650': ('edinmek', 'edinmek / satın almak'),
    'w05651': ('bulandırmak', 'bulandırmak / (argo) entrika çevirmek'),
    'w05652': ('kendine özgü', 'kendine özgü / özgün'),
    'w05653': ('kalifiye', 'nitelikli / kalifiye'),
    'w05654': ('teskin etmek', 'yatıştırmak / teskin etmek'),
    'w05656': ('üniforma', 'üniforma (resmi)'),
    'w05657': ('alan', 'geniş alan / açıklık'),
    'w05658': ('yığın', 'yığın / küme'),
    'w05659': ('yetki', 'yetki / uzmanlık alanı'),
    'w05660': ('çıkışma', 'azar / disiplin cezası'),
    'w05661': ('berbat', 'işe yaramaz / berbat'),
    'w05662': ('izole', 'yalıtılmış / tecrit edilmiş'),
    'w05663': ('besleyici', 'besleyici / doyurucu'),
    'w05664': ('kızak', 'kızak / kar arabası'),
    'w05665': ('köfte', 'köfte / pirzola'),
    'w05668': ('parlak', 'parlak / pırıl pırıl'),
    'w05669': ('hükümdar', 'hükümdar / efendi'),
    'w05671': ('kemer', 'kemer / kemerli geçit'),
    'w05673': ('analojik', 'benzer / eşdeğer'),
    'w05674': ('desen', 'desen / motif'),
    'w05675': ('suçlu', 'sorumlu / suçlu'),
    'w05676': ('polen', 'polen / çiçek tozu'),
    'w05677': ('putperest', 'putperest / pagan'),
    'w05678': ('süpürge', 'süpürge (uzun saplı)'),
    'w05680': ('tasasız', 'tasasız / kaygısız'),
    'w05681': ('önbellek', 'önbellek / nakit'),
    'w05683': ('vasiyet etmek', 'vasiyet etmek / miras bırakmak'),
    'w05685': ('sıradan', 'sıradan / vasat'),
    'w05686': ('ocak', 'ocak / (hastalık) odak'),
    'w05687': ('çirkinlik', 'rezalet / çirkinlik'),
    'w05688': ('paskalya', 'Paskalya (sıfat)'),
    'w05689': ('hızlı', 'hızlı / atak'),
    'w05690': ('anarşi', 'anarşi / kargaşa'),
    'w05693': ('müşteri', 'müşteri (sipariş veren)'),
    'w05694': ('kaşımak', 'kaşımak / taramak'),
    'w05695': ('yerüstü', 'yerüstü / karasal'),
    'w05696': ('giriş', 'giriş (araçla)'),
    'w05697': ('donanmak', 'süslenip giyinmek'),
    'w05699': ('zorlama', 'zorlama / baskı'),
    'w05700': ('eziyet etmek', 'canını sıkmak / tüketmek / harcamak'),
    'w05701': ('kaçınmak', 'kaçınmak / savuşturmak / sapmak'),
    'w05702': ('bayrak', 'bayrak / sancak'),
    'w05704': ('sahip', 'sahibi / sahip'),
    'w05705': ('bale dansçısı', 'balerin'),
    'w05706': ('mahvetmek', 'mahvetmek / yok etmek'),
    'w05708': ('dalmak', 'dalmak / dalıp çıkmak'),
    'w05709': ('cenin', 'cenin / embriyo'),
    'w05710': ('çıplak', 'çıplak / ortaya çıkmış'),
    'w05712': ('bunaltmak', 'ezmek / bunaltmak'),
    'w05713': ('vida', 'vida / pervane'),
    'w05714': ('kayıplar', 'kayıp / zarar'),
    'w05715': ('rıhtım', 'rıhtım / sahil yolu'),
    'w05717': ('sel', 'sel / su baskını'),
    'w05718': ('ilerlemek', 'ilerlemek / yoluna devam etmek'),
}

DROP = {
    'w05609': 'таиланд',
    'w05603': 'сыночек',
}
