# -*- coding: utf-8 -*-
"""B2 inceleme, parti 5."""

FIXES = {
    'w04709': ('yörünge', 'yörünge / rota'),
    'w04710': ('dekor', 'dekor / süsleme'),
    'w04711': ('intikam', 'intikam / hak edilmiş ceza'),
    'w04712': ('muhbir', 'muhbir / bilgi veren'),
    'w04714': ('son olarak', 'son olarak / en sonunda'),
    'w04715': ('cisimleştirmek', 'gerçekleştirmek / cisimleştirmek'),
    'w04716': ('bekçi', 'bekçi / gözetmen'),
    'w04721': ('arkada', 'arkasından / ardından'),
    'w04723': ('koyu', 'koyu / yoğun / sık'),
    'w04724': ('çirkince', 'çirkin'),
    'w04728': ('bronzlaşma', 'bronzluk / güneş yanığı'),
    'w04732': ('değer vermek', 'değer vermek / kıymet bilmek'),
    'w04738': ('kanla ilgili', 'kan (sıfat)'),
    'w04739': ('ihtilaflı', 'tartışmalı / ihtilaflı'),
    'w04740': ('isabetli', 'isabetli / keskin nişancı'),
    'w04741': ('kolon', 'sütun / kol (askeri)'),
    'w04742': ('lüks', 'lüks / süit'),
    'w04745': ('germek', 'germek / (giysi) giymek'),
    'w04747': ('plaster', 'yara bandı / plaster'),
    'w04748': ('akümülatör', 'akü / akümülatör'),
    'w04750': ('araştırmak', 'taramak / aramak'),
    'w04752': ('teşvik etmek', 'teşvik etmek / ödüllendirmek'),
    'w04753': ('unutulmayacak', 'unutulmaz'),
    'w04754': ('mekanik', 'mekanik / düzenek'),
    'w04755': ('dikmek', 'dikmek / (yırtığı) kapatmak'),
    'w04756': ('dal', 'dal / kol (kurum)'),
    'w04757': ('mahrumiyet', 'mahrumiyet / yoksunluk'),
    'w04759': ('mekanik', 'mekanik / makineyle'),
    'w04761': ('çekim', 'çekiş / çekme gücü / istek'),
    'w04762': ('konsantrasyon', 'yoğunlaşma / konsantrasyon'),
    'w04763': ('yaban domuzu', 'yaban domuzu / domuz'),
    'w04770': ('görünmek', 'görünmek / ortaya çıkmak'),
    'w04771': ('çok hızlı gitmek', 'koşmak / hızla gitmek'),
    'w04772': ('nurlu', 'parlayan / ışıldayan'),
    'w04773': ('şimdi', 'şimdi / bugünlerde'),
    'w04774': ('ütülemek', 'ütülemek / okşamak'),
    'w04775': ('saydam', 'saydam / şeffaf'),
    'w04776': ('esir', 'köle (kadın)'),
    'w04777': ('bekâr', 'bekâr / boş (mermi)'),
    'w04778': ('havalanmak', 'havalanmak / yükselmek'),
    'w04779': ('müstakil ev', 'müstakil ev / yazlık'),
    'w04780': ('merhem', 'merhem / krem'),
    'w04781': ('cüce', 'cüce / gnom'),
    'w04782': ('refah', 'refah / huzur'),
    'w04783': ('davalı', 'davalı / sorumlu'),
    'w04784': ('çıpa', 'çapa / demir'),
    'w04785': ('gergin', 'gergin / yoğun'),
    'w04786': ('içirmek', 'içirmek / sulamak'),
    'w04787': ('beyaz saçlı', 'kır saçlı / ak saçlı'),
    'w04791': ('ayrıntı', 'ayrıntı / özel durum'),
    'w04792': ('havayı içine çekmek', 'soluğunu içine çekmek / nefes almak'),
    'w04793': ('aktarma', 'aktarma / nakil'),
    'w04798': ('rehber', 'el kitabı / rehber (kitap)'),
    'w04799': ('tel', 'tel (çalgı) / kiriş'),
    'w04801': ('pamuk', 'pamuk / alkış / pat sesi'),
    'w04804': ('çekim', 'çekim / arzu'),
    'w04807': ('mahkeme', 'askeri mahkeme / tribunal'),
    'w04808': ('yerleşim', 'yerleşim / köy / sürgün yeri'),
    'w04809': ('toprağı sürmek', '(toprağı) sürmek / (argo) çok çalışmak'),
    'w04810': ('ezmek', 'bozguna uğratmak / yıkmak'),
    'w04812': ('yıkmak', 'yıkmak / dayanmak'),
    'w04813': ('leğen; kalça', 'leğen / kalça (leğen kemiği)'),
    'w04814': ('beceriksiz', 'yeteneksiz / beceriksiz'),
    'w04819': ('isabetli', 'yerinde / uygun'),
    'w04820': ('analizci', 'analist'),
    'w04821': ('(bir şeyi) kullanmak', 'emretmek / yönetmek'),
    'w04822': ('öz', 'kan bağı (sıfat) / öz'),
    'w04823': ('şalter', 'anahtar (elektrik) / düğme'),
    'w04825': ('toksik', 'zehirli / toksik'),
    'w04826': ('sırık', 'sırık / direk'),
    'w04829': ('tavlamak', 'çekmek / cezbetmek'),
    'w04830': ('kefaret', 'kefaret / telafi'),
    'w04831': ('beklemek', 'sonuna dek beklemek'),
    'w04834': ('yaklaşık', 'yaklaşık olarak'),
    'w04836': ('kaplama', 'kaplama / kapsam'),
    'w04837': ('kazanç', 'kazanç / gelir'),
    'w04838': ('somurtmak', 'somurtmak / küsmek'),
    'w04840': ('genellikle', 'sık sık'),
    'w04841': ('sakınmak', 'sakınmak / dikkat etmek'),
    'w04842': ('gümbürdetmek', 'gürültüyle düşürmek / (argo) öldürmek'),
    'w04845': ('yazı tipi', 'yazı tipi / font'),
    'w04848': ('fırça; el', 'fırça / el (bilekten parmağa)'),
    'w04849': ('büzmek', 'sıkmak / bastırmak'),
    'w04853': ('pazar', 'pazar / (argo) gürültü'),
    'w04854': ('hamur işi', 'hamur işi / fırın ürünü'),
    'w04856': ('bağırmak', 'böğürmek / ağlamak / kükremek'),
    'w04857': ('dedektif', 'dedektif / hafiye'),
    'w04859': ('itaatkâr', 'itaatkâr / boyun eğen'),
    'w04861': ('aralık', 'aralık / ara'),
    'w04863': ('ileri', 'ileri / öncü / cephe'),
    'w04864': ('benzerlik', 'benzerlik / benzer şey'),
    'w04865': ('işe almak', 'işe almak / (ajan) devşirmek'),
    'w04866': ('yaşlanmak', 'yaşlanmak / ihtiyarlamak'),
    'w04868': ('spontane', 'kendiliğinden / spontane'),
    'w04870': ('elle yapılan', 'el (sıfat) / elle yapılan / evcil'),
    'w04874': ('miktar', 'büyüklük / miktar / önemli kişi'),
    'w04875': ('elde etmek, çıkarmak (maden)', 'çıkarmak / elde etmek'),
    'w04877': ('bilgi edinmek', 'tanışmak / bilgi edinmek'),
    'w04879': ('dayanak', 'dayanak / vurgu / ağırlık'),
    'w04880': ('broşür', 'broşür / kitapçık'),
    'w04881': ('ithaf etmek', 'adamak / ithaf etmek'),
    'w04883': ('gençlik', 'gençlik / gençler'),
    'w04884': ('düşüş', 'azalma / düşüş'),
    'w04885': ('rehinci dükkânı', 'rehin dükkânı'),
    'w04886': ('koç', 'koç / koyun'),
    'w04889': ('çekirdek (meyve), kemikçik', 'çekirdek (meyve) / kemikçik'),
    'w04890': ('çaba', 'çaba / gayret'),
    'w04891': ('tüp', 'tüp / balon'),
    'w04892': ('heyecanlı', 'heyecanlı / kışkırtılmış'),
    'w04893': ('asla', 'asla / hiç de'),
    'w04894': ('ilham perisi', 'ilham perisi / esin kaynağı'),
    'w04895': ('üstün olmak', 'üstün olmak / aşmak'),
    'w04896': ('gönüllü', 'gönüllü olarak'),
    'w04897': ('polis', 'milis / polis (eski Sovyet)'),
    'w04902': ('konut', 'konut / mesken'),
    'w04906': ('evcil hayvan', 'evcil hayvan / öğrenci (okulun)'),
    'w04908': ('önemli ölçüde', 'önemli ölçüde / büyük ölçüde'),
    'w04910': ('zirve', 'zirve / tepe'),
}

DROP = {
    'w04909': 'тьфу',
}
