# -*- coding: utf-8 -*-
"""B2 inceleme, parti 8."""

FIXES = {
    'w05316': ('haber vermek', 'haber vermek / bildirmek'),
    'w05317': ('kırık', 'kırık parça / enkaz parçası'),
    'w05319': ('yıkıcı', 'yıkıcı / muhrip (gemi)'),
    'w05322': ('haberleşme', 'iletişim / haberleşme'),
    'w05325': ('düşünülemez', 'hayal edilemez / inanılmaz'),
    'w05329': ('başlatmak', 'başlatmak / tasarlamak / (kavga) çıkarmak'),
    'w05331': ('tayf', 'tayf / spektrum'),
    'w05332': ('çarpmak (araçla), baskı yapmak', '(araçla) üstüne sürmek / çarpmak / baskı yapmak'),
    'w05337': ('ebe', 'ebe / doğum hemşiresi'),
    'w05339': ('inmek', 'inmek (uçak)'),
    'w05341': ('şiddet içeren', 'zorla yapılan / şiddet içeren'),
    'w05342': ('albenili', 'çekici / sempatik'),
    'w05344': ('esinti', 'hafif rüzgâr / esinti'),
    'w05347': ('aksak', 'topal / aksak'),
    'w05351': ('makine', 'tezgâh / makine'),
    'w05352': ('süslemek', 'süslemek / bezemek'),
    'w05353': ('hafif', 'düşüncesiz / hoppa / hafif'),
    'w05354': ('nöbetçi (isim), saatlik', 'nöbetçi (asker) / saatlik / saat (sıfat)'),
    'w05355': ('ilaç', 'ilaç'),
    'w05356': ('debriyaj', 'debriyaj / bağlantı'),
    'w05357': ('asabi', 'çabuk sinirlenen / asabi'),
    'w05359': ('karıştırmak', 'karıştırmak / birbirine katmak'),
    'w05360': ('yumuşakça', 'yumuşak / nazikçe'),
    'w05361': ('acayip', 'tuhaf / acayip / garip biçimli'),
    'w05363': ('cumhuriyetçi', 'cumhuriyete ait / cumhuriyetçi'),
    'w05364': ('karat', 'ayar / karat'),
    'w05365': ('sınırlamak', 'sınırlamak / kısıtlamak'),
    'w05366': ('kesintisiz', 'kesintisiz / sürekli'),
    'w05367': ('büyülemek', 'büyülemek / cezbetmek'),
    'w05368': ('usta', 'usta / becerikli'),
    'w05369': ('asyalı', 'Asyalı'),
    'w05372': ('dülger', 'marangoz / dülger'),
    'w05373': ('müflis', 'iflas etmiş kişi / müflis'),
    'w05374': ('eksik', 'eksik / yarım'),
    'w05376': ('oldukça', 'oldukça / epey / uygun biçimde'),
    'w05377': ('gerekçeli', 'gerekçeli / haklı'),
    'w05379': ('girmek', 'açılmak / devreye girmek / katılmak'),
    'w05380': ('dikkatsiz', 'özensiz / dikkatsiz'),
    'w05381': ('çevik', 'çevik / hareketli'),
    'w05383': ('pas vermek', 'pas vermek / geri çekilmek'),
    'w05385': ('element', 'doğa gücü / element / doğal afet'),
    'w05387': ('kaymak', 'kaymak / süzülmek'),
    'w05388': ('gevrek', 'gevrek / çıtır'),
    'w05389': ('düşüncesiz', 'düşüncesiz / aceleci'),
    'w05392': ('su basmak', 'su basmak / batırmak / (sobayı) yakmak'),
    'w05393': ('gösterişli', 'gösterişli / dolgun / bol'),
    'w05394': ('sarışın', 'sarışın (erkek)'),
    'w05395': ('basitleştirmek', 'basitleştirmek / sadeleştirmek'),
    'w05396': ('maden ocağı', 'maden ocağı / maden'),
    'w05397': ('yük', 'yükleme / yük / indirme'),
    'w05398': ('tarif edilen', 'tarif edilen / anlatılan'),
    'w05400': ('karalamak', 'karalamak / siyaha boyamak'),
    'w05404': ('akıtmak', 'dökmek / su basmak / doldurmak'),
    'w05408': ('uygunsuz', 'uygunsuz / yakışmayan'),
    'w05410': ('yürüme', 'yürüme / yürüyüş'),
    'w05411': ('tırmanış', 'tırmanış / yükseliş'),
    'w05412': ('dalavere', 'dalavere / hile'),
    'w05415': ('çarpıp kapatmak (kapıyı)', 'çarparak kapatmak'),
    'w05416': ('en son', 'en yeni / en son'),
    'w05417': ('eğlendirmek', 'eğlendirmek / oyalamak'),
    'w05418': ('çürüme', 'çürüme / ayrışma / çözülme'),
    'w05419': ('küçük kapı', 'kapak / küçük kapı'),
    'w05420': ('pırıldamak', 'parıldamak / pırıldamak'),
    'w05421': ('maliye', 'maliye / finans'),
    'w05425': ('birey', 'birey (hayvan) / fert'),
    'w05427': ('soy', 'soy / yavrular / döl'),
    'w05428': ('ortadan kaldırmak', 'ortadan kaldırmak / tasfiye etmek'),
    'w05431': ('kripta', 'kripta / aile mezarı'),
    'w05432': ('berelenmek', 'çarpıp incinmek / berelenmek'),
    'w05434': ('tırmanmak, (argo) karıştırmak', 'tırmanmak / (içinde) gezinmek / karıştırmak'),
    'w05435': ('stabilize etmek', 'sabitlemek / dengelemek'),
    'w05436': ('kurtuluş', 'kurtuluş / kurtulma'),
    'w05437': ('aydınlatmak', 'aydınlatmak / açıklık getirmek'),
    'w05438': ('çörek', 'ekmek (küçük) / çörek / sandviç ekmeği'),
    'w05439': ('keten bezi', 'bez / tuval / (demir yolu) hat'),
    'w05442': ('bulmaca', 'bulmaca / çapraz bulmaca'),
    'w05443': ('enteriyör', 'iç mekân / dekor'),
    'w05446': ('geveze', 'geveze / konuşkan'),
    'w05449': ('düşünce', 'düşünce / derin düşünme'),
    'w05450': ('barışma', 'barışma / uzlaşma'),
    'w05451': ('bilgili', 'bilgili / uzman'),
    'w05452': ('arızalı', 'arızalı / bozuk'),
    'w05453': ('verimsiz', 'kısır / verimsiz / boşuna'),
    'w05454': ('geveze', 'geveze / boşboğaz'),
    'w05456': ('uygulamak', 'koymak / sarmak / uygulamak (sargı, ceza)'),
    'w05457': ('ayar', 'ayar / ayarlama'),
    'w05459': ('endişeli', 'endişeli / telaşlı'),
    'w05460': ('kirletmek', 'kirletmek / lekelemek'),
    'w05461': ('çatırdamak', 'çatırdamak / (argo) durmadan konuşmak'),
    'w05463': ('şifonyer', 'şifonyer / çekmeceli dolap'),
    'w05465': ('vefat', 'vefat / ölüm'),
    'w05466': ('baraj', 'baraj / set'),
    'w05467': ('üzücü', 'can sıkıcı / üzücü'),
    'w05468': ('düzenli olarak', 'düzenli olarak'),
    'w05471': ('kasiyer', 'kasiyer / veznedar'),
    'w05472': ('ürün', 'ürün / mamul'),
    'w05473': ('hurafe', 'batıl inanç / hurafe'),
    'w05474': ('harap etmek', 'boşaltmak / harap etmek / yağmalamak'),
    'w05476': ('kırkmak', 'kesmek (saç) / kırkmak / kırpmak'),
    'w05477': ('çevirmek', 'çevirmek / ters yüz etmek'),
    'w05478': ('kulaklık', 'kulaklık / (casus) muhbir'),
    'w05479': ('tanıtmak', 'tanıtmak / reklam yapmak'),
    'w05480': ('kırkmak', 'kısaltmak / budamak / (araba) önüne kırmak'),
    'w05481': ('haklı', 'haklı / gerekçeli / aklanmış'),
    'w05482': ('halef', 'halef / vâris'),
    'w05483': ('akort etmek', 'ayarlamak / akort etmek / (kanal) ayarlamak'),
    'w05484': ('ısrarlı', 'ısrarlı / acil'),
    'w05486': ('kama', 'kama / takoz'),
    'w05487': ('ölümcül', 'ölümcül / ölesiye'),
    'w05488': ('pişman olmak', 'pişman olmak'),
    'w05489': ('kanatlandırmak', 'sevindirmek'),
    'w05490': ('içtenlik', 'içtenlik / samimiyet'),
    'w05491': ('kasa', 'kasa (araç) / sepet'),
    'w05492': ('palmiye', 'palmiye / avuç içi'),
    'w05493': ('kazançlı', 'kârlı / kazançlı'),
    'w05495': ('sac', 'teneke / sac / (argo) rezalet'),
    'w05496': ('iskandil', 'iskandil / (açık artırma) lot'),
    'w05497': ('sahtekâr', 'sahte iddiacı'),
    'w05498': ('pamuk', 'pamuk (tıbbi) / vatka'),
    'w05499': ('ritim', 'ölçü (müzik) / nezaket / ritim'),
    'w05500': ('dayak', 'dayak / kırbaçlama'),
    'w05501': ('devasız', 'tedavisi olmayan / iyileşmez'),
    'w05503': ('afyon', 'afyon / opiyum'),
    'w05504': ('taç yaprağı', 'taç yaprağı / yaprak'),
    'w05506': ('yalamak', 'yalamak / yalayıp temizlemek'),
    'w05507': ('alenen', 'alenen / herkesin önünde'),
    'w05509': ('içtihat', 'emsal / içtihat'),
    'w05510': ('terör', 'terör / dehşet'),
    'w05511': ('çit', 'çit / çevre duvarı'),
    'w05512': ('eskimiş', 'eskimiş / demode'),
    'w05513': ('işe alma', 'kiralama / işe alma'),
    'w05514': ('doğrudan', 'doğrudan / bizzat'),
    'w05515': ('uğultu', 'uğultu / gümbürtü'),
    'w05516': ('frengi', 'frengi / sifilis'),
}

DROP = {
    'w05426': 'франциско',
    'w05440': 'женева',
    'w05445': 'осака',
    'w05505': 'барселона',
    'w05508': 'дог',
}
