# -*- coding: utf-8 -*-
"""B2 inceleme, parti 12."""

FIXES = {
    'w06122': ('emilim, satın alma (şirket)', 'emilme / (şirket) satın alma / yutma'),
    'w06123': ('mahpus', 'mahpus / esir'),
    'w06126': ('işaretlemek', 'işaretlemek / nişan almak'),
    'w06127': ('temel', 'temel / köklü'),
    'w06130': ('kasaba', 'kasaba / küçük köy'),
    'w06132': ('bekçi', 'bekçi / nöbetçi'),
    'w06133': ('resepsiyonist', 'resepsiyonist / kapıcı (otel)'),
    'w06134': ('kalmak', 'bulunmak / kalmak'),
    'w06135': ('neşeli kimse', 'neşeli kişi / şakacı'),
    'w06137': ('atlas', 'atlas / saten'),
    'w06139': ('bolluk', 'bolluk / bereket'),
    'w06140': ('yakıt', 'yakıt (sıfat)'),
    'w06141': ('atlı', 'atlı / at (sıfat)'),
    'w06142': ('olgunluk', 'olgunluk / yetişkinlik'),
    'w06144': ('ayartmak', 'ayartmak / baştan çıkarmak / denemek'),
    'w06145': ('kısaltmak', 'kısaltmak / azaltmak / (işten) çıkarmak'),
    'w06147': ('bilinmeyen', 'bilinmeyen / gizemli'),
    'w06148': ('kaymaklı', 'kaymaklı / krema (sıfat)'),
    'w06149': ('deneyimsiz', 'deneyimsiz / acemi'),
    'w06150': ('söndürmek', 'söndürmek / (borç) ödemek'),
    'w06151': ('alaycı', 'alaycı / ironik'),
    'w06154': ('bostan korkuluğu', 'korkuluk / ürkütücü şey'),
    'w06155': ('sonradan', 'sonradan / ilerleyen zamanda'),
    'w06156': ('fuaye', 'fuaye / giriş salonu'),
    'w06159': ('çekicilik', 'çekicilik / cazibe'),
    'w06160': ('yoğunluk', 'yoğunluk / sıklık'),
    'w06161': ('kaçınma', 'kaçınma / kaçış'),
    'w06163': ('rengarenk', 'gökkuşağı renginde / parlak'),
    'w06164': ('cömertçe', 'cömertçe / bol bol'),
    'w06166': ('sahip', 'sahip (kadın)'),
    'w06167': ('lider', 'lider / önder'),
    'w06168': ('dahil etmek', 'dahil etmek / sürüklemek'),
    'w06169': ('mezar taşı', 'mezar taşı / anıt mezar'),
    'w06171': ('vapur', 'vapur / buharlı gemi'),
    'w06174': ('gayrimeşru', 'evlilik dışı'),
    'w06175': ('kardeşçe', 'kardeşçe / kardeşlik'),
    'w06177': ('bahçe', 'küçük park / meydan bahçesi'),
    'w06178': ('tespit', 'kurma / tespit'),
    'w06179': ('çelişik', 'çelişkili / tartışmalı'),
    'w06180': ('ast', 'ast / emrindeki kişi'),
    'w06181': ('fırlatmak', 'fırlatmak / savurmak'),
    'w06182': ('yazar', 'yazar (kadın)'),
    'w06183': ('nasır', 'nasır / kabarcık'),
    'w06184': ('muhatap', 'muhatap / konuşulan kişi'),
    'w06187': ('açığa çıkarmak', 'duyurmak / açıklamak'),
    'w06190': ('oluşturma', 'oluşturma / kurma / sıralanma'),
    'w06192': ('ortaç', 'ortaç / komünyon'),
    'w06194': ('ahlaken', 'ahlaken / manen'),
    'w06196': ('aşı', 'aşı / aşılama'),
    'w06197': ('güvensizlik', 'güvensizlik / kararsızlık'),
    'w06198': ('yaptırım', 'yaptırım / onay'),
    'w06201': ('birleşmek', 'birleşmek / bir araya gelmek'),
    'w06202': ('dost', 'dostane / dost'),
    'w06203': ('atıf', 'gönderme / atıf'),
    'w06204': ('aktarma', 'aktarma / taşıma / (satır) bölme'),
    'w06207': ('taşikardi', 'taşikardi / hızlı kalp atışı'),
    'w06208': ('alt üst etmek', 'tahrip etmek / yağmalamak / bozguna uğratmak'),
    'w06209': ('dalkavukluk', 'dalkavukluk / pohpohlama'),
    'w06210': ('külah', 'boru / külah (dondurma) / emzik (biberon)'),
    'w06211': ('evlendirmek', 'evlendirmek (erkeği)'),
    'w06212': ('reçine', 'reçine / zift'),
    'w06213': ('ölçülü', 'ılımlı / ölçülü / orta'),
    'w06216': ('çit', 'çit / duvar'),
    'w06217': ('kaynaşmak', 'birleşmek / bağlanmak'),
    'w06218': ('hokey diski', 'hokey diski / rondela'),
    'w06219': ('deney tüpü', 'deney tüpü / test tüpü'),
    'w06220': ('çalmak (araç), kaçırmak', '(araç) çalmak / kaçırmak / sürüp götürmek'),
    'w06221': ('dümen', 'dümen / yönetim'),
    'w06222': ('tonoz', 'tonoz / kemer / (kanunlar) derlemesi'),
    'w06223': ('çarpmak', 'vurmak / çarpmak'),
    'w06225': ('cihaz', 'aygıt / alet / uyum sağlama'),
    'w06229': ('lehçe', 'lehçe / şive'),
    'w06232': ('mevcut', 'sayı / mevcut / nüfus'),
    'w06233': ('bozukluk', 'bozulma / bozukluk / nazar'),
    'w06234': ('bükmek', 'bükmek / eğmek'),
    'w06235': ('kirletmek', 'kirletmek / lekelemek'),
    'w06236': ('elveda demek', 'vedalaşmak / elveda demek'),
    'w06237': ('sarmaşık', 'sarmaşık (tropik) / liyan'),
    'w06238': ('arıza', 'arıza / bozulma'),
    'w06239': ('aygıtlar', 'cihazlar / donanım'),
    'w06240': ('özgü', 'özgü / doğasında olan'),
    'w06241': ('ortaya çıkma', 'ortaya çıkma / doğuş'),
    'w06243': ('toplam', 'toplam / hepsi'),
    'w06244': ('vandallık', 'vandalizm / tahribat'),
    'w06246': ('bilmek anlamak', 'bilmek / yönetmek / idare etmek'),
    'w06247': ('süre', 'süre / uzunluk'),
    'w06249': ('sıkıca', 'sıkıca / zor (paraya)'),
    'w06250': ('akmak', 'akmak / dökülmek'),
    'w06251': ('patolojik', 'patolojik / hastalıklı'),
    'w06252': ('akmak', 'akmak / sızıntı'),
    'w06253': ('bol', 'geniş / ferah'),
    'w06255': ('günah işlemek', 'günah işlemek / hata yapmak'),
    'w06256': ('esnemek', 'esnemek / dalgınlıkla bakmak'),
    'w06257': ('topuk', 'topuk (ayak)'),
    'w06259': ('şiddetli', 'çılgın / şiddetli'),
    'w06260': ('duyulmak', 'duyulmak / yankılanmak'),
    'w06261': ('yeniden yapmak', 'yeniden yapmak / değiştirmek'),
    'w06262': ('ürkmek', 'çok korkmak / ürkmek'),
    'w06264': ('geri dönülmez', 'geri döndürülemez'),
    'w06265': ('kesin', 'kesin / kategorik'),
    'w06267': ('fırıncı', 'fırıncı / ekmekçi'),
    'w06268': ('taraftar', 'taraftar / seyirci (spor)'),
    'w06269': ('üstesinden gelmek', 'başarmak / üstesinden gelmek'),
    'w06270': ('önemli ölçüde', 'önemli ölçüde / ciddi biçimde'),
    'w06271': ('gaf', 'dikkatsizlik / gaf'),
    'w06272': ('tedarik', 'tedarik / ikmal'),
    'w06273': ('çizgi', 'çizgi / fırça darbesi / ayrıntı'),
    'w06274': ('direnmek', 'inat etmek / direnmek'),
    'w06275': ('kısacası', 'kısaca / özetle'),
    'w06276': ('hamal', 'hamal / yükleyici'),
    'w06277': ('güçlendirmek', 'güçlendirmek / artırmak'),
    'w06278': ('kâhin', 'kâhin / vahiy (kehanet)'),
    'w06279': ('kullanım', 'kullanım / yararlanma'),
    'w06280': ('öfke', 'öfke / kızgınlık / isyan'),
    'w06282': ('hiyeroglif', 'hiyeroglif / işaret'),
    'w06283': ('yakışıksız', 'yakışıksız / uygunsuz'),
    'w06284': ('tepki verme', 'tepki verme / karşılık'),
    'w06285': ('tırmık', 'tırmık / (mecaz) hata'),
    'w06287': ('söz vermek', 'vaat etmek / söz vermek'),
    'w06289': ('esriklik', 'coşku / vecd'),
    'w06293': ('ihtiyaç', 'ihtiyaç / gereklilik'),
    'w06295': ('sünnet', 'sünnet / kesme'),
    'w06296': ('fön makinesi', 'saç kurutma makinesi / fön'),
    'w06297': ('kaba adam', 'kaba herif / terbiyesiz'),
    'w06299': ('ön ek', 'ön ek / ek cihaz / konsol'),
    'w06300': ('tarak', 'tarak / (horoz) ibik / (dalga) doruk'),
    'w06301': ('doğru', 'doğru (çizgi) / düz hat'),
    'w06302': ('göç', 'göç / göçmenlik'),
    'w06304': ('kilit', 'sürgü / kilit (silah) / kapak'),
    'w06305': ('veranda', 'veranda / sundurma'),
    'w06307': ('diyagram', 'diyagram / grafik'),
    'w06309': ('ani çekiş', 'ani çekiş / atılım / hamle'),
    'w06310': ('zan', 'tahmin / varsayım / uydurma'),
    'w06311': ('boşluk', 'boşluk / vakum'),
    'w06312': ('vinil', 'vinil / plak'),
    'w06314': ('cadde', 'cadde / bulvar'),
    'w06315': ('gagalamak', 'gagalamak / yem yemek'),
    'w06317': ('omuzluk', 'omuz apoleti / rütbe'),
    'w06318': ('sevgili', 'sevgili / öz / yakın'),
    'w06320': ('analoji', 'benzetme / analoji'),
    'w06321': ('barikat', 'barikat / engel'),
    'w06322': ('Kazak', 'Kozak (Cossack)'),
    'w06323': ('örmek', 'örmek / (yalan) uydurmak'),
    'w06325': ('aptallık', 'aptallık / kütlük'),
}

DROP = {
    'w06294': 'кок',
    'w06242': 'косичка',
}
