# -*- coding: utf-8 -*-
"""B2 inceleme, parti 3."""

FIXES = {
    'w04303': ('basamak', 'basamak / kademe'),
    'w04304': ('katılan', 'hazır bulunan / katılan'),
    'w04305': ('hazırlama', 'hazırlama / pişirme'),
    'w04310': ('anekdot', 'fıkra'),
    'w04313': ('aciz', 'güçsüz / aciz'),
    'w04315': ('dolaşmak', 'dolaşmak / etrafından geçmek / kaçınmak'),
    'w04317': ('yayınlamak', 'yayımlamak / (ses) çıkarmak'),
    'w04318': ('kafeterya', 'büfe / küçük lokanta'),
    'w04320': ('sonda', 'sonda / prob'),
    'w04321': ('iyileştirmek', 'iyileştirmek / şifa vermek'),
    'w04322': ('niyetini anlamak', 'dişle kırmak / niyetini anlamak'),
    'w04324': ('tasarruf etmek', 'tasarruf etmek / idareli kullanmak'),
    'w04325': ('saplamak', 'saplamak / (odun) yarmak / iğnelemek'),
    'w04326': ('adliye', 'adalet / adliye'),
    'w04328': ('katedral', 'katedral / büyük kilise'),
    'w04329': ('kötü', 'berbat / kötü'),
    'w04330': ('nekahet', 'iyileşme'),
    'w04331': ('çürük', 'çürük / bozuk'),
    'w04333': ('takılma', 'parti / takılma (argo) / topluluk'),
    'w04334': ('doruk', 'tepe / zirve / üst kesim'),
    'w04337': ('paralı', 'para (sıfat) / parayla ilgili'),
    'w04339': ('kamyonet', 'kamyonet / pikap'),
    'w04340': ('kabakulak', 'kabakulak / (küçük) domuz'),
    'w04342': ('ilahi', 'marş / ilahi'),
    'w04343': ('dikizlemek', 'gizlice bakmak / dikizlemek'),
    'w04346': ('çimen', 'çimenlik / çim'),
    'w04349': ('mücevher kutusu', 'mücevher kutusu / küçük kutu'),
    'w04350': ('sürünmek', 'sürünerek gitmek / yavaş gitmek'),
    'w04351': ('esaslı', 'önemli / esaslı'),
    'w04353': ('çorabın teki', 'uzun çorap / külotlu çorap'),
    'w04355': ('başbakan', 'başbakan'),
    'w04357': ('yaymak', 'yaymak / dağıtmak'),
    'w04360': ('yemeğe katılan malzemeler', 'malzeme / bileşen'),
    'w04361': ('ıstırap', 'ıstırap / eziyet'),
    'w04362': ('sıradan', 'alışılmış / tanıdık'),
    'w04363': ('acı verici', 'acı verici / eziyetli'),
    'w04364': ('geçme', 'geçiş / yol / bilet ücreti'),
    'w04365': ('esaret', 'esaret / tutsaklık'),
    'w04366': ('sığlık', 'sığlık / kum bankı'),
    'w04367': ('tatil beldesi', 'tatil yeri / kaplıca'),
    'w04368': ('venüs', 'Venüs'),
    'w04372': ('donmak', 'donmak / üşümek'),
    'w04373': ('sıkmak', 'sıkmak / uzatmak / çekmek'),
    'w04374': ('kompozisyon', 'kompozisyon / eser / beste'),
    'w04375': ('tüzük', 'tüzük / yönetmelik'),
    'w04376': ('ayıklamak', 'seçmek / elinden almak'),
    'w04377': ('acayip', 'tuhaf / garip'),
    'w04378': ('arife günü', 'önceki gün / arifesinde'),
    'w04379': ('rehber', 'rehber / kondüktör / iletken'),
    'w04381': ('götürmek, taşımak (alıp götürmek)', 'götürmek / alıp götürmek'),
    'w04383': ('eğilim', 'eğilim / yatkınlık'),
    'w04384': ('ayırmak', 'ayırmak / seyreltmek / yetiştirmek'),
    'w04385': ('askeri selam', 'havai fişek / selam'),
    'w04386': ('dilekçe', 'dilekçe / talep'),
    'w04387': ('işleme', 'yapma / işleme (suç)'),
    'w04391': ('banyo', 'hamam / sauna'),
    'w04394': ('idareci', 'yönetici / görevli'),
    'w04396': ('sihirbaz', 'sihirbaz / hokkabaz'),
    'w04397': ('iskele', 'iskele / rıhtım'),
    'w04398': ('eşkıya', 'eşkıya / katil'),
    'w04399': ('tereddüt etmek', 'tereddüt etmek / dalgalanmak'),
    'w04400': ('sahipsiz', 'kimsenin olmayan / sahipsiz'),
    'w04401': ('asistan', 'asistan (kadın)'),
    'w04402': ('resim', 'teknik çizim / plan'),
    'w04405': ('plastik', 'plastik (biçimlendirilebilir) / estetik (ameliyat)'),
    'w04406': ('düzeltmek', 'düzeltmek / onarmak'),
    'w04407': ('alçalmak', 'alçalmak / inmek / batmak'),
    'w04410': ('pakistan', 'Pakistan'),
    'w04411': ('Rus', "Rusya'ya ait / Rus"),
    'w04413': ('sezgi', 'sezgi / koku alma'),
    'w04415': ('av uçağı', 'avcı uçak / yok edici'),
    'w04417': ('merhamet', 'merhamet / bağışlama'),
    'w04418': ('gardırop', 'gardırop / vestiyer'),
    'w04419': ('karışmak', 'karışmak / bulaşmak'),
    'w04422': ('meşru müdafaa', 'kendini savunma / meşru müdafaa'),
    'w04423': ('düzelmek', 'düzelmek / kendini düzeltmek'),
    'w04424': ('ahlaksız', 'ahlaksız / kusurlu'),
    'w04425': ('serum', 'serum'),
    'w04426': ('sıçrama', 'sıçrama / ani artış'),
    'w04433': ('bulut', 'kara bulut'),
    'w04434': ('söndürmek', 'söndürmek / (borç) kapatmak'),
    'w04442': ('şah', 'şah / (satranç) şah'),
    'w04443': ('istemek', 'sormak / talep etmek / istemek'),
    'w04445': ('acımasız', 'acımasız / kalpsiz'),
    'w04446': ('izlemek', 'izini sürmek / gözetlemek'),
    'w04448': ('uykuya dalmak', 'uykuya dalmak / doldurmak / serpmek'),
    'w04453': ('nafile', 'boşuna / nafile'),
    'w04457': ('taksi şoför', 'taksi şoförü'),
    'w04458': ('arıza', 'arıza / aksama'),
    'w04463': ('bankamatik', 'ATM / bankamatik'),
    'w04466': ('bulunmak', 'bulunmak / içinde olmak / tutulmak'),
    'w04467': ('hasretini çekmek', 'özlemek / hasret çekmek'),
    'w04469': ('manzara', 'manzara / peyzaj'),
    'w04471': ('soymak', 'soymak (giysi) / soyundurmak'),
    'w04473': ('arazi aracı', 'arazi aracı / SUV'),
    'w04474': ('çağrılış', 'çağrı / askere çağırma'),
    'w04477': ('inilti', 'inleme'),
    'w04479': ('mezar', 'mezar / anıt mezar'),
    'w04480': ('itaat etmek', 'itaat etmek / sözünü dinlemek'),
    'w04481': ('tırmanış', 'yükseliş / tırmanış / kalkış'),
    'w04482': ('ayak', 'ayak tabanı / ayak'),
    'w04484': ('as', 'as (kart)'),
    'w04485': ('kap', 'kase / tas'),
    'w04486': ('uygar', 'medeni / uygar'),
    'w04487': ('kin', 'kin / öfke'),
    'w04488': ('kaymak', 'krema / süt kaymağı'),
    'w04489': ('bez', 'bez (anatomi)'),
    'w04492': ('iğrenç', 'iğrenç / aşağılık'),
    'w04493': ('cep boyu', 'cep (sıfat) / cep boyu'),
    'w04494': ('müteahhit', 'müteahhit / yüklenici'),
    'w04495': ('viking', 'Viking'),
    'w04498': ('sarsmak', 'havaya uçurmak / (sağlığı) bozmak / baltalamak'),
    'w04499': ('cellat', 'cellat'),
    'w04500': ('tarikat', 'tarikat / mezhep'),
    'w04501': ('işlemek', 'işlemek / işlemden geçirmek'),
    'w04502': ('dikkate almak', 'dikkate almak / hesaba katmak'),
    'w04503': ('yön', 'yön / açı'),
    'w04504': ('azarlamak', 'azarlamak / küfretmek'),
}

DROP = {
    'w04338': 'бек',
    'w04444': 'человечек',
    'w04470': 'поп',
}
