# -*- coding: utf-8 -*-
"""B2 inceleme, parti 2."""

FIXES = {
    'w04100': ('şaşırtmak', 'şaşırtmak / vurmak / yenmek'),
    'w04102': ('kılıç ağzı', 'bıçak ağzı / kılıç'),
    'w04104': ('öne sürmek', 'öne sürmek / aday göstermek / (çekmece) çekmek'),
    'w04108': ('damlacık', 'damla / damlacık'),
    'w04111': ('ailecik', 'aile (günlük dil)'),
    'w04112': ('yandaş', 'takipçi / izleyici'),
    'w04114': ('serbest bırakmak', 'serbest bırakmak / kurtarmak / boşaltmak'),
    'w04115': ('cins, ırk (hayvan)', 'cins / ırk (hayvan) / kaya (jeoloji)'),
    'w04117': ('adım atmak', 'yürümek / adım atmak'),
    'w04118': ('at ahırı', 'ahır (at)'),
    'w04119': ('beslemek', 'beslemek / (duygu) beslemek'),
    'w04120': ('düz', 'düz / yassı'),
    'w04124': ('amaç', 'amaç / kader'),
    'w04126': ('aynı ana denk gelmek', 'denk gelmek / örtüşmek'),
    'w04128': ('eşmek', 'eşelemek / karıştırmak'),
    'w04132': ('bitirmek', 'bitirmek / mezun olmak'),
    'w04134': ('iç karartıcı', 'kasvetli / hüzünlü'),
    'w04135': ('iade', 'iade / geri dönüş'),
    'w04136': ('kavramak', 'anlamak / düşünmek / kavramak'),
    'w04139': ('dayanıklı', 'dayanıklı / sebatkâr'),
    'w04142': ('imaj', 'imaj / itibar'),
    'w04143': ('kamp ateşi', 'ateş (açık) / kamp ateşi'),
    'w04144': ('destek', 'destek / dayanak / direk'),
    'w04146': ('tetik', 'tetik / horoz (silah)'),
    'w04149': ('çoğul', 'çoğul / çok sayıda'),
    'w04154': ('partilemek', 'kopmak / ayrılmak / (argo) eğlenmek'),
    'w04155': ('yalıtım', 'yalıtım / tecrit'),
    'w04156': ('misilleme yapmak', 'intikam almak'),
    'w04163': ('seçenek', 'seçenek / alternatif'),
    'w04165': ('protein', 'protein / (yumurta) akı'),
    'w04168': ('korumak', 'korumak / esirgemek'),
    'w04169': ('girmek', 'girmek / nüfuz etmek / sızmak'),
    'w04170': ('adale', 'kas'),
    'w04173': ('bağlılık', 'bağlılık / sevgi'),
    'w04175': ('kâğıt para', 'banknot / kâğıt para'),
    'w04178': ('köy', 'köy (büyük)'),
    'w04179': ('kasaplık', 'öldürücü / etkili (argo)'),
    'w04182': ('tahmin etmek', 'hesaplamak / tahmin etmek'),
    'w04185': ('eser', 'eser / yaratık'),
    'w04188': ('koşu', 'koşu / yarış'),
    'w04189': ('kuaför', 'kuaför / berber'),
    'w04190': ('dikkat', 'ihtiyat / dikkat'),
    'w04191': ('ulaşmak', 'ulaşmak / erişmek'),
    'w04195': ('beslemek', 'yetiştirmek (hayvan) / seyreltmek / boşamak'),
    'w04196': ('gerçek', 'gerçek / hakiki'),
    'w04197': ('komedyen', 'komedyen / komik oyuncu'),
    'w04198': ('vermek', 'vermek (nitelik) / eklemek'),
    'w04200': ('yaklaşık', 'yaklaşık / tahmini'),
    'w04201': ('ziyafet', 'ziyafet / resepsiyon'),
    'w04202': ('düşüncesiz', 'akılsız / gözü kara'),
    'w04208': ('genel durum', 'hâl / sağlık durumu'),
    'w04210': ('koordinatör', 'dispeçer / sevk memuru'),
    'w04211': ('tamirci', 'tamirci / makinist'),
    'w04213': ('saplamak', 'saplamak / takmak'),
    'w04214': ('perde', 'perde / jaluzi'),
    'w04215': ('sarsıntı', 'sarsıntı / (beyin) sarsıntısı'),
    'w04217': ('eğitmek', 'eğitmek / öğretmek'),
    'w04219': ('titreşim', 'titreşim / tereddüt / dalgalanma'),
    'w04220': ('çıkış', 'çıkış / (araçla) ayrılma'),
    'w04221': ('pişirmek', 'kaynatmak / pişirmek'),
    'w04222': ('eşkıya', 'eşkıya / haydut'),
    'w04223': ('bitki örtüsü', 'bitki örtüsü / flora'),
    'w04227': ('talep', 'talep / sorgulama'),
    'w04228': ('seçkin', 'zarif / seçkin'),
    'w04230': ('jilet', 'ustura / jilet'),
    'w04231': ('sıvı', 'sıvı / sulu / seyrek'),
    'w04235': ('lif', 'lif / tel'),
    'w04236': ('üretici', 'üretici / imalatçı'),
    'w04237': ('yırtmak', 'yırtmak / soymak / dövmek'),
    'w04238': ('kapik', 'kopek (para)'),
    'w04239': ('iffet', 'bekâret'),
    'w04241': ('korku', 'korku / dehşet'),
    'w04242': ('tetikte', 'tetikte / teyakkuzda'),
    'w04243': ('köklü', 'köklü / radikal'),
    'w04245': ('tutkal', 'yapıştırıcı / tutkal'),
    'w04247': ('sağdıç', 'sağdıç / arkadaş (argo)'),
    'w04250': ('ton', 'renk tonu / nüans'),
    'w04251': ('gelin', 'gelin (oğlun karısı) / yenge'),
    'w04252': ('kucaklaşmak', 'sarılmak'),
    'w04253': ('akıl yürütmek', 'akıl yürütmek / tartışmak'),
    'w04254': ('gelişmek', 'gelişmek / refah içinde olmak'),
    'w04255': ('kod', 'şifre / kod'),
    'w04256': ('hareket', 'hareket / yer değiştirme'),
    'w04257': ('münhal', 'boş kadro / iş ilanı'),
    'w04258': ('tavlamak', 'fethetmek / boyun eğdirmek'),
    'w04259': ('geri çekilme', 'geri çekilme / ayrılma / atık'),
    'w04260': ('anlamak', 'sökmek / anlamak / ayrıştırmak'),
    'w04261': ('gofret', 'gofret / waffle'),
    'w04262': ('yatırım yapmak', 'yatırmak (para) / içine koymak'),
    'w04263': ('baskı', 'baskı / yayın'),
    'w04264': ('inceleme', 'inceleme / değerlendirme'),
    'w04266': ('sneaker', 'spor ayakkabı'),
    'w04268': ('beyin inmesi', 'inme / felç'),
    'w04270': ('methiye', 'övgü'),
    'w04271': ('at arabası', 'at arabası (lüks) / fayton'),
    'w04272': ('akıtmak', 'doldurmak / dökmek'),
    'w04273': ('ambar', 'ambar / depo'),
    'w04274': ('firar', 'kaçış / firar'),
    'w04277': ('ezberlemek', 'hatırlamak / aklında tutmak'),
    'w04279': ('ayıklama', 'seçim / eleme'),
    'w04281': ('kalkış', 'kalkış (uçak) / uçuş'),
    'w04283': ('kanadalı', "Kanada'ya ait / Kanadalı"),
    'w04284': ('fakirlik', 'yoksulluk'),
    'w04287': ('tiyatro', 'tiyatro (sıfat)'),
    'w04291': ('yük', 'yük / iş yükü'),
    'w04292': ('düşman', 'düşmanca'),
    'w04296': ('yardım', 'yardım / destek'),
    'w04297': ('biçmek', 'kesmek / kısaltmak'),
    'w04299': ('katlamak', 'katlamak / toplamak / üst üste koymak'),
    'w04300': ('saygısız', 'kaba / nezaketsiz'),
    'w04301': ('hatalı', 'yanlış / hatalı'),
}

DROP = {
    'w04103': 'вест',
    'w04137': 'атлант',
    'w04212': 'венеция',
    'w04267': 'икс',
    'w04282': 'сладенький',
}
