# -*- coding: utf-8 -*-
"""B2 inceleme, parti 7."""

FIXES = {
    'w05113': ('belirsiz', 'belirsiz / bulanık'),
    'w05119': ('pupa', 'kıç (gemi) / yem'),
    'w05120': ('eylem', 'eylem / iş'),
    'w05124': ('götürmek', 'varış yerine kadar götürmek'),
    'w05125': ('yaklaşık', 'yaklaşık / örnek (davranış)'),
    'w05126': ('tekli', 'tekli / tek'),
    'w05127': ('ayrı ayrı', 'ayrı ayrı / ayrıca'),
    'w05128': ('örmek', 'örmek / bağlamak'),
    'w05129': ('iki (kart/not)', 'iki (rakam) / kötü not / ikili'),
    'w05133': ('eşsiz', 'eşsiz / muhteşem'),
    'w05134': ('rütbe', 'rütbe / derece'),
    'w05136': ('chat', 'sohbet / chat'),
    'w05137': ('diş tabibi', 'diş hekimi'),
    'w05138': ('düzenlemek', 'düzenlemek / organize etmek'),
    'w05139': ('anlaşılmaz', 'açıklanamaz / anlaşılmaz'),
    'w05143': ('kuyu (petrol/su kuyusu)', 'sondaj kuyusu / kuyu'),
    'w05144': ('engel', 'engel / bariyer'),
    'w05145': ('yaymak', 'dağıtmak / yaymak / paramparça etmek'),
    'w05147': ('kulübe', 'kulübe / köy evi'),
    'w05148': ('sinirlendirmek', 'sinirlendirmek / gerginleştirmek'),
    'w05149': ('başlamak', 'başlamak / start almak'),
    'w05150': ('şefkat', 'yumuşaklık / şefkat'),
    'w05151': ('artmak', 'artmak / büyümek'),
    'w05152': ('anma yemeği', 'anma yemeği / yas yemeği'),
    'w05153': ('birlik', 'birlik / bütünlük'),
    'w05155': ('gübre', 'gübre (hayvan)'),
    'w05156': ('tıbbi', 'hekime ait / tıbbi'),
    'w05160': ('ayartma', 'ayartma / cazibe / günaha teşvik'),
    'w05162': ('tasma', 'tasma / boyunluk'),
    'w05163': ('düzlük', 'ova / düzlük'),
    'w05165': ('istikrarlı', 'sağlam / kararlı / dayanıklı'),
    'w05167': ('bodrum', 'kiler / mahzen'),
    'w05168': ('şafak', 'şafak / alacakaranlık'),
    'w05171': ('şımartmak', 'dağıtmak / şımartmak / (saçı) salmak'),
    'w05172': ('servis', 'servis / hizmet'),
    'w05176': ('cazibeli', 'cazip / ayartıcı'),
    'w05177': ('para', 'döviz / para birimi'),
    'w05179': ('yakınlaşma', 'yaklaşma / yaklaşım'),
    'w05180': ('sürtmek', 'boş boş gezmek / aylak aylak dolaşmak'),
    'w05181': ('feryat', 'feryat / çığlık'),
    'w05183': ('parlamak', 'parlamak / parıldamak'),
    'w05184': ('binyıl', 'binyıl / bin yıllık dönem'),
    'w05185': ('boğum', 'düğüm / olay örgüsünün başlangıcı'),
    'w05186': ('gözde', 'gözde / sevilen (kişi)'),
    'w05187': ('aracı', 'komisyoncu / borsa aracısı'),
    'w05190': ('uygun', 'uygun / kullanılabilir'),
    'w05192': ('çıkarmak', 'çıkarmak / dışarı almak'),
    'w05193': ('çalıntı', 'çalıntı'),
    'w05195': ('sürdürme', 'sürdürme / koruma'),
    'w05196': ('iğneli', 'dikenli / batıcı'),
    'w05197': ('belirmek', 'belirmek / ortaya çıkmak'),
    'w05198': ('bastırmak (sesi), susturmak', 'susturmak / (motor) durdurmak / bastırmak'),
    'w05200': ('kalabalık', 'kalabalık / topluluk'),
    'w05201': ('okşamak', 'okşamak / sevmek'),
    'w05202': ('alçı', 'alçı / alçıtaşı'),
    'w05203': ('etken', 'etken / faktör'),
    'w05205': ('uygun', 'uygun / işe yarar'),
    'w05207': ('muhtar', 'muhtar / (sınıf) başkanı'),
    'w05208': ('ben (leke), nişangâh', 'ufak sinek / nişangâh / ben (yüzde)'),
    'w05209': ('manastır', 'manastır (başrahip idaresinde)'),
    'w05211': ('çarpışma', 'çatışma / kavga'),
    'w05212': ('fransız kadını', 'Fransız kadın'),
    'w05213': ('tık', 'fiskeleme / tık'),
    'w05215': ('cezbetmek', 'ayartmak / cezbetmek'),
    'w05220': ('karmaşa', 'karmaşa / kargaşa'),
    'w05222': ('coşku', 'coşku / hararet'),
    'w05224': ('sağgörülü', 'anlayışlı / sağgörülü'),
    'w05225': ('binme', 'sürme / binme / yolculuk'),
    'w05231': ('tekerlek izi', 'iz (tekerlek) / yol / çığır'),
    'w05232': ('göz', 'göz (sıfat)'),
    'w05233': ('keşfetmek', 'keşfetmek / bulmak / ortaya çıkarmak'),
    'w05234': ('tamir etmek', 'tamir etmek / onarmak'),
    'w05236': ('kiralık asker', 'paralı asker'),
    'w05237': ('kayak', 'kayak (tahta)'),
    'w05238': ('yatak', 'nehir yatağı'),
    'w05240': ('mirasçı', 'mirasçı (kadın)'),
    'w05241': ('farkındalık', 'bilinç / farkına varma'),
    'w05244': ('donmak (bilgisayar), asılı kalmak', 'donmak / asılı kalmak'),
    'w05245': ('sınırlamak', 'sınırlamak / kısıtlamak'),
    'w05247': ('kazma', 'kazma / kürek'),
    'w05249': ('açıklamak', 'açıklamak / anlatmak'),
    'w05251': ('tepkisel, jet (motor)', 'jet / tepkili / tepkisel'),
    'w05253': ('şanslı', 'şanslı / talihli'),
    'w05255': ('muska', 'muska / tılsım'),
    'w05256': ('çene çalmak', 'dedikodu yapmak'),
    'w05257': ('kabahat', 'kabahat / suç'),
    'w05260': ('şehit', 'şehit / mağdur'),
    'w05263': ('durağan', 'hareketsiz / durağan'),
    'w05264': ('güdümlü', 'yönetilebilir / güdümlü'),
    'w05265': ('bank', 'bank / sıra'),
    'w05266': ('anestezi', 'anestezi / uyuşturma'),
    'w05267': ('sembol olmak', 'simgelemek'),
    'w05268': ('uzman', 'uzman / bilir kişi'),
    'w05269': ('gazeteci', 'gazeteci (kadın)'),
    'w05271': ('sallamak', 'sallamak / savurmak'),
    'w05272': ('alçaltmak', 'düşürmek / azaltmak'),
    'w05273': ('ezberden', 'ezbere'),
    'w05274': ('lakap takmak', 'lakap takmak / adlandırmak'),
    'w05276': ('trans', 'trans / kendinden geçme hâli'),
    'w05278': ('hoşnutsuzluk', 'hoşnutsuzluk / memnuniyetsizlik'),
    'w05280': ('edinim', 'edinme / satın alma'),
    'w05282': ('acı çekmek', 'acı çekmek / eziyet çekmek / uğraşmak'),
    'w05283': ('teyakkuz', 'uyanıklık / teyakkuz'),
    'w05287': ('gürültü', 'gürültü / gümbürtü'),
    'w05289': ('iyileşmek', 'iyileşmek / düzelmek'),
    'w05290': ('sadece', 'basitçe / doğrudan'),
    'w05291': ('yıldönümü şenliği', 'yıldönümü / jübile'),
    'w05293': ('damlamak', 'damlamak / damlatmak'),
    'w05295': ('kas', 'kas (sıfat) / kasla ilgili'),
    'w05297': ('elektrik santralı', 'elektrik santrali'),
    'w05298': ('uçurum', 'uçurum / derinlik / sonsuzluk'),
    'w05299': ('dönmek', 'dönmek / döndürmek / çevresinde dolaşmak'),
    'w05300': ('tutam', 'tutam / yumak'),
    'w05301': ('şehirli', 'şehirli / kent sakini'),
    'w05302': ('patika', 'patika / keçi yolu'),
    'w05303': ('uşak', 'uşak / kâhya'),
    'w05307': ('salıncak', 'salıncak / tahterevalli'),
    'w05308': ('ifade', 'söylem / ifade / görüş'),
    'w05309': ('cezasız kalmış', 'cezasız kalan'),
    'w05311': ('havalimanı', 'küçük havaalanı / pist'),
    'w05312': ('akbaba', 'akbaba / leş yiyici'),
    'w05313': ('halat', 'halat / kablo'),
    'w05314': ('savunmak', 'savunmak / arka çıkmak'),
}

DROP = {
    'w05115': 'кое-куда',
    'w05246': 'торонто',
    'w05270': 'монреаль',
    'w05261': 'белоснежка',
}
