# -*- coding: utf-8 -*-
"""B2 inceleme, parti 10."""

FIXES = {
    'w05719': ('pazarlık', 'pazarlık / ihale'),
    'w05720': ('objektif', 'objektif / hedef'),
    'w05722': ('adapte olmak', 'uyum sağlamak'),
    'w05726': ('beşik', 'beşik / doğum yeri'),
    'w05728': ('temizlik', 'hijyen / temizlik'),
    'w05729': ('araba', 'at arabası / yük arabası'),
    'w05730': ('taşıyıcı', 'taşıyıcı / yük taşıyan'),
    'w05731': ('çaprazlamak', 'çaprazlamak / kavuşturmak'),
    'w05732': ('yardım etmek', 'yardım etmek / kurtarmak'),
    'w05733': ('öfkeli', 'öfkeli / hiddetli / şiddetli'),
    'w05736': ('dalaveracı', 'dolandırıcı (kadın)'),
    'w05737': ('çoğalmak', 'çoğalmak / üremek'),
    'w05738': ('can çekişme', 'can çekişme / ıstırap'),
    'w05740': ('dokuzlu', 'dokuz (rakam, kart)'),
    'w05741': ('kaliteli', 'kaliteli / nitelik (sıfat)'),
    'w05742': ('tür', 'tür / janr'),
    'w05745': ('testi', 'testi / sürahi'),
    'w05746': ('saman yığını', 'saman yığını / ot yığını'),
    'w05747': ('yarı', 'devre / yarı'),
    'w05748': ('çamur', 'çamur / balçık'),
    'w05751': ('kuru üzüm', 'kuru üzüm'),
    'w05752': ('koltukaltı', 'koltuk altı'),
    'w05753': ('abartmak', 'fazla değer biçmek / abartmak'),
    'w05755': ('toka, stiletto (topuk)', 'toka / topuklu (stiletto) / firkete'),
    'w05756': ('sunmak', 'teslim etmek / takdim etmek'),
    'w05757': ('kasıtlı', 'kasıtlı / bilerek'),
    'w05761': ('alkol', 'alkol / ispirto'),
    'w05763': ('naz', 'kapris / naz'),
    'w05764': ('omurga', 'omurga (gemi)'),
    'w05765': ('kriter', 'ölçüt / kriter'),
    'w05766': ('keçiyolu', 'patika / keçi yolu'),
    'w05773': ('yazara ait', 'yazara ait / telif'),
    'w05774': ('ötesinde', 'üstünde / fazla / ötesinde'),
    'w05775': ('fikir', 'fikir / plan'),
    'w05776': ('hizmet etme', 'hizmet / ibadet'),
    'w05777': ('sentetik', 'sentetik / yapay'),
    'w05778': ('asalet', 'asalet / soyluluk'),
    'w05779': ('anmak', 'anmak / hatırlamak'),
    'w05780': ('kabuk, (argo) kimlik', 'kabuk / ekmek kabuğu'),
    'w05782': ('güçlendirme', 'güçlendirme / tahkimat'),
    'w05783': ('bereket', 'fazlalık / bolluk'),
    'w05786': ('atıfta bulunmak', 'atıfta bulunmak / dayanmak'),
    'w05788': ('muhabir', 'muhabir / yazışma yapan'),
    'w05791': ('taşımak', 'taşımak / yerini değiştirmek'),
    'w05792': ('viral', 'viral / virüs (sıfat)'),
    'w05794': ('damariçi', 'damar içi / intravenöz'),
    'w05795': ('garnizon', 'garnizon / askeri birlik'),
    'w05796': ('teyze', 'teyze / hala / (argo) hanım'),
    'w05798': ('namahdut', 'sınırsız'),
    'w05799': ('burun', 'burun / yarımada ucu'),
    'w05800': ('rozet', 'priz / rozet'),
    'w05801': ('naip', 'naip / koro şefi'),
    'w05802': ('gerçekleştirmek', 'gerçekleştirmek / uygulamak'),
    'w05804': ('elverişli', 'elverişli / uygun'),
    'w05806': ('görevlendirmek', 'görevlendirmek / emanet etmek'),
    'w05807': ('eksik', 'eksik / bulunmayan'),
    'w05808': ('dağıtma', 'dağıtım / dağıtma'),
    'w05811': ('şaşı', 'eğri / çarpık / şaşı'),
    'w05812': ('takımyıldız', 'takımyıldız / burç'),
    'w05814': ('dürtmek', 'dürtmek / itmek / teşvik etmek'),
    'w05815': ('külotlu çorap', 'külotlu çorap / tayt'),
    'w05816': ('şablon', 'şablon / kalıp / klişe'),
    'w05818': ('kompozisyon', 'kompozisyon / beste'),
    'w05825': ('battaniye', 'örtü / yatak örtüsü / battaniye'),
    'w05827': ('zanaat', 'zanaat / sanat'),
    'w05828': ('bent', 'bent / set'),
    'w05829': ('hayaller kurmak', 'hayal kurmak / uydurmak'),
    'w05831': ('kişnemek', 'kişnemek / (argo) kahkaha atmak'),
    'w05833': ('sapkınlık', 'sapkınlık / çarpıtma'),
    'w05834': ('garantili', 'garantili / güvence altına alınmış'),
    'w05836': ('iflas ettirmek', 'iflas ettirmek / yıkmak / talan etmek'),
    'w05840': ('ışıklı', 'ışıklı / parlayan'),
    'w05841': ('çeşitli', 'çeşitli / çok yönlü'),
    'w05842': ('emperyal', 'imparatorluğa ait / emperyal'),
    'w05843': ('yeşillik', 'yeşillik / ot (sebze)'),
    'w05844': ('hacim', 'hacim / hacimli'),
    'w05845': ('partizan', 'gerilla / partizan'),
    'w05846': ('biriktirmek', 'koleksiyon yapmak / biriktirmek'),
    'w05847': ('etik', 'etik / ahlaki'),
    'w05848': ('kırbaçlamak, sökmek (dikişi)', 'kırbaçlamak / (dikiş) sökmek / saçmalamak'),
    'w05850': ('acımasız', 'vahşi / acımasız'),
    'w05851': ('lösemi', 'lösemi / kan kanseri'),
    'w05852': ('karşıtlık', 'karşı karşıya gelme / rekabet'),
    'w05853': ('değmek', 'dokunmak / değmek'),
    'w05854': ('aristokrat', 'aristokrat / soylu'),
    'w05855': ('kapsamak', 'kapsamak / sarmak'),
    'w05856': ('savurmak', 'atmak / fırlatmak'),
    'w05858': ('kürekkemiği', 'kürek (küçük) / kürek kemiği / spatula'),
    'w05861': ('düşürmek', 'düşürmek / (söz) bırakmak'),
    'w05862': ('öğrenmek, edinmek (bir beceriyi)', 'öğrenmek / edinmek / hâkim olmak'),
    'w05865': ('birleşik', 'birleşik / birleşmiş'),
    'w05866': ('rekabet etmek', 'rekabet etmek / yarışmak'),
    'w05867': ('önem', 'önem / anlam'),
    'w05870': ('sel', 'tufan / sel'),
    'w05872': ('sinirlenme', 'sinirlenme / rahatsızlık / tahriş'),
    'w05874': ('aylaklık etmek', 'aylaklık etmek / tembellik etmek'),
    'w05876': ('kapan', 'kapan / tuzak'),
    'w05877': ('küme', 'kalabalık / birikim'),
    'w05878': ('dayak', 'dayak / darp'),
    'w05880': ('dengesiz', 'dengesiz / kararsız'),
    'w05881': ('sel', 'çamur akıntısı / sel'),
    'w05882': ('söndürmek', 'söndürmek / (yemek) kısık ateşte pişirmek'),
    'w05883': ('eskiz', 'eskiz / taslak'),
    'w05884': ('kürek', 'kürek (kayık)'),
    'w05885': ('sinirlenmiş', 'sinirlenmiş / gergin'),
    'w05886': ('benzetim', 'benzetim / simülasyon'),
    'w05887': ('maddi', 'maddi / somut'),
    'w05888': ('suş', 'suş / tür'),
    'w05889': ('varil', 'varil / fıçı (küçük)'),
    'w05890': ('yemek', 'yemek / sofra'),
    'w05893': ('asistanlık etmek', 'yardımcı olmak / asistanlık yapmak'),
    'w05894': ('üstesinden gelmek', 'üstesinden gelmek / aşmak'),
    'w05895': ('kupür', 'kupür / fileto (et)'),
    'w05896': ('sehpa', 'altlık / sehpa / stand'),
    'w05897': ('kemirmek', 'kemirmek / çiğnemek'),
    'w05898': ('mukus', 'mukus / sümük'),
    'w05899': ('hırsız', 'hırsız (kırıp giren) / hacker'),
    'w05900': ('mucize kabilinden', 'mucize eseri / mucizevi biçimde'),
    'w05901': ('ortaklaşa', 'birlikte / ortaklaşa'),
    'w05902': ('korkuluk', 'korkuluk / tırabzan'),
    'w05903': ('torbacık', 'torba / keseli'),
    'w05905': ('navigasyon', 'seyrüsefer / navigasyon'),
    'w05907': ('taciz etmek', 'peşine düşmek / taciz etmek'),
    'w05908': ('yelpazelemek', 'şişirmek / körüklemek / abartmak'),
    'w05910': ('in', 'in / ayı yuvası'),
    'w05911': ('düşme', 'düşüş / gerileme'),
    'w05912': ('çürütülemez', 'çürütülemez / su götürmez'),
    'w05913': ('harap', 'bitkin / yorgun düşmüş'),
    'w05914': ('halk', 'halk / insanlar'),
    'w05915': ('ambar', 'ambar (gemi)'),
    'w05916': ('geri', 'geriye / ters yönde'),
    'w05917': ('geliştirmek', 'geliştirmek / iyileştirmek'),
    'w05918': ('suçlamak', 'sitem etmek / suçlamak'),
    'w05919': ('piliç', 'tavuk / piliç'),
    'w05920': ('keyfilik', 'keyfîlik / zorbalık'),
}

DROP = {
    'w05784': 'багдад',
    'w05810': 'марокко',
    'w05767': 'тату',
    'w05797': 'гадить',
    'w05809': 'строчок',
}
