# -*- coding: utf-8 -*-
"""B2 inceleme, parti 13."""

FIXES = {
    'w06326': ('doruk', 'doruk / zirve'),
    'w06329': ('iç', 'iç / iç organ'),
    'w06330': ('gizemci', 'gizemci / mistik'),
    'w06332': ('vahşi', 'vahşi / hayvani / (argo) müthiş'),
    'w06333': ('çarpıtma', 'çarpıtma / bozulma'),
    'w06334': ('telkin', 'telkin / azar / ikna'),
    'w06338': ('faydasız', 'kullanışsız / uygunsuz'),
    'w06339': ('durgunlaşmak', 'yatışmak / sakinleşmek'),
    'w06340': ('çekmek', 'cezbetmek / tuzağa çekmek'),
    'w06342': ('eğri', 'eğri / eğri çizgi'),
    'w06343': ('girdap', 'kasırga / girdap / hortum'),
    'w06344': ('biçmek', 'biçmek / (çim) kesmek / şaşı bakmak'),
    'w06345': ('yatak', 'yatak / nehir yatağı'),
    'w06346': ('yıllık', 'yıllık / her yıl olan'),
    'w06347': ('terazi', 'terazi / tartı'),
    'w06349': ('ateşli', 'ateşli / hararetli / fanatik'),
    'w06350': ('akıllı', 'akıllı / mantıklı / açıklamalı'),
    'w06351': ('robot resim', 'robot resim / kimlik tespit resmi'),
    'w06352': ('artmak', 'artmak / çoğalmak'),
    'w06354': ('sayman', 'sayman / haznedar'),
    'w06355': ('oluşmak', 'oluşmak / kurulmak'),
    'w06356': ('motor', 'motorlu / motor (sıfat)'),
    'w06359': ('kuyumcu', 'kuyumcu / mücevher ustası'),
    'w06360': ('düzensiz', 'düzensiz / karışık'),
    'w06361': ('adsızlık', 'anonimlik / kimliksizlik'),
    'w06362': ('yıkama', 'yıkama / yıkanma'),
    'w06365': ('hadım ağası', 'hadım / harem ağası'),
    'w06366': ('makinist', 'makinist / lokomotif sürücüsü'),
    'w06367': ('alçakgönüllülük', 'alçakgönüllülük / boyun eğme'),
    'w06370': ('mistisizm', 'mistisizm / gizemcilik'),
    'w06372': ('damga', 'damga / kalıp / klişe'),
    'w06374': ('baş melek', 'başmelek'),
    'w06375': ('nazar değdirmek', 'nazar değdirmek / gözlemek'),
    'w06378': ('çirkin', 'çirkin / rezil'),
    'w06379': ('pat', 'pat (satranç) / berabere'),
    'w06380': ('öğrenci', 'öğrenci / talebe'),
    'w06381': ('ipotek senedi', 'ipotek senedi / rehin belgesi'),
    'w06382': ('külçe', 'külçe / bar'),
    'w06383': ('kayık', 'kayık / bot'),
    'w06384': ('pranga', 'pranga / zincir'),
    'w06385': ('ışınsal', 'ışınsal / ışın (sıfat)'),
    'w06386': ('açı', 'açı / bakış açısı'),
    'w06387': ('atlet', 'atlet / sporcu'),
    'w06389': ('enzim', 'enzim / maya'),
    'w06390': ('tıkamak', 'tıkamak / (ağzı) kapatmak'),
    'w06393': ('hece bilmecesi', 'şarad / kelime oyunu'),
    'w06395': ('yansıtmak', 'yansıtmak / savuşturmak / püskürtmek'),
    'w06396': ('hücum etmek', 'hücum etmek / kuşatmak'),
    'w06397': ('kıvrım', 'kıvrım / viraj / bükülme'),
    'w06399': ('oluşturma', 'oluşturma / oluşum / birlik (askeri)'),
}
