# -*- coding: utf-8 -*-
"""B2 inceleme, parti 1."""

FIXES = {
    'w03902': ('antika', 'eski / eskiden kalma / antika'),
    'w03909': ('tarayıcı', 'tarayıcı / skaner'),
    'w03914': ('tırmanmak', 'tırmanmak / (içeri) girmek'),
    'w03920': ('karşılık olarak verilen', 'karşılık (sıfat) / cevap niteliğinde'),
    'w03921': ('toplanmak', 'ortalığı toplamak / temizlemek'),
    'w03922': ('geliştirmek', 'geliştirmek / hazırlamak (plan)'),
    'w03931': ('kesmek', 'kesip ayırmak / dilimlemek'),
    'w03932': ('küçük çan', 'çıngırak / çan çiçeği'),
    'w03933': ('mahkûm', 'mahkûm / tutuklu'),
    'w03935': ('korunmuş', 'korunaklı / güvenli'),
    'w03939': ('oluşmak', 'oluşmak / şekillenmek / katlanmak'),
    'w03943': ('kovmak', 'sürmek / kovmak'),
    'w03944': ('çakmak', 'çakmak / doldurmak / gol atmak'),
    'w03951': ('takım', 'takım / set'),
    'w03953': ('paylaştırmak', 'bölmek / paylaşmak'),
    'w03954': ('becerikli', 'çevik / becerikli'),
    'w03956': ('şaka', 'şaka / (argo) komik şey'),
    'w03957': ('spor (üreme hücresi)', 'spor (biyoloji)'),
    'w03961': ('bela', 'kırbaç / bela'),
    'w03964': ('kulübe', 'kulübe / kabin'),
    'w03967': ('mahlas', 'takma ad / mahlas'),
    'w03969': ('şikâyet', 'şikâyet / iddia (hak talebi)'),
    'w03970': ('usandırmak', 'bıktırmak / sıkmak'),
    'w03971': ('dansçı', 'dansçı (kadın)'),
    'w03972': ('bencil', 'bencil (kişi)'),
    'w03974': ('bloknot', 'not defteri'),
    'w03976': ('vernik', 'vernik / cila'),
    'w03977': ('dışlamak', 'dışlamak / hariç tutmak'),
    'w03980': ('amansız', 'acımasız'),
    'w03982': ('tedbir', 'önlem'),
    'w03983': ('dolandırıcılık', 'dolandırıcılık / vurgun'),
    'w03985': ('dalmak', 'zorla girmek / dalmak'),
    'w03990': ('sesli', 'ses (sıfat) / sesle ilgili'),
    'w03991': ('ayaz', 'don / ayaz'),
    'w03992': ('artış', 'artış / büyütme'),
    'w03993': ('zorlamak', 'mecbur etmek / zorlamak'),
    'w03998': ('fırlatmak', 'fırlatmak / terk etmek / bırakmak'),
    'w03999': ('eski', 'eski / uzun süredir'),
    'w04000': ('uygunsuz', 'ahlaksız / uygunsuz'),
    'w04001': ('kaçakçılık', 'kaçakçılık / kaçak mal'),
    'w04003': ('boşaltmak', 'tahliye etmek / boşaltmak'),
    'w04007': ('içine çekmek', 'içine çekmek / dahil etmek'),
    'w04012': ('fırtınalı', 'fırtınalı / gürültülü (alkış)'),
    'w04014': ('yıkama', 'çamaşır yıkama'),
    'w04015': ('fırın', 'fırın (ocak altı)'),
    'w04016': ('bağlantı', 'bağlantı (link) / sürgün'),
    'w04018': ('dilenci', 'yoksul / dilenci'),
    'w04021': ('enjektör', 'şırınga'),
    'w04024': ('cam', 'cam (sıfat) / camdan'),
    'w04029': ('şaşkınlık', 'şaşkınlık / kargaşa'),
    'w04031': ('girişmek', 'girişmek / başlamak'),
    'w04033': ('bağışlamak', 'armağan etmek / bahşetmek'),
    'w04036': ('balık sürüsü', 'sürü (balık, kuş) / (argo) hata'),
    'w04043': ('temizlik', 'temizlik / tasfiye'),
    'w04047': ('at arabası', 'araba / at arabası'),
    'w04048': ('düello', 'düello / dövüş'),
    'w04053': ('birleşim', 'birleşim / kombinasyon'),
    'w04054': ('valf', 'valf / supap'),
    'w04057': ('taşkınlık', 'yaramazlık / çılgınlık (davranış)'),
    'w04062': ('düşmana ait', 'düşman (sıfat)'),
    'w04064': ('(kapıyı) çarpmak', 'alkışlamak / (kapıyı) çarpmak'),
    'w04068': ('giriş merdiveni', 'sundurma / giriş basamakları'),
    'w04069': ('sıradan', 'banal / bayağı'),
    'w04070': ('yarım', 'yarım / yarısı'),
    'w04071': ('lolipop', 'şekerleme (sopalı) / lolipop'),
    'w04072': ('düşünme', 'düşünce / düşünme biçimi'),
    'w04074': ('kovmak', 'kovmak / dışarı atmak'),
    'w04080': ('seçmek', 'seçmek / yerden almak / toplamak'),
    'w04082': ('halka', 'halka / bağlantı'),
    'w04083': ('yontmak', '(cam, taş) kesip işlemek'),
    'w04085': ('sözünü kesmek', 'sözünü kesmek / (hepsini) öldürmek'),
    'w04087': ('iltifat', 'nezaket / iyilik'),
    'w04090': ('vahiy', 'kıyamet / vahiy'),
    'w04091': ('çıngırtı', 'çınlama / çan sesi'),
    'w04092': ('seçici', 'seçim (sıfat) / seçici'),
    'w04094': ('liman', 'liman / sığınak'),
    'w04095': ('emin', 'inançlı / emin'),
    'w04096': ('yay', 'yay (geometri) / kavis'),
    'w04099': ('azimli', 'inatçı / azimli'),
}

DROP = {
    'w03978': 'быстренько',
}
