# -*- coding: utf-8 -*-
"""B2 inceleme, parti 11."""

FIXES = {
    'w05921': ('terk edilmiş', 'terk edilmiş / yalnız bırakılmış'),
    'w05923': ('yakalamak', 'yetişmek / yakalamak / (korku) salmak'),
    'w05925': ('delmek', 'delmek / (lastik) patlatmak / iğnelemek'),
    'w05926': ('tırpan', 'saç örgüsü / tırpan'),
    'w05927': ('doldurmak', 'doldurmak / (stok) yenilemek'),
    'w05929': ('kusur', 'kusur / eksik'),
    'w05930': ('azalmak', 'azalmak / düşmek / alçalmak'),
    'w05932': ('ihtişam', 'ihtişam / muhteşemlik'),
    'w05933': ('stant', 'stant / stand'),
    'w05934': ('kavşak', 'kavşak / dörtyol'),
    'w05935': ('asık suratlı', 'asık suratlı / somurtkan'),
    'w05936': ('çarpmak', 'çarpmak / çarparak kapatmak / (argo) içmek'),
    'w05938': ('katlanmak', 'katlanmak / dayanmak'),
    'w05939': ('tembel', 'tembel / miskin'),
    'w05940': ('odun', 'odun / kereste'),
    'w05942': ('işsizlik', 'işsizlik'),
    'w05943': ('arma', 'arma / amblem'),
    'w05944': ('zeytin ağacı', 'zeytin ağacı / zeytin'),
    'w05945': ('rekabet', 'rekabet / yarış'),
    'w05946': ('manivela', 'levye / manivela / hurda'),
    'w05947': ('rahim', 'rahim / karın'),
    'w05948': ('zararlı', 'zararlı / sağlığa zararlı'),
    'w05949': ('yosun', 'yosun / karayosunu'),
    'w05951': ('kokarca (yaban gelinciği)', 'gelincik (yaban) / sansar'),
    'w05953': ('büyü', 'büyü / cazibe'),
    'w05954': ('akıcı', 'akıcı / yumuşak (hareket)'),
    'w05957': ('uzakta', 'uzakta'),
    'w05958': ('saygılı', 'saygılı / haklı (sebep)'),
    'w05960': ('çarmıh', 'çarmıha germe / haç'),
    'w05961': ('ayrışım', 'çözülme / çöküş / bozunma'),
    'w05963': ('kesir', 'kesir / saçma / ritim'),
    'w05964': ('cephane', 'cephane / mühimmat'),
    'w05965': ('ultrases', 'ultrason / ultrases'),
    'w05966': ('kürk', 'kürk manto / kürk'),
    'w05967': ('uzanmak', 'uzanmak / gerinmek'),
    'w05968': ('skleroz', 'skleroz / (günlük dil) unutkanlık'),
    'w05969': ('güveç', 'fırın yemeği / güveç'),
    'w05970': ('azaltmak', 'azaltmak / düşürmek / indirmek'),
    'w05971': ('kalkış', 'kalkış / gönderme'),
    'w05972': ('sistemik', 'sistemli / sistemik'),
    'w05973': ('et kızartması', 'kızartma / sıcak yemek'),
    'w05975': ('kana susamış', 'kana susamış / gaddar'),
    'w05976': ('tedavi', 'tedavi edici / şifalı'),
    'w05977': ('evlat', 'evlat / yavrucak'),
    'w05979': ('tavus', 'tavus kuşu'),
    'w05980': ('hükümdar', 'hükümdar / kral'),
    'w05981': ('dart oku', 'ok / mızrak / dart'),
    'w05982': ('başını sallamak', 'başını sallamak / baş sallamak'),
    'w05984': ('anı', 'anılar / hatıralar'),
    'w05985': ('cadı', 'cadı / büyücü kadın'),
    'w05986': ('hesap', 'hesaplama / hesap'),
    'w05987': ('birine zıt gitmek', 'karşı çıkmak / ters düşmek'),
    'w05988': ('fay', 'fay / kırık / çatlak'),
    'w05989': ('dile getirmek', 'dile getirmek / söylemek'),
    'w05991': ('düşürmek', 'düşürmek / bırakmak'),
    'w05992': ('çatırtı', 'çatırtı / çıtırtı'),
    'w05993': ('malikâne', 'malikâne / çiftlik'),
    'w05994': ('uyma', 'uyma / riayet'),
    'w05996': ('varlıklı', 'varlıklı / zengin'),
    'w05997': ('ayrıcalık', 'ayrıcalık / muafiyet / indirim'),
    'w05998': ('abartma', 'abartma / mübalağa'),
    'w05999': ('ağıl', 'ağıl / hayvan çiti'),
    'w06000': ('bomba uçağı', 'bombardıman uçağı'),
    'w06001': ('seslendirmek', 'seslendirmek / dile getirmek'),
    'w06004': ('çiçek hastalığı', 'çiçek hastalığı / suçiçeği'),
    'w06007': ('aktivist', 'aktivist / eylemci'),
    'w06011': ('ağaçlık', 'koru / ağaçlık'),
    'w06012': ('şefkatli', 'sevecen / şefkatli'),
    'w06013': ('dizi', 'dizi / sıra / ardışık'),
    'w06014': ('mucit', 'mucit'),
    'w06015': ('meditasyon yapmak', 'meditasyon yapmak'),
    'w06016': ('kinci', 'kinci / intikamcı'),
    'w06017': ('kararsız', 'kararsız / emin olmayan'),
    'w06018': ('pasif', 'pasif / edilgen'),
    'w06020': ('yeni eve taşınma partisi', 'yeni ev partisi / ev açılışı'),
    'w06022': ('engerek', 'engerek / (argo) zehirli kişi'),
    'w06023': ('gösterge', 'gösterge / tabela / dizin'),
    'w06024': ('yırtık', 'yırtık / paramparça'),
    'w06026': ('rehine', 'rehine (kadın)'),
    'w06027': ('etkileyici', 'etkileyici / heybetli'),
    'w06028': ('dengesiz', 'dengesiz / huysuz'),
    'w06030': ('kaynana', 'kaynana (kocanın annesi)'),
    'w06031': ('elma şarabı', 'elma şarabı / sidr'),
    'w06032': ('üçleme', 'üçlü / üçleme'),
    'w06033': ('tartmak', 'tartmak / değerlendirmek'),
    'w06034': ('doğaçlama', 'doğaçlama / emprovizasyon'),
    'w06036': ('kablo tesisatı', 'kablo tesisatı / elektrik hattı'),
    'w06037': ('en küçük', 'en küçük / asgari'),
    'w06038': ('komisyon', 'komisyon (sıfat) / ikinci el mağazası'),
    'w06039': ('kabızlık', 'kabızlık / sürgü / kilit'),
    'w06040': ('başına gelmek, olmak (aniden)', 'başına gelmek / meydana gelmek'),
    'w06041': ('kuş yavrusu', 'kuş yavrusu / civciv'),
    'w06042': ('embriyon', 'embriyon / cenin / tohum'),
    'w06043': ('baskın', 'baskın / akın / kısa gezi'),
    'w06044': ('güncel', 'güncel / geçerli'),
    'w06045': ('fenomen', 'fenomen / olağanüstü olay'),
    'w06047': ('boyun eğdirmek', 'boyun eğdirmek / tabi kılmak'),
    'w06049': ('asker kaçağı', 'asker kaçağı / firari'),
    'w06050': ('sonucunda', 'sonucunda / dolayısıyla'),
    'w06052': ('paralı', 'ücretli / paralı'),
    'w06053': ('kekelemek', 'kekelemek / (konudan) söz etmek'),
    'w06054': ('yetkin', 'yetkin / bilgili'),
    'w06055': ('cırlama', 'cıvıltı / cırlama / ince ses'),
    'w06056': ('monolog', 'monolog / tek kişilik konuşma'),
    'w06058': ('güçlenmek', 'güçlenmek / artmak'),
    'w06059': ('avuç', 'avuç / bir avuç'),
    'w06060': ('keskinlik', 'keskinlik / nükte / şiddet'),
    'w06061': ('ayakkabı', 'ayakkabı / pabuç'),
    'w06064': ('tanıştırmak', 'tanıştırmak'),
    'w06065': ('fazla bükmek', 'fazla bükmek / abartmak'),
    'w06066': ('esneme', 'esneme / germe'),
    'w06067': ('yaklaşmak', 'yaklaşmak / yakınlaşmak'),
    'w06068': ('kaynak', 'kaynak / başlangıç / pınar'),
    'w06069': ('sömürü', 'sömürü / işletme'),
    'w06071': ('yapmak', 'yapmak / imal etmek'),
    'w06072': ('kask', 'kask / miğfer'),
    'w06073': ('cahil', 'cahil / bilgisiz'),
    'w06076': ('askı', 'askı / vestiyer'),
    'w06077': ('yanıcı', 'yanıcı / yakıt'),
    'w06079': ('uzlaştırmak', 'uyumlu hale getirmek / onay almak / koordine etmek'),
    'w06081': ('takılmak', 'takılmak / sıkışmak'),
    'w06082': ('can sıkıcı', 'sıkıcı / bunaltıcı'),
    'w06084': ('diriliş', 'diriliş / dirilme'),
    'w06087': ('sadelik', 'sadelik / basitlik'),
    'w06091': ('güç', 'güç / kudret'),
    'w06092': ('satıcı', 'satıcı (kadın) / tezgâhtar'),
    'w06093': ('baltalamak', 'baltalamak / sabote etmek'),
    'w06094': ('şarjör', 'şarjör / mermi şeridi'),
    'w06095': ('iştirakçi', 'katılımcı (kadın)'),
    'w06096': ('travmatize etmek', 'yaralamak / travma yaşatmak'),
    'w06100': ('haç', 'küçük haç / çarpı'),
    'w06102': ('sağlamlaştırmak', 'güçlendirmek / sağlamlaştırmak'),
    'w06104': ('bağ', 'bağ / üzüm bağı'),
    'w06105': ('anlayışlı', 'anlayışlı'),
    'w06107': ('tasarruf', 'tasarruf / ekonomi'),
    'w06108': ('kanvas', 'tuval / kanvas'),
    'w06109': ('beden yapısı', 'beden yapısı / vücut yapısı'),
    'w06113': ('tiranlık', 'tiranlık / zorbalık'),
    'w06116': ('koklama', 'koku alma / koku duyusu / sezgi'),
    'w06117': ('gıcırtı', 'gıcırtı / çıtırtı'),
    'w06118': ('ayıklık', 'ayıklık / ayık olma'),
    'w06119': ('abonelik', 'abonelik / yazılı taahhüt'),
    'w06120': ('kıvrım', 'kıvrım / kat / pli'),
    'w06121': ('eyerlemek', 'eyerlemek / bineğe binmek'),
}

DROP = {
    'w05962': 'брюссель',
    'w05974': 'ливия',
    'w06002': 'румыния',
    'w06035': 'мошонка',
    'w06090': 'анус',
    'w06101': 'алкаш',
}
