# -*- coding: utf-8 -*-
"""B2 inceleme, parti 9."""

FIXES = {
    'w08008': ('konvülsiyon', 'konvülsiyon / çırpınma'),
    'w08009': ('anlatış', 'anlatış / sunum / özet'),
    'w08011': ('parmaksız eldiven', 'eldiven (kalın, tek parmaklı)'),
    'w08013': ('patlamak', 'patlamak / çatlamak'),
    'w08014': ('demirci dükkânı', 'demirci dükkânı / demirhane'),
    'w08015': ('sismik', 'sismik / deprem (sıfat)'),
    'w08016': ('alaycı', 'alaycı / iğneleyici'),
    'w08017': ('yolunda gitmek', 'yolunda gitmek / iyi gitmek'),
    'w08019': ('parça, kırpıntı (kumaş)', 'parça / kumaş parçası / kırpıntı'),
    'w08020': ('infilak (etme), patlama', 'patlama / infilak / vuruntu'),
    'w08021': ('soruşturma', 'soruşturma / ön sorgu'),
    'w08022': ('ihbar', 'ihbar / jurnal'),
    'w08023': ('tatbiki', 'uygulamalı / tatbiki'),
    'w08024': ('esirci', 'köle tüccarı / esirci'),
    'w08025': ('değişken', 'değişken / kararsız'),
    'w08026': ('irin', 'irin / cerahat'),
    'w08027': ('hızlanma', 'hızlanma / dağıtma / hız alma'),
    'w08029': ('sararmak', 'sararmak / benzi atmak'),
    'w08030': ('çarpmak', 'çarpmak / vurmak (kendini)'),
    'w08031': ('kült', 'kült / dinî ibadet (sıfat)'),
    'w08032': ('kılıf', 'kılıf / kılıf (telefon) / kılıf (koltuk)'),
    'w08033': ('çubuklu dondurma', 'çubuklu dondurma / eskimo'),
    'w08034': ('kesit', 'kesit / parça / doğru parçası'),
    'w08036': ('süpürge', 'süpürge (çalı) / demet'),
    'w08037': ('entegrasyon', 'entegrasyon / bütünleşme'),
    'w08039': ('servis', 'oto servis / araç tamirhanesi'),
    'w08040': ('el yazması', 'el yazması / yazma eser'),
    'w08041': ('açıklama', 'açıklama / izah'),
    'w08042': ('hüküm vermek', 'hüküm vermek / ödül vermek / karar vermek'),
    'w08043': ('dolaşım', 'dolaşım / sirkülasyon'),
    'w08044': ('renk', 'renk / boyama / renklendirme'),
    'w08045': ('kakmak', 'çakmak / kakmak / aklına sokmak'),
    'w08046': ('beceriksiz', 'beceriksiz / acemice'),
    'w08047': ('karanfil', 'karanfil / (baharat) karanfil'),
    'w08048': ('ağırsızlık', 'ağırlıksızlık / yer çekimsizliği'),
    'w08050': ('nadir noktası (gökbilim)', 'nadir noktası / en alt nokta'),
    'w08051': ('ayyaşlık nöbeti', 'içki nöbeti / uzun süreli sarhoşluk'),
    'w08052': ('mikser', 'mikser / karıştırıcı'),
    'w08053': ('şef', 'şef / orkestra şefi'),
    'w08054': ('tutamak', 'sap / tutamak'),
    'w08057': ('filotilla', 'filo / filotilla / küçük donanma'),
    'w08058': ('helezoni', 'sarmal / helezoni'),
    'w08059': ('gıkını çıkarmak', 'gıkını çıkarmak / ses çıkarmak'),
    'w08060': ('cılız', 'güçsüz / halsiz / cılız'),
    'w08064': ('karot', 'karot / örnek çekirdek'),
    'w08065': ('kambur', 'kambur / kamburlu'),
    'w08067': ('küstümotu', 'mimoza / küstüm otu'),
    'w08068': ('dağıtmak', 'dağıtmak / hızlandırmak'),
    'w08069': ('düşey çizgi', 'dikey çizgi / düşey'),
    'w08071': ('düzlem', 'düzlem / yüzey / düz alan'),
    'w08072': ('canlı kişi', 'hareketli kişi / enerjik biri'),
    'w08073': ('bacanak', 'bacanak / karı kardeşlerin kocası'),
    'w08074': ('soluk soluğa kalmak', 'soluk soluğa kalmak / puflamak'),
    'w08075': ('slogan atmak', 'slogan atmak / ritimle haykırmak'),
    'w08076': ('miyop', 'miyop / uzağı göremeyen'),
    'w08078': ('şaplak atmak', 'şaplak atmak / şıpırdatmak / (terlik) sürüklemek'),
    'w08079': ('toptan', 'toptan / toptan satışa ait'),
    'w08080': ('gerekli', 'gerekli / istenen'),
    'w08081': ('gevşemek', 'zayıflamak / gevşemek'),
    'w08082': ('kaba adam', 'kaba adam / terbiyesiz'),
    'w08083': ('takılmak', 'karışmak / bulaşmak / takılmak'),
    'w08084': ('temsilcilik', 'temsilcilik / temsil'),
    'w08085': ('dengeyi muhafaza etmek', 'dengede durmak / denge kurmak'),
    'w08086': ('kendi eliyle', 'kendi eliyle / bizzat'),
    'w08087': ('bininci', 'bininci / binlik'),
    'w08089': ('mühürlemek', 'mühürlemek / mühür vurmak'),
    'w08091': ('benzer', 'benzer / birbirine yakın'),
    'w08092': ('kendi adaylığına itiraz beyan etme', 'kendi adaylığını geri çekme / çekilme'),
    'w08093': ('kutsala saygısızlık', 'kutsala saygısızlık / küfür'),
    'w08094': ('çeşit', 'çeşit / ürün yelpazesi'),
    'w08095': ('önceden', 'önceden / ön hazırlık olarak'),
    'w08096': ('yaver', 'yaver / emir subayı'),
    'w08097': ('zulüm', 'zulüm / baskı / ezme'),
    'w08098': ('alageyik', 'alageyik / geyik dişisi'),
    'w08100': ('iri kaya', 'iri kaya / kaya parçası / kütle'),
    'w08102': ('hostes', 'hostes / uçuş görevlisi (kadın)'),
    'w08103': ('baskı yapmak', 'baskı yapmak / sıkıştırmak / rahatsız etmek'),
    'w08104': ('yüz yıllık', 'yüz yıllık / yüz yaşında'),
    'w08105': ('küçük', 'küçük / kompakt / derli toplu'),
    'w08106': ('tutucu', 'tutucu / kurallı / ağırbaşlı'),
    'w08107': ('kışkırtma', 'kışkırtıcı / provokatif'),
    'w08108': ('bira', 'bira (sıfat) / birahaneye ait'),
    'w08109': ('çerçeve, iskelet (yapı)', 'iskelet / çerçeve / yapı iskeleti'),
    'w08110': ('dikilitaş', 'dikilitaş / anıt sütun'),
    'w08111': ('yolunu bulmak', 'yolunu bulmak / beceremek / başarmak'),
    'w08112': ('meraklı seyirci', 'meraklı seyirci / boş boş bakan kişi'),
    'w08113': ('hayran', 'hayran / bilen kişi / değer bilen'),
    'w08114': ('nem', 'nem / rutubet / ıslaklık'),
    'w08115': ('kornea', 'kornea / gözün saydam tabakası'),
    'w08116': ('sinirlenmek', 'sinirlenmek / öfkelenmek'),
    'w08117': ('baharatlı', 'aromatik / kokulu'),
    'w08118': ('geçit', 'geçit / geçiş yeri / feribot'),
    'w08119': ('bakımlı', 'bakımlı / özenle bakılmış'),
    'w08120': ('uyumlu', 'uyumlu / ahenkli'),
    'w08121': ('mahmuz', 'mahmuz / ezber kâğıdı (kopya)'),
    'w08122': ('caka', 'övünme / caka / palavra'),
    'w08124': ('açıklama', 'netleştirme / ayrıntılandırma'),
    'w08125': ('mezar', 'mezar (anıt) / türbe / anıt mezar'),
    'w08126': ('korsanlık', 'korsanlık / (yazılım) korsan'),
    'w08128': ('ponpon', 'ponpon / püskül'),
    'w08129': ('kötüleştirmek', 'kötüleştirmek / bozmak'),
    'w08130': ('benzinci', 'benzin pompası / benzinlik'),
    'w08131': ('gondol', 'gondol / (balon) sepet'),
    'w08132': ('erişmek', 'yetişmek / olgunlaşmak / erişmek'),
    'w08133': ('egemen', 'egemen / bağımsız'),
    'w08134': ('arktik', 'arktik / kuzey kutbu (sıfat)'),
    'w08136': ('ateşli', 'ateşli / atış (sıfat)'),
    'w08138': ('bardak tabağı', 'çay tabağı / fincan tabağı'),
    'w08139': ('evlek', 'evlek / tarla oluğu / iz'),
    'w08141': ('danışman', 'danışman / öğütçü'),
    'w08142': ('giydirmek', 'giydirmek / süslemek'),
    'w08143': ('goblen', 'goblen / duvar halısı'),
    'w08144': ('terminoloji', 'terminoloji / terimler'),
    'w08145': ('kronoloji', 'kronoloji / olayların sırası'),
    'w08146': ('göç etmek', 'göç etmek / yurt dışına yerleşmek'),
    'w08147': ('nesir', 'düzyazı / nesir'),
    'w08148': ('mahkum etmek', 'mahkûm etmek / kaderine terk etmek'),
    'w08149': ('dönence', 'dönence / tropik'),
    'w08150': ('tatlı', 'tatlı / hoş / nefis'),
    'w08152': ('çelme', 'çelme / basamak (araç)'),
    'w08153': ('oburluk', 'oburluk / açgözlülükle yeme'),
    'w08154': ('ısrar etmek', 'ısrar etmek / direnmek'),
    'w08155': ('yüzleşme', 'karşı karşıya gelme / çatışma'),
    'w08156': ('kahramanca', 'kahramanca / yiğitçe'),
    'w08157': ('müshil', 'müshil / laksatif'),
    'w08158': ('uyuz', 'uyuz / uyuz hastalığı'),
    'w08159': ('yazım', 'yazım / imla'),
    'w08160': ('armatür', 'armatür / donatı / takviye çubuğu'),
    'w08161': ('saçak buzu', 'buz sarkıtı / saçak buzu'),
    'w08162': ('maske', 'maske / (mecaz) yalancı kılık'),
    'w08163': ('sınır muhafızı', 'sınır muhafızı / sınır askeri'),
    'w08164': ('değmek', 'değmek / temas etmek / yakın olmak'),
    'w08165': ('halter', 'halter / (kapı, futbol) direk'),
    'w08166': ('kanun koyucu', 'kanun koyucu / yasa yapıcı'),
    'w08168': ('yarış', 'yarış (yüzme) / turu'),
    'w08169': ('dans', 'dans / oyun / halay'),
    'w08170': ('türban', 'türban / sarık'),
    'w08171': ('ayda bir', 'her ay / aylık olarak'),
    'w08172': ('yer sincabı', 'yer sincabı / gelincik (kemirgen)'),
    'w08173': ('poliklinik', 'poliklinik / sağlık ocağı'),
    'w08174': ('gizlemek', 'gizlemek / kamufle etmek / maskelemek'),
    'w08175': ('eşelon', 'eşelon / askeri tren / kademe'),
    'w08176': ('itidal', 'soğukkanlılık / sükûnet'),
    'w08177': ('gelişigüzel', 'özensizce / gelişigüzel / baştan savma'),
    'w08179': ('başucu', 'başucu / zirve / doruk'),
    'w08181': ('çöpçatan', 'çöpçatan / görücü'),
    'w08182': ('taç giydirmek', 'taç giydirmek / taç giydirme töreni yapmak'),
    'w08183': ('sokak', 'dar sokak / ara sokak / köşe bucak'),
    'w08185': ('alımsız', 'çirkin / alımsız / iç açıcı olmayan'),
    'w08186': ('çakmaktaşı', 'çakmaktaşı / (mecaz) sert insan'),
    'w08187': ('süresi dolmadan', 'süresinden önce / erkenden'),
    'w08188': ('alçak', 'alçak / hilekâr'),
    'w08189': ('donatma', 'donatım / takım / olta takımı'),
    'w08190': ('yük', 'yük / sıkıntı / güçlük'),
    'w08192': ('infüzyon', 'infüzyon / damardan verme / enjeksiyon'),
    'w08194': ('açıkgöz', 'açıkgöz / kurnaz / kıvrak'),
    'w08197': ('alıcı', 'alıcı / mektup alan kişi'),
    'w08198': ('stajyer', 'stajyer / pratik yapan kişi'),
    'w08199': ('sallamak', 'sallamak / harekete geçirmek'),
    'w08200': ('eşelemek', 'eşelemek / karıştırmak / (burun) karıştırmak'),
    'w08201': ('tatlı', 'tatlı / iyi huylu / sevecen'),
    'w08202': ('barışsever', 'barışsever / uysal'),
    'w08205': ('ağırlık', 'ağırlık / kettlebell / tartı ağırlığı'),
    'w08206': ('ezberlemek', 'ezberlemek / hafızalamak'),
    'w08207': ('isteksiz', 'isteksizce / gönülsüzce'),
}

DROP = {
    'w08062': 'нагасаки',
    'w08066': 'константинополь',
    'w08063': 'содом',
    'w08101': 'импотенция',
    'w08167': 'ихний',
    'w08035': 'подлиза',
    'w08196': 'лилипут',
}
