# -*- coding: utf-8 -*-
"""B2 inceleme, parti 2."""

FIXES = {
    'w06600': ('başlatma', 'başlatma / çalıştırma / fırlatma'),
    'w06601': ('tersane', 'tersane / gemi yapım yeri'),
    'w06602': ('sürtünme', 'sürtünme / anlaşmazlık'),
    'w06604': ('kervan', 'kervan / karavan'),
    'w06605': ('format', 'format / ebat'),
    'w06606': ('dört', 'dört (rakam) / dörtlü / (not) 4'),
    'w06607': ('bürokrasi', 'bürokrasi / kırtasiyecilik'),
    'w06608': ('onarılmaz', 'onarılamaz / düzeltilemez'),
    'w06609': ('tifo', 'tifüs / tifo'),
    'w06610': ('sanatoryum', 'sanatoryum / dinlenme tesisi'),
    'w06612': ('rehin vermek', 'rehin vermek / (temel) atmak / (kulak) tıkamak'),
    'w06615': ('ayakkabıcı', 'ayakkabı tamircisi / ayakkabıcı'),
    'w06616': ('çayır çekirgesi', 'çekirge / çayır çekirgesi'),
    'w06617': ('külüstür', 'külüstür / harap ev'),
    'w06619': ('sadaka', 'sadaka / dilenci parası'),
    'w06620': ('manifesto', 'manifesto / bildiri'),
    'w06621': ('evcilleştirmek', 'evcilleştirmek / ehlileştirmek'),
    'w06622': ('büzülmek', 'büzülmek / sıkışmak'),
    'w06624': ('dövmek', 'dövmek / vurmak / titremek'),
    'w06625': ('gerdanlık', 'gerdanlık / kolye'),
    'w06626': ('bilgiç', 'bilgiç / her şeyi bilen'),
    'w06627': ('mekik', 'mekik / kayık / (alışveriş) taşıyıcısı'),
    'w06628': ('yukarıda', 'yukarıda / üstte'),
    'w06629': ('katalizör', 'katalizör / hızlandırıcı'),
    'w06630': ('yayın', 'yayın / yayıncılık'),
    'w06631': ('karşı casusluk', 'karşı istihbarat'),
    'w06632': ('köşk', 'köşk / pavyon / stant'),
    'w06633': ('göçmen', 'göçmen (ülkeyi terk eden)'),
    'w06634': ('cemaat', 'cemaat / dinî topluluk'),
    'w06636': ('post', 'koyun postu / yapağı'),
    'w06637': ('muhafazakâr', 'muhafazakâr / tutucu'),
    'w06638': ('karşılıklı', 'karşılıklı / iki taraflı'),
    'w06639': ('ev işleriyle ilgili', 'ev işleriyle ilgili / tutumlu / ekonomik'),
    'w06640': ('cereyan', 'cereyan / hava akımı'),
    'w06641': ('fena', 'cesur / atılgan / kahraman'),
    'w06642': ('beraber', 'beraber / ortaklaşa'),
    'w06643': ('ihmal', 'ihmal / küçümseme'),
    'w06644': ('incelik', 'incelik / ayrıntı / nüans'),
    'w06647': ('mücadeleci', 'dövüşçü / mücadeleci'),
    'w06649': ('uçurum', 'kayalık / uçurum'),
    'w06650': ('zührevi', 'zührevi / cinsel yolla bulaşan'),
    'w06651': ('tuğladan yapılma', 'tuğladan yapılma / tuğla (sıfat)'),
    'w06652': ('kuru ot', 'kuru ot / saman otu'),
    'w06653': ('homurtu', 'homurtu / hırıltı / kükreme'),
    'w06654': ('sürüklenerek yürümek', 'yürümek (yorgun) / sürüklenerek yürümek'),
    'w06655': ('rutubet', 'nem / rutubet'),
    'w06656': ('başrahip', 'başrahip / kilise başkanı'),
    'w06657': ('milliyet', 'milliyet / uyruk (etnik)'),
    'w06658': ('fraksyon', 'fraksiyon / grup'),
    'w06659': ('önemsiz', 'önemsiz / ikincil'),
    'w06660': ('tadım', 'tadım / tatma'),
    'w06661': ('sömürmek', 'sömürmek / işletmek'),
    'w06662': ('misafirperver', 'misafirperver / konuksever'),
    'w06663': ('branda bezi', 'branda bezi / çadır bezi'),
    'w06664': ('biraz beklemek', 'biraz beklemek / ertelemek'),
    'w06665': ('vatandaş', 'vatandaş / hemşehri (aynı ülkeden)'),
    'w06667': ('rastlamak', 'rastlaşmak / karşılaşmak'),
    'w06668': ('kene', 'kene / (alet) pense'),
    'w06671': ('dahil etmek', 'devreye sokmak / dahil etmek / kullanmak'),
    'w06672': ('alçakgönüllü', 'alçakgönüllü / uysal'),
    'w06673': ('kılıf', 'kılıf / kutu / muhafaza'),
    'w06674': ('sigara tiryakisi', 'sigara içen / tiryaki'),
    'w06675': ('folyo', 'folyo / alüminyum kâğıdı'),
    'w06676': ('fısıltı', 'fısıltı / fısıltı sesi'),
    'w06677': ('dikkatsiz', 'dikkatsiz / tedbirsiz'),
    'w06678': ('bazı yerlerde', 'bazı yerlerde / şurada burada'),
    'w06679': ('suya girme', 'yıkanma / yüzme / suya girme'),
    'w06680': ('gayret', 'gayret / özen'),
    'w06681': ('kıdem', 'kıdem / iş tecrübesi / staj'),
    'w06682': ('belirsiz', 'belirsiz / bulanık / muğlak'),
    'w06683': ('hipodrom', 'hipodrom / at yarışı pisti'),
    'w06684': ('hazırlama', 'hazırlama / derleme / düzenleme'),
    'w06685': ('uzaklaştırmak', 'uzaklaştırmak / görevden almak'),
    'w06686': ('cılız', 'cılız / zayıf / çelimsiz'),
    'w06687': ('iki yıllık', 'iki yıllık / iki yaşında'),
    'w06688': ('ucuz', 'ucuz / uygun fiyatlı'),
    'w06690': ('tanı', 'tanı / teşhis'),
    'w06691': ('alicenaplık', 'cömertlik / yüce gönüllülük'),
    'w06692': ('dayanıklılık', 'dayanıklılık / dayanma gücü'),
    'w06695': ('hindi', 'hindi (erkek) / hindi'),
    'w06696': ('çabuklaşmak', 'hızlanmak'),
    'w06697': ('monarşi', 'monarşi / krallık'),
    'w06698': ('insanlıkdışı', 'insanlık dışı / gaddar'),
    'w06700': ('kış uykusu', 'kış uykusu / uyuşukluk'),
    'w06701': ('kadın işçi', 'işçi (kadın)'),
    'w06702': ('cariye', 'cariye / gözde'),
    'w06703': ('gidermek', 'gidermek / dindirmek'),
    'w06704': ('sara', 'sara / epilepsi'),
    'w06705': ('sakat etmek', 'sakat etmek / topal bırakmak'),
    'w06706': ('konut', 'konut (sıfat) / barınmayla ilgili'),
    'w06707': ('anayasal', 'anayasal / anayasa (sıfat)'),
    'w06708': ('sakar', 'sakar / dalgın'),
    'w06709': ('iksir', 'iksir / şifa'),
    'w06710': ('karşılıklılık', 'karşılıklılık / karşılık görme'),
    'w06711': ('anemi', 'anemi / kansızlık'),
    'w06713': ('döşek', 'şilte / yatak'),
    'w06714': ('ölümlülük', 'ölüm oranı / ölümlülük'),
    'w06715': ('kurşunlama', 'kurşuna dizme / kurşunlama'),
    'w06716': ('zencefilli çörek', 'zencefilli kurabiye / tatlı kurabiye'),
    'w06718': ('çakıl taşı', 'küçük taş / çakıl'),
    'w06719': ('kürdan', 'kürdan / diş kürdanı'),
    'w06720': ('aralık', 'aralık / ara'),
    'w06721': ('gizlemek', 'gizlemek / saklamak'),
    'w06722': ('dolaşıp aramak', 'dolaşıp aramak / kolaçan etmek'),
    'w06723': ('düşüncesizlik', 'düşüncesizlik / gözü karalık'),
    'w06724': ('büyüteç', 'büyüteç / mercek'),
    'w06726': ('başıboş dolaşmak', 'başıboş dolaşmak / dolaşıp durmak'),
    'w06727': ('izmarit', 'izmarit / sigara izmariti'),
    'w06728': ('anlaşılır', 'anlaşılır / görsel / açıkça görülür'),
    'w06729': ('yavru', 'yavru / evlat / dal'),
    'w06730': ('milyonuncu', 'milyonuncu / milyonluk'),
    'w06733': ('apandis', 'apandis / ek (kitap)'),
    'w06735': ('kaça', 'kaça / ne kadar'),
    'w06736': ('mus', 'mus / köpük (saç)'),
    'w06738': ('iyileştirmek', 'iyileştirmek / şifa vermek'),
    'w06739': ('oymak', 'oymak / (sürekli) vurmak / ezberlemek'),
    'w06740': ('dokunuş', 'sürme / darbe / (tıbbi) sürüntü'),
    'w06741': ('ağrısız', 'ağrısız / acısız'),
    'w06742': ('donmak', 'donmak / donup kalmak / kalakalmak'),
    'w06743': ('telaffuz', 'telaffuz / söyleyiş'),
    'w06744': ('geçit', 'geçit / dağ geçidi'),
    'w06745': ('ilişkilendirmek', 'çağrışım yapmak / ilişkilendirilmek'),
    'w06746': ('kullanılabilir', 'uygulanabilir / kullanılabilir'),
    'w06747': ('guguk', 'guguk / guguk kuşu'),
    'w06748': ('at', 'at (sıfat) / atlara ait'),
    'w06749': ('inkar etmek', 'vazgeçmek / inkâr etmek / reddetmek'),
    'w06750': ('doldurmak', 'fırlatmak / doldurmak / bırakmak'),
    'w06751': ('şiirsel', 'şiirsel / şiir (sıfat)'),
    'w06753': ('takviye', 'takviye / yenileme / eklenme'),
    'w06754': ('tepe', 'tepe (baş) / zirve'),
    'w06755': ('güneyli', 'güneyli / güneyde yaşayan'),
    'w06756': ('oran', 'oran / ilişki'),
    'w06757': ('tabaka', 'kaplama / tabaka / baskın'),
    'w06758': ('dirilmek', 'canlanmak / dirilmek'),
    'w06759': ('akran', 'yaşıt / akran'),
    'w06761': ('duyarlı', 'duyarlı / hassas / etkilenmeye açık'),
    'w06762': ('yakıt', 'yakıt / akaryakıt'),
    'w06763': ('hafiflik', 'hafiflik / kolaylık'),
    'w06764': ('boğaz', 'boğaz / kanal'),
    'w06765': ('askeri öğrenci', 'askeri öğrenci / kurs öğrencisi'),
    'w06766': ('ayar etmek', 'ayarlamak / düzenlemek'),
    'w06767': ('kara sığır', 'manda / bufalo'),
    'w06769': ('savuşturmak', 'savuşturmak / kurtulmak / uzaklaşmak'),
    'w06770': ('rüşvet vermek', 'rüşvet vermek / gönlünü kazanmak'),
    'w06771': ('saplamak', 'saplamak / takmak'),
    'w06772': ('bakir', 'bakir / el değmemiş'),
    'w06774': ('kordon', 'kordon / ip / kablo'),
    'w06775': ('büyük dede', 'büyük dede / ata'),
    'w06776': ('ihbarcı', 'ihbarcı / muhbir'),
    'w06777': ('akış', 'akış / lağım / gider'),
    'w06778': ('aborjin', 'yerli / aborijin / ilk halk'),
    'w06780': ('soluk borusu', 'soluk borusu / trakea'),
    'w06781': ('obezite', 'obezite / şişmanlık'),
    'w06782': ('Merkür', 'Merkür / cıva'),
    'w06783': ('beceriklilik', 'beceriklilik / çeviklik'),
    'w06784': ('büst', 'büst / göğüs'),
    'w06785': ('hükmetmek', 'hükmetmek / egemen olmak'),
    'w06786': ('sap', 'sap / gövde (bitki)'),
    'w06787': ('yabanmersini', 'yaban mersini / böğürtlen türü'),
    'w06788': ('çürük', 'çürük / kokmuş / bayat'),
    'w06789': ('kolay', 'kolay / zor olmayan'),
    'w06790': ('akmak', 'akmak / sızmak / sonuç olarak çıkmak'),
    'w06791': ('orantı', 'orantı / oran'),
    'w06792': ('rasathane', 'rasathane / gözlemevi'),
    'w06794': ('tırmanmak', 'tırmanmak / güçlükle çıkmak'),
    'w06795': ('parlamak', 'parlamak / göz kamaştırmak'),
    'w06796': ('dövüş', 'kavga / dövüş'),
    'w06798': ('reşit', 'reşit / ergin'),
    'w06799': ('geçinmek', 'geçinmek / uyum sağlamak'),
}

DROP = {
    'w06618': 'туш',
}
