# -*- coding: utf-8 -*-
"""B2 inceleme, parti 6."""

FIXES = {
    'w07404': ('çıplaklık', 'çıplaklık / çıplak hâl'),
    'w07405': ('iletişimsel', 'iletişimsel / iletişim (sıfat)'),
    'w07407': ('konusal', 'konusal / tematik / konuyla ilgili'),
    'w07408': ('kin dolu', 'kin dolu / öfkeli / hırçınlaşmış'),
    'w07409': ('yaratılış', 'köken / oluşum / genesis'),
    'w07410': ('marmelat', 'marmelat / jöleli şeker'),
    'w07411': ('oğlancık', 'erkek çocuk / oğlan'),
    'w07412': ('stratejist', 'stratejist / strateji uzmanı'),
    'w07413': ('kendini beğenmişlik', 'kendini beğenmişlik / kibir'),
    'w07415': ('dulavratotu', 'dulavratotu / (argo) safdil'),
    'w07416': ('rakibe', 'rakip (kadın) / rakibe'),
    'w07417': ('diken', 'diken / dikenli bitki'),
    'w07418': ('çukur', 'çukur / çöküntü'),
    'w07419': ('tevarüs etmek', 'miras almak / devralmak'),
    'w07420': ('batmak', 'batmak / iflas etmek / yanıp bitmek'),
    'w07421': ('püskül', 'fırça / püskül'),
    'w07422': ('aritmetik', 'aritmetik / hesap'),
    'w07423': ('restorasyon', 'restorasyon / onarım'),
    'w07424': ('toprak', 'toprak / zemin / astar (boya)'),
    'w07425': ('lamba', 'lamba / aydınlatma armatürü'),
    'w07426': ('mahkum etmek', 'mahkûm etmek / kaderine terk etmek'),
    'w07427': ('mavilik', 'mavilik / mavi renk'),
    'w07428': ('ışık', 'ışık (sıfat) / ışıkla ilgili'),
    'w07429': ('drenaj', 'drenaj / su tahliyesi'),
    'w07430': ('bağdaşabilirlik', 'uyumluluk / bağdaşabilirlik'),
    'w07431': ('gönenç', 'refah / bolluk / gönenç'),
    'w07432': ('şifa', 'iyileşme / tedavi'),
    'w07435': ('doktrin', 'doktrin / öğreti'),
    'w07438': ('palavracı', 'palavracı / övüngen'),
    'w07439': ('yalvarmak', 'yalvarmak / rica edip durmak'),
    'w07441': ('zayıflamak', 'zayıflamak / kilo vermek'),
    'w07442': ('dalavereci', 'dalavereci / düzenbaz'),
    'w07443': ('kaplama', 'kaplama / döşeme'),
    'w07445': ('anmak', 'anmak / hatırlamak'),
    'w07447': ('yidiş', 'Yidiş / Yiddiş'),
    'w07448': ('doğurmak', 'doğurmak / meydana getirmek'),
    'w07450': ('ceylan', 'ceylan / gazel'),
    'w07451': ('sümbül', 'sümbül / sümbül çiçeği'),
    'w07453': ('cesaret etmek', 'cesaret etmek / göze almak'),
    'w07455': ('nazik', 'nazik / kibar'),
    'w07456': ('görülmemiş', 'görülmemiş / eşi benzeri olmayan'),
    'w07458': ('oluşturmak', 'oluşturmak / biçimlendirmek'),
    'w07459': ('anahtarlık', 'anahtarlık / süs (çanta)'),
    'w07460': ('duraklama', 'duraklama / sakinlik / durgunluk'),
    'w07461': ('şal', 'şal / atkı'),
    'w07463': ('bakmak', 'bakmak (çocuğa) / kucakta sallamak'),
    'w07464': ('yırtık', 'utanmaz / yüzsüz'),
    'w07465': ('el kaldırmak (vurmak için)', 'el kaldırmak / vurmak üzere kalkmak'),
    'w07466': ('yusufçuk', 'yusufçuk / kızböceği'),
    'w07467': ('eflatun', 'eflatun / mor'),
    'w07468': ('harap etmek', 'harap etmek / boşaltmak / yağmalamak'),
    'w07470': ('uzman', 'uzman (sıfat) / ekspertiz'),
    'w07471': ('kısa süreli', 'kısa süreli / kısa vadeli'),
    'w07472': ('dövmek', 'dövmek (demir) / şekillendirmek'),
    'w07473': ('asmak', 'asmak / (bayrak) çekmek / duyurmak'),
    'w07474': ('ana hat', 'ana hat / dış çizgi / siluet'),
    'w07475': ('dayı', 'amca / (halk dilinde) adam'),
    'w07477': ('açgözlü', 'açgözlü / hırslı'),
    'w07478': ('aranamaz', 'sırlı / anlaşılmaz / gizemli'),
    'w07479': ('koçbaşı', 'koçbaşı / hücum aracı'),
    'w07481': ('geri dönüşüm', 'geri dönüşüm / bertaraf'),
    'w07482': ('buharlaşmak', 'buharlaşmak / (argo) kaybolmak'),
    'w07483': ('elçi', 'elçi / temsilci'),
    'w07484': ('konuşmak', 'konuşmak / söylemek / söyleyip bitirmek'),
    'w07485': ('gömlek', 'gömlek / iç gömleği'),
    'w07486': ('vurup öldürmek (sinek vb.)', 'vurup öldürmek / kapatmak (bir vuruşla)'),
    'w07487': ('duvarcı', 'duvarcı / taş ustası'),
    'w07488': ('zifiri', 'zifiri / bitmek bilmez'),
    'w07489': ('kırıntı', 'kırıntı / zerre / tanecik'),
    'w07490': ('doğuştan', 'doğuştan / kalıtsal'),
    'w07491': ('akustik', 'akustik / sesle ilgili'),
    'w07492': ('(hayvanın) derisini yüzmek', 'derisini yüzmek / yüzmek'),
    'w07494': ('gırtlak', 'gırtlak / larenks'),
    'w07495': ('dolmak', 'dolmak / dolup taşmak'),
    'w07496': ('suçüstü yakalamak', 'suçüstü yakalamak / ele vermek'),
    'w07498': ('temiz', 'temiz / derli toplu'),
    'w07499': ('eğlence', 'eğlence / şenlik / parti'),
    'w07500': ('sâhiplenmek', 'sahiplenmek / zimmetine geçirmek / (ünvan) vermek'),
    'w07501': ('mazi', 'geçmiş / mazi'),
    'w07502': ('dönme', 'dönme / dönüş'),
    'w07503': ('huni', 'huni / çukur / girdap'),
    'w07504': ('sayrılık', 'rahatsızlık / keyifsizlik'),
    'w07505': ('feraset', 'ferasetli oluş / sağgörü'),
    'w07506': ('kangren', 'kangren / ölü doku'),
    'w07507': ('koşut', 'paralel / koşut çizgi / benzerlik'),
    'w07508': ('trompetçi', 'trompetçi / borazancı'),
    'w07510': ('profilaksi', 'koruyucu önlem / profilaksi'),
    'w07511': ('kenevir', 'kenevir / esrar bitkisi'),
    'w07512': ('ançüez', 'hamsi / ançüez'),
    'w07513': ('asterisk', 'yıldızcık / yıldız işareti'),
    'w07514': ('boyama', 'boyama / boya işi'),
    'w07515': ('kompartıman (tren)', 'kompartıman (tren) / kupe (araba)'),
    'w07516': ('kabuk', 'bakla / kabuk (baklagil)'),
    'w07517': ('zapt etmek', 'engellemek / durdurmak / önlemek'),
    'w07518': ('yaklaştırmak', 'yaklaştırmak / yakınlaştırmak'),
    'w07519': ('seyis', 'seyis / at bakıcısı'),
    'w07520': ('firari', 'firari kadın / kaçak'),
    'w07521': ('artık', 'fazla / aşırı / artık'),
    'w07523': ('patiska', 'patiska / ince pamuklu'),
    'w07524': ('ertelemek', 'ertelemek / geciktirmek'),
    'w07526': ('hışırtı', 'hışırtı / hafif ses'),
    'w07527': ('varyasyon', 'varyasyon / çeşitleme'),
    'w07528': ('bayağılık', 'bayağılık / basmakalıp söz'),
    'w07530': ('mabet', 'mabet / kutsal yer / kutsal emanet'),
    'w07531': ('pat diye ses çıkarmak', 'şaplak atmak / pat diye vurmak / pat diye koymak'),
    'w07532': ('yorucu', 'yorucu / bitirici'),
    'w07533': ('kızdırmak', 'kızdırmak / öfkelendirmek'),
    'w07536': ('yumuşatmak, gidermek (etkisini)', 'yumuşatmak / gidermek / düzleştirmek'),
    'w07537': ('girdap', 'girdap / anafor'),
    'w07538': ('verem', 'verem / tüberküloz'),
    'w07539': ('ders vermek', 'ders vermek / nasihat etmek'),
    'w07540': ('tâbi', 'tâbi / vasal'),
    'w07541': ('kürklü', 'kürklü / kürkten'),
    'w07542': ('mâkul', 'mantıklı / makul / sağduyulu'),
    'w07543': ('sokulmak', 'sokulmak / yaslanmak'),
    'w07544': ('akgünlük', 'akgünlük / buhur'),
    'w07546': ('iribaş', 'iribaş / kurbağa larvası'),
    'w07547': ('kaçınmak', 'kaçınmak / çekimser kalmak'),
    'w07548': ('yankesici', 'yankesici / cepçi'),
    'w07549': ('lise', 'lise / özel lise'),
    'w07550': ('döndürmek', 'döndürmek / çevirmek'),
    'w07551': ('bakterili', 'bakteriyel / bakteri kaynaklı'),
    'w07552': ('kararsız', 'kararsız / değişken'),
    'w07553': ('papaz (Katolik)', 'papaz (Katolik) / rahip'),
    'w07555': ('dolaşma', 'yürüme / dolaşma / tedavülde olma'),
    'w07557': ('ceza', 'ceza / tahsil / disiplin cezası'),
    'w07558': ('botanik', 'botanik / bitkilerle ilgili'),
    'w07559': ('homurdanmak', 'hırlamak / ters cevap vermek'),
    'w07560': ('kapitalist', 'kapitalist / sermayedar'),
    'w07561': ('aromalı', 'aromalı / hoş kokulu'),
    'w07562': ('şeytani', 'şeytani / satanik'),
    'w07563': ('şişirmek', 'şişmek / kabarmak'),
    'w07564': ('canlı', 'canlı / atılgan / hızlı konuşan'),
    'w07565': ('öncü', 'öncü / avangart'),
    'w07566': ('yutmak', 'yutmak / bol bol yutmak'),
    'w07567': ('oyma', 'oyma / kabartma / vida dişi'),
    'w07568': ('gevezelik etmek', 'gevezelik etmek / karıştırmak / yıpratmak'),
    'w07571': ('abrakadabra', 'abrakadabra / saçmalık'),
    'w07572': ('şaşılmak', 'şaşırmak / hayret etmek'),
    'w07573': ('dörtlü', 'dörtlü / kuartet'),
    'w07574': ('hoparlör', 'hoparlör / megafon'),
    'w07575': ('imam', 'imam / din önderi'),
    'w07577': ('mason', 'mason / farmason'),
    'w07578': ('gevşek ahlaklı', 'gevşek ahlaklı / başıboş / dağınık'),
    'w07579': ('termonükleer', 'termonükleer / füzyon'),
    'w07580': ('bir araya getirme', 'bir araya getirme / seçme / derleme'),
    'w07581': ('kesmek', 'kesmek / kesip ayırmak'),
    'w07583': ('cezbetmek', 'cezbetmek / kandırmak'),
    'w07584': ('ciddiyet', 'ciddiyet / önem'),
    'w07585': ('karamela', 'karamela / şeker'),
    'w07586': ('orta saha', 'orta saha oyuncusu'),
    'w07588': ('az gelişmiş', 'az gelişmiş / geri kalmış'),
    'w07589': ('zararlı', 'zararlı / yıkıcı / ölümcül'),
    'w07590': ('abraş', 'benekli / alacalı'),
    'w07592': ('abone', 'abonman / abonelik kartı'),
    'w07593': ('şaşkınlık', 'şaşkınlık / kafa karışıklığı'),
    'w07594': ('fosil', 'fosil / maden'),
    'w07595': ('öğretim üyesi', 'akademisyen / akademi üyesi'),
    'w07596': ('fesat', 'fesat / karışıklık / kargaşa'),
    'w07598': ('hesaplamak', 'hesaplamak / saymak'),
    'w07599': ('eksen', 'eksen / mil'),
    'w07600': ('çalışkan', 'çalışkan / özenli / gayretli'),
    'w07601': ('saban', 'saban / pulluk'),
    'w07602': ('hileci kumarbaz', 'hileci kumarbaz / hilebaz'),
    'w07603': ('ahlak', 'ahlak / ahlaklılık'),
}

DROP = {
    'w07433': 'камбоджа',
    'w07457': 'мали',
    'w07529': 'кувейт',
    'w07582': 'клитор',
    'w07437': 'глас',
    'w07522': 'отморозок',
    'w07469': 'заточка',
}
