# -*- coding: utf-8 -*-
"""B2 inceleme, parti 1."""

FIXES = {
    'w06400': ('yuvarlamak', 'yuvarlamak / gezdirmek (araçla) / sürmek'),
    'w06401': ('bağışlamak', 'hediye vermek / bahşetmek'),
    'w06402': ('kazan', 'kazan / kazan dairesi'),
    'w06405': ('gerçeklik', 'gerçeklik / orijinallik'),
    'w06408': ('zahmete sokmak', 'zahmete sokmak / yormak'),
    'w06409': ('sallamak', 'sallamak / el sallamak / savurmak'),
    'w06410': ('asilce', 'asilce / soylu bir biçimde'),
    'w06411': ('dostça', 'dostça / arkadaşça'),
    'w06412': ('koka bitkisi', 'koka bitkisi / koka'),
    'w06414': ('inandırıcı olmayan', 'inandırıcı olmayan / ikna edici olmayan'),
    'w06415': ('alaşım', 'alaşım / (nehirde) sal ile taşıma'),
    'w06416': ('kabuk', 'kabuk (yumurta, ceviz)'),
    'w06417': ('şaşkınlık', 'şaşkınlık / çaresizlik'),
    'w06419': ('boğulma', 'boğulma / nefes darlığı'),
    'w06420': ('gizli servis', 'gizli servis / istihbarat teşkilatı'),
    'w06422': ('ışık dizisi', 'ışık dizisi / çelenk'),
    'w06423': ('karamela', 'karamela / tereyağlı şeker'),
    'w06424': ('söndürmek', 'söndürmek / üfleyerek söndürmek'),
    'w06425': ('bastırmak', 'bastırmak / sıkıştırmak / sarılmak'),
    'w06427': ('şiddetle esmek', 'şiddetle esmek / kasıp kavurmak / öfkelenmek'),
    'w06428': ('tesisatçı', 'tesisatçı / çilingir / tornacı'),
    'w06429': ('uyum sağlamak', 'uyum sağlamak / alışmak'),
    'w06431': ('yolcu gemisi', 'yolcu gemisi / yolcu uçağı'),
    'w06432': ('uygun', 'uygun / yerinde / makul'),
    'w06434': ('istekli', 'istekli / gönüllü'),
    'w06435': ('haberci', 'haberci / müjdeci'),
    'w06436': ('dayanmak', 'dayanmak / yaslanmak'),
    'w06437': ('tepsi', 'tepsi / seyyar tezgâh / oluk'),
    'w06438': ('pipet', 'pipet / küçük boru / pipo'),
    'w06440': ('parçalamak', 'parçalamak / yıkıp dökmek'),
    'w06441': ('halletmek', 'halletmek / yoluna koymak'),
    'w06443': ('açılmak', 'açılmak / ortaya çıkmak'),
    'w06444': ('kapıcı', 'kapıcı / sokak süpürücü / silecek'),
    'w06445': ('yıkanıp gitmek', 'yıkanıp gitmek / (argo) sıvışmak'),
    'w06447': ('sürmek', 'sürmek / dürtmek / dürtükleyerek hızlandırmak'),
    'w06449': ('beklemek', 'beklemek / fırsat kollamak'),
    'w06450': ('aklını başına toplamak', 'aklını başına toplamak / vazgeçmek'),
    'w06451': ('faşist', 'faşist / faşizme ait'),
    'w06453': ('yaşlanma', 'yaşlanma / eskime'),
    'w06454': ('öngörmek', 'öngörmek / önceden hesaba katmak'),
    'w06455': ('gizli', 'gizli / örgütlü gizlilik'),
    'w06456': ('karıncık', 'karıncık / küçük mide'),
    'w06457': ('gerçekleşmek', 'gerçekleşmek / yerine gelmek'),
    'w06458': ('sarnıç', 'sarnıç / tanker / depo'),
    'w06461': ('vahşileşmek', 'vahşileşmek / hayvanlaşmak'),
    'w06463': ('eski eşya', 'eski eşya / hurda'),
    'w06464': ('cevher', 'cevher / maden filizi'),
    'w06465': ('bağırmak', 'bağırmak / haykırmak'),
    'w06467': ('etiket', 'etiket / künye'),
    'w06468': ('boru çalmak', 'boru çalmak / yaymak'),
    'w06470': ('abluka', 'abluka / kuşatma'),
    'w06472': ('nazik', 'nazik / kaygan (konu) / hassas'),
    'w06475': ('inatçılık', 'inatçılık / dikbaşlılık'),
    'w06476': ('piton', 'piton / büyük yılan'),
    'w06478': ('burç yorumu', 'burç yorumu / fal'),
    'w06479': ('sıkmak', 'sıkmak / sıkarak çıkarmak'),
    'w06480': ('tiraj', 'tiraj / baskı adedi / çekiliş'),
    'w06482': ('ses', 'ses / seslenme / tını'),
    'w06483': ('istihdam', 'istihdam / meşguliyet'),
    'w06484': ('hayalet', 'hayalet / hayal'),
    'w06485': ('rastgele', 'rastgele / gelişigüzel'),
    'w06486': ('engebeli', 'engebeli / düzensiz / pürüzlü'),
    'w06488': ('belgeler', 'belgeler / dokümantasyon'),
    'w06489': ('doymak bilmez', 'doymak bilmez / açgözlü'),
    'w06491': ('azalma', 'azalma / küçülme'),
    'w06493': ('gebe', 'hamile / gebe'),
    'w06494': ('madem ki', 'madem / eğer'),
    'w06496': ('ayrıntı', 'ayrıntı / ince ayrım / nüans'),
    'w06497': ('bitmek bilmeyen', 'bitmek bilmeyen / sonsuz'),
    'w06498': ('tükenmek', 'tükenmek / kurumak'),
    'w06499': ('elverişlilik', 'elverişlilik / uygunluk / geçerlilik'),
    'w06500': ('yelpaze', 'yelpaze / yelpaze biçimi'),
    'w06502': ('kâğıt öğütücü', 'kâğıt öğütücü / imha makinesi'),
    'w06503': ('tanka ait', 'tanka ait / tank (sıfat)'),
    'w06504': ('sağlama', 'sağlama / tahsis / verme'),
    'w06505': ('hazırcevap', 'hazırcevap / becerikli'),
    'w06506': ('toptan satın almak', 'toptan satın almak / hepsini almak'),
    'w06507': ('tütün', 'tütün (sıfat)'),
    'w06508': ('emsalsiz', 'emsalsiz / benzeri görülmemiş'),
    'w06510': ('başrahip', 'başrahip / baş keşiş'),
    'w06511': ('otlak', 'otlak / mera'),
    'w06512': ('izdüşüm', 'izdüşüm / projeksiyon'),
    'w06513': ('mineral', 'mineral / madensel'),
    'w06514': ('çekiç', 'çekiç (büyük) / balyoz'),
    'w06515': ('açıklanabilir', 'açıklanabilir / anlaşılabilir'),
    'w06516': ('rövanş', 'rövanş / intikam'),
    'w06517': ('müsvedde', 'müsvedde / taslak'),
    'w06518': ('asa', 'asa / değnek'),
    'w06519': ('sırt çantası', 'sırt çantası / okul çantası'),
    'w06521': ('eğilim', 'eğilim / yatkınlık'),
    'w06522': ('saçmak', 'saçmak / etrafa atmak'),
    'w06523': ('genel müdür', 'genel müdür / CEO'),
    'w06524': ('vızıltı', 'vızıltı / uğultu'),
    'w06525': ('silüet', 'silüet / siluet'),
    'w06526': ('dolu', 'dolu / (mecaz) yağmur'),
    'w06527': ('dahil etmek', 'dahil etmek / sürüklemek'),
    'w06528': ('gürlemek', 'gürlemek / gümbürdemek'),
    'w06529': ('eleştiri', 'eleştiri / kitap değerlendirmesi'),
    'w06530': ('tüccar', 'tüccar / esnaf (eski)'),
    'w06531': ('meslektaş', 'meslektaş / hemcins / kardeş'),
    'w06532': ('bir anda', 'bir anda / hemen'),
    'w06533': ('müvekkil', 'müvekkil / savunulan kişi'),
    'w06534': ('memnuniyetle', 'memnuniyetle / isteyerek'),
    'w06535': ('olgunlaşmamış', 'olgunlaşmamış / ham'),
    'w06537': ('partiye ait', 'partiye ait / parti üyesi'),
    'w06539': ('kefil', 'kefil / garantör'),
    'w06540': ('icat etmek', 'icat etmek / bulmak'),
    'w06541': ('bağırarak söylemek', 'bağırarak söylemek / haykırmak'),
    'w06542': ('lekesiz', 'lekesiz / günahsız'),
    'w06543': ('başvurmak', 'başvurmak / el atmak'),
    'w06544': ('azaltmak', 'azaltmak / küçültmek'),
    'w06545': ('ayırma', 'ayırma / salgı / vurgulama'),
    'w06546': ('ikon', 'ikon / (dini) tasvir'),
    'w06547': ('gözetlemek', 'gözetlemek / aramak (bakarak)'),
    'w06548': ('sürmek', 'sürmek / boyamak / ıskalamak'),
    'w06549': ('çökük', 'çökük / içe göçmüş'),
    'w06551': ('tatar yayı', 'tatar yayı / arbalet'),
    'w06553': ('kırlangıç', 'kırlangıç / (argo) tatlım'),
    'w06554': ('yağlamak', 'yağlamak / sürmek / bulaştırmak'),
    'w06555': ('hacı', 'hacı / seyyah'),
    'w06556': ('kapora', 'kapora / avans'),
    'w06557': ('gerçekleşmek', 'gerçekleşmek / yapılmak'),
    'w06559': ('dışarı atlamak', 'dışarı atlamak / fırlamak'),
    'w06561': ('topluluk', 'topluluk / takım / bütün'),
    'w06562': ('ilerlemek', 'ilerlemek / gelişmek / kötüleşmek (hastalık)'),
    'w06563': ('indirgemek', 'basitleştirmek / sadeleştirmek'),
    'w06564': ('galaktik', 'galaktik / galaksiye ait'),
    'w06566': ('hendek', 'hendek / çukur'),
    'w06567': ('yavru', 'yavru (hayvan)'),
    'w06568': ('berber', 'berber / kuaför'),
    'w06569': ('eğlendirmek', 'eğlendirmek / oyalamak'),
    'w06570': ('yalak', 'yalak / tekne (kap)'),
    'w06572': ('hakir', 'hakir / aşağılık'),
    'w06573': ('macera', 'macera / riskli girişim'),
    'w06574': ('komün', 'komün / topluluk'),
    'w06575': ('levrek', 'tatlı su levreği / perki'),
    'w06577': ('kâğıt', 'kâğıt (sıfat) / kâğıttan'),
    'w06578': ('dayanıklılık', 'dayanıklılık / sağlamlık'),
    'w06581': ('kamp yeri', 'kamp yeri / kamp alanı'),
    'w06582': ('enkaz', 'harabe / yıkıntı / bitkin kişi'),
    'w06583': ('vatandaş', 'vatandaş (kadın) / sivil hayat'),
    'w06584': ('ayrılmak', 'ayrılmak / elenmek / terk etmek'),
    'w06587': ('jaluzi', 'jaluzi / panjur'),
    'w06588': ('tutkuyla', 'tutkuyla / hararetle'),
    'w06591': ('egemenlik', 'egemenlik / hâkimiyet'),
    'w06592': ('teslim', 'teslim / kayıtsız şartsız teslim'),
    'w06593': ('gözden düşürmek', 'gözden düşürmek / itibarsızlaştırmak'),
    'w06595': ('bronzlaşmış', 'bronzlaşmış / güneşten yanmış'),
    'w06596': ('eşkıya', 'eşkıya (sıfat) / haydutça'),
    'w06597': ('minyon', 'minyon / küçük'),
    'w06599': ('bilemek', 'bilemek / (kemirerek) yemek / (gözyaşı) dökmek'),
}

DROP = {
    'w06473': 'але',
    'w06501': 'брысь',
    'w06565': 'аполлон',
    'w06490': 'пук',
    'w06560': 'халявный',
}
