# -*- coding: utf-8 -*-
"""B2 inceleme, parti 11."""

FIXES = {
    'w08408': ('vitray', 'vitray / renkli cam'),
    'w08409': ('zikzak', 'zikzak / yılankavi'),
    'w08410': ('hesapsız', 'hesapsız / sayısız / sonsuz'),
    'w08411': ('açık', 'boş / açık (kadro)'),
    'w08412': ('pazarlamak', 'satmak / pazarlamak / sürmek'),
    'w08413': ('hatırlatma kağıdı', 'kopya kâğıdı / hatırlatma kâğıdı'),
    'w08414': ('siper', 'siper / şapka siperi / güneşlik'),
    'w08415': ('çatlak', 'çatlak / yarık / dar geçit'),
    'w08416': ('kusursuz', 'kusursuz / lekesiz'),
    'w08417': ('ulumak', 'ulumak / inlemek'),
    'w08418': ('step (dansı), adım', 'step (dans) / tempo'),
    'w08419': ('armadillo', 'zırhlı gemi / armadillo'),
    'w08420': ('özellik', 'özellik / nitelik / simge'),
    'w08422': ('çatı katı', 'çatı katı / tavan arası oda'),
    'w08423': ('yağma etmek', 'yağmalamak / talan etmek'),
    'w08424': ('telemetri', 'telemetri / uzaktan ölçüm'),
    'w08425': ('hükmetmek', 'hükmetmek / egemen olmak'),
    'w08426': ('bakkal', 'bakkaliye / bakkal (sıfat)'),
    'w08428': ('güzel kokulu', 'güzel kokulu / hoş kokan'),
    'w08429': ('uyum', 'uyum / düzen / ahenk'),
    'w08430': ('netlik', 'netlik / keskinlik / sertlik'),
    'w08431': ('hortum', 'hortum / kasırga'),
    'w08432': ('billur', 'billur / kristal'),
    'w08433': ('öğleden sonra', 'öğleden sonra / ikindi'),
    'w08434': ('ekskavatör', 'ekskavatör / iş makinesi'),
    'w08435': ('plastik', 'plastik / plastik madde'),
    'w08436': ('akran', 'yaşıt (kadın) / akran'),
    'w08437': ('sergi', 'sergi / teşhir / (foto) pozlama'),
    'w08438': ('ana yurt', 'ana yurt / vatan'),
    'w08439': ('yenidoğan', 'yenidoğan / bebek'),
    'w08440': ('hava basınçlı', 'hava basınçlı / pnömatik'),
    'w08441': ('köpürtmek', 'çırpmak / köpürtmek / kabartmak'),
    'w08442': ('aldanmak', 'aldanmak / yanılmak'),
    'w08443': ('etkisiz', 'dişsiz / etkisiz'),
    'w08444': ('kırılmaz', 'kırılmaz / sarsılmaz / yıkılmaz'),
    'w08445': ('sarsmak', 'sarsmak / titretmek'),
    'w08446': ('nezaketsiz', 'nezaketsiz / soğuk / düşmanca'),
    'w08447': ('biçerdöver', 'biçerdöver / kombine'),
    'w08448': ('avm', 'avm / alışveriş merkezi'),
    'w08449': ('ajur', 'ajur / delikli işleme / düzen (dizin)'),
    'w08450': ('sarkaç', 'sarkaç / pandül'),
    'w08452': ('gaz boru hattı', 'gaz boru hattı / doğalgaz hattı'),
    'w08453': ('inceleme', 'inceleme / risale / anlaşma'),
    'w08454': ('varil', 'varil / (petrol) varil'),
    'w08455': ('kalker', 'kireçtaşı'),
    'w08456': ('apse', 'apse / çıban / irinli yara'),
    'w08457': ('heyelan', 'heyelan / toprak kayması'),
    'w08458': ('şart koşmak', 'şart koşmak / şartlarını belirlemek / iftira etmek'),
    'w08459': ('sevgili', 'sevgili (kadın, halk dili) / gönül eğlendiren'),
    'w08460': ('şirketler grubu', 'şirketler grubu / holding'),
    'w08461': ('zanaatçı', 'zanaatçı / esnaf'),
    'w08462': ('seçenek', 'seçenek / opsiyon'),
    'w08463': ('bayat', 'bayat / duygusuz / katı kalpli'),
    'w08464': ('kolik', 'kolik / kramp'),
    'w08465': ('günlük', 'günlük / her gün olan'),
    'w08466': ('tam yetkili', 'yetkili / vekil / temsilci'),
    'w08467': ('acele acele', 'aceleyle / çabucak'),
    'w08468': ('yankı', 'yankı / yansıma / iz'),
    'w08469': ('planetaryum', 'planetaryum / gök evi'),
    'w08471': ('fakir', 'yoksul / fakir / geliri olmayan'),
    'w08472': ('hararetli', 'kavurucu / yakıcı / hararetli'),
    'w08473': ('sebepli', 'gerekçeli / motive olmuş'),
    'w08474': ('eflatun', 'eflatun / leylak rengi'),
    'w08475': ('vurguncu', 'vurguncu / spekülatör'),
    'w08476': ('bitirmek', 'bitirmek / yormak / tüketmek'),
    'w08478': ('geçilmez', 'geçilmez / aşılmaz'),
    'w08479': ('keten', 'keten / keten bitkisi'),
    'w08480': ('sahte', 'sahte / yapmacık / göstermelik'),
    'w08481': ('tutulmuş', 'tutuklu / gözaltındaki kişi'),
    'w08482': ('gözdağı', 'gözdağı / korkutma'),
    'w08484': ('boncuk', 'boncuk / minik boncuk'),
    'w08485': ('eritrosit', 'eritrosit / alyuvar'),
    'w08486': ('viyola', 'viyola / alto'),
    'w08487': ('çömelme', 'çömelme / squat'),
    'w08488': ('meyan', 'meyan kökü / meyan'),
    'w08489': ('çıngırak', 'çıngırak / bebek çıngırağı'),
    'w08491': ('kesicidiş', 'kesici diş / keski / bıçak'),
    'w08493': ('estetik', 'estetik / güzellikle ilgili'),
    'w08494': ('şiir', 'şiir / lirik şiir / duygusal şiir'),
    'w08496': ('hazine', 'hazine / kaynak / pınar'),
    'w08497': ('gezi', 'gezi / seyahat / yolculuk'),
    'w08498': ('kışlamak', 'kışlamak / kışı geçirmek'),
    'w08499': ('bilgisiz', 'bilgisiz / acemi / amatör'),
    'w08500': ('çalı çırpı', 'çalı çırpı / kuru dal / kızarmış hamur (yiyecek)'),
    'w08502': ('kâr (argo), et suyu (yemek)', 'et suyu / kâr (argo)'),
    'w08504': ('göçmen', 'göçmen / göç eden kişi'),
    'w08505': ('açıklama', 'açıklama / izah'),
    'w08506': ('ceza kesmek', 'ceza kesmek / para cezası vermek'),
    'w08507': ('tembelhayvan', 'tembel hayvan (memeli)'),
    'w08508': ('öğrenmek', 'öğrenmek / uyum sağlamak / işletmeye açmak'),
    'w08509': ('dejenere etmek', 'gerilemek / dejenere olmak / bozulmak'),
    'w08511': ('ilmikli kapan', 'ilmikli kapan / tuzak'),
    'w08512': ('borş (çorba)', 'pancar çorbası / borş'),
    'w08514': ('turist', 'turist (kadın)'),
    'w08515': ('faaliyet', 'işleyiş / faaliyet'),
    'w08516': ('konuşmacı', 'konuşmacı / sunum yapan kişi'),
    'w08517': ('aristokrasi', 'aristokrasi / soylular sınıfı'),
    'w08518': ('bölümlendirme', 'sınıflandırma / bölümlendirme'),
    'w08519': ('lirik', 'lirik / duygusal'),
    'w08520': ('aday', 'aday (kadın)'),
    'w08521': ('dogma', 'dogma / kesin inanç'),
    'w08523': ('mezkûr', 'yukarıda adı geçen / mezkûr'),
    'w08526': ('gambit', 'gambit / (satranç) açılış'),
    'w08527': ('intikam', 'intikam / öç'),
    'w08528': ('durgunluk', 'durgunluk / durağanlık'),
    'w08529': ('agregat', 'agregat / makine takımı'),
    'w08530': ('adamotu', 'adamotu / mandragora'),
    'w08531': ('kap', 'kap / hacim / kapasite'),
    'w08532': ('simsar', 'simsar / komisyoncu'),
    'w08533': ('dizanteri', 'dizanteri / kanlı ishal'),
    'w08534': ('tazmin etmek', 'tazmin etmek / geri ödemek / telafi etmek'),
    'w08535': ('mitre', 'mitre / piskopos külahı'),
    'w08537': ('hız', 'hız / çabukluk'),
    'w08538': ('otçul', 'otçul / ot yiyen'),
    'w08539': ('teslim olmak', 'teslim olmak / pes etmek'),
    'w08540': ('taklidini yapmak (alay ederek)', 'taklidini yapmak / alay etmek'),
    'w08541': ('buruşturmak', 'buruşturmak / ezmek / yoğurmak'),
    'w08542': ('izinsiz', 'izinsiz / başına buyruk'),
    'w08543': ('ani şiddetli heyecan', 'ani şiddetli heyecan / cinnet'),
    'w08544': ('kaleydoskop', 'kaleydoskop / dönence'),
    'w08546': ('tımar fırçası', 'tımar fırçası / yün tarağı'),
    'w08547': ('kepçe', 'kepçe / kova / (kepçe) kabı'),
    'w08548': ('şamandıra', 'şamandıra / işaret şamandırası'),
    'w08550': ('balıkçılık', 'avlanma / balık tutma / avcılık'),
    'w08551': ('hidrolik', 'hidrolik / akışkanlar mekaniği'),
    'w08552': ('kodes, hapishane (argo)', 'kodes / hapishane (argo) / karakol nezareti'),
    'w08553': ('ağır basmak', 'ağır basmak / üstün olmak / çoğunlukta olmak'),
    'w08554': ('göz doktoru', 'göz doktoru / oftalmolog'),
    'w08555': ('dekompresyon', 'dekompresyon / basınç düşürme'),
    'w08556': ('cebe indirmek', 'cebe indirmek / zimmetine geçirmek'),
    'w08557': ('savurgan', 'savurgan / müsrif'),
    'w08558': ('fermuar', 'toka / kopça / fermuar'),
    'w08559': ('anlamlı', 'anlamlı / bilinçli / mantıklı'),
    'w08560': ('kazanmak', 'kazanmak / yenmek (oyunda) / (konuyu) işlemek'),
    'w08561': ('termometre', 'termometre / derece'),
    'w08562': ('kuyruk sokumu', 'kuyruk sokumu / kuyruk kemiği'),
    'w08564': ('ginseng', 'ginseng / ginseng kökü'),
    'w08565': ('temin', 'temin / güvence / söz'),
    'w08566': ('ringa', 'ringa balığı / tuzlu ringa'),
    'w08567': ('kütük, cellat kütüğü (idam kütüğü)', 'kütük / idam kütüğü / cellat kütüğü'),
    'w08569': ('dublör', 'dublör / gösteri sanatçısı'),
    'w08570': ('palet', 'palet / renk paleti'),
    'w08571': ('su aygırı', 'su aygırı / hipopotam'),
    'w08572': ('otantik', 'otantik / gerçek / özgün'),
    'w08573': ('ekşimek', 'ekşimek / mayalanmak / keyfi kaçmak'),
    'w08574': ('manevra ile ilgili', 'manevra ile ilgili / manevra (sıfat)'),
    'w08575': ('bard', 'halk şairi / bard / şarkıcı şair'),
    'w08576': ('ritmik', 'ritmik / düzenli'),
    'w08577': ('etkileşimli', 'etkileşimli / interaktif'),
    'w08578': ('beysbolcu', 'beyzbolcu / beyzbol oyuncusu'),
    'w08579': ('yüksek dereceli', 'yüksek rütbeli / üst düzey'),
    'w08580': ('köşegen', 'köşegen / diyagonal'),
    'w08581': ('ikindi kahvaltısı', 'ikindi kahvaltısı / öğleden sonra atıştırması'),
    'w08583': ('devingenlik', 'hareketlilik / devingenlik'),
    'w08584': ('kompresör', 'kompresör / sıkıştırıcı'),
    'w08585': ('rehber', 'rehber / tur rehberi'),
    'w08586': ('kimlik', 'kimlik / özdeşlik'),
    'w08587': ('jandarma', 'jandarma / jandarma teşkilatı'),
    'w08588': ('yıldız gemisi', 'yıldız gemisi / uzay gemisi'),
    'w08590': ('duygusuzluk', 'duygusuzluk / ilgisizlik / kayıtsızlık'),
    'w08591': ('genelkurmay', 'genelkurmay / genel kurmay'),
    'w08592': ('boğulmak (yerken)', 'boğulmak (yerken) / tıkanmak'),
    'w08593': ('zulüm', 'zulüm / baskı / kovuşturma'),
    'w08594': ('iradesiz', 'iradesiz / zayıf karakterli'),
    'w08596': ('transit', 'transit / geçiş (sıfat)'),
    'w08597': ('saplamak', 'saplamak / batırmak'),
    'w08598': ('baş döndürücü', 'baş döndürücü / inanılmaz'),
    'w08599': ('çekişme', 'çekişme / kavga / anlaşmazlık'),
    'w08600': ('orta halli', 'orta halli / fakir olmayan'),
    'w08601': ('mengene', 'mengene / (mecaz) sıkıştırma'),
    'w08602': ('eylemsizlik', 'eylemsizlik / atalet'),
    'w08604': ('özgünlük', 'özgünlük / orijinallik'),
    'w08605': ('erginleşmek', 'olgunlaşmak / (şiirsel) görmek'),
    'w08607': ('baget, uzun ince ekmek (baguette)', 'baget / uzun ince ekmek / çerçeve'),
}

DROP = {
    'w08501': 'бавария',
    'w08606': 'мальта',
    'w08608': 'анкара',
    'w08451': 'пуп',
    'w08477': 'долбануть',
    'w08568': 'остолоп',
    'w08522': 'якшаться',
}
