# -*- coding: utf-8 -*-
"""B2 inceleme, parti 13."""

FIXES = {
    'w08809': ('edinmek', 'edinmek / öğrenmek / kaynaktan almak'),
    'w08810': ('parıldamak', 'parıldamak / kıvılcım saçmak'),
    'w08811': ('çilek', 'yabani çilek / çilek'),
    'w08812': ('bakkal', 'bakkaliye / bakkal ürünleri'),
    'w08813': ('bedbin', 'kötümser / bedbin'),
    'w08814': ('tavizsiz', 'tavizsiz / uzlaşmaz'),
    'w08815': ('kokmuş', 'kokmuş / bozulmuş'),
    'w08817': ('dayanılmaz', 'dayanılmaz / katlanılmaz'),
    'w08818': ('sağlık memuru', 'sağlık memuru / hekim yardımcısı'),
    'w08820': ('yol ayrımı', 'yol ayrımı / iki yol'),
    'w08821': ('derinlik', 'derinlik / derin yer'),
    'w08823': ('koç (hayvan), Koç burcu', 'koç / Koç burcu'),
    'w08824': ('asabiyet', 'asabiyet / sinirlilik'),
    'w08825': ('nekroz', 'nekroz / doku ölümü'),
    'w08827': ('pandemi', 'pandemi / salgın'),
    'w08828': ('idealizm', 'idealizm / hayalcilik'),
    'w08829': ('maskaralanmak', 'maskaralık yapmak / soytarılık etmek'),
    'w08830': ('venüs çarığı', 'venüs çarığı (orkide) / küçük ayakkabı'),
    'w08831': ('çürüme', 'çürüme / bozunma'),
    'w08832': ('bilgili', 'bilgili / konusunda uzman'),
    'w08833': ('ant içmek', 'ant içmek / yemin etmek'),
    'w08834': ('üzülmek', 'üzülmek / kendini yemek / azap çekmek'),
    'w08836': ('fikrini anlatmak', 'kendini ifade etmek / fikrini anlatmak'),
    'w08837': ('kavurmak', 'kavurmak / hafifçe kızartmak'),
    'w08838': ('ısıtmak', 'ısıtmak / tekrar ısıtmak'),
    'w08839': ('çiğnenmiş', 'çiğnenmiş (yol) / işlek yol'),
    'w08840': ('sahtekârlık', 'sahtekârlık / sahtecilik'),
    'w08841': ('konsorsiyum', 'konsorsiyum / ortaklık'),
    'w08842': ('ilahiyat', 'ilahiyat / teoloji'),
    'w08843': ('kompost', 'kompost / organik gübre'),
    'w08844': ('pas tutmaz', 'paslanmaz / pas tutmaz'),
    'w08845': ('gözetlemek', 'gözetlemek / pusuya yatmak / kollamak'),
    'w08846': ('hükmetmek', 'hükmetmek / saltanat sürmek'),
    'w08848': ('keçeli kalem', 'keçeli kalem / boya kalemi'),
    'w08849': ('günah çıkartma hücresi', 'günah çıkarma hücresi'),
    'w08850': ('delmek', 'delmek / iğneyle delmek'),
    'w08851': ('dinamik', 'dinamik / devingen'),
    'w08852': ('yapışkan', 'yapışkan / koyu (sıvı) / bataklık'),
    'w08853': ('müsamahalı', 'hoşgörülü / müsamahalı'),
    'w08854': ('karalama', 'karalama / özensiz yazı'),
    'w08855': ('çoğunlukla', 'çoğunlukla / ağırlıklı olarak'),
    'w08856': ('göz lekesi', 'göz perdesi / katarakt / (mecaz) göze batan şey'),
    'w08857': ('baştankara', 'baştankara / mavi baştankara'),
    'w08859': ('tur', 'tur / sarım / halka'),
    'w08860': ('gayzer', 'gayzer / kaplıca'),
    'w08863': ('altlık', 'destek / payanda / altlık'),
    'w08865': ('savurgan', 'müsrif / savurgan / har vurup harman savuran'),
    'w08866': ('zamir', 'zamir / adıl'),
    'w08867': ('doyurucu', 'doyurucu / tok tutan'),
    'w08868': ('dalgalanmak', 'dalgalanmak / uçuşmak'),
    'w08869': ('aşılamak', 'aşılamak / alıştırmak / (fikir) aşılamak'),
    'w08870': ('araklamak', 'çalmak / kaçırmak (kız)'),
    'w08871': ('şişman', 'şişman / iri / semiz'),
    'w08872': ('bulutsuz', 'bulutsuz / kaygısız'),
    'w08873': ('vakitsiz', 'vakitsiz / zamansız'),
    'w08874': ('kaçınılmaz', 'kaçınılmaz / önlenemez'),
    'w08875': ('hayvan memesi', 'hayvan memesi / meme (inek)'),
    'w08878': ('kulübe', 'köy evi / kütük ev / kulübe'),
    'w08880': ('tüketmek', 'tüketmek / bitirmek / zayıf düşürmek'),
    'w08881': ('egemenlik', 'egemenlik / bağımsızlık'),
    'w08882': ('tahtırevan', 'tahtırevan / palankin'),
    'w08883': ('eşitlemek', 'eşitlemek / dengelemek'),
    'w08884': ('partisyon', 'partisyon / nota sayfası'),
    'w08885': ('eşdeğer', 'eşdeğer / denk'),
    'w08886': ('horoz mantarı', 'horoz mantarı / küçük tilki'),
    'w08887': ('perhiz yemeği', 'perhiz yemeği / yağsız / etsiz'),
    'w08888': ('poyraz', 'poyraz / Adriyatik rüzgârı'),
    'w08889': ('açılır kapanır', 'katlanır / açılır kapanır'),
    'w08890': ('karaağaç', 'karaağaç / dişbudak'),
    'w08893': ('fanatiklik', 'fanatiklik / taassup'),
    'w08894': ('bereket', 'bolluk / bereket'),
    'w08895': ('alegori', 'alegori / mecaz anlatım'),
    'w08896': ('civar', 'civar / çevredeki'),
    'w08897': ('sinsi', 'sinsi / kurnaz / işbitirici'),
    'w08898': ('tatmak', 'tatmak / yemek (yüce)'),
    'w08899': ('yük getiren', 'yük getiren / külfetli / ağır'),
    'w08900': ('oyuna dalmak', 'oyuna dalmak / aşırı oynamak'),
    'w08902': ('birleştirmek', 'birleştirmek / sağlamlaştırmak / mühürlemek'),
    'w08903': ('bilişim', 'bilişim / bilgisayar bilimi'),
    'w08905': ('karşı çıkmak', 'karşı çıkmak / direnmek'),
    'w08906': ('öz', 'öz / merkez / ortası'),
    'w08908': ('kıvırmak', 'kıvırmak / sıkmak / burmak'),
    'w08909': ('aşırı', 'aşırı / ekstremist'),
    'w08910': ('üzerini çizmek', 'üzerini çizmek / silmek'),
    'w08911': ('bozmak', 'bozmak / biçimsizleştirmek / sakat bırakmak'),
    'w08912': ('tabansız', 'korkak / tabansız'),
    'w08913': ('ısrarla belirtmek', 'ısrarla söylemek / tekrarlayıp durmak'),
    'w08914': ('günlük', 'günlük / her günkü'),
    'w08915': ('idam sehpası', 'idam sehpası / darağacı'),
    'w08916': ('tazminat', 'tazminat / ayrılma bedeli'),
    'w08917': ('şakayık (çiçek)', 'şakayık / şakayık çiçeği'),
    'w08919': ('kızak köpeği', 'kızak köpeği / laika'),
    'w08920': ('enerji tedariki', 'enerji tedariki / elektrik temini'),
    'w08921': ('yutmak', 'yutmak / hızla yutmak'),
    'w08923': ('turkuaz', 'turkuaz / firuze'),
    'w08924': ('aşırı yüklemek', 'aşırı yüklemek / boşaltıp yeniden yüklemek'),
    'w08925': ('bileşik', 'bileşik / birleşik / parçalardan oluşan'),
    'w08926': ('karışmak', 'karışmak / dolanmak / kafası karışmak'),
    'w08927': ('üst geçit', 'üst geçit / viyadük'),
    'w08928': ('çarpık, düzensiz (el yazısı)', 'çarpık / düzensiz (el yazısı) / eğri büğrü'),
    'w08929': ('sakatlamak', 'sakatlamak / şeklini bozmak'),
    'w08930': ('donuk', 'donuk / mat / parlak olmayan'),
    'w08932': ('sözlü', 'sözlü / sözle ilgili'),
    'w08933': ('kutsala saygısızlık', 'kutsala saygısızlık / mukaddesata hakaret'),
    'w08934': ('sinirlilik', 'sinirlilik / huysuzluk'),
    'w08936': ('hafıza kaybı', 'hafıza kaybı / baygınlık'),
    'w08937': ('biçim', 'biçim / kalıp / model (giysi)'),
    'w08938': ('nazar', 'nazar / göz değmesi'),
    'w08939': ('palet parçası', 'palet parçası / paletli araç ayağı'),
    'w08940': ('doymuşluk', 'doyma / doyum / doygunluk'),
    'w08941': ('durgunlaşmak', 'dinmek / yatışmak / sakinleşmek'),
    'w08942': ('kefalet', 'kefalet / güvence'),
    'w08943': ('kızgınlık', 'kızgınlık (dişi hayvan) / kızgınlık dönemi'),
    'w08944': ('ulaşılabilirlik', 'ulaşılabilirlik / erişilebilirlik'),
    'w08946': ('sersemlik', 'sersemlik / donup kalma / uyuşukluk'),
    'w08947': ('filo', 'filo / deniz filosu'),
    'w08948': ('türbe', 'türbe / aile mezarlığı'),
    'w08950': ('feyk', 'feyk / oyun / hile'),
    'w08951': ('melez', 'melez / karışım / hibrit'),
    'w08952': ('buz tepeciği', 'buz kütlesi / buz yığını'),
    'w08953': ('glokom', 'glokom / göz tansiyonu'),
    'w08954': ('kâtip', 'kâtip / yazman'),
    'w08955': ('tabya', 'tabya / kale burcu / sığınak'),
    'w08956': ('ağustos böceği', 'ağustos böceği / zikada'),
    'w08957': ('kayınpeder', 'kayınpeder (kocanın babası)'),
    'w08958': ('yaratma', 'yaratma / inşa / kurma'),
    'w08960': ('boyun eğdirme', 'boyun eğdirme / fetih'),
    'w08961': ('sabit', 'sabit / sabit değer'),
    'w08962': ('titiz', 'titiz / zahmetli / sabır isteyen'),
    'w08963': ('dörtnal', 'dörtnal / galop'),
    'w08964': ('çürük', 'diş çürüğü / çürük'),
    'w08965': ('yeniden anlatım', 'yeniden anlatım / özet anlatım'),
    'w08966': ('üniforma', 'üniforma / askerî giysi takımı'),
    'w08967': ('sükût', 'sükût / sessizlik'),
    'w08968': ('bağımsızlık', 'bağımsızlık / özerklik'),
    'w08970': ('suvat', 'suvat / hayvan içme yeri'),
    'w08972': ('paradigma', 'paradigma / örnek model'),
    'w08973': ('taramak', 'taramak / saçı taramak'),
    'w08974': ('birhücreli', 'tek hücreli'),
    'w08975': ('uzlaşmaz', 'uzlaşmaz / inatçı'),
    'w08976': ('sarmak', 'sarmak / bürümek'),
    'w08977': ('boğuk', 'boğuk / kısık / hırıltılı'),
    'w08978': ('fosil', 'taşlaşmış / fosilleşmiş'),
    'w08979': ('özenle', 'özenle / şefkatle'),
    'w08982': ('pelin otu (yavşan otu)', 'pelin otu / yavşan otu'),
    'w08983': ('emniyetle', 'emniyetle / güvenilir biçimde / sağlam'),
    'w08984': ('funda', 'funda / süpürge otu'),
    'w08986': ('hipotermi', 'hipotermi / vücut ısısı düşmesi'),
    'w08988': ('çeşitlilik', 'çeşitlilik / çok yönlülük'),
    'w08989': ('maaş', 'maaş / ücret / aylık'),
    'w08991': ('baca temizleyicisi', 'baca temizleyicisi / baca sileceği'),
    'w08992': ('hedefe yönelik', 'hedefe yönelik / adresli'),
    'w08995': ('hissiz', 'uyuşmuş / hissiz'),
    'w08996': ('ağır', 'ağır / ıstıraplı / içe sıkıntı veren'),
    'w08997': ('körleşmek', 'körleşmek / gözleri görmez olmak'),
    'w08998': ('gayretli', 'gayretli / hararetli / ateşli'),
    'w08999': ('gayda, kaval (nefesli çalgı)', 'gayda / kaval (nefesli çalgı)'),
}

DROP = {
    'w08826': 'чернобыль',
    'w08904': 'онанизм',
    'w08891': 'сфинктер',
    'w08876': 'жмот',
    'w08971': 'голодранец',
}
