# -*- coding: utf-8 -*-
"""B2 inceleme, parti 12."""

FIXES = {
    'w08609': ('dönemeç', 'dönemeç / viraj / dönüş (uçak)'),
    'w08610': ('kaba', 'kaba / adice / bayağı biçimde'),
    'w08611': ('panorama', 'panorama / geniş manzara'),
    'w08612': ('zenginleştirmek', 'zenginleştirmek / varlıklı kılmak'),
    'w08613': ('süvari askeri, dragon (asker)', 'süvari / ağır süvari / dragon (asker)'),
    'w08614': ('beşik', 'beşik / (pipo) lüle'),
    'w08615': ('döviz', 'döviz (sıfat) / dövizle ilgili'),
    'w08617': ('kurmak', 'kurmak / temellendirmek'),
    'w08618': ('pancur', 'panjur / kepenk / pancur'),
    'w08619': ('iş kesme', 'kesme / durdurma / kesinti'),
    'w08620': ('muhalif', 'muhalif / karşıt görüşlü'),
    'w08621': ('bigünah', 'günahsız / masum'),
    'w08622': ('ısırgan', 'ısırgan / ısırgan otu'),
    'w08623': ('iplik', 'iplik / yün ipliği'),
    'w08624': ('çırpınmak', 'çırpınmak / debelenmek'),
    'w08626': ('kışkırtmak', 'ikna etmeye çalışmak / propaganda yapmak / kışkırtmak'),
    'w08628': ('tabure', 'tabure / kolçaksız sandalye'),
    'w08629': ('tıklamak', 'tıklamak / çağırmak / seslenmek'),
    'w08630': ('küfür', 'küfür / sövme / azar'),
    'w08631': ('sombrero', 'sombrero / geniş kenarlı şapka'),
    'w08633': ('hoşaf', 'komposto / meyve suyu / hoşaf'),
    'w08634': ('yaygara', 'yaygara / gürültü / gürültülü ses'),
    'w08635': ('suçlanmak', 'suçlanmak / itham edilmek'),
    'w08636': ('kanlı kavga', 'kanlı kavga / katliam / kırım'),
    'w08637': ('kayın', 'kayınbirader (kocanın kardeşi) / kayın'),
    'w08638': ('bombus', 'bombus arısı / yabanarısı'),
    'w08641': ('iyileştirmek', 'aklamak / itibarını iade etmek'),
    'w08642': ('diseksiyon yapmak', 'diseksiyon yapmak / kesip incelemek'),
    'w08643': ('çiçeklenme', 'çiçeklenme / çiçek açma'),
    'w08644': ('ebelik', 'ebelik / doğum bilimi'),
    'w08645': ('(bir tür) sincap, çipmank', 'sincap benzeri kemirgen / burunduk'),
    'w08646': ('düğme', 'küçük düğme / düğmecik'),
    'w08647': ('seçimle gelen', 'seçimle gelen / seçilmiş'),
    'w08648': ('dışarıda bırakmak', 'dışlamak / aforoz etmek / ayırmak'),
    'w08649': ('sürmek', 'sürmek / yaymak'),
    'w08650': ('koparmak', 'koparmak / kesmek / yarıda bırakmak'),
    'w08651': ('etkinleşmek', 'harekete geçmek / etkinleşmek'),
    'w08652': ('farklı', 'farklı / ayırt edici'),
    'w08653': ('defne', 'defne / defne ağacı'),
    'w08656': ('ağız', 'ağız (nehir) / nehir ağzı / haliç'),
    'w08657': ('kutu', 'kutu / sepet / hasır sepet'),
    'w08658': ('keşif', 'keşif / bütçe / maliyet hesabı'),
    'w08660': ('vezir', 'vezir (satranç)'),
    'w08661': ('tayf', 'tayfsal / spektral'),
    'w08662': ('tiran', 'despot / zorba / tiran'),
    'w08663': ('piyanist (kadın piyanist)', 'piyanist (kadın)'),
    'w08665': ('yönetmek', 'yönetmek / yönetmenlik yapmak'),
    'w08667': ('laterna', 'laterna / mekanik org'),
    'w08668': ('zayıf', 'zayıf / ince yapılı'),
    'w08669': ('vida', 'vida (ahşap)'),
    'w08670': ('ihlal', 'tecavüz / ihlal / saldırı'),
    'w08671': ('süresiz', 'süresiz / sınırsız'),
    'w08672': ('barınmak', 'barınmak / örtünmek / saklanmak'),
    'w08675': ('çivit', 'çivit / indigo'),
    'w08677': ('korsaj', 'korsaj / üst kısmı (elbise) / üst'),
    'w08679': ('zenginleşme', 'zenginleşme / zenginleştirme'),
    'w08680': ('yaşam düzeni', 'yaşam düzeni / tarz / sistem'),
    'w08681': ('salamura', 'salamura / marine sos / turşu'),
    'w08682': ('karalık', 'karalık / siyahlık / kara'),
    'w08683': ('realizm', 'realizm / gerçekçilik'),
    'w08686': ('savaşsonrası', 'savaş sonrası'),
    'w08687': ('kehribar rengi', 'kehribar / kehribar renkli'),
    'w08688': ('yenmez', 'yenmez / yenilemez'),
    'w08689': ('lökosit', 'lökosit / akyuvar'),
    'w08691': ('kepek', 'kepek (tahıl) / yem'),
    'w08692': ('tutmak', 'içine almak / sığdırmak / almak'),
    'w08693': ('kendi portresi', 'otoportre / kendi portresi'),
    'w08694': ('eskrimci', 'eskrimci / eskrim yapan'),
    'w08695': ('bahadır', 'bahadır / kahraman / yiğit'),
    'w08696': ('müdüriyet', 'müdüriyet / yönetim'),
    'w08697': ('girişken', 'girişken / becerikli'),
    'w08699': ('düşman', 'nefret eden / düşman'),
    'w08700': ('donatmak', 'donatmak / ekipman sağlamak'),
    'w08701': ('nokavt etmek', 'nokavt etmek / bayıltmak'),
    'w08704': ('sık (orman), geri kalmış', 'sık (orman) / cahil / geri kalmış'),
    'w08705': ('sedir', 'sedir / sedir ağacı'),
    'w08706': ('gözden düşme', 'gözden düşme / gözden düşmüşlük'),
    'w08707': ('kesim', 'kesim / biçim / kalıp'),
    'w08708': ('firar', 'firar / askerlikten kaçma'),
    'w08709': ('reverans', 'reverans / diz kırma selamı'),
    'w08710': ('kalp hastası', 'kalp hastası / (bitki) çekirdek'),
    'w08711': ('kasımpatı', 'kasımpatı / krizantem'),
    'w08712': ('adapte etmek', 'uyarlamak / uyum sağlatmak'),
    'w08713': ('kazanmak', 'kazanmak / fethetmek'),
    'w08714': ('ayırma', 'ayırma / tahsis'),
    'w08716': ('atışma', 'atışma / laf dalaşı'),
    'w08718': ('renksiz', 'renksiz / soluk'),
    'w08719': ('gümbürdemek', 'gümbürdemek / gürlemek'),
    'w08720': ('dert', 'dert / bela / talihsizlik'),
    'w08721': ('azaltmak', 'en aza indirmek / azaltmak'),
    'w08722': ('gayrı resmi', 'gayri resmî / resmî olmayan'),
    'w08723': ('pis kokmak', 'pis kokmak / kokmak'),
    'w08725': ('tatula', 'tatula / afyon (mecaz) / sersemletici'),
    'w08726': ('anıtlaştırmak', 'ölümsüzleştirmek / anıtlaştırmak'),
    'w08728': ('kelime hazinesi', 'kelime hazinesi / sözcük dağarcığı'),
    'w08730': ('düzeltmek', 'düzeltmek / ayarlamak'),
    'w08731': ('zarf', 'zarf / lehçe'),
    'w08732': ('mantıklı bir şekilde', 'mantıklı bir şekilde / mantıksal olarak'),
    'w08733': ('atlama ipi', 'atlama ipi / ip'),
    'w08734': ('kınamak', 'kınamak / eleştirmek'),
    'w08736': ('amfora', 'amfora / çift kulplu küp'),
    'w08737': ('itibarını kırmak', 'itibarını zedelemek / gözden düşürmek'),
    'w08738': ('fesatçı', 'fesatçı / kışkırtıcı / ayaklanma çıkaran'),
    'w08739': ('tepesi açılmak', 'kel olmak / saçları dökülmek / tepesi açılmak'),
    'w08740': ('sanatsal', 'sanatçı ruhlu / sanatsal / gösterişli'),
    'w08741': ('dayanaksız', 'nedensiz / dayanaksız / sebepsiz'),
    'w08742': ('temyiz etmek', 'temyize götürmek / itiraz etmek'),
    'w08743': ('prodüktivite', 'verimlilik / üretkenlik'),
    'w08744': ('yansıtmak', 'yansıtmak / göstermek / temsil etmek'),
    'w08748': ('meridyen', 'meridyen / boylam dairesi'),
    'w08749': ('ataman', 'ataman / Kazak lideri'),
    'w08751': ('boyun eğdirmek', 'boyun eğdirmek / bağımlı kılmak / tabi kılmak'),
    'w08753': ('göçmek', 'göç etmek / göçmek'),
    'w08754': ('ağza alınmaz', 'anlatılamaz / ağza alınmaz / tarif edilemez'),
    'w08755': ('yuvarlaklaştırmak', 'yuvarlamak / yuvarlaklaştırmak / (sayıyı) yuvarlamak'),
    'w08756': ('bilgili', 'bilgili / okumuş / kitap kurdu'),
    'w08757': ('cephane', 'teçhizat / askerî donanım'),
    'w08758': ('saçma, mantıksız (ayrıca huysuz)', 'huysuz / saçma / kavgacı'),
    'w08759': ('yenilemek', 'yenilemek / yeniden başlatmak'),
    'w08760': ('bütünsel', 'kapsamlı / her şeyi kapsayan'),
    'w08761': ('kalıp', 'kalıp / ayakkabı kalıbı / prangalık'),
    'w08762': ('ifadesiz', 'duygusuz / soğukkanlı / ifadesiz'),
    'w08763': ('biçimlendirmek', 'biçimlendirmek / oluşturmak / şekillendirmek'),
    'w08764': ('önceden kestirilemeyecek', 'kestirilemez / öngörülemez'),
    'w08765': ('şişkinlik', 'şişkinlik / şişme'),
    'w08766': ('aralık', 'aralık / açıklık / ışık geçiren yer'),
    'w08767': ('referandum', 'referandum / halkoylaması'),
    'w08768': ('mütenasip', 'orantılı / mütenasip'),
    'w08769': ('ima', 'kara çalma / iftira / suçlama'),
    'w08771': ('dipçik', 'dipçik / tüfek dipçiği'),
    'w08772': ('tavlamak', 'kendi tarafına çekmek / kandırıp çekmek'),
    'w08773': ('yetiştirilen kişi', 'eğitilen kişi / yetiştirme (yetimhane)'),
    'w08774': ('yıkıcı', 'yıkıcı / sabotaj (sıfat)'),
    'w08775': ('bağlamak', 'bağlamak / zincirlemek / (demir) dövmek'),
    'w08778': ('biteviye', 'monoton / tekdüze / biteviye'),
    'w08779': ('tahnit', 'mumyalama / tahnit'),
    'w08780': ('cilt', 'cilt / kitap kapağı / (pencere) çerçevesi'),
    'w08781': ('kova', 'kova (küçük) / soğutma kovası'),
    'w08782': ('yaban domuzu', 'yaban domuzu / erkek yaban domuzu'),
    'w08783': ('güvenilirlik', 'güvenilirlik / sağlamlık'),
    'w08784': ('molla', 'molla / din adamı'),
    'w08785': ('parfüm', 'hoş koku / buhur / güzel koku'),
    'w08786': ('ithalat', 'ithalat / içeri getirme'),
    'w08787': ('kuramcı', 'kuramcı / teorisyen'),
    'w08789': ('teskin etmek', 'yatıştırmak / sakinleştirmek / susturmak'),
    'w08790': ('kinci', 'kinci / hınç tutan'),
    'w08792': ('batırmak', 'iflas ettirmek / yıkmak / harap etmek'),
    'w08793': ('uğraşmak', 'uğraşmak / koşuşturmak'),
    'w08794': ('komik', 'komik / komedi (sıfat)'),
    'w08795': ('aşağılık', 'adi / değersiz / kalitesiz'),
    'w08797': ('mutabakat', 'birlik / bütünleşme / kaynaşma'),
    'w08798': ('kalp kası', 'kalp kası / miyokard'),
    'w08799': ('sigaralık', 'sigaralık / sigara tabakası'),
    'w08802': ('aşikarlık', 'aşikârlık / açıklık'),
    'w08803': ('hümanist', 'hümanist / insancıl'),
    'w08804': ('askı', 'askı (giysi) / omuz askısı'),
    'w08805': ('karabina', 'karabina / kısa tüfek'),
    'w08806': ('gaf', 'gaf / yanlış / ıska'),
    'w08807': ('dolaşmak', 'dolaşmak / dolaşıma girmek'),
    'w08808': ('iz bırakmak', 'iz bırakmak / ayak izi bırakmak'),
}

DROP = {
    'w08632': 'нептун',
    'w08674': 'австрия',
    'w08690': 'фольксваген',
    'w08796': 'филиппины',
    'w08676': 'гульден',
    'w08673': 'испражняться',
    'w08724': 'дохнуть',
}
