# -*- coding: utf-8 -*-
"""B2 inceleme, parti 3."""

FIXES = {
    'w06800': ('çam', 'çam (sıfat) / çamdan'),
    'w06802': ('yenilgi', 'bozgun / yenilgi / tahrip'),
    'w06804': ('fışkırma', 'fışkırma / akım / jet'),
    'w06806': ('tüketmek', 'harcamak / tüketmek'),
    'w06807': ('önlemek', 'önlemek / engellemek'),
    'w06808': ('flakon (ilaç)', 'ampul (ilaç) / şişecik'),
    'w06810': ('kast', 'kast / zümre'),
    'w06811': ('abraş', 'alacalı / benekli (at)'),
    'w06813': ('basınç', 'basınç / baskı / hamle'),
    'w06814': ('cafcaf', 'gösteriş / cafcaf / göz boyama'),
    'w06816': ('(nefesini) tutmak, gizlemek', '(nefesini) tutmak / gizlemek / (kin) beslemek'),
    'w06817': ('kıskaç', 'kıskaç / pençe (yengeç)'),
    'w06821': ('suçluluk', 'suçluluk / kabahat'),
    'w06822': ('içine almak', 'içine almak / sığdırmak'),
    'w06823': ('bulunma', 'katılım / bulunma / gizli buluşma'),
    'w06826': ('silahşor', 'silahşor / muşketör'),
    'w06828': ('bent', 'paragraf / bent'),
    'w06831': ('konklav', 'konklav / gizli toplantı'),
    'w06833': ('hesap sorma', 'hesaplaşma / infaz / cezalandırma'),
    'w06835': ('nezle', 'nezle / burun akıntısı'),
    'w06838': ('su aygırı', 'su aygırı / hipopotam'),
    'w06839': ('korku', 'korku / ürperti'),
    'w06840': ('dağıtmak', 'dağıtmak / saçmak'),
    'w06841': ('kahverengi', 'kahverengi / boz'),
    'w06843': ('aldırmazlık', 'kayıtsızlık / ilgisizlik'),
    'w06844': ('satış', 'satış / pazarlama'),
    'w06848': ('uzak', 'uzak / ücra'),
    'w06849': ('tüketmek', 'tüketmek / kullanmak'),
    'w06850': ('çalışkan', 'çalışkan / gayretli'),
    'w06851': ('tıkaç', 'ağız tıkacı'),
    'w06852': ('ölçülülük', 'ölçülülük / temkin'),
    'w06853': ('isteka', 'bilardo istekası / sopa'),
    'w06854': ('rulo, top (kumaş/kağıt)', 'rulo / top (kumaş, kâğıt)'),
    'w06855': ('kiriş', 'kiriş / tendon'),
    'w06856': ('âdeta', 'âdeta / resmen'),
    'w06857': ('keyiflendirmek', 'eğlendirmek / neşelendirmek'),
    'w06859': ('seyyar', 'seyyar / gezici'),
    'w06860': ('yünlü', 'yünlü / yün'),
    'w06861': ('serap', 'serap / hayal'),
    'w06862': ('reseptör', 'reseptör / alıcı'),
    'w06863': ('bilgisizlik', 'bilgisizlik / cehalet'),
    'w06864': ('akın', 'akın / baskın'),
    'w06866': ('vatan', 'vatan / anavatan'),
    'w06868': ('acınacak', 'acınacak / içler acısı'),
    'w06869': ('bağlantılı olmak', 'bağlantılı olmak / haberleşmek'),
    'w06874': ('çiğnemek', 'çiğnemek / ezmek'),
    'w06875': ('korumak', 'korumak / nöbet tutmak / beklemek'),
    'w06876': ('ısrar', 'ısrar / kararlılık'),
    'w06878': ('yay', 'yay / (mecaz) itici güç'),
    'w06879': ('irkilmek', 'irkilmek / ürpermek'),
    'w06880': ('kaçıran', 'kaçıran / araba hırsızı'),
    'w06881': ('kuburluk', 'silah kılıfı'),
    'w06882': ('köşk, kabin (gemi)', 'kabin (kaptan) / (ormanda) kesme / dövüş'),
    'w06884': ('döndürmek', 'geri vermek / iade etmek'),
    'w06885': ('yoğurmak', 'yoğurmak / şekil vermek / yapıştırmak'),
    'w06886': ('kurnaz', 'kurnaz / zekice'),
    'w06887': ('dakik', 'dakik / titiz'),
    'w06888': ('iki taraflı', 'iki taraflı / çift yönlü'),
    'w06889': ('ilginç', 'ilginç / eğlenceli'),
    'w06890': ('çözmek', 'çözmek / yoluna koymak'),
    'w06891': ('cüce', 'cüce / bodur'),
    'w06894': ('ifade şekli', 'ifade şekli / formülasyon'),
    'w06895': ('kimera', 'kimera / hayal / kuruntu'),
    'w06896': ('kapanmak', 'kapanmak / kendini kapatmak / inkâr etmek'),
    'w06897': ('sopa', 'çubuk / sopa / dal'),
    'w06898': ('gösterme', 'gösterme / ibraz / sunma'),
    'w06900': ('yayınlamak', 'yayınlamak / iletmek'),
    'w06903': ('takılmak, şaka yapmak (birine)', 'takılmak / şaka yapmak'),
    'w06904': ('afiş', 'afiş / ilan'),
    'w06906': ('yatıştırmak', 'yatıştırmak / bastırmak'),
    'w06907': ('mücadeleci', 'mücadeleci / atılgan'),
    'w06909': ('iyi niyet', 'iyi niyet / lütuf'),
    'w06910': ('sadakatsizlik', 'sadakatsizlik / hıyanet'),
    'w06913': ('çimdiklemek', 'çimdiklemek / (ot) koparmak / yakmak (soğuk)'),
    'w06914': ('pazu', 'pazu / pazu kası'),
    'w06915': ('araştırmak', 'araştırmak / el yordamıyla aramak'),
    'w06916': ('av hayvanı', 'av hayvanı / yaban hayvanı / (argo) saçmalık'),
    'w06917': ('aylak', 'aylak / boş / işsiz'),
    'w06918': ('atardamarla ilgili', 'atardamarla ilgili / arteriyel'),
    'w06919': ('önceden', 'önceden / ileriye doğru'),
    'w06920': ('kızartmak', 'kızartmak / kavurmak'),
    'w06921': ('bozmak', 'bozmak / çarpıtmak'),
    'w06923': ('izah etmek', 'netleştirmek / açıklığa kavuşturmak'),
    'w06925': ('ahlaksızlık', 'ahlaksızlık / edepsizlik'),
    'w06926': ('manzara', 'manzara / peyzaj'),
    'w06927': ('sağ salim', 'sağ salim / sorunsuz'),
    'w06929': ('yapılabilir', 'yapılabilir / uygulanabilir'),
    'w06931': ('kıyma', 'kıyma / (yemek) iç'),
    'w06934': ('yanıt', 'yanıt / yankı / tepki'),
    'w06935': ('gemici çırağı', 'gemici çırağı / miço'),
    'w06937': ('dilim', 'dilim / bölüm / segment'),
    'w06938': ('deniz kazası', 'gemi kazası / gemi batması'),
    'w06939': ('kaçınmak', 'kaçınmak / savuşmak'),
    'w06940': ('siper', 'siper / hendek'),
    'w06941': ('sürtünmek', 'sürtünmek / ovulmak'),
    'w06942': ('yaygın', 'yaygın / geçerli'),
    'w06944': ('göz alıcı', 'göz alıcı / parlak'),
    'w06945': ('koordine etmek', 'koordine etmek / eşgüdüm sağlamak'),
    'w06946': ('kanat çırpışı', 'sallama / kanat çırpışı / el hareketi'),
    'w06947': ('kısmak', 'kısmak / azaltmak'),
    'w06948': ('bahçecilik', 'bahçecilik / meyvecilik'),
    'w06950': ('direk', 'direk / gemi direği'),
    'w06951': ('anormal', 'anormal / aykırı'),
    'w06952': ('liste', 'liste / döküm'),
    'w06953': ('saf kimse', 'saf kişi / sadedil'),
    'w06954': ('tuzsuz', 'tatsız / tuzsuz / tatlı (su)'),
    'w06955': ('maden', 'maden yatağı / yatak'),
    'w06956': ('bol', 'bol / bereketli'),
    'w06957': ('arızi', 'kazara / arızi / istemeden'),
    'w06958': ('esmek', 'esmek / savurmak / hafifçe esmek'),
    'w06959': ('cimri', 'cimri / eli sıkı'),
    'w06960': ('dizgin', 'dizgin / gem / (mecaz) kontrol'),
    'w06961': ('ezme', 'ezme / patates'),
    'w06962': ('torba', 'torba / heybe'),
    'w06963': ('kütle', 'kütle / geniş alan / dizi'),
    'w06965': ('incik', 'incik / kaval kemiği'),
    'w06966': ('sadaka', 'sadaka / kırıntı / küçük rüşvet'),
    'w06967': ('engizisyon', 'engizisyon / iman mahkemesi'),
    'w06969': ('tornavida', 'tornavida / (içki) screwdriver'),
    'w06970': ('oymak, çıkarmak (göz için)', 'oymak / (göz) çıkarmak'),
    'w06971': ('vasat', 'vasat / sıradan'),
    'w06972': ('dörde bölmek', 'dörde bölmek / çeyreklemek'),
    'w06973': ('hilal', 'hilal / yarım ay'),
    'w06974': ('sırtlan', 'sırtlan / hiyena'),
    'w06977': ('uzatmak', 'uzatmak / germek / esnetmek'),
    'w06978': ('radyasyon', 'radyasyon / ışınımsal'),
    'w06979': ('özerk', 'özerk / bağımsız'),
    'w06980': ('bağışlamak', 'bağışlamak / affetmek / esirgemek'),
    'w06981': ('tane', 'tane (ağırlık ölçüsü) / gren'),
    'w06982': ('asyalı', 'Asyalı kadın'),
    'w06983': ('histeri', 'histeri / kriz'),
    'w06985': ('kolektör', 'kolektör / toplayıcı / tahsildar'),
    'w06987': ('taraftar', 'taraftar / bağlı kişi / yandaş'),
    'w06988': ('duyarlı', 'duyarlı / hassas / kolay etkilenen'),
    'w06989': ('ezmek', 'ezmek / (kas) ısıtmak / (bacak) açmak'),
    'w06990': ('şizofren', 'şizofren / şizofreni hastası'),
    'w06991': ('ameliyatla almak', 'kesip almak / ameliyatla almak'),
    'w06993': ('eşanlamlı', 'eşanlamlı / sinonim'),
    'w06995': ('keçi sakal', 'keçi sakal / küçük sakal'),
    'w06996': ('brifing', 'brifing / bilgilendirme toplantısı'),
    'w06997': ('rüya', 'rüya / düş'),
    'w06998': ('tek', 'tek / yalnız / münferit'),
    'w07000': ('dilim', 'dilim / ince parça'),
}

DROP = {
    'w06805': 'ливан',
    'w06877': 'муженёк',
}
