# -*- coding: utf-8 -*-
"""B2 inceleme, parti 8."""

FIXES = {
    'w07808': ('boyunduruk', 'boyunduruk / esaret'),
    'w07809': ('dökünmek', 'dökünmek / üstüne dökülmek / (ter) içinde kalmak'),
    'w07810': ('hazırlanmak', 'silahlanmak / hazırlanmak'),
    'w07811': ('gezinti', 'gezinti / yürüyüş yolu'),
    'w07812': ('pompalamak', 'pompalamak / boşaltmak'),
    'w07813': ('yan çizmek', 'yan çizmek / kaytarmak'),
    'w07814': ('duygudaş', 'duygudaş / sempatizan'),
    'w07815': ('dayanıklı', 'dayanıklı / dirençli'),
    'w07816': ('dolandırıcılık', 'dolandırıcılık / kazık atma'),
    'w07818': ('müdahale', 'müdahale / işgal'),
    'w07819': ('aylaklık', 'aylaklık / tembellik'),
    'w07820': ('fosil', 'fosil / taşlaşmış kalıntı'),
    'w07821': ('söylemek', 'söylemek / (söz) ağzından kaçırmak'),
    'w07822': ('senkron', 'eş zamanlı / senkron'),
    'w07823': ('beklemek', 'nöbet tutmak / gözetlemek / beklemek'),
    'w07824': ('harcamak', 'harcamak / tüketmek'),
    'w07825': ('alıngan', 'alıngan / dokungan'),
    'w07826': ('ek bina', 'ek bina / ek kısım'),
    'w07827': ('düşürmek', 'yere sermek / düşürmek / (şaşkınlığa) düşürmek'),
    'w07828': ('öcü', 'öcü / somurtkan kişi'),
    'w07829': ('jambon', 'jambon / but'),
    'w07830': ('ağız', 'gırtlak girişi / ağız / boğaz'),
    'w07833': ('vulverin', 'vaşak (Kuzey) / gulo / wolverine'),
    'w07835': ('tatminkâr', 'tatmin edici / yeterli / orta (not)'),
    'w07836': ('kendine âşık', 'kendine âşık / narsist'),
    'w07837': ('jant teli, tığ (örgü)', 'jant teli / örgü şişi / tığ'),
    'w07838': ('zar', 'zar / membran'),
    'w07839': ('nitelendirmek', 'değerlendirmek / nitelendirmek'),
    'w07840': ('kaçık', 'çılgın / kaçık / delişmen'),
    'w07841': ('inatçı', 'inatçı / dik başlı / kaprisli'),
    'w07842': ('insanüstü', 'insanüstü / insanlık dışı'),
    'w07843': ('sonuçsuz', 'sonuçsuz / boşuna'),
    'w07844': ('kolibri', 'sinek kuşu / kolibri'),
    'w07845': ('fit', 'fit (uzunluk) / ayak ölçüsü'),
    'w07846': ('yormak', 'yormak / bitkin düşürmek'),
    'w07847': ('döngü', 'döngü / devir daim'),
    'w07848': ('kıvrım (beyin), dönemeç', 'kıvrım (beyin) / dönemeç'),
    'w07849': ('radyo dalga', 'radyo dalgası'),
    'w07850': ('çarpmak', 'çarpmak / kafayı vurmak'),
    'w07851': ('beceri', 'beceri / hüner / el çabukluğu'),
    'w07852': ('yük boşaltmak', 'boşaltmak / indirmek (yük)'),
    'w07853': ('baharatlı', 'baharatlı / keskin kokulu'),
    'w07854': ('parçalamak', 'ezmek / parçalamak / kafasını ezmek'),
    'w07856': ('cesaretle', 'cesurca / yiğitçe'),
    'w07857': ('vana', 'vana / valf / musluk'),
    'w07858': ('ticaret', 'ticaret / iş'),
    'w07859': ('çaresizlik', 'çaresizlik / acizlik'),
    'w07861': ('kahin', 'kâhin / falcı / müneccim'),
    'w07862': ('çökertme', 'devirme / iktidardan indirme'),
    'w07863': ('antrepo', 'antrepo / depo / ambar'),
    'w07864': ('kaynak', 'pınar / kaynak'),
    'w07865': ('geçirmek (vakit)', '(vakit) geçirmek / kısaltmak'),
    'w07866': ('tekrarlanan', 'defalarca / tekrarlanan / çok kez'),
    'w07867': ('evren', 'evren / kâinat'),
    'w07868': ('yoldaşlık', 'yoldaşlık / ortaklık / dostluk'),
    'w07870': ('saydamlık', 'saydamlık / şeffaflık'),
    'w07872': ('edinmek', 'ele geçirmek / ustalaşmak / öğrenmek'),
    'w07873': ('finale kalan', 'finale kalan / finalist'),
    'w07875': ('salgılamak', 'yaymak / salgılamak / akıtmak'),
    'w07876': ('kıskanç', 'kıskanç / haset'),
    'w07877': ('antik', 'antik / eski Yunan-Roma dönemi'),
    'w07880': ('ısınmak', 'ısınmak / kızmak'),
    'w07881': ('çekişmek', 'çekişmek / ters cevap vermek / karşılık vermek'),
    'w07882': ('oyun yazarı', 'oyun yazarı / tiyatro yazarı'),
    'w07883': ('izleme', 'izleme / uyma / peşinden gitme'),
    'w07884': ('sarkmak', 'sarkmak / aşağı sarkmak'),
    'w07885': ('deformasyon', 'deformasyon / bozulma'),
    'w07886': ('seyahat', 'seyahat / gezginlik'),
    'w07887': ('kamp yatağı', 'portatif yatak / kamp yatağı'),
    'w07888': ('tarh', 'çiçek tarhı / tarh'),
    'w07889': ('amaçsız', 'amaçsız / gayesiz'),
    'w07890': ('kamış', 'kamış / saz'),
    'w07891': ('kabak', 'kabak (sakız) / sakız kabağı'),
    'w07894': ('sayım', 'sayım / nüfus sayımı'),
    'w07895': ('kamçı', 'kamçı / kırbaç'),
    'w07896': ('dermatolog', 'dermatolog / cilt doktoru'),
    'w07897': ('daksund', 'daksund / (fiyat) tarife'),
    'w07898': ('tek kullanımlık', 'tek kullanımlık / bir kereye mahsus'),
    'w07899': ('yayınevi', 'yayınevine ait / yayıncılık (sıfat)'),
    'w07900': ('analitik', 'analitik / çözümsel'),
    'w07901': ('şişmek', 'şişmek / ödem yapmak'),
    'w07902': ('koroya ait', 'koroya ait / koro (sıfat)'),
    'w07904': ('kondüktör', 'kondüktör / biletçi'),
    'w07906': ('ilaç', 'ilaç / merhem / şifalı karışım'),
    'w07907': ('bölük', 'süvari bölüğü / filo'),
    'w07908': ('üzüntü', 'üzüntü / hayal kırıklığı'),
    'w07911': ('arzu', 'arzu / şehvet / istek'),
    'w07912': ('ev arkadaşı', 'birlikte yaşayan / sevgili (resmî olmayan)'),
    'w07913': ('ortaya çıkarmak', 'ortaya çıkarmak / tespit etmek'),
    'w07914': ('dayanmak', 'dayanmak / dirençle karşı çıkmak / inat etmek'),
    'w07915': ('gelip geçici', 'gelip geçici / kısa süreli'),
    'w07916': ('cazibeli', 'cazibeli / çekici'),
    'w07917': ('müdür', 'müdür / şef / yönetici'),
    'w07918': ('plato', 'plato / yaylak'),
    'w07920': ('entrika çevirmek', 'entrika çevirmek / merak uyandırmak'),
    'w07922': ('gamalı haç', 'gamalı haç / svastika'),
    'w07924': ('akıtmak', 'dökmek / (döküm) yapmak / dalgalanmak'),
    'w07925': ('ikame madde', 'ikame madde / yedek / vekil'),
    'w07926': ('indirmek', 'indirmek (dosya)'),
    'w07929': ('cızırtı', 'tıslama / cızırtı'),
    'w07931': ('oğlak', 'oğlak burcu / dağ keçisi'),
    'w07932': ('pasifist', 'pasifist / barışsever'),
    'w07934': ('uçan', 'uçan / uçuş (sıfat)'),
    'w07935': ('ekonomist', 'ekonomist / iktisatçı'),
    'w07936': ('kellik', 'kellik / kel yer'),
    'w07939': ('cimrilik etmek', 'cimrilik etmek / açgözlülük etmek'),
    'w07941': ('kızak', 'kızak / çocuk kızağı'),
    'w07942': ('engelleyici', 'engelleyici / inhibitör'),
    'w07943': ('vurgulamak', 'vurgulamak / altını çizmek'),
    'w07944': ('yazarlık', 'yazarlık / yazarlık işi'),
    'w07945': ('aktifleştirmek', 'harekete geçirmek / aktifleştirmek'),
    'w07946': ('gezip dolaşmak', 'gezip dolaşmak / dolaşmak'),
    'w07947': ('dökülmek', 'dökülmek / yağmak'),
    'w07948': ('kokmuş', 'kokuşmuş / pis kokulu'),
    'w07949': ('alaycı', 'alaycı / iğneleyici'),
    'w07951': ('düpedüz', 'düpedüz / doğrudan / kestirmeden'),
    'w07953': ('bütün', 'bütün / toplam / bileşke'),
    'w07954': ('hakem', 'hakem / tahkim kişisi'),
    'w07955': ('rüşvet (argo), geri tepme', 'geri tepme / komisyon (argo) / rüşvet (argo)'),
    'w07956': ('ıslık çalmak', 'ıslık çalmak / ıslıkla çalmak'),
    'w07957': ('gümrükçü', 'gümrük memuru'),
    'w07958': ('itinasız', 'özensiz / dağınık / itinasız'),
    'w07959': ('karşı hücum', 'karşı saldırı / karşı hücum'),
    'w07960': ('tüketmek', 'tüketmek / harcamak'),
    'w07961': ('vahşi', 'acımasız / şiddetli / korkunç'),
    'w07962': ('tık', 'tıklama / tık'),
    'w07964': ('kızdırmak', 'kızdırmak / öfkelendirmek / rahatsız etmek'),
    'w07965': ('sürgü', 'sürgü / mandal'),
    'w07966': ('öfkelenmek', 'öfkelenmek / parlamak'),
    'w07967': ('itibar', 'itibar / saygınlık / onur'),
    'w07968': ('tayyare', 'uçak (eski) / tayyare'),
    'w07969': ('ayrışım', 'ayrışma / bölünme / parçalanma'),
    'w07971': ('totalizatör', 'totalizatör / bahis sistemi'),
    'w07972': ('horoz', 'horoz (sıfat) / horoza ait'),
    'w07973': ('invasyon', 'istila / akın'),
    'w07975': ('haydutluk', 'haydutluk / soygun / eşkıyalık'),
    'w07976': ('dalkavuk', 'dalkavuk / yağcı'),
    'w07977': ('sone', 'sone / on dört dizelik şiir'),
    'w07978': ('boyamak', 'boyayıp kapatmak / üstünü boyamak'),
    'w07979': ('mantar', 'mantar (sıfat) / mantarlı'),
    'w07980': ('yol', 'ana yol / güzergâh / (sindirim) yolu'),
    'w07981': ('güvensiz', 'güvensiz / kuşkucu'),
    'w07982': ('karbeyaz', 'kar gibi beyaz / bembeyaz'),
    'w07983': ('hakem', 'hakem / maç hakemi'),
    'w07984': ('apse', 'apse / cerahat'),
    'w07985': ('vehim', 'vehim / hayal / musallat olan düşünce'),
    'w07986': ('anagram', 'anagram / harf oyunu'),
    'w07987': ('bağlılık', 'bağlılık / sadakat'),
    'w07988': ('kalabalık', 'kalabalık / insanla dolu'),
    'w07990': ('çene çalmak', 'dedikodu yapmak / çene çalmak'),
    'w07991': ('lezzetsiz', 'lezzetsiz / tatsız'),
    'w07992': ('hayret', 'hayret / şaşkınlık'),
    'w07994': ('yanyana yaşamak', 'bir arada yaşamak / birlikte var olmak'),
    'w07995': ('absent', 'absent / apsent (içki)'),
    'w07996': ('pilotluk yapmak', 'pilotluk yapmak / uçak kullanmak'),
    'w07999': ('balıkçık', 'yavru balık / balık yavrusu'),
    'w08000': ('iğrenç', 'iğrenç / mide bulandırıcı'),
    'w08001': ('üşenmek', 'üşenmek / tembellik etmek'),
    'w08002': ('yavaşça', 'yavaşça / akıcı biçimde / yumuşakça'),
    'w08003': ('yaklaşarak uçmak', 'yaklaşarak uçmak / uçarak yaklaşmak'),
    'w08004': ('ayla', 'hale / ayla'),
    'w08005': ('şart koşmak', 'öngörmek / şart koşmak / planlamak'),
    'w08006': ('yağış', 'yağış / yağmur ve kar'),
    'w08007': ('tasarlamak', 'tasarlamak / inşa etmek'),
}

DROP = {
    'w07831': 'босния',
    'w07878': 'будапешт',
    'w07892': 'сингапур',
    'w07903': 'хельсинки',
    'w07910': 'катар',
    'w07930': 'монголия',
    'w07937': 'непал',
    'w07940': 'эфиопия',
    'w07950': 'чад',
    'w07927': 'известия',
    'w07919': 'ост',
}
