# -*- coding: utf-8 -*-
"""B2 inceleme, parti 5."""

FIXES = {
    'w07203': ('sera', 'sera / seracık'),
    'w07204': ('tıkıştırmak', 'tıkıştırmak / sokmak'),
    'w07206': ('tirbuşon', 'tirbuşon / tirbuşon (uçak dönüşü)'),
    'w07207': ('mizaç', 'mizaç / huy'),
    'w07208': ('muhrip', 'muhrip / destroyer'),
    'w07211': ('savunmak', 'savunmak / korumak / arka çıkmak'),
    'w07212': ('tutam, lüle (saç teli)', 'saç tutamı / lüle'),
    'w07213': ('duruş', 'duruş / vücut duruşu'),
    'w07214': ('ak pelikan', 'pelikan'),
    'w07218': ('bölüştürmek', 'dağıtmak / bölüştürmek / paylaştırmak'),
    'w07219': ('susam', 'susam / (mecaz) sihirli anahtar'),
    'w07221': ('şaşlık', 'şiş kebap / şaşlık'),
    'w07222': ('hayız', 'âdet / regl'),
    'w07223': ('bozkır', 'bozkır / step'),
    'w07224': ('cüzzam', 'cüzzam / lepra'),
    'w07225': ('limonluk', 'sera / limonluk'),
    'w07226': ('heyecan', 'heyecan / hırs / tutku'),
    'w07227': ('kılık değiştirmek', 'gizlemek / maskelemek / kamufle etmek'),
    'w07229': ('şaklatmak', 'şaklatmak / tıklamak / (fındık) kırmak'),
    'w07230': ('kereviz', 'kereviz / kereviz sapı'),
    'w07231': ('kuzu', 'kuzu / (dini) kurban'),
    'w07232': ('kutsallık', 'kutsallık / ermişlik'),
    'w07233': ('fiyonk', 'fiyonk / kurdele'),
    'w07236': ('yerleşim', 'yerleşim / köy'),
    'w07237': ('spekülasyon', 'spekülasyon / vurgunculuk'),
    'w07238': ('manik', 'manik / takıntılı'),
    'w07239': ('ezkaza', 'yanlışlıkla / istemeden'),
    'w07240': ('mekânsal', 'mekânsal / uzaysal'),
    'w07241': ('belirsiz bir şekilde', 'belirsizce / anlaşılmaz biçimde'),
    'w07243': ('alacakaranlık', 'alacakaranlık / akşam karanlığı'),
    'w07244': ('katma', 'ekleme / ilave'),
    'w07245': ('düzensiz', 'düzensiz / kaotik'),
    'w07246': ('halktan biri', 'halktan biri / sıradan insan'),
    'w07247': ('kıyı', 'kıyı (sıfat) / sahildeki'),
    'w07248': ('çarpmak (kalp için)', 'çarpmak (kalp) / dövünmek / titremek'),
    'w07249': ('devlet desteği', 'sübvansiyon / devlet yardımı'),
    'w07250': ('ahır', 'ahır / domuz ahırı'),
    'w07251': ('pişman olmak', 'pişman olmak / tövbe etmek'),
    'w07252': ('müteahhit', 'müteahhit / inşaat firması'),
    'w07253': ('baterist', 'baterist / (işçi) öncü'),
    'w07254': ('macera', 'macera / serüven'),
    'w07257': ('kıvırcık', 'kıvırcık / bukleli'),
    'w07258': ('karton', 'karton / mukavva'),
    'w07260': ('çardak', 'çardak / kameriye'),
    'w07261': ('mecazi', 'mecazi / imgesel / canlı'),
    'w07262': ('görecelik', 'görecelik / izafiyet'),
    'w07263': ('dizgi hatası', 'dizgi hatası / yazım hatası'),
    'w07266': ('haber vermek', 'haber vermek / işaret olmak / müjdelemek'),
    'w07269': ('durağan', 'sabit / durağan / hastanede yatarak'),
    'w07270': ('soya fasulyesi', 'soya / soya fasulyesi'),
    'w07272': ('işlev görmek', 'işlev görmek / çalışmak'),
    'w07273': ('hava ile şişirilen', 'şişme / hava ile şişirilen'),
    'w07274': ('keser (marangoz aleti)', 'keser / marangoz baltası'),
    'w07276': ('dahi çocuk', 'dahi çocuk / harika çocuk'),
    'w07277': ('hörgüç', 'kambur / hörgüç'),
    'w07278': ('alıkoyma', 'alıkoyma / el koyma / çıkarma'),
    'w07279': ('erimek', 'erimek / çözünmek / kaybolmak'),
    'w07280': ('bulaşık makinesi', 'bulaşık makinesi / bulaşıkçı (kadın)'),
    'w07281': ('darbeli', 'darbeli / impuls (sıfat)'),
    'w07282': ('yok olmak', 'yok olmak / kaybolmak'),
    'w07283': ('bataklık', 'bataklık (sıfat) / bataklığa ait'),
    'w07284': ('soluk', 'soluk / mat / donuk'),
    'w07285': ('kokmak (kötü/keskin)', 'kokmak (kötü) / vurmak / yıkmak'),
    'w07288': ('eğitim', 'eğitim / antrenman / kurs'),
    'w07289': ('cellat', 'cellat / infaz memuru'),
    'w07290': ('poliçe', 'poliçe / senet'),
    'w07291': ('susmak', 'susmak / sesi kesilmek'),
    'w07292': ('güneybatı', 'güneybatı (sıfat)'),
    'w07293': ('tanımak', 'tanımak / ayırt etmek'),
    'w07294': ('belagatli', 'belagatli / anlamlı'),
    'w07296': ('girdap', 'girdap / derin çukur'),
    'w07297': ('çekirge', 'çekirge / çekirge sürüsü'),
    'w07300': ('mezmur', 'mezmur / ilahi'),
    'w07301': ('ekim', 'ekim / ekin'),
    'w07302': ('gurme', 'gurme / yemek meraklısı'),
    'w07303': ('yaşa bağlı', 'yaşa bağlı / yaş (sıfat)'),
    'w07304': ('bozmak', 'bozmak / şeklini bozmak / sakat bırakmak'),
    'w07305': ('sos', 'sos / et suyu'),
    'w07306': ('sosyalist', 'sosyalist / sosyalizme ait'),
    'w07307': ('akıl öğretmek', 'akıl öğretmek / ikna etmek'),
    'w07308': ('açıklık', 'açıklık / (merdiven) sahanlık / geçiş'),
    'w07309': ('sundurma', 'sundurma / gölgelik'),
    'w07310': ('kumbara', 'kumbara / birikim'),
    'w07311': ('tarla kuşu', 'tarla kuşu / erken kalkan kişi'),
    'w07312': ('karşıtlık', 'karşıtlık / zıtlık'),
    'w07313': ('itikat', 'itikat / inanç'),
    'w07314': ('banyo yapmak', 'yıkamak / yüzdürmek'),
    'w07315': ('ibik', 'küçük tarak / ibik / tarak (deniz ürünü)'),
    'w07316': ('hükümdar', 'hükümdar / egemen'),
    'w07317': ('masajcı', 'masajcı (kadın)'),
    'w07318': ('karışmak', 'karışmak / birbirine karışmak'),
    'w07319': ('vişne', 'vişne (sıfat) / vişne renkli'),
    'w07320': ('kısa hikâye', 'kısa hikâye / novella'),
    'w07323': ('bir avuç', 'avuç / bir avuç dolusu'),
    'w07325': ('eğmek', 'eğmek / bükmek'),
    'w07326': ('ekümenik', 'evrensel / ekümenik'),
    'w07328': ('bilinçli', 'bilinçli / farkında'),
    'w07330': ('arı', 'arı (sıfat) / arıya ait'),
    'w07331': ('anlatmak', 'anlatmak / ifade etmek / sunmak'),
    'w07332': ('hazırlamak', 'hazırlamak / hazırlık yapmak'),
    'w07333': ('mesafe', 'mesafe / menzil'),
    'w07336': ('yanlışlıkla', 'yanlışlıkla / hatalı olarak'),
    'w07337': ('yakıcı', 'kavurucu / yakıcı'),
    'w07338': ('koyak', 'vadi (küçük) / koyak'),
    'w07339': ('Haçlı', 'Haçlı / haçlı seferi savaşçısı'),
    'w07340': ('düşünceli', 'düşünceli / dalgın'),
    'w07342': ('zar', 'zar / perde'),
    'w07343': ('hokkabazlık yapmak', 'hokkabazlık yapmak / (kelimelerle) oynamak'),
    'w07347': ('yenileme', 'uzatma / yenileme'),
    'w07348': ('ayak yuvarı', 'küçük yastık / ayak yuvarı / parmak ucu'),
    'w07349': ('özyaşamöyküsü', 'özyaşam öyküsü / otobiyografi'),
    'w07350': ('çadır', 'çadır / büyük çadır'),
    'w07351': ('şişmanlık', 'şişmanlık / dolgunluk / bütünlük'),
    'w07352': ('tensel', 'tensel / bedensel'),
    'w07353': ('yaşayabilir', 'yaşayabilir / dayanıklı'),
    'w07354': ('dikiş', 'dikiş / dikiş işi'),
    'w07355': ('tabla, gövde (çalgı parçası)', 'tabla / gövde (çalgı) / güverte'),
    'w07356': ('sallamak', 'sallamak / harekete geçirmek'),
    'w07357': ('dizilim', 'dizilim / saç şekillendirme / döşeme'),
    'w07358': ('efsane', 'efsane / rivayet / halk anlatısı'),
    'w07359': ('kuyruk sallamak', 'kuyruk sallamak / dolambaçlı gitmek / kaçamak yapmak'),
    'w07360': ('büyüleyici', 'büyüleyici / çok çekici'),
    'w07361': ('lokal', 'yerel / lokal'),
    'w07362': ('burgu, matkap (alet)', 'burgu / matkap / sondaj aleti'),
    'w07363': ('kabadayı', 'kavgacı / kabadayı'),
    'w07364': ('siklon', 'siklon / alçak basınç'),
    'w07365': ('yoğunluk', 'yoğunluk / şiddet'),
    'w07366': ('idealist', 'idealist / hayalperest'),
    'w07368': ('borç', 'borç / borçlanma'),
    'w07370': ('oluşum', 'oluşum / gelişme'),
    'w07371': ('fobi', 'fobi / korku (patolojik)'),
    'w07372': ('açık (renk)', 'aydınlık / açık renk / neşeli'),
    'w07373': ('ardıç kuşu', 'ardıç kuşu / tarla kuşu'),
    'w07374': ('candan', 'candan / misafirperver'),
    'w07375': ('çember', 'çember / halka'),
    'w07376': ('şaplak', 'şaplak / tokat'),
    'w07377': ('kasılmak', 'kasılmak / kısalmak / azalmak'),
    'w07378': ('asma', 'asma / sarmaşık dalı / söğüt dalı'),
    'w07379': ('yeniden doğmak', 'yeniden doğmak / dönüşmek'),
    'w07380': ('veteriner', 'veteriner / hayvan hekimliğine ait'),
    'w07381': ('dengeli', 'dengeli / sakin'),
    'w07382': ('aşırı', 'aşırı / ölçüsüz / sonsuz'),
    'w07383': ('çat pat', 'çat pat / kırık / bozuk'),
    'w07384': ('hiddetli', 'hiddetli / öfkeli'),
    'w07387': ('aklına getirmek', 'aklına getirmek / akıl vermek'),
    'w07388': ('küçük dil', 'küçük dil / dilcik / (ayakkabı) dil'),
    'w07389': ('şampiyon', 'şampiyon (kadın)'),
    'w07391': ('nakletmek', 'nakletmek / taşımak'),
    'w07394': ('dava', 'dava / çekişme'),
    'w07395': ('akıtmak', 'dökmek / boşaltmak'),
    'w07396': ('uzun vadeli', 'uzun yıllık / çok yıllık / kalıcı'),
    'w07397': ('istirham etmek', 'yalvararak istemek / büyü yapmak / istirham etmek'),
    'w07398': ('fitil', 'fitil / (argo) azar'),
    'w07400': ('vatoz', 'vatoz / (çatı) eğimi'),
    'w07401': ('inovasyon', 'yenilik / inovasyon'),
    'w07402': ('diş eti', 'diş eti / diş eti dokusu'),
    'w07403': ('ekipman', 'ekipman / donanım'),
}

DROP = {
    'w07220': 'гнида',
    'w07295': 'тёлка',
}
