# -*- coding: utf-8 -*-
"""B2 inceleme, parti 4."""

FIXES = {
    'w07001': ('eskrim', 'eskrim / kılıç oyunu'),
    'w07002': ('balyoz', 'balyoz / iri çekiç'),
    'w07003': ('bel', 'bel / bel bölgesi'),
    'w07004': ('ihtiyatlı', 'ihtiyatlı / temkinli'),
    'w07005': ('sarmak', 'sarmak / paketlemek / (yola) sapmak'),
    'w07008': ('kısırlık', 'kısırlık / kısır olma'),
    'w07010': ('şeri', 'şeri / jerez'),
    'w07011': ('güve', 'kelebek (küçük) / pervane böceği'),
    'w07013': ('rüzgarlı', 'rüzgârlı / hafif meşrep'),
    'w07014': ('daraltmak', 'daraltmak / kısmak'),
    'w07015': ('sayaç', 'sayaç / sayıcı'),
    'w07016': ('göktaşı', 'göktaşı / meteor'),
    'w07017': ('kanepe', 'kanepe / sedir'),
    'w07018': ('aşırıcı', 'aşırıcı / ekstremist'),
    'w07019': ('yüz buruşturmak', 'yüz buruşturmak / kıvırmak'),
    'w07020': ('eşlik etmek', 'eşlik etmek / işbirliği yapmak (oyunda)'),
    'w07025': ('gaz yağı', 'gaz yağı / kerosen'),
    'w07027': ('kullanmak', 'kullanmak / tüketmek'),
    'w07028': ('hava ile ilgili', 'hava ile ilgili / hava durumu (sıfat)'),
    'w07030': ('yele', 'yele / uzun saç'),
    'w07031': ('yanlışsız', 'kusursuzca / hatasız'),
    'w07032': ('eğmek (diz çökmek için)', 'eğmek / (diz) çökmek'),
    'w07033': ('güvenilmez', 'güvenilmez / sağlam olmayan'),
    'w07034': ('çıplak', 'çıplak / lüt'),
    'w07035': ('şişmek', 'şişmek / kabarmak'),
    'w07036': ('gonca', 'gonca / tomurcuk'),
    'w07037': ('firar etmek', 'firar etmek / (askerden) kaçmak'),
    'w07038': ('vazgeçirmek', 'vazgeçirmeye çalışmak / caydırmak'),
    'w07039': ('giyim', 'giysi / kıyafet (resmi)'),
    'w07040': ('geliştirici', 'geliştirici / tasarımcı'),
    'w07041': ('misket tüfeği', 'misket tüfeği / fitilli tüfek'),
    'w07042': ('dairesel', 'dairesel / çember biçimli'),
    'w07043': ('kötüleştirmek', 'ağırlaştırmak / kötüleştirmek'),
    'w07044': ('ayrılma', 'ayrılma / yan hat / seyahatler'),
    'w07045': ('sınır dışı etme', 'sınır dışı etme / sürgün'),
    'w07046': ('tolerans', 'hoşgörü / tolerans'),
    'w07047': ('dizilmek', 'sıraya girmek / dizilmek'),
    'w07048': ('pilot', 'pilot / havacı'),
    'w07050': ('boyanmak', 'boyanmak / makyaj yapmak'),
    'w07052': ('dana', 'buzağı / dana'),
    'w07053': ('yapılamaz', 'yapılamaz / gerçekleştirilemez'),
    'w07054': ('tamamlamak', 'tamamlamak / eklemek'),
    'w07055': ('altlık', 'astar / altlık'),
    'w07056': ('brülör', 'brülör / ocak başlığı / yakıcı'),
    'w07057': ('şık', 'şık / süslü / gösterişli'),
    'w07059': ('indikatör', 'gösterge / indikatör'),
    'w07061': ('dengeleyici', 'dengeleyici / stabilizatör'),
    'w07062': ('dökük', 'eski püskü / köhne'),
    'w07064': ('alış', 'satın alma / toptan alım'),
    'w07066': ('finanse etmek', 'finanse etmek / fon sağlamak'),
    'w07067': ('hafif', 'ciddiyetsiz / hafif'),
    'w07068': ('tencere', 'tencere / kazan / melon şapka'),
    'w07069': ('öfke', 'öfke / kızgınlık'),
    'w07070': ('saptamak', 'saptamak / tespit etmek'),
    'w07072': ('balad', 'balad / halk türküsü'),
    'w07073': ('hükmetmek', 'hükmetmek / karar vermek'),
    'w07074': ('uyarılmak', 'heyecanlanmak / uyarılmak'),
    'w07075': ('uydurmak', 'uydurmak / acele ettirmek'),
    'w07076': ('suya ait, (mitolojide) su cini', 'su (sıfat) / su cini'),
    'w07079': ('bozma', 'kötüleşme / bozulma'),
    'w07080': ('kurma', 'yapılaşma / bina inşası'),
    'w07081': ('ikiyüzlü', 'ikiyüzlü / iki yüzlü'),
    'w07082': ('tercihen', 'tercihen / istenilir'),
    'w07085': ('haince', 'haince / sözünde durmayan'),
    'w07086': ('hayalî', 'hayalî / sahte / sanal'),
    'w07087': ('pahalı', 'pahalı / maliyetli'),
    'w07088': ('kararmak', 'kararmak / kararmaya başlamak'),
    'w07090': ('rahat', 'sakinleşme / huzur / teselli'),
    'w07091': ('birikmek', 'birikmek / yığılmak'),
    'w07092': ('ayırmak', 'ayırmak / sınıflandırmak'),
    'w07094': ('nöbet (vardiya)', 'nöbet / vardiya'),
    'w07095': ('dökmek', 'dökmek / doldurmak'),
    'w07096': ('donuk', 'cansız / donuk'),
    'w07097': ('dantel', 'dantel / işlemeli örgü'),
    'w07098': ('şnaps', 'şnaps / sert içki'),
    'w07099': ('artist', 'sanatçı (kadın) / oyuncu (kadın)'),
    'w07100': ('dana', 'boğa yavrusu / izmarit (argo)'),
    'w07101': ('sekiz', 'sekiz (rakam) / sekizli'),
    'w07102': ('tunç', 'bronz / tunç'),
    'w07103': ('prestij', 'prestij / saygınlık'),
    'w07105': ('lahit', 'lahit / sarkofaj'),
    'w07106': ('çıkıntı', 'çıkıntı / çıkıntılı yer'),
    'w07107': ('ahlaka aykırı', 'ahlaksız / ahlaka aykırı'),
    'w07108': ('mezbaha', 'mezbaha / kesimhane'),
    'w07109': ('suç ortağı', 'suç ortağı / ortak'),
    'w07110': ('enkaz', 'hurda / eski püskü eşya'),
    'w07111': ('ilahi takdir', 'ilahi takdir / kader'),
    'w07112': ('mide yanması', 'mide yanması / ekşime'),
    'w07113': ('vejetasyon', 'bitki örtüsü / bitkiler'),
    'w07114': ('bölme', 'bölme / bölüm / bölünme'),
    'w07115': ('kesmek, parçalamak (balta ile)', 'baltayla kesmek / ikiye bölmek'),
    'w07116': ('tır şoförü', 'tır şoförü / uzun yol şoförü'),
    'w07117': ('hayallere dalmak', 'hayal kurmak / hayallere dalmak'),
    'w07118': ('dikkatsiz', 'dikkatsiz / ilgisiz'),
    'w07119': ('bekâret', 'iffet / bekâret'),
    'w07120': ('mahcubiyet', 'mahcubiyet / utanma'),
    'w07121': ('kırbaç', 'kırbaç / kamçı'),
    'w07123': ('sindirmek', 'sindirmek / hazmetmek / katlanmak'),
    'w07124': ('ortadan kaldırmak', 'ortadan kaldırmak / gidermek'),
    'w07125': ('iddialı', 'iddialı / gösterişli'),
    'w07126': ('gülmek', 'kahkaha atmak / gülmek'),
    'w07127': ('epey alımlı', 'alımlı / güzel (fazla)'),
    'w07128': ('biz', 'biz / delgi'),
    'w07129': ('badem', 'badem / bademcik'),
    'w07130': ('büro', 'büro / yazı işleri / kırtasiye'),
    'w07131': ('dağ sıçanı', 'dağ sıçanı / marmot'),
    'w07133': ('yararsız', 'boşuna / beyhude / yararsız'),
    'w07135': ('aykırılık', 'uyumsuzluk / aykırılık'),
    'w07136': ('tarif edilemez', 'tarif edilemez / anlatılamaz'),
    'w07137': ('kabuk', 'kabuk / soyulmuş kabuk'),
    'w07138': ('şişmanlamak', 'şişmanlamak / kilo almak'),
    'w07139': ('dinamik', 'dinamik / gelişim seyri'),
    'w07140': ('abaküs', 'abaküs / hesap (çekişme)'),
    'w07141': ('baş örtüsü', 'duvak / tül'),
    'w07143': ('verimlilik', 'verimlilik / üretkenlik'),
    'w07144': ('özet', 'özet / ders notu'),
    'w07145': ('yayın yapmak', 'yayın yapmak / konuşmak'),
    'w07146': ('dize ait', 'diz (sıfat) / dize ait'),
    'w07147': ('düzenbaz', 'kurnaz kişi / düzenbaz'),
    'w07148': ('kurnaz', 'kurnaz / sokulgan kişi'),
    'w07149': ('telaffuz etmek', 'telaffuz etmek / söyleyebilmek / azarlamak'),
    'w07150': ('emir', 'emir / prens (Arap)'),
    'w07151': ('kabarcık', 'kabarcık / su toplaması'),
    'w07152': ('kuvöz', 'kuvöz / kuluçka makinesi'),
    'w07154': ('nal', 'nal / at nalı'),
    'w07156': ('milimetrik', 'milimetrik / milimetre (sıfat)'),
    'w07158': ('anonim eser sahibi', 'anonim kişi / ismini gizleyen'),
    'w07160': ('esmer', 'esmer / bronz tenli'),
    'w07161': ('az', 'yetersiz / kıt / az'),
    'w07163': ('akarsu kolu', 'kol (nehir) / akış'),
    'w07164': ('nektar', 'nektar / bal özü'),
    'w07166': ('konfor', 'rahatlık / sıcaklık / huzur'),
    'w07168': ('boylam', 'boylam / uzunluk'),
    'w07169': ('abece', 'alfabe / abece'),
    'w07170': ('ovmak', 'ovmak / sürmek / ovalamak'),
    'w07171': ('sessiz', 'sessiz / dilsiz'),
    'w07172': ('leş', 'leş / ceset (hayvan)'),
    'w07173': ('hesaplayıcı', 'hesap makinesi'),
    'w07175': ('çarpmak', 'çarpmak / rastlamak'),
    'w07179': ('ipek', 'ipek / ipek gibi'),
    'w07180': ('pagan', 'pagan / putperest'),
    'w07181': ('sallanan', 'sallanan / güvenilmez / oynak'),
    'w07183': ('vizon', 'vizon / (hayvan) yuva'),
    'w07184': ('bozuk', 'kullanılmaz / bozuk / yetersiz'),
    'w07185': ('canhıraş', 'yürek parçalayıcı / içler acısı'),
    'w07186': ('düşme', 'düşme / azalma / alçalma'),
    'w07191': ('galyalı', 'Galyalı / Galli'),
    'w07192': ('dilbilgisi', 'dilbilgisi / gramer'),
    'w07193': ('yırtıcı', 'yırtıcı / açgözlü'),
    'w07194': ('gülünç', 'gülünç / çok komik'),
    'w07195': ('düşler', 'hayal / düş'),
    'w07197': ('sıra', 'sıra / dizi (asker)'),
    'w07198': ('delmek', 'delmek / matkapla delmek'),
    'w07199': ('popülasyon', 'popülasyon / nüfus (biyoloji)'),
    'w07202': ('akıtmak', 'dökmek / akıtmak / doldurmak (içki)'),
}

DROP = {
    'w07049': 'дегенерат',
    'w07177': 'комнатка',
}
