# -*- coding: utf-8 -*-
"""B2 inceleme, parti 7."""

FIXES = {
    'w07604': ('tarantula', 'tarantula / örümcek (zehirli)'),
    'w07605': ('akıllı', 'akıllı / zeki / cin gibi'),
    'w07606': ('komutan', 'komutan / ordu komutanı'),
    'w07607': ('antrakt', 'ara (tiyatro) / antrakt'),
    'w07608': ('kriminalistik', 'kriminalistik / adli bilim'),
    'w07609': ('yapışmak', 'yapışmak / yapışkan olmak / sokulmak'),
    'w07611': ('endüstriyel', 'endüstriyel / sanayi (sıfat)'),
    'w07612': ('kutlama', 'kutlama (sıfat) / tebrik'),
    'w07614': ('döküm, eritme (metalürji)', 'eritme / döküm / (metal) ergitme'),
    'w07615': ('boncuklar', 'boncuk (dizi) / boncuk kolye'),
    'w07616': ('barka', 'barka / üç direkli gemi'),
    'w07617': ('ölçmek', 'ölçmek / denemek (giysi)'),
    'w07618': ('alâmet', 'alâmet / kehanet / işaret'),
    'w07620': ('eğri', 'eğri / bükülmüş / kıvrık'),
    'w07621': ('turnike', 'turnike / bükülmüş ip'),
    'w07622': ('ısıl', 'ısıl / ısı (sıfat)'),
    'w07624': ('eğik', 'eğik / meyilli'),
    'w07625': ('tarafsızlık', 'tarafsızlık / yansızlık'),
    'w07626': ('büyülemek', 'büyülemek / etkilemek'),
    'w07627': ('kötü', 'kötü / berbat'),
    'w07628': ('kaynamak', 'kaynamak / köpürmek / fokurdamak'),
    'w07629': ('insansever', 'hayırsever / insansever'),
    'w07632': ('şamdan', 'şamdan / mumluk'),
    'w07633': ('kızdırmak', 'kızdırmak / öfkelendirmek'),
    'w07634': ('gayda', 'gayda / (mecaz) sıkıcı iş'),
    'w07635': ('azaltmak', 'azaltmak / düşürmek / alçaltmak'),
    'w07636': ('tartmak', 'tartmak / değerlendirmek'),
    'w07637': ('tef', 'tef / davul (küçük)'),
    'w07638': ('kararsız', 'kararsız / çekingen'),
    'w07639': ('yaşayış', 'günlük yaşam / yaşayış tarzı'),
    'w07640': ('obur', 'oburun biri / obur'),
    'w07642': ('canavarlık', 'vahşet / canavarlık'),
    'w07643': ('tanımak', 'tanımak / öğrenmek / kavramak'),
    'w07644': ('karar (örn. BM kararı)', 'karar (BM vb.) / öneri'),
    'w07645': ('çapraz', 'enine / çapraz / karşısında'),
    'w07646': ('atik', 'çevik / atik / eli çabuk'),
    'w07647': ('karakterize etmek', 'nitelendirmek / tanımlamak'),
    'w07648': ('yürüyüş', 'yürüyüş / alay / geçit'),
    'w07649': ('sandal, kale (satranç taşı)', 'kale (satranç) / sandal (kayık)'),
    'w07651': ('glikoz', 'glikoz / şeker'),
    'w07653': ('açıkgöz davranmak', 'açıkgözlülük yapmak / kurnazlık yapmak'),
    'w07654': ('ton', 'tonlama / vurgu'),
    'w07656': ('kaldırmak', 'biraz kaldırmak / yükseltmek'),
    'w07657': ('teşvik etmek', 'teşvik etmek / güdülemek'),
    'w07658': ('aşırma', 'intihal / aşırma'),
    'w07661': ('eklemek', 'dökmek / eklemek / aşılamak'),
    'w07662': ('arabacı', 'arabacı / faytoncu'),
    'w07663': ('tasarımcı', 'tasarımcı / lego seti / mühendis'),
    'w07664': ('bağlantı', 'bağlantı / karşılıklı ilişki'),
    'w07665': ('laktoz', 'laktoz / süt şekeri'),
    'w07669': ('husumet beslemek', 'düşmanlık etmek / husumeti olmak'),
    'w07670': ('parıldamak', 'parıldamak / titreşmek'),
    'w07671': ('hayvanca', 'hayvanca / vahşi'),
    'w07672': ('bölüm', 'bölüm (bölme sonucu) / özel'),
    'w07673': ('eski usul', 'eski usul / eski tarz'),
    'w07674': ('pehlivan', 'pehlivan / güçlü adam'),
    'w07675': ('sürüklemek', 'sürükleyip getirmek'),
    'w07676': ('yetiştirme çiftliği', 'fidanlık / yetiştirme çiftliği'),
    'w07677': ('abide', 'anıt / abide'),
    'w07679': ('astroloji', 'astroloji / yıldız falı'),
    'w07680': ('diyakoz', 'diyakoz / papaz yardımcısı'),
    'w07681': ('yönetici', 'yönetici / organizatör'),
    'w07682': ('eşitlik', 'eşitlik / hak eşitliği'),
    'w07683': ('kurtarıcı', 'kurtarıcı / özgürlük getiren'),
    'w07685': ('vanilyalı', 'vanilyalı / vanilya (sıfat)'),
    'w07686': ('gazlamak', 'gaza basmak / hızlanmak'),
    'w07688': ('alıcı', 'alıcı / radyo / sığınak'),
    'w07689': ('anestezist', 'anestezist / anestezi uzmanı'),
    'w07690': ('preri', 'preri / otlak'),
    'w07692': ('döş', 'döş / göğüs eti / bacon'),
    'w07693': ('taramak (bir bölgeyi)', 'taramak / didik didik aramak'),
    'w07694': ('semender', 'semender / tritona'),
    'w07695': ('gösterişli', 'gösterişli / süslü / yapmacık'),
    'w07698': ('verimli', 'verimli / bereketli'),
    'w07699': ('mayo', 'mayo (erkek) / deniz şortu'),
    'w07700': ('ninni', 'ninni (sıfat) / beşik'),
    'w07701': ('ölçüm', 'ölçüm / ölçme'),
    'w07702': ('ölçmek', 'ölçmek / denemek'),
    'w07703': ('akışkan', 'akışkan / sıvı / (mecaz) çekim gücü'),
    'w07704': ('turna', 'turna / kuyu kolu'),
    'w07705': ('olumsuz', 'olumsuz / olumsuz biçimde'),
    'w07708': ('tüp', 'tüp / macun tüpü'),
    'w07709': ('yurtsever', 'yurtsever / vatanseverlik (sıfat)'),
    'w07710': ('sakin', 'sakin / huzurlu / dingin'),
    'w07711': ('titrek', 'titrek / titreyen'),
    'w07712': ('çalılık', 'çalılık / sık ağaçlık'),
    'w07713': ('iğne', 'iğne / iğne (arı) / dil ucu'),
    'w07715': ('kısaltma', 'kısaltma / kısaltma (harf)'),
    'w07716': ('akran', 'yaşıt / akran'),
    'w07717': ('fazlalık', 'fazlalık / artık'),
    'w07718': ('etkin', 'etkili / etkin'),
    'w07721': ('bitki çay', 'bitki çayı / kaynatma'),
    'w07722': ('sarsmak', 'sarsmak / heyecanlandırmak / rahatsız etmek'),
    'w07723': ('cızırdamak', 'tıslamak / cızırdamak / fışırdamak'),
    'w07725': ('kırmak', 'kırmak / patlatmak / (argo) öldürmek'),
    'w07726': ('kıl', 'kıl / sert tüy / tıraşsız sakal'),
    'w07727': ('aşılamak', 'aşılamak / alıştırmak / (ağaç) aşılamak'),
    'w07728': ('fiyonk', 'fiyonk / küçük kurdele'),
    'w07729': ('konveyör', 'konveyör / bant / montaj hattı'),
    'w07730': ('bütünleşik', 'kapsamlı / bütünleşik / karma'),
    'w07732': ('karşıya geçirmek', 'karşıya geçirmek / nakletmek'),
    'w07733': ('yabanarısı', 'yabanarısı (sıfat)'),
    'w07735': ('nesnellik', 'nesnellik / tarafsızlık'),
    'w07736': ('aldanmak', 'yanılmak / yanlış hesaplamak'),
    'w07738': ('denizlik', 'denizlik / pencere pervazı'),
    'w07740': ('çalı', 'çalı / çalılık'),
    'w07741': ('yakınlaştırmak', 'yakınlaştırmak / birbirine yaklaştırmak'),
    'w07742': ('toprak', 'toprak (sıfat) / bölgesel'),
    'w07743': ('pompa', 'pompa / gösteriş'),
    'w07744': ('hint sümbülü', 'hint sümbülü / (oyun) tavla'),
    'w07745': ('servis', 'servis / yemek takımı / çay takımı'),
    'w07747': ('kaldırıcı', 'kriko / kaldırıcı'),
    'w07748': ('atmak', 'atmak / zonklamak / titreşmek'),
    'w07749': ('gözüpek', 'gözü pek / gözüpek'),
    'w07750': ('mağara', 'mağara (küçük) / grotto'),
    'w07751': ('safra', 'safra / (mecaz) hınç'),
    'w07753': ('çizgisel', 'çizgisel / doğrusal / lineer'),
    'w07754': ('sıkıştırmak', 'sıkıştırmak / parmağını sıkıştırmak'),
    'w07755': ('belirsiz', 'belirsiz / muğlak'),
    'w07756': ('nazik', 'nazik / kibar / nezaketli'),
    'w07757': ('buruşuk', 'buruşuk / kırışık'),
    'w07758': ('ikiz', 'ikiz / çift (ikiz)'),
    'w07759': ('buğu', 'buğu / hafif sis'),
    'w07762': ('kızıllık', 'kızıllık / al yanak'),
    'w07763': ('kararlılık', 'kararlılık / azim'),
    'w07765': ('çomar', 'çoban köpeği / kurt köpeği'),
    'w07766': ('egzoz', 'egzoz / egzoz gazı'),
    'w07767': ('aşılama', 'aşılama / aşı olma'),
    'w07769': ('başvurmak', 'başvurmak / dilekçe vermek / rica etmek'),
    'w07770': ('saygın', 'saygın / otoriter / yetkili'),
    'w07771': ('gençliğe mahsus', 'gençlik (sıfat) / gençlere ait'),
    'w07772': ('kumral', 'kumral / açık kahverengi'),
    'w07773': ('insiyaki', 'içgüdüsel / sezgisel'),
    'w07774': ('istekli', 'istekli / arzulayan'),
    'w07775': ('istikrar', 'istikrar / dayanıklılık / kararlılık'),
    'w07777': ('yorum', 'yorum / yorumlama / tefsir'),
    'w07778': ('düzenlemek', 'düzenlemek / editörlük yapmak'),
    'w07779': ('papatya', 'papatya (küçük) / koyungözü'),
    'w07780': ('bürünmek', 'kaplanmak / bürünmek'),
    'w07781': ('melankoli', 'melankoli / hüzün'),
    'w07782': ('batırmak', 'batırmak / daldırmak'),
    'w07784': ('ham madde', 'ham madde / hammadde'),
    'w07785': ('fosil', 'fosil / maden (yer altı zenginliği)'),
    'w07787': ('kadınlık', 'kadınsılık / kadınlık'),
    'w07788': ('ihracat', 'ihracat / dışarı taşıma / çıkarma'),
    'w07790': ('müsaade etmek', 'izin vermek / onaylamak / yaptırım uygulamak'),
    'w07792': ('toprak', 'toprak (sıfat) / topraktan'),
    'w07793': ('hafif', 'hafif / yüksüz / eşyasız'),
    'w07794': ('aşırı', 'aşırı / ölçüsüz'),
    'w07795': ('harika', 'harika / mucize / ilginç şey'),
    'w07796': ('baraj gölü', 'baraj gölü / rezervuar'),
    'w07797': ('çözücü', 'çözücü / tiner'),
    'w07798': ('sahte', 'hileli / aldatıcı / sahte'),
    'w07799': ('it', 'sokak köpeği / melez köpek'),
    'w07800': ('göz çukuru', 'göz çukuru / göz yuvası'),
    'w07801': ('baharat', 'baharat / (mecaz) çekicilik'),
    'w07802': ('azca', 'azca / biraz az'),
    'w07803': ('elastik', 'elastik / esnek'),
    'w07804': ('yörünge', 'yörünge / yörüngesel'),
    'w07805': ('temel', 'temel / esas / ilke'),
    'w07806': ('denetim', 'denetim / mali denetim'),
}

DROP = {
    'w07631': 'козявка',
    'w07668': 'кипр',
    'w07786': 'рогоносец',
}
