# -*- coding: utf-8 -*-
"""B2 inceleme, parti 10."""

FIXES = {
    'w08208': ('gösterge paneli', 'gösterge paneli / kalkan / sigorta kutusu'),
    'w08209': ('ekşi krema', 'ekşi krema / smetana'),
    'w08210': ('yuvarlanmak', 'yuvarlanmak / kaymak / aşağı inmek'),
    'w08211': ('kirletmek', 'kirletmek / lekelemek / itibarını zedelemek'),
    'w08212': ('bükmek', 'bükmek / eğmek'),
    'w08214': ('gebe kalmak', 'hamile kalmak / gebe kalmak'),
    'w08215': ('büzmek', 'sıkmak / büzmek / çekip çıkarmak'),
    'w08217': ('yıpranmak', 'zayıflamak / gevşemek'),
    'w08218': ('temel', 'temel / köklü / esaslı'),
    'w08219': ('kurgu', 'kurgu / hayal ürünü / uydurma'),
    'w08220': ('santral', 'santral / anahtar'),
    'w08221': ('parke', 'parke / parke zemin'),
    'w08222': ('folklor', 'folklor / halk kültürü'),
    'w08223': ('yayılmak', 'yayılmak / büyümek / genişlemek'),
    'w08224': ('tonalite', 'tonalite / ton'),
    'w08225': ('teneke', 'teneke (sıfat) / tenekeden'),
    'w08226': ('özgürlük', 'özgürlük / serbestlik / laubalilik'),
    'w08227': ('otogar', 'otogar / otobüs terminali'),
    'w08228': ('fısıldamak', 'fısıldamak / fısıldayıp söylemek'),
    'w08229': ('mahvetmek', 'mahvetmek / yok etmek'),
    'w08230': ('akmak', 'akıp gitmek / sızmak'),
    'w08231': ('pazen', 'pazen / (halk dilinde) masal, hikâye'),
    'w08232': ('harfi harfine', 'kelimesi kelimesine / harfi harfine'),
    'w08233': ('kum taşı', 'kumtaşı'),
    'w08234': ('leopar', 'pars / leopar'),
    'w08236': ('but', 'but / uyluk (halk dili)'),
    'w08238': ('pullar', 'pul / balık pulu'),
    'w08241': ('üretici', 'üretici / imalatçı'),
    'w08242': ('dedikoducu', 'dedikoducu / dedikodu yapan'),
    'w08243': ('çözmek', 'çözmek / açmak / (marka) popülerleştirmek'),
    'w08244': ('yapılandırma', 'yapılandırma / konfigürasyon'),
    'w08245': ('unutkan', 'unutkan / dalgın'),
    'w08247': ('tipi', 'tipi / kar fırtınası'),
    'w08248': ('tepe', 'yükselti / tepe / yayla'),
    'w08250': ('kalfa', 'çırak / kalfa'),
    'w08251': ('kahramanlık', 'kahramanlık / yiğitlik'),
    'w08253': ('doldurmak', 'doldurmak / yenilemek / takviye etmek'),
    'w08255': ('sarışın', 'sarışın / açık saçlı'),
    'w08257': ('aydınlatmak', 'aydınlanmak / açıklığa kavuşmak'),
    'w08260': ('tedavi edilebilir', 'tedavi edilebilir / iyileşebilir'),
    'w08261': ('yer belirleme', 'konum / yer / mekân'),
    'w08262': ('mayınlamak', 'mayınlamak / mayın döşemek'),
    'w08263': ('astrolog', 'astrolog / müneccim'),
    'w08264': ('serbest', 'keyfî / serbest / rastgele'),
    'w08265': ('sapan', 'sapan / çatal'),
    'w08266': ('üçgen', 'üçgen / üçgen biçimli'),
    'w08267': ('kalpazan', 'kalpazan / sahte para basan'),
    'w08268': ('haince', 'haince / hain'),
    'w08269': ('melez', 'melez / hibrit'),
    'w08270': ('yelken', 'yelkenli / yelken (sıfat)'),
    'w08271': ('misina', 'misina / olta ipi'),
    'w08272': ('sessiz', 'sessiz / sesli olmayan'),
    'w08273': ('hemfikir', 'hemfikir / oybirliği ile'),
    'w08274': ('desise', 'desise / entrika / oyun'),
    'w08275': ('kasıt', 'kasıt / niyet / plan'),
    'w08277': ('primatlar', 'primatlar / maymungiller'),
    'w08278': ('topaç', 'topaç / fırıldak'),
    'w08279': ('yazım', 'imla / yazım / ortografi'),
    'w08280': ('satranç oyuncusu', 'satranç oyuncusu / satranççı'),
    'w08281': ('sebep', 'sebep / gerekçe / mantık'),
    'w08282': ('saçma', 'anlaşılmaz laf / saçmalık / zırva'),
    'w08283': ('reprodüksiyon', 'reprodüksiyon / kopya / çoğaltma'),
    'w08284': ('geç kalmak', 'geç kalmak / gecikmek'),
    'w08285': ('ayırmak', 'ayırmak / birbirinden koparmak'),
    'w08286': ('seferberlik', 'seferberlik / mobilizasyon'),
    'w08287': ('nakış', 'nakış / işleme'),
    'w08288': ('kızgın', 'kızgın / kızıl / akkor'),
    'w08289': ('püskürtmek', 'püskürtmek / sıçratmak / serpmek'),
    'w08290': ('yaslı', 'yaslı / hüzünlü / kederli'),
    'w08291': ('pantomima', 'pantomim / mimik oyunu'),
    'w08292': ('çuval', 'çuval / torba'),
    'w08294': ('yeniden inşa etmek', 'yeniden inşa etmek / yeniden kurmak'),
    'w08295': ('gelişigüzel', 'gelişigüzel / baştan savma / zar zor'),
    'w08296': ('dilenmek', 'dilenmek / avuç açmak'),
    'w08297': ('minyatür', 'minyatür / küçük ölçekli iş'),
    'w08299': ('çamaşırcı', 'çamaşırcı (kadın)'),
    'w08300': ('kutucuk', 'kutucuk / küçük çekmece'),
    'w08301': ('günlük dil', 'günlük konuşma dili / konuşma (sıfat)'),
    'w08302': ('batırmak', 'batırmak / daldırmak / yüklemek'),
    'w08304': ('gerçekleştirilebilir', 'gerçekleştirilebilir / yapılabilir'),
    'w08305': ('yapışmak', 'yapışmak / yapışıp kalmak'),
    'w08306': ('yarışmak', 'yarışmak / rekabet etmek'),
    'w08307': ('posta arabası', 'posta arabası / yolcu arabası'),
    'w08308': ('dilenmek', 'dilenmek / yalvarıp istemek'),
    'w08309': ('rezervasyon', 'rezervasyon / yer ayırma'),
    'w08310': ('turp', 'turp / kırmızı turp'),
    'w08311': ('sakatlamak', 'sakat etmek / sakatlamak'),
    'w08312': ('yama', 'yama / yama parçası'),
    'w08313': ('anlamak', 'anlamak / kavramak'),
    'w08314': ('ayırt edilebilir', 'tanınabilir / kolay tanınan'),
    'w08315': ('buzultaş', 'buzultaş / moren'),
    'w08316': ('kutu', 'kutu / mücevher sandığı'),
    'w08317': ('hayvanat bahçesi', 'hayvanat bahçesi / hayvan kafesi'),
    'w08318': ('çakırkeyf', 'çakırkeyf / hafif sarhoş'),
    'w08319': ('seslenmek', 'seslenmek / haykırmak / ünlemek'),
    'w08320': ('dürtü', 'dürtü / istek / ihtiyaç (fizyolojik)'),
    'w08322': ('araştırma', 'araştırma / arama'),
    'w08323': ('orak', 'orak / ay (hilal)'),
    'w08325': ('tokat', 'tokat / şamar'),
    'w08326': ('hortum', 'hortum (fil) / hortum'),
    'w08327': ('alay etmek', 'alay etmek / alaya almak'),
    'w08328': ('melas', 'pekmez / melas / şurup'),
    'w08329': ('pense; kene', 'pense / kıskaç / kene'),
    'w08330': ('sanmak', 'sanmak / zannetmek / saymak'),
    'w08331': ('kükreme', 'kükreme / hırlama'),
    'w08332': ('hırs', 'hırs / şan şöhret tutkusu'),
    'w08334': ('primadonna', 'primadonna / başrol kadın'),
    'w08335': ('manyetizma', 'manyetizma / cazibe'),
    'w08336': ('belirme', 'ortaya çıkış / doğuş / belirme'),
    'w08338': ('şaşı', 'şaşı / şaşı gözlü'),
    'w08339': ('açığa çıkarmak', 'açığa çıkarmak / çıplak bırakmak'),
    'w08340': ('yormak', 'yormak / bitirmek'),
    'w08341': ('akıl almaz', 'akıl almaz / baş döndürücü'),
    'w08342': ('ekleme', 'ekleme / araya sokma'),
    'w08343': ('korumak', 'korumak / beklemek / gözetmek'),
    'w08344': ('ilişkilendirmek', 'ilişkilendirmek / çağrıştırmak'),
    'w08346': ('anjin', 'anjin / bademcik iltihabı'),
    'w08348': ('kalkan', 'kalkan (balık) / pisi balığı'),
    'w08349': ('çekinmek', 'çekinmek / ürkmek / cesaret edememek'),
    'w08350': ('küçük yılan', 'küçük yılan / fermuar'),
    'w08352': ('baskı', 'baskı / sıkıntı / eziyet'),
    'w08353': ('zora sokmak', 'zora sokmak / karmaşıklaştırmak'),
    'w08354': ('bombalama', 'bombalama / bombardıman'),
    'w08355': ('tarak', 'tarak / saç fırçası'),
    'w08356': ('sürgün', 'sürgün / sürgün edilmiş kişi'),
    'w08357': ('yol (mecazi)', 'yol / hayat yolu / iz'),
    'w08358': ('merhametli', 'merhametli / şefkatli'),
    'w08359': ('botanik', 'botanik / bitki bilimi'),
    'w08360': ('donmak', 'donmak / üşümek'),
    'w08361': ('döllenme', 'döllenme / tohumlama'),
    'w08362': ('saymak', 'uymak / saygı göstermek / korumak'),
    'w08363': ('gulaş', 'gulaş / güveç eti'),
    'w08364': ('artık', 'kalıntı / artık / geçmişten kalma'),
    'w08366': ('ansızlık', 'ansızlık / beklenmedik oluş'),
    'w08367': ('öcü', 'öcü / korkunç yaratık'),
    'w08368': ('talk', 'talk / talk pudrası'),
    'w08369': ('aykırı', 'aykırı / tam tersine'),
    'w08370': ('tutmak', 'tasarlamak / planlamak / niyet etmek'),
    'w08371': ('hadımlaştırma', 'hadımlaştırma / kastrasyon'),
    'w08373': ('yağsız', 'yağsız / light'),
    'w08375': ('azarlamak', 'azarlamak / paylamak / küfretmek'),
    'w08377': ('aşçı', 'aşçı (kadın)'),
    'w08378': ('kondansatör', 'kondansatör / yoğunlaştırıcı'),
    'w08380': ('kamış olta ile balık tutmak', 'olta ile balık tutmak / balık tutmak'),
    'w08382': ('hulasa etmek', 'sonuçlandırmak / özetlemek / hulasa etmek'),
    'w08383': ('modernizasyon', 'modernizasyon / güncelleştirme'),
    'w08384': ('şeytan', 'şeytan / cin'),
    'w08385': ('üremek', 'üremek / çoğalmak'),
    'w08386': ('kürek mahkûmu', 'kürek mahkûmu / ağır ceza mahkûmu'),
    'w08389': ('kat', 'kat / tabaka / katman'),
    'w08390': ('iliştirmek', 'iğneyle tutturmak / iliştirmek'),
    'w08391': ('gençleşmek', 'gençleşmek / gençleşme'),
    'w08392': ('büzülmek', 'daralmak / ince hâle gelmek'),
    'w08394': ('bebek bezi', 'kundak bezi / alt bezi'),
    'w08395': ('aklıselimlik', 'normallik / sağlıklı oluş'),
    'w08397': ('telsizci', 'telsizci / telsiz operatörü'),
    'w08398': ('gösterici', 'gösterici / eylemci'),
    'w08399': ('proje hazırlama', 'tasarım / proje hazırlama'),
    'w08400': ('çalışkan', 'çalışkan / işine bağlı'),
    'w08401': ('milyarıncı', 'milyarıncı / milyarlık'),
    'w08402': ('otit', 'otit / orta kulak iltihabı'),
    'w08403': ('adilik', 'adilik / aşağılık / alçaklık'),
    'w08404': ('lor', 'lor / süzme peynir'),
    'w08406': ('birikmek', 'birikmek / toplanmak'),
}

DROP = {
    'w08351': 'лаос',
    'w08376': 'дрейфить',
}
