"""Elle dogrulanmis ceviriler.

Otomatik sozluk birlestirme somut isim ve fiillerde iyi calisiyor ama soyut
baglaclar, edatlar ve zarflarda cuvalliyor (WikDict "исключительно" icin
"sade", "следовательно" icin "itibaren" veriyor). Bunlar en sik kullanilan
kelimeler oldugu icin elle yaziliyor.

Bicim:  bare -> (turkce, vurgulu_form | None)
Vurgulu form None ise Badestrand'daki hali kullanilir; sozlukte olmayan
cok kelimeli kaliplar icin acikca yazilir.
"""

OVERRIDES = {
    # ─────────────────────────── Zamirler ───────────────────────────
    'я': ('ben', 'я'),
    'ты': ('sen', 'ты'),
    'он': ('o (erkek)', 'он'),
    'она': ('o (kadın)', 'она́'),
    'оно': ('o (cansız)', 'оно́'),
    'мы': ('biz', 'мы'),
    'вы': ('siz', 'вы'),
    'они': ('onlar', 'они́'),
    'это': ('bu, bu şey', 'э́то'),
    'этот': ('bu', 'э́тот'),
    'тот': ('şu, o', 'тот'),
    'такой': ('böyle, öyle bir', 'тако́й'),
    'который': ('ki, hangi', 'кото́рый'),
    'кто': ('kim', 'кто'),
    'что': ('ne, ki', 'что'),
    'чей': ('kimin', 'чей'),
    'свой': ('kendi', 'свой'),
    'себя': ('kendini, kendine', 'себя́'),
    'сам': ('kendisi, bizzat', 'сам'),
    'самый': ('en, ta kendisi', 'са́мый'),
    'весь': ('bütün, tüm', 'весь'),
    'каждый': ('her, her bir', 'ка́ждый'),
    'любой': ('herhangi bir, her', 'любо́й'),
    'другой': ('başka, diğer', 'друго́й'),
    'некоторый': ('bazı, kimi', 'не́который'),
    'никакой': ('hiçbir', 'никако́й'),
    'никто': ('hiç kimse', 'никто́'),
    'ничто': ('hiçbir şey', 'ничто́'),

    # ─────────────────────────── Edatlar ────────────────────────────
    'в': ('içinde, -e', 'в'),
    'на': ('üstünde, -e', 'на'),
    'с': ('ile, -den', 'с'),
    'по': ('boyunca, -e göre', 'по'),
    'из': ('-den, içinden', 'из'),
    'к': ('-e doğru, -e', 'к'),
    'у': ('yanında, -de (sahiplik)', 'у'),
    'за': ('arkasında, için', 'за'),
    'от': ('-den, -dan', 'от'),
    'о': ('hakkında, dair', 'о'),
    'для': ('için', 'для'),
    'до': ('-e kadar, -den önce', 'до'),
    'после': ('-den sonra', 'по́сле'),
    'перед': ('önünde, -den önce', 'пе́ред'),
    'под': ('altında', 'под'),
    'над': ('üstünde, üzerinde', 'над'),
    'между': ('arasında', 'ме́жду'),
    'через': ('üzerinden, -den sonra', 'че́рез'),
    'при': ('yanında, sırasında', 'при'),
    'без': ('-sız, olmadan', 'без'),
    'вокруг': ('etrafında, çevresinde', 'вокру́г'),
    'против': ('karşı, aleyhine', 'про́тив'),
    'среди': ('arasında, ortasında', 'среди́'),
    'вместо': ('yerine', 'вме́сто'),
    'кроме': ('hariç, dışında', 'кро́ме'),
    'благодаря': ('sayesinde', 'благодаря́'),
    'вопреки': ('-e karşın, aksine', 'вопреки́'),
    'согласно': ('-e göre, uyarınca', 'согла́сно'),
    'вследствие': ('sonucunda, yüzünden', 'всле́дствие'),
    'ввиду': ('-den dolayı, göz önüne alınarak', 'ввиду́'),

    # ──────────────────── Baglaclar ve baglayicilar ─────────────────
    'и': ('ve, ile', 'и'),
    'а': ('ise, oysa', 'а'),
    'но': ('ama, fakat', 'но'),
    'или': ('veya, ya da', 'и́ли'),
    'однако': ('ancak, fakat', 'одна́ко'),
    'зато': ('buna karşılık, ama', 'зато́'),
    'чтобы': ('-mek için, diye', 'что́бы'),
    'если': ('eğer, şayet', 'е́сли'),
    'когда': ('-diğinde, ne zaman', 'когда́'),
    'пока': ('-ken, -e kadar', 'пока́'),
    'хотя': ('-e rağmen, gerçi', 'хотя́'),
    'поэтому': ('bu yüzden, bu nedenle', 'поэ́тому'),
    'следовательно': ('dolayısıyla, bu nedenle', 'сле́довательно'),
    'поскольку': ('-diği için, madem ki', 'поско́льку'),
    'впрочем': ('gerçi, esasen', 'впро́чем'),
    'причём': ('üstelik, hem de', 'причём'),
    'якобы': ('sözde, güya', 'я́кобы'),
    'будто': ('sanki, güya', 'бу́дто'),
    'словно': ('sanki, adeta', 'сло́вно'),
    'ведь': ('ya, hani', 'ведь'),
    'итак': ('böylece, öyleyse', 'ита́к'),
    'наконец': ('sonunda, nihayet', 'наконе́ц'),
    'например': ('örneğin, mesela', 'наприме́р'),
    # ───────────── Selamlasma ve gunluk kaliplar ─────────────
    'привет': ('merhaba, selam', 'приве́т'),
    'папа': ('baba', 'па́па'),
    'мама': ('anne', 'ма́ма'),
    'хлеб': ('ekmek', 'хлеб'),
    'хромой': ('aksak, topal', 'хромо́й'),
    'еда': ('yemek, yiyecek', 'еда́'),
    'здравствуйте': ('merhaba (resmî)', 'здра́вствуйте'),
    'спасибо': ('teşekkür ederim, sağ ol', 'спаси́бо'),
    'пожалуйста': ('lütfen, rica ederim', 'пожа́луйста'),
    'извините': ('affedersiniz, özür dilerim', 'извини́те'),
    'прощай': ('elveda', 'проща́й'),
    'здравствуй': ('merhaba', 'здра́вствуй'),
    'доброе утро': ('günaydın', 'до́брое у́тро'),
    'добрый день': ('iyi günler', 'до́брый день'),
    'добрый вечер': ('iyi akşamlar', 'до́брый ве́чер'),
    'спокойной ночи': ('iyi geceler', 'споко́йной но́чи'),
    'до свидания': ('hoşça kal, görüşürüz', 'до свида́ния'),
    'как дела': ('nasılsın', 'как дела́'),
    'очень приятно': ('memnun oldum', 'о́чень прия́тно'),
    'хорошо': ('iyi, peki', 'хорошо́'),
    'плохо': ('kötü, fena', 'пло́хо'),
    'прекрасно': ('harika, mükemmel', 'прекра́сно'),
    'прекрасный': ('harika, muhteşem', 'прекра́сный'),
    'отлично': ('mükemmel, harika', 'отли́чно'),
    'замечательно': ('harika, çok güzel', 'замеча́тельно'),
    'конечно': ('elbette, tabii', 'коне́чно'),
    'да': ('evet', 'да'),
    'нет': ('hayır, yok', 'нет'),

    # Cok kelimeli kaliplar (sozlukte lemma olarak yok)
    'потому что': ('çünkü', 'потому́ что'),
    'так как': ('çünkü, -diği için', 'так как'),
    'то есть': ('yani', 'то есть'),
    'несмотря на': ('-e rağmen', 'несмотря́ на'),
    'таким образом': ('böylece, bu şekilde', 'таки́м о́бразом'),
    'кроме того': ('ayrıca, bunun yanı sıra', 'кро́ме того́'),
    'тем не менее': ('yine de, buna rağmen', 'тем не ме́нее'),
    'между тем': ('bu arada, oysa', 'ме́жду тем'),
    'в частности': ('özellikle, bilhassa', 'в ча́стности'),
    'в целом': ('genel olarak, bütün olarak', 'в це́лом'),
    'в основном': ('esasen, çoğunlukla', 'в основно́м'),
    'прежде всего': ('her şeyden önce, öncelikle', 'пре́жде всего́'),
    'во-первых': ('birincisi, ilk olarak', 'во-пе́рвых'),
    'во-вторых': ('ikincisi', 'во-вторы́х'),
    'в отличие от': ('-in aksine, -den farklı olarak', 'в отли́чие от'),
    'по сравнению с': ('-e kıyasla, -e göre', 'по сравне́нию с'),
    'в связи с': ('-den dolayı, ile bağlantılı olarak', 'в свя́зи с'),
    'в результате': ('sonucunda, neticesinde', 'в результа́те'),
    'в течение': ('süresince, boyunca', 'в тече́ние'),
    'в ходе': ('sırasında, esnasında', 'в хо́де'),
    'на основе': ('temelinde, esas alınarak', 'на осно́ве'),
    'с точки зрения': ('açısından, bakımından', 'с то́чки зре́ния'),
    'в качестве': ('olarak, sıfatıyla', 'в ка́честве'),
    'по мере': ('arttıkça, ölçüsünde', 'по ме́ре'),
    'наряду с': ('ile birlikte, yanı sıra', 'наряду́ с'),

    # ──────────────────────────── Zarflar ───────────────────────────
    'исключительно': ('yalnızca, sırf', 'исключи́тельно'),
    'очень': ('çok, pek', 'о́чень'),
    'слишком': ('fazla, aşırı', 'сли́шком'),
    'довольно': ('oldukça, epeyce', 'дово́льно'),
    'почти': ('neredeyse, hemen hemen', 'почти́'),
    'совсем': ('tamamen, hiç', 'совсе́м'),
    'вовсе': ('hiç, asla', 'во́все'),
    'отнюдь': ('asla, hiç de', 'отню́дь'),
    'крайне': ('son derece, aşırı', 'кра́йне'),
    'весьма': ('oldukça, hayli', 'весьма́'),
    'чрезвычайно': ('son derece, olağanüstü', 'чрезвыча́йно'),
    'достаточно': ('yeterince, oldukça', 'доста́точно'),
    'особенно': ('özellikle', 'осо́бенно'),
    'именно': ('tam olarak, tam da', 'и́менно'),
    'даже': ('bile, hatta', 'да́же'),
    'уже': ('artık, çoktan', 'уже́'),
    'ещё': ('daha, hâlâ', 'ещё'),
    'только': ('sadece, ancak', 'то́лько'),
    'лишь': ('sadece, ancak', 'лишь'),
    'конечно': ('elbette, tabii', 'коне́чно'),
    'разумеется': ('tabii ki, şüphesiz', 'разуме́ется'),
    'безусловно': ('kesinlikle, kuşkusuz', 'безусло́вно'),
    'возможно': ('belki, muhtemelen', 'возмо́жно'),
    'вероятно': ('muhtemelen, büyük olasılıkla', 'вероя́тно'),
    'наверное': ('herhalde, muhtemelen', 'наве́рное'),
    'обязательно': ('mutlaka, kesinlikle', 'обяза́тельно'),
    'всегда': ('her zaman, daima', 'всегда́'),
    'никогда': ('asla, hiçbir zaman', 'никогда́'),
    'иногда': ('bazen, ara sıra', 'иногда́'),
    'часто': ('sık sık, sıkça', 'ча́сто'),
    'редко': ('nadiren, seyrek', 'ре́дко'),
    'обычно': ('genellikle, çoğunlukla', 'обы́чно'),
    'вдруг': ('aniden, birden', 'вдруг'),
    'сразу': ('hemen, derhal', 'сра́зу'),
    'постепенно': ('yavaş yavaş, kademeli olarak', 'постепе́нно'),
    'наоборот': ('tam tersine, aksine', 'наоборо́т'),
    'вместе': ('birlikte, beraber', 'вме́сте'),
    'отдельно': ('ayrı ayrı, ayrıca', 'отде́льно'),
    'раньше': ('daha önce, eskiden', 'ра́ньше'),
    'позже': ('daha sonra, sonradan', 'по́зже'),
    'потом': ('sonra, ardından', 'пото́м'),
    'затем': ('sonra, ardından', 'зате́м'),
    'сейчас': ('şimdi, şu anda', 'сейча́с'),
    'теперь': ('artık, şimdi', 'тепе́рь'),
    'тогда': ('o zaman, öyleyse', 'тогда́'),

    # ───────────────────────── Soyut isimler ────────────────────────
    'возможность': ('imkân, olanak', 'возмо́жность'),
    'необходимость': ('gereklilik, zorunluluk', 'необходи́мость'),
    'значение': ('anlam, önem', 'значе́ние'),
    'смысл': ('anlam, mana', 'смысл'),
    'причина': ('sebep, neden', 'причи́на'),
    'следствие': ('sonuç, netice', 'сле́дствие'),
    'последствие': ('sonuç, akıbet', 'после́дствие'),
    'цель': ('amaç, hedef', 'цель'),
    'задача': ('görev, problem', 'зада́ча'),
    'условие': ('koşul, şart', 'усло́вие'),
    'обстоятельство': ('durum, koşul', 'обстоя́тельство'),
    'положение': ('durum, konum', 'положе́ние'),
    'состояние': ('durum, hâl', 'состоя́ние'),
    'уровень': ('düzey, seviye', 'у́ровень'),
    'степень': ('derece, ölçü', 'сте́пень'),
    'качество': ('nitelik, kalite', 'ка́чество'),
    'количество': ('nicelik, miktar', 'коли́чество'),
    'свойство': ('özellik, nitelik', 'сво́йство'),
    'особенность': ('özellik, ayırt edici yön', 'осо́бенность'),
    'признак': ('belirti, işaret', 'при́знак'),
    'способ': ('yöntem, yol', 'спо́соб'),
    'средство': ('araç, vasıta', 'сре́дство'),
    'подход': ('yaklaşım', 'подхо́д'),
    'основа': ('temel, esas', 'осно́ва'),
    'основание': ('temel, gerekçe', 'основа́ние'),
    'правило': ('kural', 'пра́вило'),
    'порядок': ('düzen, sıra', 'поря́док'),
    'развитие': ('gelişme, kalkınma', 'разви́тие'),
    'изменение': ('değişiklik, değişim', 'измене́ние'),
    'рост': ('büyüme, artış', 'рост'),
    'увеличение': ('artış, çoğalma', 'увеличе́ние'),
    'сокращение': ('azaltma, kısaltma', 'сокраще́ние'),
    'снижение': ('düşüş, azalma', 'сниже́ние'),
    'влияние': ('etki, nüfuz', 'влия́ние'),
    'воздействие': ('etki', 'возде́йствие'),
    'опыт': ('deneyim, tecrübe', 'о́пыт'),
    'умение': ('beceri, yetenek', 'уме́ние'),
    'способность': ('yetenek, kabiliyet', 'спосо́бность'),
    'преимущество': ('avantaj, üstünlük', 'преиму́щество'),
    'недостаток': ('eksiklik, kusur', 'недоста́ток'),
    'попытка': ('deneme, girişim', 'попы́тка'),
    'усилие': ('çaba, gayret', 'уси́лие'),
    'деятельность': ('faaliyet, etkinlik', 'де́ятельность'),
    'явление': ('olgu, fenomen', 'явле́ние'),
    'событие': ('olay', 'собы́тие'),
    'случай': ('durum, vaka', 'слу́чай'),
    'сведения': ('bilgiler', 'све́дения'),
    'источник': ('kaynak', 'исто́чник'),
    'вывод': ('sonuç, çıkarım', 'вы́вод'),
    'заключение': ('sonuç, karar', 'заключе́ние'),
    'мнение': ('görüş, fikir', 'мне́ние'),
    'представление': ('kavram, tasavvur', 'представле́ние'),
    'понятие': ('kavram', 'поня́тие'),
    'мысль': ('düşünce', 'мысль'),

    # ──────────────────────────── Fiiller ───────────────────────────
    'являться': ('olmak, teşkil etmek', 'явля́ться'),
    'означать': ('anlamına gelmek', 'означа́ть'),
    'требовать': ('gerektirmek, talep etmek', 'тре́бовать'),
    'позволять': ('izin vermek, olanak tanımak', 'позволя́ть'),
    'обеспечивать': ('sağlamak, temin etmek', 'обеспе́чивать'),
    'использовать': ('kullanmak', 'испо́льзовать'),
    'применять': ('uygulamak', 'применя́ть'),
    'создавать': ('yaratmak, oluşturmak', 'создава́ть'),
    'формировать': ('biçimlendirmek, oluşturmak', 'формирова́ть'),
    'сформировать': ('oluşturmak, biçimlendirmek', 'сформирова́ть'),
    'развивать': ('geliştirmek', 'развива́ть'),
    'влиять': ('etkilemek', 'влия́ть'),
    'зависеть': ('bağlı olmak', 'зави́сеть'),
    'относиться': ('ilgili olmak, davranmak', 'относи́ться'),
    'касаться': ('değinmek, ilgilendirmek', 'каса́ться'),
    'включать': ('içermek, dahil etmek', 'включа́ть'),
    'содержать': ('içermek', 'содержа́ть'),
    'состоять': ('oluşmak, ibaret olmak', 'состоя́ть'),
    'существовать': ('var olmak, mevcut olmak', 'существова́ть'),
    'происходить': ('olmak, meydana gelmek', 'происходи́ть'),
    'возникать': ('ortaya çıkmak, doğmak', 'возника́ть'),
    'достигать': ('ulaşmak, erişmek', 'достига́ть'),
    'добиваться': ('başarmak, elde etmek', 'добива́ться'),
    'удаваться': ('başarmak, becerebilmek', 'удава́ться'),
    'стараться': ('gayret etmek, çabalamak', 'стара́ться'),
    'доказывать': ('kanıtlamak', 'дока́зывать'),
    'объяснять': ('açıklamak', 'объясня́ть'),
    'описывать': ('betimlemek, tarif etmek', 'опи́сывать'),
    'определять': ('belirlemek, tanımlamak', 'определя́ть'),
    'устанавливать': ('kurmak, tespit etmek', 'устана́вливать'),
    'отмечать': ('belirtmek, kutlamak', 'отмеча́ть'),
    'подчёркивать': ('vurgulamak', 'подчёркивать'),
    'указывать': ('işaret etmek, belirtmek', 'ука́зывать'),
    'предлагать': ('önermek, teklif etmek', 'предлага́ть'),
    'отказываться': ('reddetmek, vazgeçmek', 'отка́зываться'),
    'учитывать': ('dikkate almak, göz önünde bulundurmak', 'учи́тывать'),
    'рассматривать': ('incelemek, ele almak', 'рассма́тривать'),
    'осуществлять': ('gerçekleştirmek, yürütmek', 'осуществля́ть'),
    'выполнять': ('yerine getirmek, uygulamak', 'выполня́ть'),
    'оказывать': ('sağlamak, göstermek (etki)', 'ока́зывать'),
    'приводить': ('getirmek, yol açmak', 'приводи́ть'),
    'вызывать': ('yol açmak, çağırmak', 'вызыва́ть'),
    'полагать': ('sanmak, varsaymak', 'полага́ть'),
    'считать': ('saymak, kabul etmek', 'счита́ть'),

    # ─────────────────────────── Sifatlar ───────────────────────────
    'важный': ('önemli', 'ва́жный'),
    'необходимый': ('gerekli, zorunlu', 'необходи́мый'),
    'возможный': ('mümkün, olası', 'возмо́жный'),
    'основной': ('temel, ana', 'основно́й'),
    'главный': ('başlıca, ana', 'гла́вный'),
    'общий': ('genel, ortak', 'о́бщий'),
    'особый': ('özel, ayrı', 'осо́бый'),
    'различный': ('farklı, çeşitli', 'разли́чный'),
    'подобный': ('benzer, böyle', 'подо́бный'),
    'современный': ('çağdaş, modern', 'совреме́нный'),
    'настоящий': ('gerçek, şimdiki', 'настоя́щий'),
    'следующий': ('sonraki, ertesi', 'сле́дующий'),
    'предыдущий': ('önceki', 'предыду́щий'),
    'дальнейший': ('sonraki, ileriki', 'дальне́йший'),
    'значительный': ('önemli, kayda değer', 'значи́тельный'),
    'существенный': ('esaslı, önemli', 'суще́ственный'),
    'сложный': ('karmaşık, zor', 'сло́жный'),
    'устойчивый': ('istikrarlı, sürdürülebilir', 'усто́йчивый'),
    'постоянный': ('sürekli, kalıcı', 'постоя́нный'),
    'временный': ('geçici', 'вре́менный'),
    'дополнительный': ('ek, ilave', 'дополни́тельный'),
    'единственный': ('tek, yegâne', 'еди́нственный'),
    'очевидный': ('apaçık, bariz', 'очеви́дный'),
    'точный': ('kesin, tam', 'то́чный'),
    'конкретный': ('somut, belirli', 'конкре́тный'),
}


# Uygulamanin ilk bolumunde gorunecek kelimeler.
#
# Ham frekans siralamasinda ilk bolum bastan asagi zamir ve edat cikiyor
# ("я, не, что, в, и"); yeni baslayan biri icin ogretici degil. Buraya
# gunluk hayatta hemen ise yarayan kelimeler geliyor.
STARTER = [
    'привет', 'здравствуйте', 'спасибо', 'пожалуйста', 'да', 'нет',
    'извините', 'до свидания', 'доброе утро', 'добрый день',
    'добрый вечер', 'спокойной ночи', 'как дела', 'хорошо', 'плохо',
    'очень приятно', 'прекрасно', 'человек', 'имя', 'друг', 'семья',
    'мама', 'папа', 'вода', 'хлеб', 'еда', 'дом', 'город', 'улица',
    'работа', 'день', 'ночь', 'утро', 'вечер', 'время', 'год',
    'сегодня', 'завтра', 'вчера', 'много', 'мало', 'большой',
    'маленький', 'новый', 'старый', 'быть', 'иметь', 'делать', 'знать',
    'думать', 'говорить', 'сказать', 'видеть', 'слышать', 'хотеть',
    'мочь', 'идти', 'ехать', 'жить', 'работать', 'читать', 'писать',
    'есть', 'пить', 'спать', 'любить', 'понимать', 'помочь', 'дать',
]

# Ilk bolumlerde kalmasina izin verilen islev kelimeleri. Digerleri
# (zamirler, nadir edatlar, parcaciklar) geriye itiliyor.
FUNCTION_KEEP = {'и', 'но', 'или', 'не', 'да', 'нет', 'с', 'в', 'на'}
