# -*- coding: utf-8 -*-
"""Dış inceleme raporu, grup 9."""

FIXES = {
    'w08160': ('armatür', 'demir donatı / inşaat demiri'),
    'w08170': ('türban', 'sarık'),
    'w08190': ('yük', 'zorluk / meşakkat'),
    'w08205': ('ağırlık', 'tartı ağırlığı / kettlebell'),
    'w08208': ('gösterge paneli', 'pul (kabuk) / pano / siperlik'),
    'w08211': ('kirletmek', 'lekelemek / kötülemek'),
    'w08215': ('büzmek', 'sıkıştırmak / (üstten) çekip almak'),
    'w08248': ('tepe', 'yayla / yükselti'),
    'w08264': ('serbest', 'rastgele / keyfî'),
    'w08346': ('anjin', 'bademcik iltihabı / anjin'),
    'w08371': ('hadımlaştırma', 'hadım etme / kastrasyon'),
    'w08382': ('hulasa etmek', 'özetlemek / sonuçlandırmak'),
    'w08403': ('adilik', 'alçaklık / adilik'),
    'w08411': ('açık', 'boş'),
    'w08412': ('pazarlamak', 'satmak / elden çıkarmak'),
    'w08419': ('armadillo', 'zırhlı memeli (armadillo) / zırhlı savaş gemisi'),
    'w08426': ('bakkal', 'bakkaliye (sıfat)'),
    'w08443': ('etkisiz', 'dişsiz / (mecaz) etkisiz'),
    'w08446': ('nezaketsiz', 'hoş olmayan / düşmanca'),
    'w08463': ('bayat', 'bayat / duygusuz'),
    'w08472': ('hararetli', 'kavurucu'),
    'w08476': ('bitirmek', 'yıpratmak / bitkin düşürmek'),
    'w08480': ('sahte', 'yapmacık / sahte'),
    'w08515': ('faaliyet', 'işleyiş'),
    'w08518': ('bölümlendirme', 'sınıflandırma'),
    'w08529': ('agregat', 'agrega / ünite'),
    'w08531': ('kap', 'kapasite / hacim / kap'),
    'w08541': ('buruşturmak', 'ezmek / yoğurmak / buruşturmak'),
    'w08558': ('fermuar', 'kopça / toka'),
    'w08560': ('kazanmak', 'yenmek (oyunda)'),
    'w08583': ('devingenlik', 'hareketlilik'),
    'w08592': ('boğulmak (yerken)', 'boğazına takılmak / hızlı yutmak'),
    'w08626': ('kışkırtmak', 'propaganda yapmak / ikna etmeye çalışmak'),
    'w08637': ('kayın', 'kayınbirader (kocanın erkek kardeşi)'),
    'w08644': ('ebelik', 'doğum bilimi / ebelik'),
    'w08645': ('sincap benzeri kemirgen / burunduk', 'yer sincabı'),
    'w08650': ('koparmak', 'kesmek / sona erdirmek'),
    'w08658': ('keşif', 'maliyet çizelgesi / bütçe'),
    'w08660': ('vezir', 'vezir (satranç taşı)'),
    'w08677': ('korsaj', 'elbise üst kısmı / korsaj'),
    'w08691': ('kepek', 'buğday kepeği'),
    'w08693': ('kendi portresi', 'otoportre'),
    'w08696': ('müdüriyet', 'yönetim / idare'),
    'w08697': ('girişken', 'girişimci'),
    'w08699': ('düşman', 'nefret eden kimse'),
    'w08713': ('kazanmak', 'fethetmek / kazanmak'),
    'w08714': ('ayırma', 'ödenek'),
    'w08721': ('azaltmak', 'en aza indirmek'),
    'w08725': ('tatula', 'sersemlik / tatula'),
    'w08726': ('anıtlaştırmak', 'ölümsüzleştirmek'),
    'w08739': ('tepesi açılmak', 'kel olmak'),
    'w08740': ('sanatsal', 'sanatçı ruhlu'),
    'w08741': ('dayanaksız', 'nedensiz'),
    'w08753': ('göçmek', 'göç etmek'),
    'w08754': ('ağza alınmaz', 'tarif edilemez'),
    'w08755': ('yuvarlaklaştırmak', 'yuvarlamak (sayı)'),
    'w08756': ('bilgili', 'çok okumuş'),
    'w08759': ('yenilemek', 'yeniden başlatmak'),
    'w08768': ('mütenasip', 'orantılı'),
    'w08773': ('eğitilen kişi / yetiştirme (yetimhane)', 'himaye altındaki kişi / öğrenci'),
    'w08775': ('bağlamak', 'dövüp yapmak / zincire vurmak'),
    'w08778': ('biteviye', 'monoton / tekdüze'),
    'w08779': ('tahnit', 'mumyalama'),
    'w08811': ('çilek', 'yabani çilek'),
    'w08834': ('üzülmek', 'ıstırap çekmek'),
    'w08836': ('fikrini anlatmak', 'kendini ifade etmek'),
    'w08839': ('çiğnenmiş', 'işlek (yol)'),
    'w08846': ('hükmetmek', 'hükümdarlık etmek'),
    'w08863': ('altlık', 'destek / payanda'),
    'w08878': ('kulübe', 'köy evi (Rus tipi)'),
    'w08887': ('perhiz yemeği', 'etsiz / perhiz (sıfat)'),
    'w08894': ('bereket', 'bolluk'),
    'w08897': ('sinsi', 'işgüzar / kurnaz'),
    'w08899': ('yük getiren', 'külfetli / yorucu'),
    'w08911': ('bozmak', 'çirkinleştirmek / sakatlamak'),
    'w08912': ('tabansız', 'korkak'),
    'w08916': ('tazminat', 'ayrılma tazminatı'),
    'w08927': ('üst geçit', 'viyadük / estakat'),
    'w08936': ('hafıza kaybı', 'baygınlık / kendinden geçme'),
    'w08950': ('feyk', 'aldatıcı hareket / çalım'),
    'w08960': ('boyun eğdirme', 'fetih / boyun eğdirme'),
    'w08970': ('suvat', 'hayvan sulama yeri'),
    'w08983': ('emniyetle', 'güvenilir biçimde'),
    'w08992': ('hedefe yönelik', 'adresli / adres (sıfat)'),
    'w08995': ('hissiz', 'uyuşmuş / hissiz'),
}

EXTR = {
    'w08403': ('Ama yine de ima ettim, yani adice bir şey yaptım.', 'Ama ona ima ettim, bu da aslında bir alçaklıktı.'),
    'w08558': ('Ceketimdeki fermuarı onarmam lazım.', 'Ceketimin kopçasını onarmam lazım.'),
    'w08626': ('Sizi aramıza katmaya çalışmak için gelmedim.', 'Sizi ikna etmek için gelmedim.'),
    'w08650': ("La Motta, Sugar Ray'in yenilmezlik ünvanını elinden almış oldu. Büyük bir boksör olduğunu kanıtladı.", "Bu zaferle La Motta, Robinson'ın zafer serisini sona erdiriyor."),
    'w08768': ('Sonuçta, yıllar boyunca, masraflar cirodan daha hızlı arttı.', 'Sonuçta zamanla masraflar ciroyla orantılı olarak arttı.'),
    'w08773': ('Mürebbiyeler korumalarını eğitmek için onlara ip atlatıyordu.', 'Mürebbiyeler öğrencilerine zıplamayı öğretiyordu.'),
    'w08779': ('Birçoğumuz için temizlenip güzelleştirilmek aslında bizi yansıtmaz.', 'Birçoğumuz mumyalamanın gerçek bizi göstermediğini anlıyor.'),
    'w08916': ("Artık 20,000 pound'a yakın paraları vardır.", 'Ayrılma tazminatı tutarı 20 bin pound oldu.'),
}

EXDROP = {
}

DROP = {
    'w08546': 'карда',
}

FIELDS = {}

POS = {}
