# -*- coding: utf-8 -*-
"""Dış inceleme raporu, grup 3."""

FIXES = {
    'w02017': ('kızarmış ekmek (tost)', 'tost / kadeh kaldırma konuşması'),
    'w02018': ('takım', 'takım / (üye) alımı'),
    'w02022': ('çek', 'fiş / çek'),
    'w02024': ('gezmek', 'kaymak / binmek / gezmek'),
    'w02031': ('başlatmak', 'edinmek / çalıştırmak (motor)'),
    'w02045': ('beceriksiz', 'beceriksiz / sakar'),
    'w02046': ('enli', 'geniş / enli'),
    'w02049': ('utanmak', 'utanmak / çekinmek'),
    'w02058': ('resim', 'resim / görüntü'),
    'w02061': ('çırpınmak', 'dövüşmek / (kalp) çarpmak'),
    'w02071': ('ılık', 'ılık / sıcak'),
    'w02075': ('depozito', 'rehin / depozito'),
    'w02076': ('et', 'beden / et'),
    'w02080': ('şefkatli', 'hassas / yumuşak / şefkatli'),
    'w02103': ('dayanmak', 'dayanmak / dışarı çıkarmak / (ders) çıkarmak'),
    'w02107': ('oda', 'mekân / oda'),
    'w02116': ('düzen', 'düzen / rejim / mod'),
    'w02120': ('perde', 'perde / eylem / tutanak'),
    'w02135': ('resim', 'çizim / resim'),
    'w02141': ('silah', 'alet / silah'),
    'w02162': ('bilmece', 'bilmece / muamma'),
    'w02177': ('sayı (dergi) / yayın', 'mezuniyet / sayı (dergi) / yayın'),
    'w02203': ('kovalamak', 'kovalamak / (hızlı) sürmek'),
    'w02206': ('uydu', 'uydu / yol arkadaşı'),
    'w02209': ('ret', 'ret / vazgeçme'),
    'w02210': ('ayva tüyü', 'hafif tüy / tüycük'),
    'w02218': ('zincir', 'zincir / (dağ) sırası'),
    'w02222': ('ziyaret etmek', 'ziyaret etmek / devam etmek'),
    'w02233': ('eksiklik', 'eksiklik / dezavantaj'),
    'w02237': ('dağarcık', 'yedek / stok / (kelime) dağarcığı'),
    'w02243': ('düzensizlik', 'dağınıklık / düzensizlik'),
    'w02246': ('ofis', 'büro / ofis'),
    'w02259': ('otomat', 'otomat / otomatik silah'),
    'w02260': ('artış', 'artış / terfi'),
    'w02262': ('yakalamak', 'yetişmek / yakalamak'),
    'w02264': ('onur', 'onur / üstünlük'),
    'w02265': ('bir araya getirmek', 'bir araya getirmek / indirgemek'),
    'w02271': ('betimleme', 'tasvir / tarif'),
    'w02272': ('cet', 'ata'),
    'w02275': ('komşu', 'komşu (kadın) / oda arkadaşı'),
    'w02283': ('açık', 'açık / aydınlık / parlak'),
    'w02286': ('hediye etmek', 'hediye etmek / vermek'),
    'w02292': ('ince dal', 'budak / ince dal'),
    'w02298': ('rock', 'rock (müzik) / kader'),
    'w02315': ('işe yaramak', 'işe yaramak / uygun olmak'),
    'w02335': ('etrafından dolaşmak', 'dolaşmak / geride bırakmak'),
    'w02359': ('metot', 'yöntem'),
    'w02383': ('düz', 'düz / eşit'),
    'w02391': ('yıldırım', 'yıldırım / şimşek / fermuar'),
    'w02409': ('başarı', 'başarı / ulaşma'),
    'w02411': ('battaniye', 'battaniye / yorgan'),
    'w02414': ('vurmak', 'vurmak / (kapı) çalmak'),
    'w02421': ('elmas', 'pırlanta'),
    'w02445': ('gövde (ağaç)', 'gövde / namlu'),
    'w02447': ('yatırmak', 'yatırım yapmak / koymak / katmak'),
    'w02451': ('ateş', 'sıcak / ateş'),
    'w02452': ('meydan', 'meydan / alan'),
    'w02453': ('bilezik', 'bilezik / bileklik'),
    'w02464': ('bileşim / içindekiler', 'bileşim / kadro'),
    'w02465': ('uçurtma / ejderha (masal)', 'yılan / ejderha'),
    'w02472': ('liman', 'liman / (bağlantı) portu'),
    'w02479': ('figür', 'figür / şekil'),
    'w02488': ('oluşturmak', 'oluşturmak / (miktar) tutmak'),
    'w02500': ('çar', 'çar / hükümdar'),
    'w02502': ('teslim etmek', 'teslim etmek / (sınava) girmek / kiraya vermek'),
    'w02507': ('trafik sıkışıklığı', 'trafik sıkışıklığı / tıkaç / mantar'),
    'w02515': ('kemer', 'kemer / kuşak / bel'),
    'w02519': ('başarmak', 'başarmak / talep etmek'),
    'w02526': ('savunucu', 'savunucu / defans oyuncusu'),
    'w02531': ('amatör', 'amatör / meraklı'),
    'w02532': ('varış', 'varış / gelir'),
    'w02552': ('patika', 'patika / yol'),
    'w02558': ('tel', 'tel / kablo'),
    'w02568': ('doğrulama', 'onay / doğrulama'),
    'w02584': ('ilişkilendirmek', 'bağlamak / ilişkilendirmek'),
    'w02591': ('teslim etmek / götürmek', 'teslim etmek / (rahatsızlık) vermek'),
    'w02599': ('memleket', 'vatan / memleket'),
    'w02606': ('acımak', 'sempati duymak / acımak'),
    'w02639': ('alet', 'cihaz / alet'),
    'w02660': ('kesmek', 'kesmek / oymak'),
    'w02662': ('ödül', 'prim / ikramiye / ödül'),
    'w02690': ('değer', 'maliyet / değer'),
    'w02704': ('hitap', 'hitap / muamele / kullanım'),
    'w02714': ('hükümdar', 'hükümdar / efendi'),
    'w02719': ('kur yapmak', 'bakmak / kur yapmak'),
    'w02726': ('klasör', 'klasör / dosya'),
    'w02729': ('toprak', 'toprak / zemin'),
    'w02731': ('kelebek', 'kelebek / papyon'),
    'w02736': ('susuzluk', 'susuzluk / özlem'),
    'w02754': ('nakliye', 'ulaşım / taşıt / nakliye'),
    'w02778': ('sonuç', 'soruşturma / sonuç'),
    'w02790': ('bağlı kalmak', 'uymak / bağlı kalmak'),
    'w02797': ('moda', 'modaya uygun / moda'),
    'w02810': ('ele geçirme', 'ele geçirme / kavrama'),
    'w02822': ('ambar', 'ambar / kulübe'),
    'w02838': ('rapor', 'rapor / sunum'),
    'w02852': ('kurt', 'solucan / kurtçuk'),
    'w02855': ('düzeltme', 'düzeltme / iyileşme'),
    'w02873': ('genel', 'genel / ana'),
    'w02892': ('jeton', 'jeton / püf noktası'),
    'w02901': ('bakış açısı', 'perspektif / bakış açısı / beklenti'),
    'w02908': ('pratik', 'uygulama / pratik / staj'),
    'w02912': ('onarım', 'onarım / yeniden inşa'),
    'w02920': ('tırmanmak', 'tırmanmak / girmek'),
    'w02924': ('sınır', 'kenar / eşik / sınır'),
    'w02925': ('toplamak', 'toplamak / (kilo) almak / (numara) çevirmek'),
    'w02941': ('izleme', 'izleme / görüntülenme'),
    'w02947': ('kozalak / şişlik', 'kozalak / şişlik / önemli kişi'),
    'w02966': ('kazanmak', 'fethetmek / kazanmak'),
    'w02985': ('parfüm', 'parfüm / ruhlar'),
    'w02994': ('dışarı çıkarmak', 'dışarı çıkarmak / (çıktı) vermek'),
    'w03006': ('soğan', 'soğan / yay (silah)'),
    'w03022': ('sürüngen', 'alçak / sürüngen'),
    'w03024': ('grafik', 'grafik / çizelge'),
}

EXTR = {
    'w02017': ("Ali'nin dedesi tostçuydu.", "Ali'nin dedesi tost hazırlar ve satardı."),
    'w02018': ('Foruma üye alımı durdurulmalı.', 'Foruma katılımcı alımı durdurulmalı.'),
    'w02076': ('Öğretmenleri ne kadar cinsel bir güvensizlik öğretmiş onlara.', 'Öğretmenleri onlara bedene karşı ne büyük bir güvensizlik öğretmiş!'),
    'w02153': ('Silahları vardı.', 'Tüfekleri vardı.'),
    'w02166': ('Kelle sağ olsun da külah bulunur.', 'Önemli olan sağlıklı olmak, iş de bulunur.'),
    'w02170': ('Ortalığı yakıyorsun.', 'Harika görünüyorsun.'),
    'w02202': ('O, yabancı dil yeteneğinden faydalanabileceği bir iş arıyor.', 'O, yabancı dil bilgisinden yararlanabileceği bir iş arıyor.'),
    'w02225': ('Foruma üye alımı durdurulmalı.', 'Foruma katılımcı alımı durdurulmalı.'),
    'w02235': ('Allah kerimdir ama kerimin kuyusu derindir.', 'Tanrı merhametlidir ve merhametinin kuyusu ne kadar derindir.'),
    'w02243': ('Hava ağır, odam tam bir enkazdı.', 'Odada nefes alacak hava yoktu, her yer dağınıktı.'),
    'w02267': ('Hık demiş babasının burnundan düşmüş.', 'Babasına tıpatıp benziyor.'),
    'w02306': ('Yüzsüze yüzsüz olacaksın.', 'Ona aynı karşılığı ver.'),
    'w02320': ('Bu kek un, süt, yumurta ve şeker içerir.', 'Bu pasta un, süt, yumurta ve şeker içerir.'),
    'w02358': ('ve şöyle düşünür, "Bir yerde rolün de bitmesi gerekir."', 'O düşünür: "Bu prova bir gün bitmek zorunda."'),
    'w02359': ('Bizim sunduğumuz çözümün iki temel avantajı var.', 'Sunduğumuz yöntemin iki temel avantajı var.'),
    'w02381': ('Şimdi o tebessüm, mesleki çevrede, "aldatıcı sevinç" olarak biliniyor.', 'Ticarette böyle bir gülümseme "aptalı kandırdım!" diye bilinir.'),
    'w02435': ('Facebook yöneticileri ile yakında bir görüşmem var.', 'Yakında Facebook genel merkezinde bir toplantım var.'),
    'w02447': ('Neden işe kendinizden bir şeyler katmamak?', 'Neden işe kendinizden bir şeyler katmıyorsunuz?'),
    'w02472': ('ve bütün bu renkler alttaki bir ana hazneden çıkıyor.', 'Ve bütün renkler alttaki merkezi porttan geçiyor.'),
    'w02495': ('Birinin beni rahatsız etmesini sevmiyorum.', 'Birinin dikkatimi dağıtmasından hoşlanmıyorum.'),
    'w02505': ("Ali'nin dedesi hac malzemecisiydi.", "Ali'nin dedesi dinî eşya satardı."),
    'w02566': ('Tabii ki, adalet sistemi onların suçunu herkesin bildiği eski suçlardan kabul ediyor.', 'Elbette ceza adaleti onları sıradan dolandırıcılar olarak görür.'),
    'w02594': ('Gömüleri gizli bir yere saklamamız gerekiyor.', 'Ganimeti gizli bir yere saklamamız gerekiyor.'),
    'w02623': ("Tom'un tam bir deste ödenmemiş park biletleri var.", "Tom'un ödenmemiş bir yığın park cezası var."),
    'w02628': ('Ve sıraya girin, tek bir çizgi halinde sıralanın.', 'Sonra kendinizi bağlayıp bağlı hâlde sırada durursunuz.'),
    'w02634': ("Ali'nin dedesi turşucuydu.", "Ali'nin dedesi turşu ve salamura satıcısıydı."),
    'w02659': ('Seçimin resmî olmayan sonuçları açığa çıktı.', 'Seçimin ön sonuçları belli oldu.'),
    'w02687': ('Bir nevi alçıya almak gibi.', 'Mecazi olarak, kırıkta olduğu gibi atel uygulayacağız.'),
    'w02756': ('Sonunda rahip, yeniden inşa için bana güven duydu.', 'Sonunda rahip kilisenin yeniden inşasını bana emanet etti.'),
    'w02763': ("Ali'nin dedesi beyaz eşya tamircisiydi.", "Ali'nin dedesi ev aletleri tamir ustasıydı."),
    'w02806': ('Şefkatin motivasyon olarak bileşeni daha iyiye ulaşmak için hırs yaratıyor.', 'Empatinin motivasyon bileşeni, ortak iyiliğe yönelik çabaya katkıda bulunur.'),
    'w02815': ('Aslanın üzerinden bir tabaka sıyırabilirim.', 'Ve öldürülmemiş bir aslanın derisini yüzebilirim.'),
    'w02822': ('Bir İncil satıcısı, tek bacaklı bir filozofu bir ahıra çekiyor.', 'Bir İncil satıcısı, felsefe yapan tek bacaklı bir kızı kulübeye çekiyor.'),
    'w02833': ('LN: Bazılarının da bir timsahınkine benzer burunları vardı.', 'LN: Diğerleri ise timsah gibi bir suratlıydı.'),
    'w02836': ('Düğüne bayram koçu gibi gelmiş.', 'Düğüne aşırı süslenmiş halde geldi.'),
    'w02868': ('İşte, şimdi size tarihin ispatı, o yıldan bir fotoğrafım.', 'Tarihsel doğruluk için işte o yıldan bir fotoğrafım.'),
    'w02891': ('Görünen o ki beşinci sınıftaki içgüdülerim doğruydu.', 'Beşinci sınıftaki önsezilerim beni yanıltmadı:'),
    'w02920': ('Bu volkanın en içteki kısmına inmek istiyorum.', 'Bu yanardağın tam içine girmek istiyorum.'),
    'w02944': ('İçi bombacıklarla dolu büyük bir hazne.', 'Bu, küçük kalibreli bombalarla dolu büyük bir bidon.'),
    'w02947': ('Biz bir numarayız, Birleşik Devletler büyük ve iş başında.', 'Biz bir numarayız. Birleşik Devletler önemli bir isimdir.'),
    'w02959': ('Yapılacak iş dediğin atla deve değil, altı üstü güç ile yer değişiminin çarpımına eşit.', 'İş kurt değil, kuvvetin yer değiştirmeyle çarpımıdır.'),
    'w03005': ('O kadar sıcaktı ki ceketimi çıkardım.', 'O kadar sıcaktı ki yağmurluğumu çıkardım.'),
}

EXDROP = {
    'w02362': 'Зелёно-хмурные глаза во мрачных патрицах травы — прочь.',
}

DROP = {
    'w02255': 'побе́да',
}

FIELDS = {'w02123': {'ru': ('мексика', 'Мексика')}}
