# -*- coding: utf-8 -*-
"""Dış inceleme raporu, grup 4."""

FIXES = {
    'w03109': ('lider', 'lider / şef'),
    'w03127': ('dinmek', 'durmak / kesilmek'),
    'w03128': ('alay', 'ironi'),
    'w03138': ('akıtmak', 'dökmek / akıtmak'),
    'w03164': ('araştırma', 'öğrenme / inceleme'),
    'w03168': ('düzenli', 'düzenli / özenli'),
    'w03175': ('belirtmek', 'belirtmek / kutlamak'),
    'w03194': ('katkı', 'katkı / mevduat'),
    'w03203': ('kanun', 'kanun / kodeks'),
    'w03217': ('lavabo', 'lavabo / deniz kabuğu'),
    'w03226': ('ilerlemek', 'gelişmek / ilerlemek'),
    'w03253': ('kazanmak', 'edinmek / satın almak'),
    'w03263': ('tugay', 'ekip / tugay'),
    'w03269': ('oditoryum', 'derslik / dinleyici kitlesi'),
    'w03284': ('öğretmen', 'öğretim görevlisi / eğitmen'),
    'w03285': ('indirmek', 'indirmek / (tetiği) çekmek'),
    'w03298': ('koca', 'eş / koca'),
    'w03302': ('öğrenci', 'kız öğrenci'),
    'w03304': ('âlem', 'krallık / egemenlik'),
    'w03320': ('anne', 'anne (konuşma dili)'),
    'w03337': ('fısıldamak', 'ipucu vermek / önermek'),
    'w03340': ('basmak', 'yazmak (daktilo) / basmak'),
    'w03347': ('kat', 'katman / tabaka'),
    'w03353': ('batarya', 'pil / radyatör / (güneş) paneli'),
    'w03360': ('görünüş', 'görünürlük / görünüş'),
    'w03376': ('çalıştırmak', 'eğitmek / antrenman yaptırmak'),
    'w03385': ('menteşe', 'ilmek / menteşe'),
    'w03388': ('kabul etmek', 'izin vermek / varsaymak'),
    'w03390': ('her şeye gücü yeten', 'her şeye kadir'),
    'w03395': ('yüksek', 'yüksekte / yükseğe'),
    'w03410': ('çağırmak', 'çağırmak / teşvik etmek'),
    'w03427': ('kuduz', 'çılgın / kuduz'),
    'w03438': ('kırmak', 'kırmak / bölmek'),
    'w03441': ('tehlikeli', 'riskli'),
    'w03448': ('rehin vermek', 'yerleştirmek / temel atmak / rehin vermek'),
    'w03450': ('efsane', 'mit'),
    'w03455': ('suikast', 'suikast girişimi'),
    'w03466': ('gösterim', 'gösteri / sergileme'),
    'w03491': ('karşı', 'zıt / karşı'),
    'w03499': ('yakmak', 'yakmak / coşmak'),
    'w03530': ('kınamak', 'kınamak / mahkûm etmek'),
    'w03542': ('ocak (fırın)', 'ocak / levha'),
    'w03557': ('devir', 'döngü / çevrim'),
    'w03558': ('dürtü', 'dürtü / sinyal'),
    'w03561': ('nüsha', 'nüsha / örnek (birey)'),
    'w03564': ('azaltma', 'azalma / kısaltma'),
    'w03617': ('atamak', 'atamak / reçete etmek'),
    'w03633': ('sancı (doğum)', 'çatışma / (doğum) sancısı'),
    'w03642': ('lakap', 'lakap / (hayvan) adı'),
    'w03660': ('oynamak', 'canlandırmak / kura çekmek'),
    'w03662': ('sızdırmak', 'boşaltmak / sızdırmak'),
    'w03668': ('lazımlık', 'saksı / lazımlık'),
    'w03719': ('kesin', 'kararlı / kesin'),
    'w03729': ('rahat', 'sıcak / samimi / rahat'),
    'w03738': ('musluk', 'musluk / vinç'),
    'w03776': ('ince tabaka', 'film / ince tabaka'),
    'w03791': ('muayene etmek', 'incelemek / muayene etmek'),
    'w03822': ('oturmak', 'ikamet etmek / yaşamak'),
    'w03827': ('itiş', 'itme / sarsıntı / itici güç'),
    'w03876': ('hava atmak', 'hava atmak / (kendine) sormak'),
    'w03880': ('sallanmak', 'sallanmak / aylak aylak dolaşmak'),
    'w03902': ('antika', 'eski / antika'),
    'w03941': ('gelenek', 'âdet / gelenek'),
    'w03961': ('bela', 'kırbaç / bela'),
    'w03969': ('şikâyet', 'şikâyet / iddia'),
    'w03998': ('fırlatmak', 'fırlatmak / ihmal etmek'),
    'w04003': ('boşaltmak', 'tahliye etmek'),
    'w04016': ('bağlantı', 'bağlantı / atıf / sürgün'),
}

EXTR = {
    'w03102': ('Benim çalacağım parçanın adı "Fête de la Belle."', 'Islıkla çalacağım melodinin adı "Güzelin Bayramı".'),
    'w03126': ('Larva halini aldığımda, diğer sürüklenenlerin arasına katıldım.', 'İribaş olduğumda başıboşlara katıldım.'),
    'w03142': ('Ali haddini hududunu bilmiyor.', 'Ali kendini ayık kafayla değerlendiremiyor.'),
    'w03172': ('Tom ve Mary ile birlikte güzel bir zaman geçirdiler.', 'Tom ve Mary birlikte güzel vakit geçirdiler.'),
    'w03269': ('Öğretmen öğrencilerin konferans salonundan ayrılmasına izin vermedi.', 'Öğretmen öğrencilerin dersliği terk etmesine izin vermedi.'),
    'w03284': ('Onların her ikisi de iyi öğretmenlerdir.', 'İkisi de iyi öğretim görevlileridir.'),
    'w03292': ('Orada evinden 90 km uzakta yaşayan kararlı bir öğrenci var.', 'Bu tavan arasında, evinden 60 mil uzakta yaşayan çalışkan bir öğrenci var.'),
    'w03321': ('Sağ kolum askıda.', 'Sağ kolum sargılı.'),
    'w03448': ('Etik açıdan doğru bir tasarım yapmayı amaçladık.', 'Bu yüzden bunu doğrudan tasarımın içine yerleştirmek istedik.'),
    'w03455': ('Suikast, trajik ve korkunç olarak belirtildi.', 'Suikast girişimi trajik ve korkunç olarak nitelendirildi.'),
    'w03489': ('Kadın para kesesini vermezse haydutlar onun canına kıyacaklardı; ya parası ya da canı.', 'Haydutlar ya cüzdanını ya canını ister; kadınlar ise ikisini de.'),
    'w03649': ('Ali haddini hududunu bilmiyor.', 'Ali kendini ayık kafayla değerlendiremiyor.'),
    'w03706': ("Mars'ı ve ötesini düşledin mi?", "Mars'a, yıldızlara bir keşif seferi düşledin mi?"),
    'w03816': ('Terapistin dediğin gibi: "Bugün nasıl hissediyorsun?"', 'İşte hekimin sorusu tam olarak budur: "Bugün kendinizi nasıl hissediyorsunuz?"'),
    'w03880': ('Şehrin göbeğinde, tatlı hayatın nimetlerinde faydalandı.', 'Şehirde aylak aylak dolaşıp eğleniyor ve yüksek sosyetenin tadını çıkarıyordu.'),
    'w03998': ('O görevini terk etti.', 'O görevlerini ihmal etti.'),
    'w04003': ('Sonuçta ben kaybettim ve havayoluyla taşındım.', 'Tartışmayı kaybettim ve beni uçakla tahliye ettiler.'),
}

EXDROP = {
}

DROP = {
}

FIELDS = {'w03382': {'ru': ('вьетнам', 'Вьетнам')}}
