# -*- coding: utf-8 -*-
"""Dış inceleme raporu, grup 1."""

FIXES = {
    'w00083': ('ki', '-en / -an (ilgi zamiri) / hangi'),
    'w00096': ('delikanlı', 'delikanlı / erkek arkadaş'),
    'w00109': ('bakmak', 'bakmak / izlemek'),
    'w00160': ('karı', 'eş / karı'),
    'w00163': ('kardeş', 'erkek kardeş'),
    'w00179': ('olmak', 'meydana gelmek / olmak'),
    'w00194': ('ise', 'ama / oysa'),
    'w00201': ('pahalı', 'pahalı / sevgili'),
    'w00222': ('durum', 'durum / olay / vesile'),
    'w00226': ('tarih', 'tarih / hikâye'),
    'w00272': ('mesut', 'mutlu'),
    'w00303': ('ilişki', 'ilişki / tutum'),
    'w00304': ('yer', 'toprak / yer / dünya'),
    'w00313': ('kabul etmek', 'kabul etmek / (duş) almak'),
    'w00327': ('heyecanlanmak', 'endişelenmek / heyecanlanmak'),
    'w00329': ('ışık', 'ışık / dünya'),
    'w00335': ('berbat', 'korkunç / berbat'),
    'w00340': ('üzerinden', 'sonra / üzerinden'),
    'w00341': ('doğru', 'sadık / doğru'),
    'w00355': ('efendi', 'bay / efendi'),
    'w00392': ('koşmak', 'koşmak / kaçmak'),
    'w00394': ('bağ', 'bağlantı / iletişim'),
    'w00399': ('karar', 'karar / çözüm'),
    'w00403': ('seçenek', 'seçim'),
    'w00410': ('temsil etmek', 'temsil etmek / sunmak / hayal etmek'),
    'w00416': ('görünmek', 'ortaya çıkmak / belirmek'),
    'w00417': ('yönetmek', 'götürmek / yönetmek / davranmak'),
    'w00420': ('aynı fikirde', 'razı / aynı fikirde / ünsüz'),
    'w00424': ('başkan', 'cumhurbaşkanı / başkan'),
    'w00426': ('enteresan', 'ilginç'),
    'w00435': ('kabul etmek', 'kabul etmek / (duş) almak'),
    'w00436': ('tanıtmak', 'tanıtmak / sunmak / hayal etmek'),
    'w00449': ('tümüyle', 'toplam / yalnızca'),
    'w00460': ('tutunmak', 'tutunmak / (uzak) durmak'),
    'w00475': ('genel', 'genel / ortak'),
    'w00495': ('imge', 'imge / görüntü / tarz'),
    'w00497': ('cevap vermek', 'cevap vermek / sorumlu olmak'),
    'w00520': ('ameliyat', 'ameliyat / operasyon'),
    'w00523': ('hür', 'serbest / boş / özgür'),
    'w00535': ('bilmek', 'becermek / -ebilmek'),
    'w00559': ('son', 'son / uç'),
    'w00573': ('öğüt', 'öğüt / konsey'),
    'w00576': ('kız arkadaş', 'kız arkadaş / (kadın) arkadaş'),
    'w00579': ('yüksek', 'yüksek / uzun boylu'),
    'w00581': ('oturmak', 'oturmak / binmek'),
    'w00583': ('yumurcak', 'ufaklık / bebek'),
    'w00586': ('hafif', 'hafif / kolay'),
    'w00588': ('bulmak', 'uydurmak / icat etmek'),
    'w00593': ('konuşma', 'konuşma / söz'),
    'w00608': ('ortadan kalkmak', 'kaybolmak / yok olmak'),
    'w00610': ('yaklaşmak', 'yaklaşmak / uymak'),
    'w00611': ('teklif', 'teklif / cümle'),
    'w00626': ('giyim', 'giysi / kıyafet'),
    'w00629': ('kavram', 'kavram / fikir'),
    'w00630': ('netice', 'sonuç'),
    'w00632': ('özel', 'kişisel'),
    'w00641': ('reddetmek', 'reddetmek / vazgeçmek'),
    'w00653': ('darbe', 'darbe / vuruş'),
    'w00657': ('çeşitli', 'farklı / çeşitli'),
    'w00658': ('bir defa', 'bir gün / bir zamanlar'),
    'w00659': ('ispat', 'kanıt'),
    'w00662': ('karmaşık', 'karmaşık / zor'),
    'w00665': ('yoksa', 'yoksa / başka türlü'),
    'w00670': ('tedbir', 'ölçü / önlem'),
    'w00683': ('kapamak', 'kapatmak'),
    'w00691': ('doküman', 'belge'),
    'w00704': ('endişelenmek', 'endişelenmek / atlatmak / üzülmek'),
    'w00716': ('davranmak', 'hareket etmek / davranmak / etki etmek'),
    'w00718': ('hakimiyet', 'iktidar / yetki / güç'),
    'w00719': ('pişirmek', 'pişirmek / hazırlamak'),
    'w00743': ('patron', 'şef / patron'),
    'w00744': ('keşfetmek', 'bulmak / fark etmek'),
    'w00746': ('cins', 'cins / soy'),
    'w00755': ('yoksul', 'yoksul / zavallı'),
    'w00766': ('akım', 'akım / akış / süre'),
    'w00779': ('evlilik', 'evlilik / kusurlu ürün'),
    'w00798': ('bırakmak', 'terk etmek / ayrılmak'),
    'w00799': ('mükemmel', 'mükemmel / tam'),
    'w00800': ('hakim', 'yargıç / hakem'),
    'w00805': ('hizmet', 'hizmet / askerlik'),
    'w00807': ('atmak', 'atmak / bırakmak'),
    'w00815': ('nitelik', 'nitelik / kalite'),
    'w00820': ('işaret', 'sinyal / işaret'),
    'w00834': ('arayış', 'arama / araştırma'),
    'w00840': ('görünmek', 'görünmek / gibi gelmek'),
    'w00842': ('yol açmak', 'çağırmak / yol açmak'),
    'w00878': ('yönetmek', 'yönetmek / düzeltmek'),
    'w00883': ('işlemek', 'gerçekleştirmek / işlemek'),
    'w00886': ('borç', 'borç / görev'),
    'w00901': ('işgal etmek', 'işgal etmek / (yer) almak / ödünç almak'),
    'w00904': ('plana almak', 'planlamak'),
    'w00923': ('gözetlemek', 'gözlemlemek / izlemek'),
    'w00933': ('endişelendirmek', 'rahatsız etmek / endişelendirmek'),
    'w00946': ('kalın kafalı', 'künt / kalın kafalı'),
    'w00955': ('açı', 'köşe / açı'),
    'w00959': ('beden', 'gövde / bel / kamp'),
    'w00960': ('endişelendirmek', 'endişelendirmek / heyecanlandırmak'),
    'w00963': ('daire', 'daire / çevre'),
    'w00969': ('sıra', 'hamle / gidiş'),
    'w00987': ('gerektirmek', 'talep etmek / gerektirmek'),
}

EXTR = {
    'w00070': ('Sana bunun dışında bir şey vereceğim.', 'Sana bunun dışında her şeyi vereceğim.'),
    'w00078': ('Babam gençken yakışıklı olmalı!!', 'Babam gençken yakışıklıymış olmalı.'),
    'w00141': ('O her zaman sessiz kaldı.', 'O bütün zaman boyunca tek kelime etmedi.'),
    'w00186': ('Bu kabilede kimin yaşayıp kimin yaşamayacağına o karar verir.', 'Bu kolonide yaşam ve ölüm onun elinde.'),
    'w00289': ('Yapılacak iş dediğin atla deve değil, altı üstü güç ile yer değişiminin çarpımına eşit.', 'İş kurt değil, kuvvetin yer değiştirmeyle çarpımıdır.'),
    'w00333': ('Babam gençken yakışıklı olmalı!!', 'Babam gençken yakışıklıymış olmalı.'),
    'w00451': ('Kelle sağ olsun da külah bulunur.', 'Önemli olan sağlıklı olmak, iş de bulunur.'),
    'w00531': ('Bize gelin. Allah ne verdiyse yeriz.', 'Bize gelin. Elimizde ne varsa onunla ağırlarız.'),
    'w00588': ('Kitabımın konusunu buldum.', 'Kitabımın konusunu ben kurguladım.'),
    'w00592': ('Kitapları sevin, onlar hayatın karmaşasında ayakta kalmanıza yardımcı olurlar.', 'Kitapları sevin: hayatın karmaşasını anlamanıza yardımcı olur.'),
    'w00614': ("Hakkıdır, Hakk'a tapan, milletimin istiklâl!", "Özgürlük, Tanrı'ya tapan halkımın hakkıdır."),
    'w00630': ('Muayene sonuçları gelecek haftaya hazır olacak.', 'Muayene sonuçları bir hafta içinde hazır olacak.'),
    'w00932': ('Bize gelin. Allah ne verdiyse yeriz.', 'Bize gelin. Elimizde ne varsa onunla ağırlarız.'),
    'w00970': ('Tom zengin bir aileden geldiğini iddia etti.', 'Tom zengin bir ailede büyüdüğünü iddia etti.'),
}

EXDROP = {
    'w00045': 'У всех форм жизни есть инстинктивное стремление выжить.',
    'w00061': 'У всех форм жизни есть инстинктивное стремление выжить.',
    'w00076': 'Тому должно быть по меньшей мере тридцать лет.',
    'w00100': 'Уж не ядовит.',
    'w00152': 'Для многих женщин любовь стоит на первом месте.',
    'w00571': 'Я надеюсь, что она вернётся к шести часам.',
}

DROP = {
}
