# -*- coding: utf-8 -*-
"""Dış inceleme raporu, grup 2."""

FIXES = {
    'w01022': ('yer', 'zemin / cinsiyet'),
    'w01027': ('taşımak', 'taşımak / üstlenmek'),
    'w01035': ('alan', 'alan / tarla'),
    'w01062': ('tiz', 'çınlayan / ötümlü'),
    'w01075': ('açıklama', 'açıklama / başvuru'),
    'w01078': ('tamamen', 'gayet / oldukça'),
    'w01081': ('uğraş', 'uğraş / ders'),
    'w01094': ('kutu', 'kutu / çekmece / sandık'),
    'w01095': ('araç', 'araç / yöntem / madde'),
    'w01099': ('medikal', 'tıbbi'),
    'w01111': ('şef', 'şef / amir'),
    'w01123': ('akılsızlık', 'aptallık / saçmalık'),
    'w01127': ('belâ', 'sıkıntı / felaket'),
    'w01130': ('tanımak', 'tanımak / öğrenmek'),
    'w01143': ('basınç', 'basınç / baskı'),
    'w01196': ('avlu', 'avlu / bahçe'),
    'w01200': ('meydan okuması', 'meydan okuma / çağrı'),
    'w01213': ('ağrımak', 'hasta olmak / ağrımak'),
    'w01218': ('davranışlar', 'davranış'),
    'w01228': ('oturmak', 'çömelmek / oturmak'),
    'w01231': ('yabancı', 'yabancı / başkasının'),
    'w01233': ('artı', 'artı / avantaj'),
    'w01260': ('ev', 'eve ait / evcil / evde yapılan'),
    'w01272': ('yükselmek', 'yükselmek / tırmanmak'),
    'w01276': ('ayrılmak', 'yola çıkmak / hareket etmek'),
    'w01278': ('sohbet etmek', 'gevezelik etmek / sohbet etmek'),
    'w01279': ('öz', 'öz / ana'),
    'w01283': ('görüş', 'görme / görüş'),
    'w01296': ('alçak', 'alçak / düşük'),
    'w01303': ('yapmak', 'inşa etmek / kurmak'),
    'w01307': ('reddetmek', 'reddetmek / vazgeçmek'),
    'w01308': ('bölge', 'bölge / toprak'),
    'w01310': ('libre', 'pound / sterlin'),
    'w01321': ('denetim', 'kontrol / denetim'),
    'w01332': ('başarmak', 'başa çıkmak / idare etmek'),
    'w01336': ('güvenmek', 'güvenmek / hesaplamak'),
    'w01338': ('fikir', 'gösteri / temsil / fikir'),
    'w01347': ('makale', 'makale / madde'),
    'w01352': ('tırmanmak', 'tırmanmak / karışmak'),
    'w01361': ('cihaz', 'cihaz / düzen'),
    'w01367': ('tereyağı', 'yağ / tereyağı'),
    'w01379': ('ağa', 'bey / toprak sahibi'),
    'w01387': ('öpme', 'öpücük'),
    'w01389': ('izin vermek', 'izin vermek / (hata) yapmak'),
    'w01390': ('görev', 'görev / problem'),
    'w01391': ('kalem, kapı kolu (kulp anlamı)', 'tükenmez kalem / kulp / sap'),
    'w01396': ('işçi', 'işçi / çalışma (sıfat)'),
    'w01398': ('tutmak', 'yakalamak / (balık) tutmak'),
    'w01401': ('yanaşmak', 'yaklaşmak'),
    'w01406': ('gemi', 'gemi / tekne'),
    'w01408': ('pazar', 'pazar / piyasa'),
    'w01423': ('anlamak', 'tahmin etmek / akıl etmek'),
    'w01425': ('vakitlice', 'zamanında'),
    'w01436': ('iş arkadaşı', 'partner / iş arkadaşı'),
    'w01441': ('versiyon', 'sürüm / versiyon'),
    'w01442': ('almak', 'girişmek / tutmak'),
    'w01443': ('oluşturmak', 'yaratmak'),
    'w01453': ('boğulmak', 'batmak / boğulmak'),
    'w01472': ('kıç', 'kıç / arka'),
    'w01473': ('görev', 'görev / makam / gönderi'),
    'w01476': ('program', 'aktarma / yayın'),
    'w01486': ('çarşamba', 'çarşamba / çevre'),
    'w01488': ('kavanoz', 'kavanoz / teneke kutu'),
    'w01491': ('ürkmek', 'korkmak'),
    'w01500': ('yaratık', 'yaratık / yaratma'),
    'w01516': ('belirti', 'belirti / özellik'),
    'w01525': ('hareket', 'davranış / eylem'),
    'w01526': ('işaret etmek', 'belirtmek / işaret etmek'),
    'w01532': ('dışarı çıkarmak', 'dışarı çıkarmak / (karar) vermek'),
    'w01534': ('yargılamak', 'yargılamak / değerlendirmek'),
    'w01537': ('durmak', 'durmak / konaklamak'),
    'w01539': ('görev', 'görev / pozisyon'),
    'w01544': ('torba', 'çuval / torba'),
    'w01550': ('adli', 'adli / yargısal'),
    'w01560': ('banyo', 'küvet / banyo'),
    'w01562': ('şube', 'şube / bölüm'),
    'w01571': ('sesini kesmek', 'susmak'),
    'w01573': ('temel', 'temel / neden'),
    'w01576': ('hediye', 'hediye / yetenek'),
    'w01577': ('farketmek', 'fark etmek'),
    'w01581': ('cisim', 'nesne / alan'),
    'w01584': ('dövüş', 'kavga'),
    'w01587': ('şişman', 'kalın / şişman'),
    'w01589': ('birleşik', 'tek / birleşik'),
    'w01623': ('itiraf', 'itiraf / kabul'),
    'w01651': ('gülüş', 'gülümseme'),
    'w01652': ('kapamak', 'kapatmak'),
    'w01673': ('muhteşem', 'nefis / harika'),
    'w01676': ('getirmek', 'getirmek / yol açmak'),
    'w01685': ('ayakkabı', 'bot / ayakkabı'),
    'w01694': ('yüzyıl', 'yüzyıl / çağ'),
    'w01695': ('sıcaklık', 'sıcaklık / ateş'),
    'w01719': ('teyze', 'teyze / hala'),
    'w01721': ('özen', 'özen / kaygı'),
    'w01731': ('küre', 'küre / top / balon'),
    'w01735': ('gülüş', 'kahkaha / gülme'),
    'w01742': ('sivri', 'sivri / keskin / acı'),
    'w01744': ('politik', 'siyasi'),
    'w01747': ('sefer', 'sefer / uçuş'),
    'w01751': ('açılış', 'açılış / keşif'),
    'w01754': ('seremoni', 'tören'),
    'w01762': ('fon,vakıf', 'fon / vakıf'),
    'w01763': ('içermek', 'içermek / açmak'),
    'w01781': ('füze', 'roket / füze'),
    'w01782': ('eksik', 'yetersiz'),
    'w01783': ('hayvan', 'yabani hayvan / canavar'),
    'w01784': ('akıllı', 'makul / akıllı'),
    'w01788': ('kabul', 'kabul / (ilaç) alma'),
    'w01804': ('bir araya getirmek', 'bir araya getirmek / götürmek'),
    'w01810': ('selamlamak', 'selamlamak / hoş karşılamak'),
    'w01819': ('filo', 'donanma / filo'),
    'w01822': ('başlatmak', 'başlatmak / fırlatmak'),
    'w01854': ('görünmek', 'görünmek / gelmek'),
    'w01861': ('bisküvi', 'bisküvi / kurabiye'),
    'w01863': ('girmek (bilgi), tanıtmak', 'uygulamaya koymak / (veri) girmek'),
    'w01878': ('büyük köpek', 'köpek / av köpeği'),
    'w01885': ('öneride bulunmak', 'tavsiye etmek'),
    'w01887': ('bozuk para', 'önemsiz şey / bozuk para'),
    'w01901': ('mobil', 'mobil / cep'),
    'w01909': ('hizmetçi', 'uşak / hizmetçi'),
    'w01910': ('top', 'top (silah)'),
    'w01914': ('koğuş (hastane)', 'koğuş / oda'),
    'w01917': ('hayran', 'hayran / taraftar'),
    'w01922': ('kir', 'çamur / kir'),
    'w01931': ('tartışmak', 'bahse girmek / tartışmak'),
    'w01947': ('tabak', 'tabak / (uydu) çanağı'),
    'w01969': ('çiğ', 'çiğ / nemli'),
    'w01974': ('sıkı', 'katı / sıkı'),
    'w01975': ('yazı tahtası', 'tahta / yazı tahtası'),
    'w01995': ('basit', 'basit / kolay'),
    'w02005': ('arızalanmak', 'kırılmak / bozulmak'),
    'w02007': ('araştırmak', 'soruşturmak / araştırmak'),
}

EXTR = {
    'w01010': ("Ali'nin dedesi salepçiydi.", "Ali'nin dedesi salep hazırlar ve satardı."),
    'w01043': ('Kelle sağ olsun da külah bulunur.', 'Önemli olan sağlıklı olmak, iş de bulunur.'),
    'w01078': ('Yeni evimden tamamen memnunum.', 'Yeni evimden gayet memnunum.'),
    'w01149': ('Trafiği de hesaba katacak olursak, bir saatten önce varamayız.', 'Trafiği hesaba katarsak en az bir saatte varırız.'),
    'w01316': ("Ali'nin dedesi gözlükçüydü.", "Ali'nin dedesi gözlük satar ve tamir ederdi."),
    'w01420': ('Söz konusu tarafa mensup olmaktan dolayı bir sorun yaşıyor musunuz?', 'Bu partiye mensup olmaktan dolayı bir sorun yaşıyor musunuz?'),
    'w01447': ('"Jonah Lehrer, sadece lanet olası bir sosyopat."', 'Ya da: "Jonah Lehrer lanet olası bir deli."'),
    'w01487': ('Ve elektrotlar yahut anten yardımıyla bu kasılmayı algılayıp kola hareket etmesini söylüyoruz.', 'Artık elektrotlar yardımıyla sinyali yakalayıp kolu hareket ettirebiliyoruz.'),
    'w01499': ("İlki David'in belirttiği insan belası.", "David'in fark ettiği ilk sorun insanın kötülüğüydü."),
    'w01534': ('Bana arkadaşını söyle, sana kim olduğunu söyleyeyim.', 'İnsan hakkında arkadaşlarına bakarak fikir edinilebilir.'),
    'w01542': ('Bu kek un, süt, yumurta ve şeker içerir.', 'Bu pasta un, süt, yumurta ve şeker içerir.'),
    'w01601': ("Mary'nin gülü o kadar güzel ki bir türlü doyamıyor.", 'Maria güzel güllerine bir türlü doyamıyor.'),
    'w01610': ('Mary sincaplar konusunda dünyanın önde gelen uzmanıdır.', 'Mary, proteinler konusunda dünyanın önde gelen uzmanıdır.'),
    'w01658': ('Mahkumlar arasında en hızlı büyüyen nüfus ise siyahi kadınlar.', 'Hapsedilenler arasında artan pay ise siyahi kadınlara aittir.'),
    'w01673': ('Piliç lezzetliydi.', 'Piliç nefisti.'),
    'w01691': ('(Alkışlar) Çok çılgınca! Şimdi --- (Gülüşmeler) Şaşırtıcı şeylerin her zaman olabileceğine inanırım.', '(Alkışlar) Saçmalık bu! (Gülüşmeler) Şaşırtıcı şeylerin sürekli yaşandığına inanıyorum.'),
    'w01702': ('Dün lunaparkta öğretmenime rastladım.', 'Dün kültür ve dinlenme parkında öğretmenime rastladım.'),
    'w01715': ('Gökyüzünden bakıldığında, nehir kocaman bir yılan gibi görünüyordu.', 'Yüksekten bakıldığında nehir kocaman bir yılana benziyordu.'),
    'w01721': ('Ağacı nem, insanı gam yer.', 'İnsanı yaşlandıran iş değil, kaygıdır.'),
    'w01741': ('Personelimiz üç iş günü içinde sizinle irtibat kuracaktır.', 'Temsilcimiz üç iş günü içinde sizinle iletişime geçecektir.'),
    'w01792': ('Hasta için en önemlisi vakitlice yapılacak bir doktor kontrolüdür.', 'Hasta için en önemlisi doktorun zamanında yapacağı bakımdır.'),
    'w01824': ('Tom yedek lastiği almak için bagajı açtı.', 'Tom yedek tekerleği almak için bagajı açtı.'),
    'w01849': ('Bir bardak kahve içti ve doğruca işe yollandı.', 'Bir fincan kahve içti ve işe koyuldu.'),
}

EXDROP = {
    'w01328': 'Положи книгу на верх шкафа.',
}

DROP = {
}
