# -*- coding: utf-8 -*-
"""Ucuncu tur dis inceleme raporu (2026-08-17).

Kaynak: review_11_b2.txt ... review_24_c1.txt parcalarinin tamami
(B2 + C1 katmani, ~5600 satir) elle ve model destekli iki asamali
taramadan gecirildi.

Raporun tespit ettigi baskin hata kalibi: dogru bir birinci anlamin
yanina virgulle alakasiz bir ikinci kelime eklenmesi ("avaz",
"mustakbel", "sofa", "ajine" gibi sozcukler onlarca kayitta tekrar
ediyor). Bu dosya raporun satirlarini tasiyor; kalibin taranmasi
sonucu bulunan ek kayitlar da buraya eklendi.

Her satirda Rusca kelime de yaziliyor: apply_fixes.py kimlik ile
kelime tutmuyorsa satira dokunmuyor.
"""

REPORT3_TR = {
    'w03987': ('раздеться', 'soyunmak'),
    'w04092': ('избирательный', 'seçimle ilgili, seçici'),
    'w04100': ('поражать', 'şaşırtmak, hayrete düşürmek'),
    'w04102': ('клинок', 'kılıç ağzı, bıçak ağzı'),
    'w04108': ('капелька', 'damlacık'),
    'w04110': ('круча', 'dik yamaç, uçurum'),
    'w04126': ('совпасть', 'aynı ana denk gelmek, çakışmak'),
    'w04131': ('критик', 'eleştirmen'),
    'w04132': ('окончить', 'bitirmek, tamamlamak'),
    'w04143': ('костёр', 'kamp ateşi, şenlik ateşi'),
    'w04144': ('опора', 'destek, dayanak'),
    'w04166': ('франк', 'frank (para birimi)'),
    'w04173': ('привязанность', 'bağlılık, sevgi'),
    'w04182': ('прикинуть', 'tahmin etmek, hesaplamak'),
    'w04188': ('забег', 'koşu, yarış turu'),
    'w04204': ('белка', 'sincap'),
    'w04207': ('верующий', 'imanlı, inanan'),
    'w04208': ('самочувствие', 'genel durum, hâl'),
    'w04213': ('воткнуть', 'saplamak, sokmak'),
    'w04218': ('образованный', 'eğitimli, okumuş'),
    'w04237': ('драть', 'yırtmak, parçalamak'),
    'w04256': ('передвижение', 'hareket, yer değiştirme'),
    'w04264': ('рассмотрение', 'inceleme, ele alma'),
    'w04269': ('гуд', 'iyi, tamam (argo)'),
    'w04281': ('вылет', 'kalkış, uçuş'),
    'w04322': ('раскусить', 'niyetini anlamak, çözmek'),
    'w04337': ('денежный', 'paralı, parasal'),
    'w04357': ('распространять', 'yaymak, dağıtmak'),
    'w04358': ('зонтик', 'şemsiye'),
    'w04373': ('затянуть', 'sıkmak, geciktirmek'),
    'w04380': ('симпатия', 'sempati, hoşlanma'),
    'w04383': ('склонность', 'eğilim, meyil'),
    'w04385': ('салют', 'askeri selam, havai fişek'),
    'w04390': ('переписка', 'yazışma, mektuplaşma'),
    'w04407': ('опускаться', 'alçalmak, düşmek'),
    'w04421': ('восприятие', 'algı, algılama'),
    'w04424': ('порочный', 'ahlaksız, sapkın'),
    'w04465': ('милосердный', 'merhametli, şefkatli'),
    'w04476': ('мех', 'kürk'),
    'w04487': ('злоба', 'kin, hınç'),
    'w04503': ('аспект', 'yön, açı'),
    'w04524': ('коль', 'eğer, ise'),
    'w04545': ('чудак', 'tuhaf adam, acayip tip'),
    'w04584': ('распознать', 'tanımak, tespit etmek'),
    'w04591': ('резинка', 'silgi, lastik bant'),
    'w04599': ('интрига', 'entrika, desise'),
    'w04664': ('остроумный', 'nükteli, zekice'),
    'w04683': ('катить', 'yuvarlamak, sürmek'),
    'w04700': ('врываться', 'zorla girmek, dalmak'),
    'w04705': ('кончик', 'uç'),
    'w04712': ('осведомитель', 'muhbir, ihbarcı'),
    'w04745': ('натянуть', 'germek, çekmek'),
    'w04761': ('тяга', 'çekim, itki'),
    'w04768': ('списать', 'kopya çekmek, silmek (borç)'),
    'w04791': ('частность', 'ayrıntı, özel durum'),
    'w04804': ('влечение', 'çekim, eğilim'),
    'w04809': ('пахать', 'toprağı sürmek, çok çalışmak'),
    'w04810': ('разгромить', 'ezmek, bozguna uğratmak'),
    'w04812': ('сносить', 'yıkmak, katlanmak'),
    'w04842': ('грохнуть', 'güm diye düşürmek, öldürmek'),
    'w04850': ('уговаривать', 'ikna etmeye çalışmak, kandırmak'),
    'w04863': ('передовой', 'ileri, öncü'),
    'w04875': ('добывать', 'elde etmek, çıkarmak (maden)'),
    'w04894': ('муза', 'ilham perisi'),
    'w04898': ('истец', 'davacı'),
    'w04908': ('значительно', 'önemli ölçüde, hayli'),
    'w04930': ('подводный', 'sualtı'),
    'w04956': ('траур', 'yas, matem'),
    'w04974': ('коленка', 'diz'),
    'w04978': ('вымогательство', 'gasp, zorla para alma'),
    'w04985': ('конструкция', 'yapı, konstrüksiyon'),
    'w04992': ('радиостанция', 'radyo istasyonu'),
    'w04997': ('мэтр', 'usta, üstat'),
    'w05111': ('горевать', 'yas tutmak, kederlenmek'),
    'w05120': ('деяние', 'eylem, fiil'),
    'w05125': ('примерный', 'yaklaşık, örnek'),
    'w05126': ('одиночный', 'tekli, yalnız'),
    'w05142': ('дефект', 'kusur, arıza'),
    'w05162': ('ошейник', 'tasma'),
    'w05166': ('мудрец', 'bilge'),
    'w05174': ('бриться', 'tıraş olmak'),
    'w05175': ('грим', 'makyaj (sahne makyajı)'),
    'w05182': ('морковь', 'havuç'),
    'w05190': ('годный', 'uygun, geçerli'),
    'w05199': ('кливер', 'flok (yelken)'),
    'w05207': ('староста', 'muhtar, sınıf başkanı'),
    'w05208': ('мушка', 'ben (leke), nişangâh'),
    'w05219': ('вал', 'sur, mil (şaft)'),
    'w05220': ('неразбериха', 'karmaşa, keşmekeş'),
    'w05233': ('обнаруживать', 'keşfetmek, ortaya çıkarmak'),
    'w05241': ('осознание', 'farkındalık, bilinç'),
    'w05244': ('зависнуть', 'donmak (bilgisayar), asılı kalmak'),
    'w05247': ('кирка', 'kazma'),
    'w05249': ('разъяснить', 'açıklamak, izah etmek'),
    'w05251': ('реактивный', 'tepkisel, jet (motor)'),
    'w05261': ('белоснежка', 'Pamuk Prenses'),
    'w05268': ('знаток', 'uzman, erbap'),
    'w05282': ('мучиться', 'acı çekmek, ıstırap çekmek'),
    'w05287': ('грохот', 'gürültü, gümbürtü'),
    'w05299': ('кружить', 'dönmek, tur atmak'),
    'w05314': ('отстаивать', 'savunmak'),
    'w05319': ('разрушитель', 'yıkıcı, tahripçi'),
    'w05325': ('невообразимый', 'düşünülemez, hayal edilemez'),
    'w05329': ('затевать', 'başlatmak, girişmek'),
    'w05332': ('наезжать', 'çarpmak (araçla), baskı yapmak'),
    'w05333': ('покраснеть', 'kızarmak'),
    'w05343': ('грубиян', 'kaba adam, terbiyesiz'),
    'w05351': ('станок', 'makine, tezgâh'),
    'w05360': ('мягко', 'yumuşakça, hafifçe'),
    'w05367': ('очаровать', 'büyülemek, cezbetmek'),
    'w05377': ('обоснованный', 'gerekçeli, haklı'),
    'w05383': ('пасовать', 'pas vermek, boyun eğmek'),
    'w05388': ('хрустящий', 'gevrek, çıtır'),
    'w05394': ('блондин', 'sarışın'),
    'w05419': ('дверца', 'küçük kapı, kapak'),
    'w05438': ('булка', 'çörek, ekmekçik'),
    'w05448': ('похоть', 'şehvet'),
    'w05456': ('накладывать', 'uygulamak, koymak'),
    'w05459': ('встревоженный', 'endişeli, tedirgin'),
    'w05465': ('кончина', 'vefat, ölüm'),
    'w05478': ('наушник', 'kulaklık'),
    'w05481': ('оправданный', 'haklı, meşru'),
    'w05520': ('суматоха', 'kargaşa, telaş'),
    'w05539': ('рослый', 'uzun boylu, iri yarı'),
    'w05568': ('раздражительный', 'sinirli, çabuk kızan'),
    'w05569': ('ода', 'kaside, övgü şiiri'),
    'w05571': ('бесчисленный', 'sayısız'),
    'w05581': ('комендант', 'komutan, bina yöneticisi'),
    'w05586': ('сдержанный', 'ölçülü, ağırbaşlı'),
    'w05599': ('цеплять', 'takılmak, cezbetmek'),
    'w05607': ('притон', 'batakhane, gizli yuva'),
    'w05619': ('спутница', 'yol arkadaşı, refakatçi'),
    'w05620': ('тщеславие', 'kibir, boş gurur'),
    'w05636': ('предвзятый', 'önyargılı, taraflı'),
    'w05639': ('доверчивый', 'saf, kolay inanan'),
    'w05645': ('скромность', 'alçakgönüllülük, tevazu'),
    'w05651': ('мутить', 'bulandırmak, kışkırtmak'),
    'w05652': ('своеобразный', 'kendine özgü, has'),
    'w05653': ('квалифицированный', 'kalifiye, nitelikli'),
    'w05666': ('сопоставить', 'karşılaştırmak'),
    'w05674': ('узор', 'desen, motif'),
    'w05675': ('виновник', 'suçlu, sorumlu'),
    'w05689': ('стремительный', 'hızlı, atak'),
    'w05692': ('ухудшиться', 'kötüleşmek'),
    'w05700': ('изводить', 'eziyet etmek, canını sıkmak'),
    'w05719': ('торг', 'pazarlık'),
    'w05721': ('слабеть', 'zayıflamak, güçten düşmek'),
    'w05733': ('яростный', 'öfkeli, hiddetli'),
    'w05740': ('девятка', 'dokuzlu, dokuz numara'),
    'w05753': ('переоценивать', 'abartmak, yeniden değerlendirmek'),
    'w05768': ('программист', 'programcı'),
    'w05773': ('авторский', 'yazara ait, telif'),
    'w05776': ('служение', 'hizmet etme'),
    'w05796': ('тётка', 'teyze, hala'),
    'w05809': ('строчок', 'kuzu göbeği mantarı'),
    'w05814': ('подталкивать', 'dürtmek, itmek'),
    'w05817': ('потопить', 'batırmak, suya boğmak'),
    'w05827': ('ремесло', 'zanaat, meslek'),
    'w05833': ('извращение', 'sapkınlık, çarpıtma'),
    'w05836': ('разорить', 'iflas ettirmek, mahvetmek'),
    'w05842': ('имперский', 'emperyal, imparatorluğa ait'),
    'w05848': ('пороть', 'kırbaçlamak, sökmek (dikişi)'),
    'w05865': ('объединённый', 'birleşik, müttefik'),
    'w05866': ('соперничать', 'rekabet etmek'),
    'w05874': ('бездельничать', 'aylaklık etmek, boş durmak'),
    'w05887': ('вещественный', 'maddi, somut'),
    'w05890': ('трапеза', 'yemek, öğün'),
    'w05891': ('клоп', 'tahtakurusu'),
    'w05910': ('берлога', 'in, mağara'),
    'w05912': ('неопровержимый', 'çürütülemez, su götürmez'),
    'w05919': ('кура', 'piliç, tavuk'),
    'w05921': ('покинутый', 'terk edilmiş'),
    'w05929': ('изъян', 'kusur, arıza'),
    'w05933': ('стенд', 'stant, sergi standı'),
    'w05935': ('угрюмый', 'asık suratlı, somurtkan'),
    'w05938': ('вытерпеть', 'katlanmak, dayanmak'),
    'w05947': ('утроба', 'rahim, karın'),
    'w05953': ('чары', 'büyü, sihir'),
    'w05958': ('уважительный', 'saygılı, geçerli'),
    'w05967': ('потянуться', 'uzanmak, gerinmek'),
    'w05969': ('запеканка', 'güveç, fırında pişen yemek'),
    'w05970': ('снижать', 'azaltmak, düşürmek'),
    'w05971': ('отправление', 'kalkış, gönderme'),
    'w05977': ('чадо', 'evlat, çocuk'),
    'w05991': ('ронять', 'düşürmek'),
    'w05993': ('имение', 'malikâne, arazi'),
    'w05994': ('соблюдение', 'uyma, riayet'),
    'w05996': ('состоятельный', 'varlıklı, zengin'),
    'w05997': ('льгота', 'ayrıcalık, imtiyaz'),
    'w05999': ('загон', 'ağıl, hayvan barınağı'),
    'w06004': ('оспа', 'çiçek hastalığı'),
    'w06008': ('пупок', 'göbek'),
    'w06049': ('дезертир', 'asker kaçağı, firari'),
    'w06054': ('компетентный', 'yetkin, ehliyetli'),
    'w06058': ('усиливаться', 'güçlenmek, şiddetlenmek'),
    'w06060': ('острота', 'keskinlik, nükte'),
    'w06068': ('исток', 'kaynak'),
    'w06070': ('венок', 'çelenk'),
    'w06079': ('согласовать', 'uyumlu hale getirmek, onaylatmak'),
    'w06094': ('обойма', 'şarjör (mermi kovanı)'),
    'w06103': ('муниципалитет', 'belediye'),
    'w06105': ('понимающий', 'anlayışlı'),
    'w06107': ('экономия', 'tasarruf'),
    'w06120': ('складка', 'kıvrım, kırışık'),
    'w06121': ('оседлать', 'eyerlemek, binmek'),
    'w06122': ('поглощение', 'emilim, satın alma (şirket)'),
    'w06130': ('посёлок', 'kasaba, yerleşim yeri'),
    'w06134': ('пребыть', 'kalmak, mukim olmak'),
    'w06135': ('весельчак', 'şen şakrak kişi, neşeli adam'),
    'w06139': ('изобилие', 'bolluk'),
    'w06145': ('сокращать', 'kısaltmak, azaltmak'),
    'w06147': ('неведомый', 'bilinmeyen, meçhul'),
    'w06149': ('неопытный', 'deneyimsiz, acemi'),
    'w06158': ('титька', 'meme (argo)'),
    'w06161': ('уклонение', 'kaçınma, vergi kaçırma'),
    'w06167': ('вожак', 'lider, önder'),
    'w06168': ('вовлечь', 'dahil etmek, katmak'),
    'w06188': ('наклоняться', 'eğilmek'),
    'w06195': ('бронзовый', 'bronz renginde'),
    'w06197': ('неуверенность', 'güvensizlik, kararsızlık'),
    'w06201': ('объединяться', 'birleşmek'),
    'w06209': ('лесть', 'dalkavukluk, pohpohlama'),
    'w06212': ('смола', 'reçine, sakız'),
    'w06218': ('шайба', 'rondela, hokey diski'),
    'w06220': ('угонять', 'çalmak (araç), kaçırmak'),
    'w06221': ('кормило', 'dümen'),
    'w06222': ('свод', 'tonoz, kanunlar bütünü'),
    'w06238': ('поломка', 'arıza, bozulma'),
    'w06260': ('раздаться', 'duyulmak, yankılanmak'),
    'w06267': ('пекарь', 'fırıncı'),
    'w06268': ('болельщик', 'taraftar'),
    'w06269': ('осилить', 'üstesinden gelmek, başarmak'),
    'w06276': ('грузчик', 'hamal, yük taşıyıcı'),
    'w06278': ('оракул', 'kâhin'),
    'w06280': ('возмущение', 'öfke, infial'),
    'w06284': ('реагирование', 'tepki verme'),
    'w06297': ('хам', 'kaba adam, terbiyesiz'),
    'w06302': ('иммиграция', 'göç, içgöç'),
    'w06309': ('рывок', 'ani çekiş, atılım'),
    'w06316': ('пожарник', 'itfaiyeci'),
    'w06318': ('родимый', 'sevgili, öz'),
    'w06327': ('пудра', 'pudra (yüz pudrası)'),
    'w06331': ('джокер', 'joker'),
    'w06332': ('зверский', 'vahşi, canavarca'),
    'w06333': ('искажение', 'çarpıtma, bozulma'),
    'w06334': ('внушение', 'telkin, öğüt'),
    'w06335': ('трубопровод', 'boru hattı'),
    'w06341': ('неестественный', 'doğal olmayan, yapmacık'),
    'w06345': ('ложе', 'yatak'),
    'w06356': ('моторный', 'motor, motorlu'),
    'w06366': ('машинист', 'makinist'),
    'w06367': ('смирение', 'alçakgönüllülük, boyun eğme'),
    'w06370': ('мистика', 'mistisizm, gizemcilik'),
    'w06375': ('сглазить', 'nazar değdirmek'),
    'w06381': ('закладная', 'ipotek senedi'),
    'w06383': ('бот', 'kayık, bot'),
    'w06427': ('бушевать', 'şiddetle esmek, kudurmak'),
    'w06561': ('ансамбль', 'topluluk, ekip'),
    'w06573': ('авантюра', 'macera, serüven'),
    'w06574': ('коммуна', 'komün'),
    'w06578': ('прочность', 'dayanıklılık, sağlamlık'),
    'w06588': ('страстно', 'tutkuyla, ateşli biçimde'),
    'w06593': ('скомпрометировать', 'gözden düşürmek, karalamak'),
    'w06600': ('пуск', 'başlatma, fırlatma'),
    'w06601': ('верфь', 'tersane'),
    'w06608': ('непоправимый', 'onarılmaz, telafisi imkânsız'),
    'w06621': ('приручить', 'evcilleştirmek, alıştırmak'),
    'w06623': ('сардина', 'sardalya'),
    'w06630': ('вещание', 'yayın, yayıncılık'),
    'w06632': ('павильон', 'köşk, sergi binası'),
    'w06634': ('паства', 'cemaat, sürü'),
    'w06636': ('руно', 'post, yapağı'),
    'w06650': ('венерический', 'zührevi, cinsel yolla bulaşan'),
    'w06656': ('настоятель', 'başrahip, cemaat lideri'),
    'w06664': ('повременить', 'biraz beklemek, ertelemek'),
    'w06667': ('повстречаться', 'rastlamak, rastlaşmak'),
    'w06669': ('дрель', 'matkap'),
    'w06682': ('расплывчатый', 'belirsiz, bulanık'),
    'w06685': ('отстранять', 'uzaklaştırmak, görevden almak'),
    'w06702': ('наложница', 'cariye, odalık'),
    'w06703': ('утолить', 'gidermek, doyurmak'),
    'w06706': ('жилищный', 'konut, mesken'),
    'w06708': ('растяпа', 'sakar, beceriksiz'),
    'w06720': ('интервал', 'aralık'),
    'w06726': ('скитаться', 'başıboş dolaşmak, gezinmek'),
    'w06727': ('окурок', 'izmarit'),
    'w06735': ('почём', 'kaça, ne kadar'),
    'w06739': ('долбить', 'oymak, ezberlemek'),
    'w06742': ('застыть', 'donmak, katılaşmak'),
    'w06744': ('перевал', 'geçit, dağ geçidi'),
    'w06753': ('пополнение', 'takviye, ekleme'),
    'w06754': ('макушка', 'tepe, baş tepesi'),
    'w06761': ('восприимчивый', 'duyarlı, çabuk etkilenen'),
    'w06764': ('пролив', 'boğaz, geçit'),
    'w06765': ('курсант', 'askeri öğrenci'),
    'w06769': ('отбиться', 'savuşturmak, ayrılmak'),
    'w06775': ('прадед', 'büyük dede'),
    'w06798': ('совершеннолетний', 'reşit, ergin'),
    'w06822': ('вместить', 'içine almak, sığdırmak'),
    'w06839': ('испуг', 'korku, ürkme'),
    'w06844': ('сбыт', 'satış, pazarlama'),
    'w06859': ('передвижной', 'seyyar, taşınabilir'),
    'w06874': ('топтать', 'çiğnemek, ezmek'),
    'w06885': ('лепить', 'yoğurmak, biçimlendirmek'),
    'w06895': ('химера', 'kimera, hayal ürünü'),
    'w06897': ('прут', 'sopa, çubuk'),
    'w06906': ('усмирить', 'yatıştırmak, teskin etmek'),
    'w06915': ('шарить', 'araştırmak, karıştırmak'),
    'w06934': ('отклик', 'yanıt, tepki'),
    'w06935': ('юнга', 'gemici çırağı'),
    'w06946': ('взмах', 'kanat çırpışı, el sallama'),
    'w06949': ('утёнок', 'ördek yavrusu'),
    'w06954': ('пресный', 'tuzsuz, lezzetsiz'),
    'w06963': ('массив', 'kütle, dizi'),
    'w06973': ('полумесяц', 'hilal, yarımay'),
    'w06985': ('коллектор', 'kolektör, ana boru'),
    'w07002': ('кувалда', 'balyoz'),
    'w07007': ('инвентарь', 'envanter, demirbaş'),
    'w07019': ('корчить', 'yüz buruşturmak, taklit etmek'),
    'w07025': ('керосин', 'gaz yağı'),
    'w07040': ('разработчик', 'geliştirici, yapımcı'),
    'w07044': ('разъезд', 'ayrılma, kavşak'),
    'w07053': ('невыполнимый', 'yapılamaz, imkânsız'),
    'w07068': ('котелок', 'tencere, kazan'),
    'w07106': ('выступ', 'çıkıntı, tümsek'),
    'w07109': ('соучастник', 'suç ortağı'),
    'w07111': ('провидение', 'ilahi takdir, kader'),
    'w07123': ('переваривать', 'sindirmek, hazmetmek'),
    'w07146': ('коленный', 'dize ait'),
    'w07161': ('скудный', 'az, kıt'),
    'w07168': ('долгота', 'boylam, uzunluk'),
    'w07177': ('комнатка', 'küçük oda'),
    'w07211': ('заступаться', 'savunmak, arka çıkmak'),
    'w07246': ('простолюдин', 'sıradan halktan kimse, avam'),
    'w07252': ('застройщик', 'müteahhit, inşaat yatırımcısı'),
    'w07278': ('изъятие', 'müsadere, geri alma'),
    'w07282': ('кануть', 'yok olmak, kaybolmak'),
    'w07293': ('распознавать', 'tanımak, ayırt etmek'),
    'w07316': ('властитель', 'hükümdar, hâkim'),
    'w07359': ('вилять', 'kuyruk sallamak, kaçamak yapmak'),
    'w07378': ('лоза', 'asma, asma dalı'),
    'w07413': ('самомнение', 'kendini beğenmişlik, kibir'),
    'w07426': ('обречь', 'mahkum etmek, yazgılamak'),
    'w07469': ('заточка', 'bileme, bıçak (argo)'),
    'w07481': ('утилизация', 'geri dönüşüm, atık değerlendirme'),
    'w07496': ('уличить', 'suçüstü yakalamak'),
    'w07515': ('купе', 'kompartıman (tren)'),
    'w07540': ('вассал', 'tâbi, derebeyliğe bağlı kişi'),
    'w07553': ('кюре', 'papaz (Katolik)'),
    'w07627': ('скверно', 'kötü, fena'),
    'w07635': ('понижать', 'azaltmak, düşürmek'),
    'w07663': ('конструктор', 'tasarımcı, yapı seti'),
    'w07678': ('пасынок', 'üvey oğul, yan sürgün'),
    'w07688': ('приёмник', 'alıcı, radyo'),
    'w07725': ('кокнуть', 'kırmak, öldürmek'),
    'w07772': ('русый', 'kumral'),
    'w07816': ('надувательство', 'dolandırıcılık, hile'),
    'w07828': ('бука', 'öcü'),
    'w07837': ('спица', 'jant teli, tığ (örgü)'),
    'w07897': ('такса', 'dachshund, tarife'),
    'w07955': ('откат', 'rüşvet (argo), geri tepme'),
    'w07980': ('тракт', 'yol, güzergah'),
    'w08006': ('осадки', 'yağış, çökelti'),
    'w08011': ('рукавица', 'parmaksız eldiven'),
    'w08033': ('эскимо', 'çubuklu dondurma'),
    'w08042': ('присудить', 'hüküm vermek, ödül vermek'),
    'w08064': ('керн', 'karot, çekirdek numune'),
    'w08082': ('невежа', 'kaba adam, terbiyesiz'),
    'w08100': ('валун', 'iri kaya, kaya parçası'),
    'w08161': ('сосулька', 'saçak buzu, buz sarkıtı'),
    'w08162': ('личина', 'maske, kılık'),
    'w08175': ('эшелон', 'eşelon, tren konvoyu'),
    'w08199': ('раскачать', 'sallamak, kışkırtmak'),
    'w08200': ('ковырять', 'eşelemek, karıştırmak'),
    'w08205': ('гиря', 'ağırlık, gülle'),
    'w08208': ('щиток', 'gösterge paneli, kalkan'),
    'w08223': ('разрастаться', 'yayılmak, büyümek'),
    'w08414': ('козырёк', 'siper, gölgelik'),
    'w08458': ('оговорить', 'şart koşmak, iftira etmek'),
    'w08459': ('пассия', 'sevgili, gönül eğlencesi'),
    'w08475': ('спекулянт', 'vurguncu, karaborsacı'),
    'w08496': ('кладезь', 'hazine, kaynak'),
    'w08542': ('самовольный', 'izinsiz, keyfi'),
    'w08543': ('аффект', 'ani şiddetli heyecan, cinnet'),
    'w08599': ('распря', 'çekişme, husumet'),
    'w08636': ('побоище', 'kanlı kavga, katliam'),
    'w08642': ('препарировать', 'diseksiyon yapmak, hazırlamak'),
    'w08658': ('смета', 'keşif, tahmini bütçe'),
    'w08677': ('лиф', 'korsaj'),
    'w08704': ('дремучий', 'sık (orman), geri kalmış'),
    'w08710': ('сердечник', 'kalp hastası, öz'),
    'w08823': ('овен', 'koç (hayvan), Koç burcu'),
    'w08839': ('торный', 'çiğnenmiş, aşınmış'),
    'w08887': ('постный', 'perhiz yemeği, yağsız'),
    'w08917': ('пион', 'ayıgülü'),
    'w08922': ('блуд', 'zina, fuhuş'),
    'w08989': ('получка', 'maaş, ücret'),
}

# Raporun bildirdigi kalibin ("dogru anlamin yanina alakasiz bir ikinci
# kelime") veri setinin tamaminda taranmasi sonucu bulunan ek kayitlar.
# Enjekte edilen sozcukler: avaz, mustakbel, sofa, ajine, plato, aga,
# atfetmek. Her biri 5-20 alakasiz Rusca kelimeye atanmisti.
REPORT3_EXTRA = {
    'w00503': ('голос', 'ses'),
    'w00545': ('заняться', 'uğraşmak, meşgul olmak'),
    'w00575': ('босс', 'patron, şef'),
    'w00728': ('поставить', 'koymak, yerleştirmek'),
    'w00996': ('задать', 'sormak, vermek'),
    'w01394': ('мастер', 'usta, ustabaşı'),
    'w01644': ('сайт', 'site, web sitesi'),
    'w01972': ('направить', 'yönlendirmek, göndermek'),
    'w02443': ('патрон', 'fişek, kartuş'),
    'w02639': ('прибор', 'alet, cihaz'),
    'w02714': ('повелитель', 'hükümdar, efendi'),
    'w02928': ('здравый', 'sağlıklı, aklı başında'),
    'w03328': ('положенный', 'belirlenmiş, gerekli'),
    'w03702': ('предоставлять', 'sağlamak, sunmak'),
    'w03876': ('задаваться', 'kendine sormak, kurulmak'),
    'w04198': ('придавать', 'vermek, katmak'),
    'w04262': ('вкладывать', 'yatırım yapmak, koymak'),
    'w04991': ('присвоить', 'kendine mal etmek'),
    'w05093': ('нападающий', 'forvet, saldıran'),
    'w05669': ('властелин', 'hükümdar, efendi'),
    'w05786': ('ссылаться', 'atıfta bulunmak, dayanmak'),
    'w07732': ('переправлять', 'karşıya geçirmek, iletmek'),
}
