# -*- coding: utf-8 -*-
"""Kullanicinin gonderdigi hata raporundan uretilen duzeltmeler.

Kaynak: rusca_turkce_hata_raporu.xlsx (628 dogrulanmis bulgu).
Bu dosya elle duzenlenebilir; `apply_fixes.py` okur.

Anlam sayisi ikiyle sinirli: uc ve fazlasi kart yuzunde kafa
karistiriyor, kullanicinin kurali bu.
"""

# id -> (rusca, dogru_turkce)
REPORT_TR = {
    'w00055': ('мочь', 'yapabilmek, -ebilmek'),
    'w00084': ('сделать', 'yapmak'),
    'w00096': ('парень', 'delikanlı, genç'),
    'w00108': ('вернуться', 'dönmek'),
    'w00112': ('собираться', 'toplanmak, niyet etmek'),
    'w00124': ('пытаться', 'denemek, çalışmak (bir şey yapmaya)'),
    'w00175': ('извинить', 'affetmek, bağışlamak'),
    'w00178': ('начать', 'başlamak'),
    'w00212': ('поехать', 'yola çıkmak, gitmeye başlamak'),
    'w00236': ('заниматься', 'uğraşmak, meşgul olmak'),
    'w00243': ('пройти', 'geçmek'),
    'w00250': ('милый', 'sevimli, tatlı'),
    'w00263': ('номер', 'numara, sayı'),
    'w00269': ('ли', 'mi'),
    'w00274': ('бросить', 'bırakmak, terk etmek'),
    'w00303': ('отношение', 'ilişki, tutum'),
    'w00308': ('закончить', 'bitirmek'),
    'w00311': ('проверить', 'kontrol etmek, doğrulamak'),
    'w00313': ('принять', 'kabul etmek, almak'),
    'w00315': ('забрать', 'almak, geri almak'),
    'w00319': ('можно', 'mümkün, olabilir'),
    'w00335': ('ужасный', 'berbat, korkunç'),
    'w00336': ('встретиться', 'buluşmak, karşılaşmak'),
    'w00362': ('стать', 'olmak, haline gelmek'),
    'w00369': ('послать', 'göndermek'),
    'w00380': ('вечеринка', 'parti'),
    'w00385': ('обычный', 'olağan, sıradan'),
    'w00399': ('решение', 'karar, çözüm'),
    'w00401': ('провести', 'geçirmek (vakit), yürütmek'),
    'w00410': ('представлять', 'temsil etmek, hayal etmek'),
    'w00414': ('справиться', 'üstesinden gelmek, başarmak'),
    'w00417': ('вести', 'yönetmek, sürmek'),
    'w00420': ('согласный', 'aynı fikirde, razı / ünsüz (dilbilgisi)'),
    'w00428': ('отпустить', 'bırakmak, salıvermek'),
    'w00429': ('беспокоиться', 'endişelenmek, kaygılanmak'),
    'w00436': ('представить', 'tanıtmak, sunmak'),
    'w00444': ('бывать', '(ara sıra) olmak, bulunmak'),
    'w00446': ('честь', 'onur, şeref'),
    'w00452': ('равный', 'eşit'),
    'w00454': ('передать', 'iletmek, aktarmak'),
    'w00458': ('заметить', 'fark etmek, farkına varmak'),
    'w00459': ('кое-что', 'birkaç şey, bir şeyler'),
    'w00461': ('вещий', 'kehanet nitelikli, önsezili'),
    'w00466': ('переть', 'sızmak (belli olmak, dışa vurmak), zorla ilerlemek'),
    'w00474': ('сообщение', 'mesaj, bildiri'),
    'w00493': ('курс', 'kur (döviz), ders/kurs (eğitim)'),
    'w00495': ('образ', 'biçem, görünüm'),
    'w00504': ('честный', 'dürüst'),
    'w00507': ('достать', '(uzanıp) almak, elde etmek'),
    'w00514': ('заткнуться', 'susmak, çenesini kapamak'),
    'w00530': ('следить', 'izlemek, takip etmek'),
    'w00535': ('уметь', 'bilmek, yapabilmek'),
    'w00538': ('минуть', 'geçmek (zaman için)'),
    'w00540': ('весить', 'tartmak, (kilo) çekmek'),
    'w00554': ('устроить', 'ayarlamak, düzenlemek'),
    'w00558': ('поступить', 'davranmak, (okula/işe) girmek'),
    'w00560': ('проводить', 'geçirmek (vakit), yürütmek'),
    'w00576': ('подруга', 'kız arkadaş (platonik anlamda), dost'),
    'w00582': ('давно', 'uzun zamandır, çok önceden'),
    'w00592': ('разобраться', 'anlamak, çözmek'),
    'w00602': ('пригласить', 'davet etmek'),
    'w00603': ('страшный', 'korkunç, ürkütücü'),
    'w00610': ('подходить', 'yaklaşmak, uygun olmak'),
    'w00613': ('любимый', 'sevilen, en sevdiği'),
    'w00619': ('хватать', 'yetmek (yeterli olmak) / kapmak, yakalamak (tutma anlamı)'),
    'w00633': ('вспомнить', 'anımsamak, hatırlamak'),
    'w00641': ('отказаться', 'reddetmek, vazgeçmek'),
    'w00648': ('сделка', 'anlaşma, pazarlık'),
    'w00649': ('обо', 'hakkında (edat)'),
    'w00651': ('повезти', 'şanslı olmak / (araçla) götürmek'),
    'w00653': ('удар', 'darbe, vuruş'),
    'w00661': ('подойти', 'yaklaşmak, uygun olmak/gelmek'),
    'w00664': ('уничтожить', 'yok etmek, imha etmek'),
    'w00670': ('мера', 'tedbir, önlem'),
    'w00698': ('расследование', 'soruşturma'),
    'w00700': ('осторожный', 'sakıngan, dikkatli'),
    'w00704': ('переживать', 'endişelenmek, yaşamak (bir duyguyu)'),
    'w00705': ('когда-нибудь', 'bir gün, herhangi bir zaman'),
    'w00715': ('называться', 'adlandırılmak, denilmek'),
    'w00725': ('сомневаться', 'şüphe duymak, emin olamamak'),
    'w00738': ('заботиться', '(birine/bir şeye) bakmak, ilgilenmek'),
    'w00743': ('шеф', 'patron, şef'),
    'w00751': ('ударить', 'vurmak, çarpmak'),
    'w00752': ('обвинение', 'itham, suçlama'),
    'w00777': ('сожалеть', 'pişman olmak, üzülmek'),
    'w00783': ('колледж', 'kolej'),
    'w00794': ('действие', 'eylem, hareket'),
    'w00812': ('полностью', 'tamamen, tamamıyla'),
    'w00818': ('великолепный', 'muhteşem, harikulade'),
    'w00836': ('гордиться', 'gurur duymak, övünmek'),
    'w00890': ('ставить', 'koymak, yerleştirmek'),
    'w00894': ('сюрприз', 'sürpriz'),
    'w00897': ('охрана', 'koruma, güvenlik'),
    'w00912': ('невозможный', 'imkansız'),
    'w00926': ('сойти', 'inmek (araçtan), geçmek (bir şey olarak)'),
    'w00930': ('бой', 'dövüş, kavga'),
    'w00933': ('беспокоить', 'endişelendirmek, rahatsız etmek'),
    'w00940': ('участок', 'arsa, parsel (arazi) / karakol (polis)'),
    'w00944': ('забирать', 'almak, el koymak'),
    'w00946': ('тупой', 'kalın kafalı, aptal / kör'),
    'w00952': ('название', 'isim, ad'),
    'w00970': ('вырасти', 'büyümek'),
    'w00973': ('пользоваться', 'kullanmak, faydalanmak'),
    'w00980': ('поддерживать', 'desteklemek'),
    'w00981': ('ездить', '(araçla) gitmek, seyahat etmek'),
    'w00984': ('проект', 'proje'),
    'w00997': ('проверять', 'kontrol etmek, doğrulamak'),
    'w01003': ('нанять', 'işe almak'),
    'w01009': ('нуждаться', 'ihtiyacı olmak, muhtaç olmak'),
    'w01012': ('доступ', 'erişim'),
    'w01018': ('отпечаток', 'iz, baskı'),
    'w01027': ('нести', 'taşımak'),
    'w01033': ('доставить', 'ulaştırmak, teslim etmek'),
    'w01040': ('лететь', 'uçmak'),
    'w01044': ('тратить', 'harcamak'),
    'w01051': ('постоять', 'bir süre ayakta durmak / (kendini) savunmak'),
    'w01057': ('недавно', 'yakınlarda, geçenlerde'),
    'w01064': ('управлять', 'idare etmek, yönetmek'),
    'w01082': ('лагерь', 'kamp'),
    'w01088': ('устраивать', 'ayarlamak, düzenlemek'),
    'w01089': ('страдать', 'acı çekmek, ıstırap çekmek'),
    'w01091': ('разрешение', 'izin / çözünürlük (görüntü için)'),
    'w01093': ('размер', 'boyut, ölçü'),
    'w01096': ('срок', 'süre, vade'),
    'w01100': ('собирать', 'toplamak'),
    'w01105': ('умолять', 'yalvarmak, rica etmek (ısrarla)'),
    'w01109': ('возвращение', 'dönüş, geri dönme'),
    'w01130': ('узнавать', 'tanımak, öğrenmek'),
    'w01140': ('пережить', 'yaşamak (bir olayı), atlatmak'),
    'w01149': ('меньше', 'daha az, daha küçük'),
    'w01156': ('путешествие', 'yolculuk, seyahat'),
    'w01163': ('расстроенный', 'üzgün, canı sıkkın'),
    'w01171': ('честно', 'dürüstçe'),
    'w01178': ('нечто', 'bir şey'),
    'w01188': ('полезный', 'faydalı, yararlı'),
    'w01189': ('видимый', 'görünür, görülebilir'),
    'w01193': ('деталь', 'ayrıntı, detay'),
    'w01197': ('подходящий', 'elverişli, uygun'),
    'w01199': ('сознание', 'bilinç'),
    'w01206': ('поработать', 'biraz çalışmak'),
    'w01207': ('уважать', 'saygı duymak'),
    'w01210': ('спорить', 'tartışmak'),
    'w01221': ('крупный', 'büyük, önemli'),
    'w01222': ('воля', 'irade'),
    'w01225': ('ужас', 'dehşet, korku'),
    'w01226': ('связанный', 'bağlı, ilişkili'),
    'w01236': ('модель', 'model (soyut/matematiksel model), manken'),
    'w01239': ('примерно', 'yaklaşık, civarında'),
    'w01243': ('когда-либо', 'herhangi bir zaman, hiç (soru/olumsuzda)'),
    'w01256': ('винить', 'suçlamak'),
    'w01262': ('подозревать', 'kuşkulanmak, şüphelenmek'),
    'w01263': ('симпатичный', 'hoş, çekici'),
    'w01265': ('застрелить', 'vurmak (silahla), ateş ederek öldürmek'),
    'w01274': ('ощущение', 'his, duygu'),
    'w01278': ('болтать', 'sohbet etmek, gevezelik etmek'),
    'w01291': ('сотрудник', 'çalışan, iş arkadaşı'),
    'w01304': ('контакт', 'temas, iletişim'),
    'w01315': ('наблюдение', 'gözlem, gözetim'),
    'w01317': ('битва', 'cenk, savaş'),
    'w01320': ('арест', 'tutuklama'),
    'w01326': ('красота', 'güzellik'),
    'w01336': ('рассчитывать', 'güvenmek, hesaba katmak'),
    'w01341': ('издеваться', 'alay etmek, eziyet etmek'),
    'w01342': ('кусочек', 'parçacık, küçük parça'),
    'w01354': ('поддержать', 'desteklemek'),
    'w01361': ('устройство', 'cihaz, aygıt / düzen (bağlama göre)'),
    'w01366': ('перерыв', 'ara, mola'),
    'w01380': ('перейти', 'geçmek (bir yerden/duruma)'),
    'w01391': ('ручка', 'kalem / kapı kolu (kulp anlamı)'),
    'w01409': ('множество', 'çokluk, pek çok (şey)'),
    'w01414': ('выстрелить', 'ateş etmek, ateşlemek'),
    'w01436': ('напарник', 'iş arkadaşı, partner (görev ortağı)'),
    'w01437': ('толпа', 'kalabalık, kitle'),
    'w01440': ('тихо', 'sessizce, yavaşça'),
    'w01443': ('творить', 'oluşturmak, yaratmak'),
    'w01453': ('тонуть', 'boğulmak'),
    'w01460': ('надоесть', 'bıktırmak, canını sıkmak'),
    'w01463': ('ближайший', 'en yakın'),
    'w01472': ('зад', 'kıç, popo'),
    'w01477': ('спасение', 'kurtarma, kurtuluş'),
    'w01479': ('двойной', 'çift, ikili'),
    'w01490': ('истинный', 'gerçek, hakiki'),
    'w01497': ('невинный', 'masum, günahsız'),
    'w01502': ('край', 'kenar (edge) / bölge, yöre (region)'),
    'w01512': ('грубый', 'kaba, kaba saba'),
    'w01515': ('гореть', 'yanmak'),
    'w01523': ('прикрытие', 'örtü, kılıf (mecazi)'),
    'w01527': ('отдавать', 'vermek, geri vermek'),
    'w01529': ('предмет', 'nesne, konu (ders)'),
    'w01532': ('вынести', 'dışarı çıkarmak, taşımak / (karar) vermek'),
    'w01539': ('должность', 'görev, memuriyet'),
    'w01541': ('возникнуть', 'ortaya çıkmak, doğmak (mecazi)'),
    'w01542': ('торт', 'kek, pasta'),
    'w01551': ('заказ', 'sipariş'),
    'w01553': ('разбудить', 'uyandırmak'),
    'w01556': ('настаивать', 'ısrar etmek'),
    'w01559': ('волшебный', 'sihirli, büyülü'),
    'w01562': ('отделение', 'şube, bölüm'),
    'w01570': ('заглянуть', 'göz atmak, uğramak'),
    'w01577': ('замечать', 'farketmek, fark etmek'),
    'w01580': ('бред', 'saçmalık, hezeyan'),
    'w01582': ('обратный', 'ters, geri (dönüş)'),
    'w01586': ('записка', 'not, pusula'),
    'w01589': ('единый', 'birleşik, tek'),
    'w01590': ('невиновный', 'suçsuz, masum'),
    'w01601': ('красавица', 'güzel kadın, güzel kız'),
    'w01605': ('мина', 'mayın (patlayıcı)'),
    'w01606': ('выше', 'daha yüksek, daha uzun (boy için)'),
    'w01610': ('эксперт', 'uzman'),
    'w01614': ('наступить', 'adım atmak (basmak) / (mevsim vb. için) gelmek'),
    'w01630': ('требоваться', 'gerekmek, ihtiyaç duyulmak'),
    'w01640': ('коробок', 'kutu, kibrit kutusu'),
    'w01649': ('репутация', 'itibar, şöhret'),
    'w01656': ('туфля', 'ayakkabı'),
    'w01658': ('доля', 'pay, hisse / alın yazısı (kader anlamı)'),
    'w01660': ('обмен', 'değişim, değiş tokuş'),
    'w01671': ('заканчивать', 'bitirmek, tamamlamak'),
    'w01679': ('ценный', 'değerli'),
    'w01688': ('везти', '(araçla) götürmek, taşımak'),
    'w01689': ('соглашение', 'anlaşma'),
    'w01691': ('хрень', 'saçmalık, zırva'),
    'w01725': ('гонка', 'yarış'),
    'w01726': ('кормить', 'beslemek'),
    'w01738': ('боевой', 'savaşa ait, askeri'),
    'w01752': ('проникнуть', 'sızmak, gizlice girmek'),
    'w01753': ('диск', 'disk'),
    'w01767': ('тащить', 'sürüklemek, çekmek'),
    'w01771': ('холодильник', 'buzdolabı'),
    'w01788': ('приём', 'kabul, resepsiyon / yöntem / doz (bağlama göre)'),
    'w01789': ('удачный', 'başarılı, isabetli'),
    'w01790': ('успешный', 'başarılı'),
    'w01791': ('кнопка', 'düğme'),
    'w01803': ('дура', 'aptal, salak (kadın için)'),
    'w01804': ('сводить', 'bir araya getirmek, indirgemek'),
    'w01807': ('оценка', 'not (okul notu), değerlendirme'),
    'w01810': ('приветствовать', 'selamlamak, karşılamak'),
    'w01811': ('путешествовать', 'seyahat etmek'),
    'w01812': ('проститутка', 'fahişe'),
    'w01814': ('руль', 'direksiyon (araba) / gidon (bisiklet)'),
    'w01822': ('запустить', 'başlatmak, çalıştırmak'),
    'w01823': ('карьер', 'taş ocağı (maden ocağı)'),
    'w01826': ('печальный', 'üzgün, hüzünlü'),
    'w01827': ('ответственный', 'sorumlu'),
    'w01829': ('сообщать', 'bildirmek, haber vermek'),
    'w01831': ('космический', 'uzaya ait, kozmik'),
    'w01832': ('марка', 'posta pulu, marka (ticari)'),
    'w01834': ('страховка', 'sigorta'),
    'w01844': ('древний', 'antik, kadim'),
    'w01848': ('неприятный', 'nahoş, tatsız'),
    'w01855': ('заканчиваться', 'bitmek, sona ermek'),
    'w01861': ('печенье', 'bisküvi, kurabiye'),
    'w01863': ('ввести', 'girmek (bilgi), tanıtmak'),
    'w01864': ('крошка', 'kırıntı / bebeğim, tatlım (sevgi ifadesi)'),
    'w01870': ('разделить', 'bölmek'),
    'w01873': ('прочить', '(bir göreve) aday göstermek, öngörmek'),
    'w01875': ('открыться', 'açılmak'),
    'w01877': ('обеспечить', 'sağlamak, temin etmek'),
    'w01885': ('советовать', 'öneride bulunmak, tavsiye etmek'),
    'w01887': ('мелочь', 'bozuk para / önemsiz şey'),
    'w01899': ('отличаться', 'farklı olmak, ayrılmak (bir özellikle)'),
    'w01911': ('образование', 'eğitim, öğrenim'),
    'w01914': ('палата', 'koğuş (hastane) / meclis (parlamento)'),
    'w01917': ('фанат', 'hayran, taraftar'),
    'w01925': ('лечить', 'tedavi etmek'),
    'w01927': ('незаконный', 'yasadışı, kanunsuz'),
    'w01931': ('поспорить', 'tartışmak, iddiaya girmek'),
    'w01934': ('забить', 'çakmak (çivi), gol atmak (futbol)'),
    'w01943': ('намерение', 'niyet'),
    'w01944': ('повернуть', 'döndürmek, çevirmek'),
    'w01953': ('сердиться', 'kızmak, sinirlenmek'),
    'w01964': ('подготовка', 'hazırlık'),
    'w01967': ('фраза', 'ibare, cümlecik'),
    'w01997': ('прибыль', 'kâr, kazanç'),
    'w02000': ('надевать', 'giymek, takmak'),
    'w02025': ('отчёт', 'rapor'),
    'w02027': ('шикарный', 'şık, lüks'),
    'w02038': ('портить', 'bozmak, mahvetmek'),
    'w02041': ('фальшивый', 'sahte, taklit'),
    'w02044': ('поход', 'gezi, sefer'),
    'w02051': ('справедливый', 'adil, doğru'),
    'w02058': ('картинка', 'resim, görsel'),
    'w02082': ('отнять', 'almak, elinden almak'),
    'w02087': ('обладать', 'sahip olmak'),
    'w02111': ('падение', 'düşüş, düşme'),
    'w02128': ('сведение', 'bilgi / indirgeme'),
    'w02175': ('подразделение', 'alt birim, departman'),
    'w02186': ('поражение', 'yenilgi, mağlubiyet'),
    'w02188': ('доставать', '(uzanıp) almak, elde etmek'),
    'w02204': ('указать', 'belirtmek, göstermek'),
    'w02220': ('оказать', '(yardım vb.) sağlamak, göstermek'),
    'w02227': ('охранять', 'gözetmek, korumak'),
    'w02257': ('увеличить', 'artırmak, büyütmek'),
    'w02264': ('достоинство', 'onur, haysiyet / liyakat (bağlama göre)'),
    'w02265': ('свести', 'bir araya getirmek, tanıştırmak / (bağlama göre) indirgemek'),
    'w02280': ('вылечить', 'iyileştirmek, tedavi etmek'),
    'w02315': ('годиться', 'işe yaramak, uygun olmak'),
    'w02335': ('обойти', 'etrafından dolaşmak, atlatmak'),
    'w02368': ('удивиться', 'şaşırmak'),
    'w02425': ('благой', 'hayırlı, iyi (yüce anlamda)'),
    'w02479': ('фигура', 'figür, şekil'),
    'w02504': ('жаждать', 'susamak, arzulamak'),
    'w02509': ('напряжение', 'gerilim, gerginlik'),
    'w02545': ('плыть', 'yüzmek'),
    'w02554': ('ресурс', 'kaynak'),
    'w02578': ('представиться', 'kendini tanıtmak / (fırsat için) çıkmak, görünmek'),
    'w02593': ('этап', 'safha, aşama'),
    'w02594': ('добыча', 'ganimet, av'),
    'w02613': ('сплошной', 'sürekli, kesintisiz'),
    'w02624': ('завершить', 'tamamlamak, bitirmek'),
    'w02628': ('строй', 'düzen, dizi (askeri saf)'),
    'w02646': ('сражение', 'savaş, muharebe'),
    'w02660': ('вырезать', 'kesmek, oymak'),
    'w02673': ('экскурсия', 'gezi, tur'),
    'w02721': ('уронить', 'düşürmek'),
    'w02727': ('частица', 'parçacık (fizik) / takı (dilbilgisi)'),
    'w02739': ('отсутствовать', 'bulunmamak, yok olmak'),
    'w02749': ('избранный', 'seçilmiş, seçkin'),
    'w02755': ('иметься', 'bulunmak, mevcut olmak'),
    'w02817': ('засада', 'pusu, tuzak'),
    'w02823': ('вытаскивать', 'çekip çıkarmak'),
    'w02832': ('парок', 'buhar, buharcık'),
    'w02835': ('направиться', 'yönelmek'),
    'w02847': ('слать', 'göndermek, yollamak'),
    'w02854': ('насладиться', 'keyfini çıkarmak, tadını çıkarmak'),
    'w02863': ('запуск', 'başlatma, fırlatma'),
    'w02925': ('набирать', 'toplamak, kazanmak'),
    'w02949': ('выдающийся', 'seçkin, olağanüstü'),
    'w02957': ('пробраться', 'sızmak, gizlice geçmek'),
    'w02984': ('езжать', '(araçla) gidip gelmek'),
    'w02994': ('выводить', 'dışarı çıkarmak, (leke/haşere) gidermek'),
    'w02995': ('врезать', '(sertçe) vurmak'),
    'w03007': ('рядовой', 'er (asker) / sıradan, olağan'),
    'w03021': ('стая', 'sürü'),
    'w03032': ('профиль', 'profil'),
    'w03039': ('ключевой', 'anahtar niteliğinde, kilit'),
    'w03091': ('погубить', 'mahvetmek, yok etmek'),
    'w03140': ('выставлять', 'sergilemek, öne sürmek (aday için)'),
    'w03186': ('возить', 'taşımak, götürüp getirmek (araçla)'),
    'w03211': ('высказать', 'dile getirmek, ifade etmek'),
    'w03217': ('раковина', 'lavabo (mutfak/banyo) / kabuk (deniz kabuğu)'),
    'w03220': ('напасть', 'bela, felaket'),
    'w03221': ('чинить', 'tamir etmek, düzeltmek'),
    'w03222': ('глоток', 'yudum'),
    'w03224': ('командный', 'takım+, takıma ait'),
    'w03239': ('толочь', 'ezmek, dövmek (havanda)'),
    'w03254': ('уговор', 'anlaşma, sözleşme'),
    'w03266': ('разыгрывать', 'oynamak, çekiliş yapmak'),
    'w03272': ('исходить', 'kaynaklanmak, ileri gelmek'),
    'w03318': ('совать', 'sokmak, tıkıştırmak'),
    'w03341': ('приставать', 'musallat olmak, sataşmak'),
    'w03386': ('лихорадка', 'ateş (hastalık), telaş/çılgınlık (mecazi)'),
    'w03425': ('выдвинуть', 'öne sürmek, ileri sürmek'),
    'w03442': ('бумажка', 'kağıt parçası, kağıt'),
    'w03448': ('заложить', 'rehin vermek, ipotek etmek / temelini atmak'),
    'w03452': ('поиметь', 'elde etmek'),
    'w03459': ('раздеваться', 'soyunmak'),
    'w03467': ('порядочный', 'dürüst, terbiyeli'),
    'w03481': ('нота', 'nota (müzik/diplomatik)'),
    'w03500': ('вынуть', 'çıkarmak'),
    'w03508': ('возглавить', 'başında olmak, yönetmek'),
    'w03530': ('осудить', 'kınamak, mahkum etmek'),
    'w03572': ('возглавлять', 'yönetmek, başında olmak'),
    'w03575': ('стадо', 'sürü'),
    'w03579': ('сплетня', 'dedikodu'),
    'w03584': ('соответствующий', 'uygun, ilgili'),
    'w03587': ('задыхаться', 'nefes darlığı çekmek, boğulmak'),
    'w03589': ('стареть', 'yaşlanmak'),
    'w03624': ('мыло', 'sabun'),
    'w03654': ('завершение', 'tamamlanma, bitiş'),
    'w03660': ('разыграть', 'oynamak, çekiliş yapmak'),
    'w03669': ('вытворять', '(tuhaf şeyler) yapmak, çıkarmak'),
    'w03673': ('перевозка', 'ulaştırma, nakliye'),
    'w03693': ('лопнуть', 'patlamak'),
    'w03711': ('катер', 'motorbot, deniz taşıtı'),
    'w03716': ('пинок', 'tekme'),
    'w03720': ('хвастаться', 'övünmek, böbürlenmek'),
    'w03746': ('ветка', 'dal'),
    'w03784': ('сострадание', 'merhamet, şefkat'),
    'w03799': ('баллотироваться', 'adaylığını koymak, seçime girmek'),
    'w03823': ('водный', 'su ile ilgili, sucul'),
    'w03842': ('сунуть', 'sokmak, tıkıştırmak'),
    'w03866': ('неожиданность', 'sürpriz, beklenmedik şey'),
    'w04104': ('выдвигать', 'öne sürmek, ileri sürmek (öneri/aday için)'),
    'w04115': ('порода', 'cins, ırk (hayvan) / kaya türü (jeoloji)'),
    'w04142': ('имидж', 'imaj, görüntü'),
    'w04146': ('курок', 'tetik'),
    'w04147': ('ля', 'la (nota) / (argo bir ünlem)'),
    'w04175': ('купюра', 'kâğıt para, banknot'),
    'w04259': ('отход', 'geri çekilme, ayrılma'),
    'w04273': ('амбар', 'ambar, tahıl ambarı'),
    'w04294': ('успешно', 'başarıyla'),
    'w04315': ('обходить', 'dolaşmak, etrafından geçmek'),
    'w04321': ('исцелить', 'iyileştirmek, şifa vermek'),
    'w04333': ('тусовка', 'takılma, eğlenti'),
    'w04381': ('уносить', 'götürmek, taşımak (alıp götürmek)'),
    'w04406': ('исправлять', 'düzeltmek, tamir etmek'),
    'w04471': ('раздеть', 'soymak, üstünü çıkarmak'),
    'w04477': ('стон', 'inilti'),
    'w04492': ('гнусный', 'iğrenç, alçakça'),
    'w04493': ('карманный', 'cep boyu, cepte taşınan'),
    'w04547': ('разрывать', 'yırtmak, koparmak'),
    'w04572': ('удачно', 'başarıyla, şansla'),
    'w04580': ('зрелый', 'olgun'),
    'w04601': ('промах', 'gaf, hata'),
    'w04605': ('опасение', 'endişe, kaygı'),
    'w04613': ('увеличивать', 'artırmak, büyütmek'),
    'w04620': ('отключать', 'kapatmak, bağlantısını kesmek'),
    'w04648': ('пересекаться', 'kesişmek'),
    'w04653': ('ломаться', 'bozulmak, kırılmak'),
    'w04670': ('возвратиться', 'dönmek'),
    'w04711': ('возмездие', 'intikam, ceza'),
    'w04738': ('кровяной', 'kanla ilgili, kan+'),
    'w04777': ('холостой', 'bekâr / boş, kurusıkı (bağlama göre)'),
    'w04778': ('взлетать', 'havalanmak, kalkış yapmak'),
    'w04822': ('кровный', 'kan bağı olan, öz'),
    'w04837': ('заработок', 'kazanç'),
    'w04862': ('угробить', 'mahvetmek, öldürmek (argo)'),
    'w04866': ('состариться', 'yaşlanmak, ihtiyarlamak'),
    'w04873': ('коробочка', 'kutucuk'),
    'w04889': ('косточка', 'çekirdek (meyve), kemikçik'),
    'w04949': ('наклониться', 'eğilmek'),
    'w04951': ('приютить', 'barındırmak, sığınak vermek'),
    'w04957': ('помещать', 'yerleştirmek, koymak'),
    'w04982': ('взор', 'bakış, nazar'),
    'w04998': ('окраина', 'kenar mahalle, dış mahalle'),
    'w05023': ('сбавить', 'azaltmak, indirmek'),
    'w05028': ('выдерживать', 'dayanmak, katlanmak'),
    'w05031': ('постановление', 'karar, kararname'),
    'w05045': ('турне', 'tur, turne'),
    'w05047': ('икра', 'havyar / baldır (bağlama göre)'),
    'w05054': ('переборщить', 'abartmak, aşırıya kaçmak'),
    'w05066': ('сыпать', 'dökmek, saçmak (taneli madde için)'),
    'w05078': ('взламывать', 'kırıp girmek, hacklemek'),
    'w05081': ('клочок', 'parça, kırpıntı'),
    'w05086': ('урна', 'çöp kutusu, sandık (oy sandığı)'),
    'w05101': ('щель', 'yarık, çatlak'),
    'w05108': ('зарядка', 'şarj (etme) / (sabah) jimnastiği'),
    'w05124': ('довезти', '(birini bir yere) götürmek, bırakmak'),
    'w05134': ('ранг', 'rütbe, derece'),
    'w05143': ('скважина', 'kuyu (petrol/su kuyusu)'),
    'w05151': ('увеличиваться', 'artmak, büyümek'),
    'w05192': ('вынимать', 'çıkarmak, dışarı almak'),
    'w05198': ('глушить', 'bastırmak (sesi), susturmak'),
    'w05205': ('пригодный', 'uygun, elverişli'),
    'w05211': ('стычка', 'çarpışma, çatışma'),
    'w05232': ('глазной', 'göze ait, göz+'),
    'w05235': ('булавка', 'toplu iğne'),
    'w05274': ('прозвать', 'lakap takmak'),
    'w05280': ('приобретение', 'edinim, kazanım'),
    'w05289': ('улучшиться', 'iyileşmek, düzelmek'),
    'w05328': ('проволока', 'tel'),
    'w05335': ('бит', 'bit (bilgisayar) / bit (müzik ritmi)'),
    'w05344': ('ветерок', 'esinti, meltem'),
    'w05354': ('часовой', 'nöbetçi (isim) / saatlik, saate ait (sıfat)'),
    'w05362': ('проклясть', 'lanetlemek, beddua etmek'),
    'w05381': ('шустрый', 'çevik, atik'),
    'w05415': ('захлопнуть', 'çarpıp kapatmak (kapıyı)'),
    'w05434': ('лазить', 'tırmanmak, (argo) karıştırmak/eşelemek'),
    'w05496': ('лот', 'iskandil, çekül'),
    'w05513': ('наём', 'kiralama, işe alma'),
    'w05515': ('гул', 'uğultu, gürültü'),
    'w05559': ('экспонат', 'sergilenen eser, obje'),
    'w05573': ('объехать', 'araçla dolaşmak, etrafından geçmek (araçla)'),
    'w05587': ('клеймо', 'damga, leke (mecazi)'),
    'w05695': ('наземный', 'yerüstü, karasal'),
    'w05716': ('фанатка', 'hayran (kadın)'),
    'w05724': ('дуло', 'namlu (ağzı)'),
    'w05731': ('скрестить', 'çaprazlamak, melezlemek'),
    'w05755': ('шпилька', 'toka, stiletto (topuk)'),
    'w05769': ('воздействовать', 'etkilemek'),
    'w05775': ('задумка', 'fikir, tasarı'),
    'w05791': ('перемещать', 'taşımak, yer değiştirmek'),
    'w05862': ('освоить', 'öğrenmek, edinmek (bir beceriyi)'),
    'w05870': ('потоп', 'sel, tufan'),
    'w05871': ('крестить', 'vaftiz etmek'),
    'w05872': ('раздражение', 'sinirlenme, tahriş'),
    'w05925': ('проколоть', 'delmek, iğnelemek'),
    'w05948': ('вредно', 'zararlı'),
    'w05981': ('дротик', 'cirit, dart'),
    'w05989': ('высказывать', 'dile getirmek, ifade etmek'),
    'w05992': ('треск', 'çatırtı, çatlama sesi'),
    'w06040': ('приключиться', 'başına gelmek, olmak (aniden)'),
    'w06065': ('перегибать', 'fazla bükmek, abartmak'),
    'w06074': ('сак', 'çanta, torba'),
    'w06099': ('семеро', 'yedisi (birlikte)'),
    'w06100': ('крестик', 'haç, küçük haç'),
    'w06140': ('топливный', 'yakıtla ilgili, yakıt+'),
    'w06159': ('привлекательность', 'çekicilik'),
    'w06181': ('швырять', 'fırlatmak, savurmak'),
    'w06190': ('построение', 'oluşturma, yapı'),
    'w06234': ('согнуть', 'bükmek, eğmek'),
    'w06240': ('присущий', 'özgü, has'),
    'w06252': ('течь', "sızıntı, delik (isim anlamı için); fiil ise 'akmak' doğru"),
    'w06261': ('переделывать', 'yeniden yapmak, değiştirmek'),
    'w06304': ('затвор', 'kilit/sürgü mekanizması, obtüratör (kamera)'),
    'w06344': ('косить', 'biçmek, kaytarmak'),
    'w06350': ('толковый', 'akıllı, becerikli'),
    'w06427': ('бушевать', 'şiddetle yanmak/esmek, kudurmak (mecazi)'),
    'w06548': ('мазать', '(sürmek doğru; ayrıca argo anlamı: atışta) ıskalamak'),
    'w06605': ('формат', 'format, biçim'),
    'w06643': ('пренебрежение', 'ihmal, küçümseme'),
    'w06654': ('брести', 'sürüklenerek yürümek, ağır ağır yürümek'),
    'w06718': ('камушек', 'çakıl taşı, taşcık'),
    'w06722': ('рыскать', 'dolaşıp aramak, gezinmek (arayarak)'),
    'w06731': ('разжигать', 'tutuşturmak, kışkırtmak (mecazi)'),
    'w06738': ('исцелять', 'iyileştirmek'),
    'w06851': ('кляп', 'tıkaç, ağız tıkacı'),
    'w06854': ('рулон', 'rulo, top (kumaş/kağıt)'),
    'w06860': ('шерстяной', 'yünlü'),
    'w06869': ('сообщаться', 'bağlantılı olmak, birbirine açılmak'),
    'w06882': ('рубка', 'köşk, kabin (gemi) / kesme (odun için)'),
    'w06887': ('пунктуальный', 'dakik'),
    'w06892': ('ишь', 'bak sen!, vay canına'),
    'w06900': ('транслировать', 'yayınlamak, yayımlamak'),
    'w06903': ('подшучивать', 'takılmak, şaka yapmak (birine)'),
    'w06917': ('праздный', 'aylak, tembel'),
    'w06930': ('браток', 'kardeşim, dostum (hitap sözü)'),
    'w06941': ('тереться', 'sürtünmek'),
    'w06953': ('простак', 'saf kimse, safdil'),
    'w06962': ('сума', 'torba, çanta'),
    'w06970': ('выколоть', 'oymak, çıkarmak (göz için)'),
    'w06975': ('пищевод', 'yemek borusu'),
    'w06980': ('миловать', 'bağışlamak, affetmek'),
    'w06989': ('размять', 'ezmek, esnetmek'),
    'w07032': ('преклонить', 'eğmek (diz çökmek için)'),
    'w07043': ('усугубить', 'kötüleştirmek, ağırlaştırmak'),
    'w07049': ('дегенерат', 'dejenere (kişi), soysuzlaşmış kişi'),
    'w07057': ('нарядный', 'şık, süslü'),
    'w07076': ('водяной', 'suya ait / (mitolojide) su cini'),
    'w07094': ('вахта', 'nöbet (vardiya)'),
    'w07114': ('деление', 'bölme, bölüm'),
    'w07115': ('разрубить', 'kesmek, parçalamak (balta ile)'),
    'w07137': ('кожура', 'kabuk'),
    'w07142': ('немка', 'Alman kadın/kız'),
    'w07144': ('конспект', 'özet, not'),
    'w07204': ('запихивать', 'tıkıştırmak, doldurmak (bir şeyin içine sokmak)'),
    'w07227': ('замаскировать', 'kılık değiştirmek, gizlemek'),
    'w07251': ('каяться', 'pişman olmak, tövbe etmek'),
    'w07283': ('болотный', 'bataklık+, bataklığa ait'),
    'w07285': ('разить', 'kokmak (kötü/keskin)'),
    'w07308': ('пролёт', 'açıklık, merdiven kolu'),
    'w07309': ('навес', 'sundurma, gölgelik'),
    'w07355': ('дека', 'tabla, gövde (çalgı parçası)'),
    'w07357': ('укладка', 'saç şekillendirme / istifleme'),
    'w07362': ('бур', 'burgu, matkap (alet) / Bur (halk, büyük harfle)'),
    'w07376': ('шлепок', 'şaplak, tokat'),
    'w07427': ('синь', 'mavilik, gökyüzü mavisi'),
    'w07428': ('световой', 'ışıkla ilgili, ışık+'),
    'w07439': ('упрашивать', 'yalvarmak, rica etmek'),
    'w07474': ('очертание', 'ana hat, çevrim'),
    'w07486': ('прихлопнуть', 'vurup öldürmek (sinek vb.), çarpıp kapatmak'),
    'w07499': ('гулянка', 'eğlence, âlem'),
    'w07519': ('конюх', 'seyis'),
    'w07522': ('отморозок', 'gaddar/acımasız kişi, it herif'),
    'w07536': ('сгладить', 'yumuşatmak, gidermek (etkisini)'),
    'w07539': ('поучать', 'ders vermek, nasihat etmek (küçümseyerek)'),
    'w07564': ('бойкий', 'canlı, atılgan'),
    'w07614': ('плавка', 'döküm, eritme (metalürji)'),
    'w07615': ('бусы', 'boncuklar'),
    'w07739': ('голодовка', 'açlık grevi'),
    'w07754': ('прищемить', 'sıkıştırmak, kıstırmak'),
    'w07846': ('выматывать', 'yormak, tüketmek'),
    'w07857': ('вентиль', 'vana, valf'),
    'w07865': ('скоротать', 'geçirmek (vakit)'),
    'w07889': ('бесцельный', 'amaçsız'),
    'w07911': ('вожделение', 'arzu, şehvet'),
    'w07914': ('упереться', 'dayanmak, inat etmek'),
    'w07966': ('вспылить', 'öfkelenmek, tepesi atmak'),
    'w07996': ('пилотировать', 'pilotluk yapmak, uçurmak'),
    'w08003': ('подлететь', 'yaklaşarak uçmak, süzülerek gelmek'),
    'w08019': ('лоскут', 'parça, kırpıntı (kumaş)'),
    'w08152': ('подножка', 'basamak'),
    'w08197': ('адресат', 'alıcı, muhatap'),
    'w08212': ('сгибать', 'bükmek, eğmek'),
    'w08229': ('сгубить', 'mahvetmek, yıkmak'),
    'w08242': ('сплетник', 'dedikoducu'),
    'w08262': ('заминировать', 'mayınlamak'),
    'w08275': ('умысел', 'kasıt, niyet'),
    'w08290': ('скорбный', 'yaslı, hüzünlü'),
    'w08292': ('куль', 'çuval'),
    'w08300': ('ящичек', 'kutucuk, çekmece'),
    'w08308': ('клянчить', 'dilenmek, sızlanarak istemek'),
    'w08312': ('заплатка', 'yama'),
    'w08322': ('изыскание', 'araştırma, inceleme'),
    'w08327': ('глумиться', 'alay etmek, küçümsemek'),
    'w08339': ('обнажать', 'açığa çıkarmak, soymak (deri/yara için)'),
    'w08340': ('вымотать', 'yormak, bitkin düşürmek'),
    'w08372': ('половица', 'döşeme tahtası'),
    'w08376': ('дрейфить', 'korkmak, ödleklik etmek'),
    'w08415': ('расщелина', 'çatlak, yarık'),
    'w08418': ('степ', 'step (dansı), adım'),
    'w08477': ('долбануть', 'vurmak, çakmak (argo)'),
    'w08502': ('навар', 'kâr (argo), et suyu (yemek)'),
    'w08508': ('осваивать', 'öğrenmek, edinmek'),
    'w08527': ('мщение', 'intikam, öç'),
    'w08540': ('передразнивать', 'taklidini yapmak (alay ederek)'),
    'w08547': ('ковш', 'kepçe'),
    'w08552': ('кутузка', 'kodes, hapishane (argo)'),
    'w08592': ('давиться', 'boğulmak (yerken)'),
    'w08624': ('барахтаться', 'çırpınmak'),
    'w08630': ('брань', 'küfür, ağız kavgası'),
    'w08652': ('отличающийся', 'farklı, farklılaşan'),
    'w08657': ('короб', 'kutu, sandık'),
    'w08702': ('пастись', 'otlamak'),
    'w08709': ('реверанс', 'reverans'),
    'w08716': ('перебранка', 'atışma, ağız kavgası'),
    'w08723': ('смердеть', 'pis kokmak'),
    'w08759': ('возобновлять', 'yenilemek, yeniden başlatmak'),
    'w08850': ('прокалывать', 'delmek, iğnelemek'),
    'w08883': ('уравнивать', 'eşitlemek'),
    'w08898': ('вкушать', 'tatmak, yemekten zevk almak'),
    'w08906': ('сердцевина', 'öz, çekirdek'),
    'w08924': ('перегружать', 'aşırı yüklemek'),
    'w08939': ('трак', 'palet parçası, tırtıl (araç parçası)'),
    'w08992': ('адресный', 'hedefe yönelik, adrese özgü'),
}

# Ornek cumlesi kelimeyle uyusmayan kayitlar.
REPORT_CLEAR_EXAMPLE = {
    'w00055',  # мочь
    'w00375',  # тереть
    'w00422',  # ранний
    'w00480',  # прислать
    'w00499',  # радостный
    'w01236',  # модель
    'w01263',  # симпатичный
    'w01605',  # мина
    'w01606',  # выше
    'w02061',  # биться
    'w02140',  # кутить
    'w02210',  # пушок
    'w03239',  # толочь
    'w03514',  # махать
    'w04740',  # меткий
    'w05434',  # лазить
    'w06344',  # косить
    'w06548',  # мазать
    'w06980',  # миловать
    'w06989',  # размять
    'w07615',  # бусы
    'w08498',  # зимовать
    'w08573',  # киснуть
}

# Tur etiketi yanlis olanlar.
#
# Son ucu raporun aciklama sutununda ("tur='noun' iken ...") gecti ama oneri
# sutununda ceviri yazdigi icin ilk geciste yalnizca ceviri uygulanmisti;
# etiket isim olarak kalmisti.
REPORT_POS = {
    'w00048': 'verb',  # знать
    'w08417': 'verb',  # выть
    'w00055': 'verb',  # мочь — yardimci fiil, 'guc' isim cevirisinden kalmisti
    'w00362': 'verb',  # стать — cevirisi "olmak", isim anlami arkaik
    'w06252': 'verb',  # течь — cevirisi fiil ("akmak"), isim anlami ayri kayit
}
