# -*- coding: utf-8 -*-
"""Besinci tur: son ve detayli denetim raporu (2026-08-18).

Kaynak: words_all.csv (8992 satir) 450 satirlik 20 parcaya bolunup
her parca ayri ajanla hem baslik kelime hem ornek cumle acisindan
tarandi. Bu dosya raporun BOLUM 1'ini (baslik kelime cevirileri)
tasiyor.

Raporun oneri sutunu aciklama da tasiyordu ("baba (verilen ikinci
anlam ata yanlis)"); aciklamalar ayiklandi, yalnizca cevirinin
kendisi alindi. Ayiklanamayan satirlar elle gozden gecirildi.
"""

REPORT5_TR = {
    'w00096': ('парень', 'delikanlı, erkek arkadaş'),
    'w00099': ('отец', 'baba'),
    'w00100': ('уж', '(isim) kolan yılanı, zehirsiz yılan türü'),
    'w00329': ('свет', 'ışık, dünya'),
    'w00459': ('кое-что', 'bir şey (belirsiz)'),
    'w00512': ('крутой', 'dik, sert; (argo) harika/süper'),
    'w00534': ('штука', 'şey (nesne), adet'),
    'w00556': ('известный', 'bilinen, malum; meşhur'),
    'w00600': ('носить', 'giymek, taşımak'),
    'w00624': ('карта', 'kart (oyun kağıdı), harita'),
    'w00687': ('штат', 'eyalet, personel (kadro)'),
    'w00746': ('род', 'cins, tür, soy'),
    'w00768': ('армия', 'ordu'),
    'w00802': ('убедиться', 'emin olmak, ikna olmak'),
    'w00804': ('куча', 'yığın, (çok fazla/bir sürü)'),
    'w00837': ('ошибаться', 'yanılmak, hata yapmak'),
    'w00867': ('вариант', 'seçenek, alternatif'),
    'w00968': ('кусок', 'parça, lokma'),
    'w00992': ('святой', 'aziz, ermiş'),
    'w00993': ('трубка', 'ahize (telefon), boru/tüp'),
    'w01032': ('начинаться', 'başlamak'),
    'w01049': ('исследование', 'araştırma, inceleme'),
    'w01071': ('менять', 'değiştirmek'),
    'w01213': ('болеть', 'ağrımak, hasta olmak'),
    'w01227': ('тест', 'test, sınav'),
    'w01260': ('домашний', 'ev, eve ait'),
    'w01381': ('испытывать', 'hissetmek, yaşamak (bir duyguyu)'),
    'w01403': ('выступать', 'konuşma yapmak, (bir görüşü) savunmak'),
    'w01461': ('изучать', 'öğrenmek, incelemek'),
    'w01473': ('пост', 'görev, makam'),
    'w01476': ('передача', 'program, yayın'),
    'w01488': ('банка', 'kavanoz, teneke kutu'),
    'w01489': ('интервью', 'röportaj, mülakat'),
    'w01500': ('создание', 'yaratık, yaratma'),
    'w01510': ('квартал', '(şehir) blok, çeyrek (yıl)'),
    'w01591': ('мотив', 'motif, sebep'),
    'w01616': ('рост', 'boy (uzunluk), büyüme'),
    'w01627': ('эфир', 'yayın, (kimyasal) eter'),
    'w01736': ('повреждение', 'hasar, yaralanma'),
    'w01751': ('открытие', 'açılış, keşif'),
    'w01797': ('док', 'rıhtım, yükleme rampası'),
    'w01809': ('снег', 'kar'),
    'w01916': ('удалить', 'silmek, kaldırmak'),
    'w01954': ('оборудование', 'ekipman, teçhizat'),
    'w01995': ('простой', 'basit, kolay'),
    'w02100': ('несчастье', 'talihsizlik, felaket'),
    'w02103': ('выносить', 'dayanmak, katlanmak; (ders vb.) çıkarmak'),
    'w02179': ('бак', 'tank, depo (genel kap)'),
    'w02527': ('галактика', 'galaksi'),
    'w02540': ('прелестный', 'sevimli, güzel'),
    'w02568': ('подтверждение', 'doğrulama, teyit'),
    'w02597': ('прыжок', 'atlama, sıçrama'),
    'w02783': ('сфера', 'alan, küre'),
    'w02805': ('разделять', 'paylaşmak, katılmak (bir görüşe)'),
    'w02822': ('сарай', 'ambar, kulübe, depo'),
    'w02915': ('оборот', 'dönme, devir'),
    'w02959': ('произведение', 'eser, çarpım (matematikte)'),
    'w02985': ('духи', 'parfüm, ruhlar (manevi varlık)'),
    'w03065': ('воспитывать', 'yetiştirmek, terbiye etmek'),
    'w03100': ('заброшенный', 'terk edilmiş, bakımsız'),
    'w03103': ('близнец', 'ikiz'),
    'w03105': ('настроить', 'ayarlamak, kurmak'),
    'w03116': ('поворачивать', 'dönmek, çevirmek'),
    'w03119': ('убеждение', 'ikna, inanç/kanaat'),
    'w03120': ('взлететь', 'havalanmak, uçuşa geçmek'),
    'w03121': ('презентация', 'sunum, prezentasyon'),
    'w03122': ('соответствие', 'uygunluk, uyum'),
    'w03125': ('взволнованный', 'heyecanlı, telaşlı'),
    'w03129': ('задержка', 'gecikme'),
    'w03131': ('узел', 'düğüm'),
    'w03132': ('выгодный', 'kazançlı, avantajlı'),
    'w03133': ('сложность', 'karmaşıklık, zorluk'),
    'w03134': ('разглядеть', 'fark etmek, seçebilmek'),
    'w03143': ('периметр', 'çevre'),
    'w03147': ('критический', 'kritik, tehlikeli'),
    'w03157': ('покрывать', 'örtmek, kaplamak'),
    'w03160': ('разработка', 'geliştirme, gelişme'),
    'w03162': ('несовершеннолетний', 'reşit olmayan, küçük'),
    'w03167': ('перевозить', 'taşımak, nakletmek'),
    'w03168': ('аккуратный', 'düzenli, özenli'),
    'w03177': ('сосуд', 'kap, kase'),
    'w03180': ('рыбалка', 'balık tutma'),
    'w03182': ('орбита', 'yörünge'),
    'w03183': ('поставщик', 'tedarikçi'),
    'w03189': ('побочный', 'yan, ikincil'),
    'w03203': ('кодекс', 'kanun, yasa metni'),
    'w03208': ('окружение', 'etraf, çevre'),
    'w03210': ('парик', 'peruk'),
    'w03215': ('ядро', 'çekirdek, öz'),
    'w03227': ('литература', 'yazın, literatür'),
    'w03258': ('волнение', 'heyecan, kaygı'),
    'w03267': ('стойка', 'tezgah, masa'),
    'w03276': ('копаться', 'eşmek, karıştırmak'),
    'w03278': ('прикоснуться', 'dokunmak, değmek'),
    'w03281': ('воспитание', 'yetiştirme, terbiye'),
    'w03293': ('коляска', 'tekerlekli sandalye, çocuk arabası'),
    'w03310': ('каюта', 'kamara'),
    'w03314': ('вторжение', 'istila'),
    'w03321': ('повязка', 'sargı, bandaj'),
    'w03331': ('походить', 'andırmak, benzemek'),
    'w03349': ('вводить', 'sokmak, dahil etmek'),
    'w03350': ('ядовитый', 'zehirli'),
    'w03354': ('резюме', 'özgeçmiş'),
    'w03361': ('ива', 'söğüt'),
    'w03380': ('ограничение', 'kısıtlama, sınırlama'),
    'w03385': ('петля', 'menteşe, halka'),
    'w03390': ('всемогущий', 'her şeye kadir, kadir-i mutlak'),
    'w03393': ('угощать', 'ikram etmek, ısmarlamak'),
    'w03396': ('люцифер', 'Lüsifer'),
    'w03401': ('хищник', 'yırtıcı hayvan, avcı'),
    'w03410': ('призывать', 'çağırmak, teşvik etmek'),
    'w03417': ('смыть', 'yıkamak, sürüklemek'),
    'w03418': ('заявка', 'başvuru, talep'),
    'w03420': ('рвать', 'yırtmak, koparmak'),
    'w03426': ('дельфин', 'yunus'),
    'w03428': ('телохранитель', 'koruma, muhafız'),
    'w03429': ('вертолёт', 'helikopter'),
    'w03434': ('панель', 'panel, gösterge paneli'),
    'w03461': ('постановка', 'kurma, oluşturma'),
    'w03484': ('устоять', 'dayanmak, direnmek'),
    'w03504': ('столетие', 'yüzyıl'),
    'w03507': ('кубок', 'kupa'),
    'w03512': ('портал', 'geçit, kapı'),
    'w03525': ('скакать', 'sıçramak, dörtnal gitmek'),
    'w03527': ('интеллект', 'zekâ, akıl'),
    'w03538': ('дотронуться', 'dokunmak'),
    'w03551': ('еле', 'zar zor, güçlükle'),
    'w03558': ('импульс', 'dürtü, sinyal'),
    'w03562': ('обеспокоенный', 'endişeli, kaygılı'),
    'w03566': ('плотный', 'yoğun, sıkı'),
    'w03580': ('громко', 'yüksek sesle, gürültüyle'),
    'w03583': ('разводиться', 'boşanmak, üremek'),
    'w03596': ('обходиться', 'mal olmak, idare etmek'),
    'w03612': ('попка', 'popo, kıç'),
    'w03613': ('терпеливый', 'sabırlı'),
    'w03614': ('душевный', 'içten, sıcakkanlı'),
    'w03621': ('одобрение', 'onay, tasvip'),
    'w03626': ('сомнительный', 'şüpheli, kuşkulu'),
    'w03627': ('пожелание', 'dilek, istek'),
    'w03636': ('сбивать', 'çarpmak (araçla), düşürmek'),
    'w03639': ('певица', 'şarkıcı (kadın)'),
    'w03640': ('активировать', 'etkinleştirmek, aktive etmek'),
    'w03641': ('спор', 'tartışma, çekişme'),
    'w03646': ('закричать', 'bağırmak, çığlık atmak'),
    'w03648': ('соединение', 'bileşik, bağlantı'),
    'w03662': ('слить', 'sızdırmak, akıtmak'),
    'w03663': ('увлекаться', 'ilgilenmek, düşkün olmak'),
    'w03671': ('заботливый', 'şefkatli, düşünceli'),
    'w03672': ('письменный', 'yazılı'),
    'w03677': ('отражение', 'yansıma, görüntü'),
    'w03698': ('неуместный', 'yersiz, uygunsuz'),
    'w03700': ('искренне', 'içtenlikle, samimiyetle'),
    'w03718': ('лампочка', 'ampul'),
    'w03727': ('единица', 'birim, tekil'),
    'w03728': ('удивление', 'hayret, şaşkınlık'),
    'w03767': ('разоблачить', 'ifşa etmek, maskesini düşürmek'),
    'w03769': ('самостоятельно', 'kendi başına, bağımsızca'),
    'w03771': ('виза', 'vize'),
    'w03772': ('энергетический', 'enerji ile ilgili, enerjik'),
    'w03777': ('напоминание', 'hatırlatma'),
    'w03791': ('осматривать', 'muayene etmek, incelemek'),
    'w03792': ('природный', 'doğal'),
    'w03804': ('ус', 'bıyık, balen'),
    'w03808': ('обучать', 'eğitmek, öğretmek'),
    'w03816': ('терапевт', 'terapist, pratisyen hekim'),
    'w03830': ('гадать', 'tahmin etmek, fal bakmak'),
    'w03838': ('правдивый', 'doğru, gerçeği yansıtan'),
    'w03851': ('крепко', 'sıkıca, derin (uykuda)'),
    'w03856': ('утверждение', 'iddia, ifade'),
    'w03860': ('повышать', 'artırmak, yükseltmek'),
    'w03870': ('запирать', 'kilitlemek'),
    'w03881': ('гроза', 'fırtına, gök gürültülü fırtına'),
    'w03887': ('стремление', 'arzu, gayret, çaba'),
    'w03890': ('допустимый', 'kabul edilebilir, caiz'),
    'w03892': ('скользкий', 'kaygan'),
    'w04019': ('сердцебиение', 'kalp atışı'),
    'w04036': ('косяк', 'kapı pervazı, balık sürüsü'),
    'w04088': ('воображаемый', 'hayali, imgesel'),
    'w04096': ('дуга', 'yay, kavis'),
    'w04099': ('упорный', 'azimli, inatçı'),
    'w04111': ('семейка', 'ailecik, aile'),
    'w04114': ('освобождать', 'serbest bırakmak, özgürleştirmek'),
    'w04122': ('перебивать', 'sözünü kesmek, lafını kesmek'),
    'w04124': ('предназначение', 'amaç, kader'),
    'w04135': ('возврат', 'iade, geri verme'),
    'w04138': ('коррупция', 'yolsuzluk, rüşvet'),
    'w04139': ('стойкий', 'dayanıklı, sağlam'),
    'w04149': ('множественный', 'çoğul, çoklu'),
    'w04152': ('отвращение', 'tiksinti, iğrenme'),
    'w04155': ('изоляция', 'yalıtım, izolasyon'),
    'w04202': ('безрассудный', 'düşüncesiz, pervasız'),
    'w04226': ('чайка', 'martı'),
    'w04236': ('производитель', 'üretici'),
    'w04241': ('жуть', 'korku, dehşet'),
    'w04242': ('начеку', 'tetikte, uyanık'),
    'w04247': ('дружка', 'sağdıç'),
    'w04248': ('магнит', 'mıknatıs'),
    'w04249': ('детектор', 'detektör, algılayıcı'),
    'w04250': ('оттенок', 'ton, nüans'),
    'w04253': ('рассуждать', 'akıl yürütmek, tartışmak'),
    'w04254': ('процветать', 'gelişmek, refah bulmak'),
    'w04257': ('вакансия', 'münhal, boş kadro'),
    'w04261': ('вафля', 'gofret, waffle'),
    'w04271': ('карета', 'at arabası, fayton'),
    'w04276': ('обыкновенный', 'sıradan, olağan'),
    'w04278': ('почтение', 'saygı, hürmet'),
    'w04282': ('сладенький', 'tatlım, canım'),
    'w04316': ('издатель', 'yayıncı, yayımcı'),
    'w04324': ('экономить', 'tasarruf etmek, biriktirmek'),
    'w04325': ('колоть', 'saplamak, bıçaklamak'),
    'w04345': ('занавеска', 'perde'),
    'w04363': ('мучительный', 'acı verici, ıstıraplı'),
    'w04374': ('сочинение', 'kompozisyon, yazı ödevi'),
    'w04379': ('проводник', 'rehber, kılavuz'),
    'w04388': ('склонный', 'eğilimli, meyilli'),
    'w04396': ('фокусник', 'sihirbaz'),
    'w04411': ('российский', "Rus, Rusya'ya ait"),
    'w04414': ('дискуссия', 'tartışma, müzakere'),
    'w04417': ('пощада', 'merhamet, af'),
    'w04419': ('ввязываться', 'karışmak, bulaşmak'),
    'w04434': ('погасить', 'söndürmek, ödeyip kapatmak'),
    'w04439': ('смешивать', 'karıştırmak'),
    'w04441': ('уставать', 'yorulmak'),
    'w04443': ('запрашивать', 'istemek, talep etmek'),
    'w04446': ('выслеживать', 'izlemek, takip etmek'),
    'w04448': ('засыпать', 'uykuya dalmak, uyuyakalmak'),
    'w04461': ('намёк', 'ima, ipucu'),
    'w04466': ('содержаться', 'bulunmak, içermek'),
    'w04468': ('компас', 'pusula'),
    'w04470': ('поп', 'papaz, popo (argo)'),
    'w04476': ('мех', 'kürk, körük'),
    'w04481': ('подъём', 'tırmanış, yükseliş'),
    'w04518': ('провожать', 'uğurlamak, eşlik etmek'),
    'w04520': ('поклоняться', 'tapmak, ibadet etmek'),
    'w04525': ('избитый', 'dövülmüş, darp edilmiş'),
    'w04532': ('последовательность', 'sıra, dizilim'),
    'w04536': ('рассеянный', 'dalgın, dağınık'),
    'w04537': ('замочить', 'ıslatmak; (argo) öldürmek'),
    'w04542': ('приговорить', 'mahkûm etmek, hüküm vermek'),
    'w04553': ('правдоподобный', 'inandırıcı, gerçekçi'),
    'w04558': ('гидра', 'hidra'),
    'w04561': ('соединять', 'birleştirmek, bağlamak'),
    'w04569': ('суша', 'kara, karasal alan'),
    'w04573': ('ягода', 'meyve, yemiş'),
    'w04575': ('стучаться', 'kapıyı çalmak, vurmak'),
    'w04587': ('выделяться', 'öne çıkmak, salgılanmak'),
    'w04597': ('восход', 'doğuş, yükseliş'),
    'w04610': ('уплыть', 'yüzerek uzaklaşmak, açılmak'),
    'w04611': ('сообразить', 'anlamak, kavramak'),
    'w04615': ('замужество', 'evlilik'),
    'w04624': ('поить', 'içirmek, su vermek'),
    'w04628': ('крах', 'çöküş, iflas'),
    'w04631': ('метка', 'işaret, etiket'),
    'w04633': ('клеить', 'yapıştırmak'),
    'w04638': ('ястреб', 'atmaca, şahin'),
    'w04646': ('штурм', 'hücum, saldırı; (mecazi) beyin fırtınası'),
    'w04647': ('клык', 'köpek dişi, azı dişi'),
    'w04657': ('характеристика', 'özellik, nitelendirme'),
    'w04660': ('разрываться', 'ikiye bölünmek, kararsız kalmak'),
    'w04663': ('превращение', 'dönüşüm'),
    'w04667': ('зловещий', 'uğursuz, kötü alâmetli'),
    'w04676': ('магистр', 'yüksek lisans, master derecesi'),
    'w04677': ('человечность', 'insanlık, insaniyet'),
    'w04679': ('похвала', 'övgü, takdir'),
    'w04680': ('отражать', 'yansıtmak'),
    'w04682': ('усталость', 'yorgunluk'),
    'w04689': ('крикнуть', 'bağırmak, haykırmak'),
    'w04703': ('хихикать', 'kıkırdamak, kıs kıs gülmek'),
    'w04704': ('запутать', 'kafasını karıştırmak, dolaştırmak'),
    'w04707': ('лужа', 'su birikintisi'),
    'w04714': ('напоследок', 'son olarak, sonunda'),
    'w04716': ('смотритель', 'bekçi, gözetici'),
    'w04723': ('густой', 'koyu, sık, gür'),
    'w04728': ('загар', 'bronzlaşma, bronz ten'),
    'w04732': ('дорожить', 'değer vermek'),
    'w04737': ('енот', 'rakun'),
    'w04738': ('кровяной', 'kanla ilgili, kana ait'),
    'w04751': ('мочиться', 'işemek, idrar yapmak'),
    'w04755': ('зашить', 'dikmek, dikiş atmak'),
    'w04757': ('лишение', 'mahrumiyet, yoksunluk'),
    'w04762': ('концентрация', 'konsantrasyon, yoğunlaşma'),
    'w04764': ('импровизировать', 'doğaçlama yapmak'),
    'w04765': ('уборщица', 'temizlikçi (kadın)'),
    'w04782': ('благополучие', 'refah, iyilik hali'),
    'w04788': ('оса', 'eşek arısı, yaban arısı'),
    'w04798': ('справочник', 'rehber, kılavuz'),
    'w04800': ('бывало', 'eskiden olurdu, vaktiyle'),
    'w04808': ('поселение', 'yerleşim, yerleşke'),
    'w04813': ('таз', 'leğen; kalça/pelvis'),
    'w04821': ('распорядиться', '(bir şeyi) kullanmak, değerlendirmek'),
    'w04827': ('американка', 'Amerikalı kadın'),
    'w04831': ('дожидаться', 'beklemek'),
    'w04833': ('дуэт', 'düet'),
    'w04836': ('покрытие', 'kaplama'),
    'w04845': ('шрифт', 'yazı tipi, font'),
    'w04848': ('кисть', 'fırça; el'),
    'w04859': ('покорный', 'itaatkâr, boyun eğen'),
    'w04861': ('промежуток', 'aralık, ara'),
    'w04864': ('подобие', 'benzerlik, suret'),
    'w04865': ('завербовать', 'işe almak, örgüte katmak'),
    'w04867': ('ботаник', 'botanikçi; (argo) inek'),
    'w04870': ('ручной', 'elle yapılan, el ile ilgili'),
    'w04872': ('вспотеть', 'terlemek'),
    'w04879': ('упор', 'dayanak, vurgu'),
    'w04881': ('посвящать', 'ithaf etmek, adamak'),
    'w04891': ('баллон', 'tüp, silindir'),
    'w04892': ('возбуждённый', 'heyecanlı, gergin'),
    'w04895': ('превосходить', 'üstün olmak, geçmek'),
    'w04906': ('питомец', 'evcil hayvan, besleme'),
    'w04921': ('сообщник', 'suç ortağı'),
    'w04922': ('зависимый', 'bağımlı'),
    'w04932': ('занавес', 'perde'),
    'w04939': ('хребет', 'sırt, sıradağ'),
    'w04942': ('логический', 'mantıksal, mantıki'),
    'w04945': ('восстанавливать', 'onarmak, yeniden inşa etmek'),
    'w04953': ('соломинка', 'pipet, saman çöpü'),
    'w04955': ('лось', 'Kanada geyiği/mus (elk)'),
    'w04968': ('поцарапать', 'çizmek, tırmalamak'),
    'w04971': ('излишний', 'gereksiz, fazla'),
    'w04976': ('расовый', 'ırksal'),
    'w04981': ('червяк', 'solucan, kurtçuk'),
    'w04990': ('продукция', 'ürün, üretim'),
    'w04999': ('астма', 'astım'),
    'w05000': ('аннулировать', 'iptal etmek'),
    'w05001': ('низко', 'alçak, alçakta'),
    'w05006': ('объединение', 'birleşme, birleştirme'),
    'w05009': ('рюмка', 'kadeh, votka kadehi'),
    'w05010': ('чучело', 'kukla, korkuluk (bostan korkuluğu)'),
    'w05015': ('затрата', 'masraf, harcama'),
    'w05018': ('медуза', 'denizanası'),
    'w05020': ('молчаливый', 'sessiz, suskun'),
    'w05022': ('надоедливый', 'can sıkıcı, sinir bozucu, bezdirici'),
    'w05024': ('пожирать', 'yutmak, obur gibi yemek'),
    'w05032': ('эффективность', 'verimlilik, etkinlik'),
    'w05038': ('разочароваться', 'hayal kırıklığına uğramak'),
    'w05041': ('изложить', 'anlatmak, açıklamak'),
    'w05046': ('пристань', 'iskele, rıhtım'),
    'w05049': ('дрянной', 'berbat, adi, kalitesiz'),
    'w05055': ('постройка', 'yapı, bina, inşaat'),
    'w05064': ('пика', 'mızrak; zirve/doruk'),
    'w05065': ('пробел', 'boşluk'),
    'w05070': ('втроём', 'üçü birlikte, üç kişi'),
    'w05077': ('отрывать', 'koparmak, ayırmak, dikkatini dağıtmak'),
    'w05092': ('болт', 'cıvata'),
    'w05102': ('разделение', 'bölünme, ayrım'),
    'w05107': ('квалификация', 'yeterlilik, uzmanlık'),
    'w05113': ('неясный', 'belirsiz'),
    'w05121': ('противоречие', 'çelişki'),
    'w05129': ('двойка', 'iki (kart/not)'),
    'w05168': ('заря', 'şafak, seher'),
    'w05185': ('завязка', 'boğum, bağ'),
    'w05193': ('краденый', 'çalıntı, çalınmış'),
    'w05195': ('поддержание', 'sürdürme, devam ettirme'),
    'w05200': ('сборище', 'kalabalık, güruh'),
    'w05221': ('воскреснуть', 'dirilmek'),
    'w05225': ('езда', 'binme, biniş, sürüş'),
    'w05227': ('акр', 'akr'),
    'w05228': ('ягуар', 'jaguar'),
    'w05234': ('ремонтировать', 'tamir etmek, onarmak'),
    'w05242': ('накопить', 'biriktirmek'),
    'w05254': ('ль', 'soru eki (mi/mı)'),
    'w05272': ('понизить', 'alçaltmak, düşürmek'),
    'w05276': ('транс', 'trans'),
    'w05293': ('капать', 'damlamak'),
    'w05296': ('скетч', 'skeç'),
    'w05301': ('горожанин', 'şehirli, kentli'),
    'w05308': ('высказывание', 'ifade, söz, beyan'),
    'w05322': ('коммуникация', 'haberleşme, iletişim'),
    'w05323': ('побриться', 'tıraş olmak'),
    'w05341': ('насильственный', 'şiddet içeren, zorla yapılan'),
    'w05352': ('украшать', 'süslemek, donatmak'),
    'w05359': ('спутать', 'karıştırmak'),
    'w05363': ('республиканский', 'cumhuriyetçi'),
    'w05365': ('ограничить', 'sınırlamak, kısıtlamak'),
    'w05368': ('искусный', 'usta, hünerli, mahir'),
    'w05376': ('прилично', 'oldukça, gayet iyi'),
    'w05380': ('небрежный', 'dikkatsiz, özensiz'),
    'w05382': ('пропаганда', 'propaganda'),
    'w05386': ('мутация', 'mutasyon'),
    'w05387': ('скользить', 'kaymak, süzülmek'),
    'w05389': ('опрометчивый', 'düşüncesiz, tedbirsiz, aceleci'),
    'w05392': ('затопить', 'su basmak, sel basmak, batırmak'),
    'w05393': ('пышный', 'gösterişli, tantanalı'),
    'w05398': ('описанный', 'tarif edilen, anlatılan'),
    'w05403': ('кровопролитие', 'kan dökülmesi'),
    'w05407': ('этикетка', 'etiket'),
    'w05411': ('восхождение', 'tırmanış, çıkış'),
    'w05412': ('махинация', 'dalavere, hile'),
    'w05413': ('публиковать', 'yayımlamak'),
    'w05418': ('разложение', 'çürüme, ayrışma'),
    'w05432': ('ушибиться', 'berelenmek, kendini incitmek'),
    'w05436': ('избавление', 'kurtuluş, kurtulma'),
    'w05438': ('булка', 'çörek, francala'),
    'w05449': ('раздумье', 'düşünce, tereddüt'),
    'w05451': ('знающий', 'bilgili, bilen'),
    'w05472': ('изделие', 'ürün, mamul'),
    'w05485': ('гель', 'jel'),
    'w05488': ('раскаиваться', 'pişman olmak'),
    'w05491': ('кузов', 'kasa, gövde'),
    'w05508': ('дог', 'Büyük Dan (köpek cinsi)'),
    'w05514': ('непосредственно', 'doğrudan'),
    'w05521': ('созреть', 'olgunlaşmak'),
    'w05525': ('подошва', 'taban, ayakkabı tabanı'),
    'w05528': ('цемент', 'çimento'),
    'w05530': ('приблизить', 'yakınlaştırmak'),
    'w05531': ('изготовление', 'yapım, üretim'),
    'w05533': ('закругляться', 'toparlamak, sözü bitirmek'),
    'w05534': ('притяжение', 'çekim, yerçekimi'),
    'w05535': ('сообразительный', 'zeki, çabuk kavrayan'),
    'w05537': ('топить', 'ısıtmak, batırmak'),
    'w05544': ('сноб', 'snob'),
    'w05546': ('подражать', 'taklit etmek, özenmek'),
    'w05552': ('манекен', 'manken'),
    'w05582': ('смущённый', 'utanmış, mahcup'),
    'w05584': ('специфический', 'özgül, spesifik'),
    'w05589': ('чулан', 'depo odası, kiler'),
    'w05590': ('зачастую', 'sık sık, genellikle'),
    'w05597': ('шурин', 'kayınbirader'),
    'w05608': ('каток', 'buz pateni sahası, (yol) silindiri'),
    'w05611': ('предприниматель', 'girişimci'),
    'w05612': ('поверх', 'üstüne, üzerine'),
    'w05621': ('опираться', 'dayanmak, abanmak'),
    'w05622': ('почётный', 'fahri, şanlı'),
    'w05623': ('расширять', 'genişletmek'),
    'w05627': ('благополучный', 'sorunsuz, güvenli bir şekilde'),
    'w05628': ('штурвал', 'dümen'),
    'w05638': ('беспечный', 'kaygısız, tasasız'),
    'w05642': ('побуждение', 'dürtü, güdü'),
    'w05644': ('смятение', 'kargaşa, şaşkınlık'),
    'w05647': ('инсулин', 'insülin'),
    'w05648': ('спинка', 'sırt'),
    'w05658': ('груда', 'yığın, küme'),
    'w05662': ('изолированный', 'izole, tecrit edilmiş'),
    'w05665': ('котлета', 'köfte'),
    'w05677': ('язычник', 'putperest'),
    'w05680': ('беззаботный', 'tasasız, kaygısız'),
    'w05686': ('очаг', 'ocak, kaynak'),
    'w05693': ('заказчик', 'müşteri'),
    'w05694': ('чесать', 'kaşımak, taramak'),
    'w05698': ('потребление', 'tüketim'),
    'w05702': ('знамя', 'bayrak, sancak'),
    'w05706': ('губить', 'mahvetmek, yok etmek'),
    'w05712': ('угнетать', 'bunaltmak, ezmek'),
    'w05737': ('размножаться', 'çoğalmak, üremek'),
    'w05738': ('агония', 'can çekişme, ızdırap'),
    'w05741': ('качественный', 'kaliteli, nitelikli'),
    'w05745': ('кувшин', 'testi, sürahi'),
    'w05757': ('умышленный', 'kasıtlı, bilinçli'),
    'w05780': ('корочка', 'kabuk, (argo) kimlik/diploma'),
    'w05782': ('укрепление', 'güçlendirme, pekiştirme'),
    'w05792': ('вирусный', 'viral'),
    'w05820': ('монополия', 'tekel, monopol'),
    'w05843': ('зелень', 'yeşillik, sebze'),
    'w05849': ('штык', 'süngü'),
    'w05852': ('противостояние', 'karşıtlık, çatışma'),
    'w05855': ('охватывать', 'kapsamak, sarmak'),
    'w05867': ('значимость', 'önem, ehemmiyet'),
    'w05869': ('проститься', 'vedalaşmak, ayrılmak'),
    'w05884': ('весло', 'kürek'),
    'w05885': ('раздражённый', 'sinirlenmiş, tahriş olmuş'),
    'w05892': ('моргать', 'göz kırpmak, kırpıştırmak'),
    'w05894': ('преодолевать', 'üstesinden gelmek, aşmak'),
    'w05907': ('домогаться', 'taciz etmek, sarkıntılık etmek'),
    'w05927': ('пополнить', 'doldurmak, takviye etmek'),
    'w05934': ('перекрёсток', 'kavşak'),
    'w05946': ('лом', 'manivela, levye'),
    'w05951': ('хорёк', 'gelincik'),
    'w05954': ('плавный', 'akıcı, yumuşak'),
    'w05972': ('системный', 'sistemik, sistematik'),
    'w06000': ('бомбардировщик', 'bomba uçağı, bombardıman uçağı'),
    'w06007': ('активист', 'aktivist, eylemci'),
    'w06014': ('изобретатель', 'mucit, icatçı'),
    'w06017': ('неуверенный', 'kararsız, emin olmayan'),
    'w06020': ('новоселье', 'yeni eve taşınma partisi'),
    'w06028': ('неуравновешенный', 'dengesiz'),
    'w06034': ('импровизация', 'doğaçlama'),
    'w06044': ('актуальный', 'güncel'),
    'w06066': ('растяжка', 'esneme, germe'),
    'w06067': ('сближаться', 'yaklaşmak'),
    'w06075': ('яблоня', 'elma ağacı'),
    'w06083': ('философский', 'felsefi'),
    'w06094': ('обойма', 'şarjör'),
    'w06096': ('травмировать', 'travmatize etmek, travma yaşatmak'),
    'w06106': ('грызун', 'kemirgen'),
    'w06119': ('подписка', 'abonelik'),
    'w06127': ('фундаментальный', 'temel, esas'),
    'w06138': ('уменьшаться', 'azalmak, küçülmek'),
    'w06142': ('зрелость', 'olgunluk'),
    'w06160': ('плотность', 'yoğunluk'),
    'w06162': ('аккорд', 'akor'),
    'w06186': ('хомяк', 'hamster'),
    'w06191': ('скрипеть', 'gıcırdamak'),
    'w06194': ('морально', 'ahlaken, duygusal olarak'),
    'w06195': ('бронзовый', 'bronz'),
    'w06223': ('ударять', 'çarpmak, vurmak'),
    'w06237': ('лиана', 'sarmaşık'),
    'w06241': ('возникновение', 'ortaya çıkma, oluşum'),
    'w06242': ('косичка', 'saç örgüsü, örgü'),
    'w06243': ('итого', 'toplam, yekûn'),
    'w06270': ('существенно', 'önemli ölçüde, hatırı sayılır derecede'),
    'w06272': ('снабжение', 'tedarik, arz'),
    'w06299': ('приставка', 'ön ek, konsol'),
    'w06302': ('иммиграция', 'göç, dışarıdan göç'),
    'w06313': ('тау', 'tau'),
    'w06327': ('пудра', 'pudra, toz'),
    'w06334': ('внушение', 'telkin, ima'),
    'w06360': ('беспорядочный', 'düzensiz, karmakarışık'),
    'w06415': ('сплав', 'alaşım, akarsuda taşıma/rafting'),
    'w06422': ('гирлянда', 'ışık dizisi, süs zinciri'),
    'w06538': ('жокей', 'jokey'),
    'w06546': ('икона', 'ikon'),
    'w06575': ('окунь', 'levrek, tatlı su levreği'),
    'w06580': ('дипломатия', 'diplomasi'),
    'w06599': ('точить', 'bilemek, kemirmek'),
    'w06617': ('развалюха', 'külüstür, harabe'),
    'w06624': ('колотить', 'dövmek, vurmak'),
    'w06633': ('эмигрант', 'göçmen'),
    'w06637': ('консерватор', 'muhafazakâr'),
    'w06645': ('наёмный', 'ücretli, tutulmuş (işçi)'),
    'w06651': ('кирпичный', 'tuğladan yapılma, tuğla rengi'),
    'w06660': ('дегустация', 'tadım'),
    'w06662': ('гостеприимный', 'misafirperver, konuksever'),
    'w06675': ('фольга', 'folyo'),
    'w06680': ('усердие', 'gayret, azim'),
    'w06681': ('стаж', 'kıdem, iş deneyimi'),
    'w06684': ('составление', 'hazırlama, düzenleme'),
    'w06687': ('двухлетний', 'iki yıllık'),
    'w06692': ('выносливость', 'dayanıklılık'),
    'w06695': ('индюк', 'hindi'),
    'w06710': ('взаимность', 'karşılıklılık'),
    'w06729': ('отпрыск', 'yavru, evlat'),
    'w06743': ('произношение', 'telaffuz'),
    'w06748': ('конский', 'ata ait, at'),
    'w06770': ('подкупать', 'rüşvet vermek, ayartmak'),
    'w06772': ('девственный', 'bakir, el değmemiş'),
    'w06773': ('банджо', 'banjo'),
    'w06774': ('шнур', 'kordon, kablo'),
    'w06777': ('сток', 'akış, gider'),
    'w06784': ('бюст', 'büst, göğüs'),
    'w06789': ('нетрудный', 'kolay'),
    'w06790': ('вытекать', 'akmak, sonucu çıkmak'),
    'w06797': ('плавник', 'yüzgeç'),
    'w06802': ('разгром', 'yenilgi, bozgun'),
    'w06804': ('струя', 'fışkırma, akıntı'),
    'w06816': ('затаить', '(nefesini) tutmak, gizlemek'),
    'w06849': ('потреблять', 'tüketmek'),
    'w06875': ('сторожить', 'korumak, nöbet tutmak'),
    'w06876': ('настойчивость', 'ısrar, kararlılık'),
    'w06877': ('муженёк', 'kocacık, kocacığım'),
    'w06886': ('хитроумный', 'kurnaz, zekice tasarlanmış'),
    'w06888': ('двусторонний', 'iki taraflı, çift taraflı'),
    'w06890': ('урегулировать', 'çözmek, halletmek'),
    'w06891': ('карликовый', 'cüce, bodur'),
    'w06909': ('благосклонность', 'iyi niyet, destek/onay'),
    'w06920': ('пожарить', 'kızartmak'),
    'w06929': ('выполнимый', 'yapılabilir, gerçekleştirilebilir'),
    'w06947': ('убавить', 'kısmak, azaltmak'),
    'w06951': ('аномальный', 'anormal, sapkın'),
    'w06952': ('перечень', 'liste, döküm'),
    'w06956': ('обильный', 'bol, bereketli'),
    'w06958': ('веять', 'esmek, yaymak/hissettirmek'),
    'w06966': ('подачка', 'sadaka, bahşiş'),
    'w06971': ('посредственный', 'vasat, sıradan'),
    'w06978': ('радиационный', 'radyasyona ait, radyasyonel'),
    'w06988': ('впечатлительный', 'duyarlı, kolay etkilenen'),
    'w06994': ('телепатия', 'telepati'),
    'w07000': ('ломтик', 'dilim'),
    'w07013': ('ветреный', 'rüzgarlı'),
    'w07014': ('сужать', 'daraltmak'),
    'w07015': ('счётчик', 'sayaç'),
    'w07027': ('употребить', 'kullanmak, tüketmek'),
    'w07035': ('пухнуть', 'şişmek'),
    'w07038': ('отговаривать', 'vazgeçirmek, caydırmak'),
    'w07046': ('терпимость', 'tolerans'),
    'w07047': ('выстраиваться', 'dizilmek, sıralanmak'),
    'w07058': ('педиатрия', 'pediatri'),
    'w07061': ('стабилизатор', 'dengeleyici, stabilizatör'),
    'w07063': ('пешеход', 'yaya'),
    'w07066': ('финансировать', 'finanse etmek'),
    'w07069': ('негодование', 'öfke, kızgınlık'),
    'w07073': ('рассудить', 'hükmetmek, düşünmek'),
    'w07074': ('возбуждаться', 'uyarılmak, heyecanlanmak'),
    'w07095': ('насыпать', 'dökmek'),
    'w07120': ('смущение', 'mahcubiyet, utanma'),
    'w07124': ('устранять', 'ortadan kaldırmak, gidermek'),
    'w07125': ('претенциозный', 'iddialı, gösterişli'),
    'w07136': ('неописуемый', 'tarif edilemez, anlatılamaz'),
    'w07140': ('счёты', 'abaküs'),
    'w07149': ('выговорить', 'telaffuz etmek, dile getirmek'),
    'w07151': ('волдырь', 'kabarcık, su toplaması'),
    'w07171': ('безмолвный', 'sessiz, suskun'),
    'w07180': ('языческий', 'pagan'),
    'w07181': ('шаткий', 'sallanan, dengesiz'),
    'w07190': ('боксировать', 'boks yapmak'),
    'w07194': ('уморительный', 'gülünç, çok komik'),
    'w07212': ('прядь', 'tutam, lüle (saç teli)'),
    'w07226': ('азарт', 'heyecan, hırs'),
    'w07229': ('щёлкать', 'şaklatmak, çıtlatmak'),
    'w07238': ('маниакальный', 'manik, obsesif'),
    'w07248': ('колотиться', 'çarpmak (kalp için), güm güm vurmak'),
    'w07253': ('ударник', 'baterist, davulcu'),
    'w07254': ('похождение', 'macera'),
    'w07256': ('утроить', 'üç katına çıkarmak'),
    'w07260': ('беседка', 'çardak, kameriye'),
    'w07272': ('функционировать', 'işlev görmek, çalışmak'),
    'w07281': ('импульсный', 'darbeli, pulslu'),
    'w07284': ('тусклый', 'soluk, donuk'),
    'w07288': ('тренинг', 'eğitim, kurs'),
    'w07289': ('кат', 'cellat'),
    'w07295': ('тёлка', 'düve, (argo) hatun'),
    'w07300': ('псалом', 'mezmur, ilahi'),
    'w07303': ('возрастной', 'yaşa bağlı, yaş+'),
    'w07305': ('подливка', 'sos, salça'),
    'w07319': ('вишнёвый', 'vişne, vişne rengi'),
    'w07320': ('новелла', 'kısa hikâye, öykü'),
    'w07322': ('тигрица', 'dişi kaplan'),
    'w07325': ('наклонить', 'eğmek, yatırmak'),
    'w07331': ('излагать', 'anlatmak, ifade etmek'),
    'w07343': ('жонглировать', 'hokkabazlık yapmak'),
    'w07351': ('полнота', 'şişmanlık, dolgunluk'),
    'w07352': ('плотский', 'tensel, cismani'),
    'w07353': ('жизнеспособный', 'yaşayabilir, canlılığını sürdürebilen'),
    'w07360': ('обворожительный', 'büyüleyici, çekici'),
    'w07379': ('переродиться', 'yeniden doğmak, dönüşmek'),
    'w07380': ('ветеринарный', 'veteriner, veterinerlik+'),
    'w07389': ('чемпионка', 'şampiyon'),
    'w07405': ('коммуникационный', 'iletişimsel, iletişim+'),
    'w07408': ('озлобленный', 'kin dolu, öfkeli, hınçlı'),
    'w07412': ('стратег', 'stratejist'),
    'w07417': ('колючка', 'diken'),
    'w07418': ('впадина', 'çukur, girinti, kovuk'),
    'w07420': ('прогореть', 'batmak, iflas etmek'),
    'w07431': ('достаток', 'gönenç, refah'),
    'w07437': ('глас', 'ses'),
    'w07438': ('хвастун', 'palavracı, hava atan'),
    'w07450': ('газель', 'ceylan'),
    'w07455': ('учтивый', 'nazik, kibar'),
    'w07465': ('замахнуться', 'el kaldırmak (vurmak için)'),
    'w07468': ('опустошать', 'harap etmek, yakıp yıkmak'),
    'w07470': ('экспертный', 'uzman, uzmanlık+'),
    'w07473': ('вывесить', 'asmak, ilan etmek'),
    'w07479': ('таран', 'koçbaşı'),
    'w07482': ('испаряться', 'buharlaşmak'),
    'w07484': ('проговорить', 'konuşmak, söylemek'),
    'w07492': ('свежевать', '(hayvanın) derisini yüzmek'),
    'w07495': ('наполняться', 'dolmak'),
    'w07498': ('опрятный', 'temiz, düzenli'),
    'w07509': ('китаянка', 'Çinli kadın'),
    'w07516': ('стручок', 'kabuk, bakla'),
    'w07518': ('приближать', 'yaklaştırmak'),
    'w07523': ('батист', 'patiska, ince pamuklu kumaş'),
    'w07524': ('отсрочить', 'ertelemek'),
    'w07526': ('шорох', 'hışırtı'),
    'w07528': ('банальность', 'bayağılık, sıradanlık'),
    'w07533': ('сердить', 'kızdırmak, sinirlendirmek'),
    'w07534': ('бойкот', 'boykot'),
    'w07543': ('прижиматься', 'sokulmak, yapışmak'),
    'w07547': ('воздерживаться', 'kaçınmak'),
    'w07567': ('резьба', 'oyma, oyukla süsleme'),
    'w07568': ('трепать', 'gevezelik etmek, dedikodu yapmak'),
    'w07578': ('распущенный', 'gevşek ahlaklı, çapkın'),
    'w07583': ('завлечь', 'cezbetmek, çekmek'),
    'w07588': ('недоразвитый', 'az gelişmiş'),
    'w07589': ('пагубный', 'zararlı, yıkıcı'),
    'w07594': ('ископаемый', 'fosil'),
    'w07598': ('подсчитывать', 'hesaplamak, saymak'),
    'w07605': ('смышлёный', 'akıllı, zeki'),
    'w07609': ('липнуть', 'yapışmak'),
    'w07617': ('померить', 'ölçmek'),
    'w07621': ('жгут', 'turnike'),
    'w07623': ('туя', 'tuya (ağaç türü)'),
    'w07624': ('наклонный', 'eğik, meyilli'),
    'w07626': ('завораживать', 'büyülemek, mest etmek'),
    'w07628': ('бурлить', 'kaynamak, köpürmek'),
    'w07631': ('козявка', 'sümük (argo/çocuk dili)'),
    'w07638': ('нерешительный', 'kararsız, tereddütlü'),
    'w07643': ('познавать', 'tanımak, öğrenmek'),
    'w07644': ('резолюция', 'karar (örn. BM kararı)'),
    'w07648': ('шествие', 'yürüyüş, alay'),
    'w07649': ('ладья', 'sandal, kale (satranç taşı)'),
    'w07656': ('приподнять', 'kaldırmak'),
    'w07657': ('побуждать', 'teşvik etmek, harekete geçirmek'),
    'w07669': ('враждовать', 'husumet beslemek, çekişmek'),
    'w07670': ('мерцать', 'parıldamak, titreşerek ışımak'),
    'w07673': ('старинка', 'eski usul, eski tarz'),
    'w07676': ('питомник', 'yetiştirme çiftliği, kuluçkahane'),
    'w07681': ('распорядитель', 'yönetici, idareci'),
    'w07691': ('буде', 'eğer, ise'),
    'w07693': ('прочёсывать', 'taramak (bir bölgeyi)'),
    'w07695': ('вычурный', 'gösterişli, yapmacık'),
    'w07698': ('плодотворный', 'verimli, üretken'),
    'w07700': ('колыбельный', 'beşiğe ait, ninni'),
    'w07701': ('замер', 'ölçüm'),
    'w07706': ('инквизитор', 'engizisyoncu'),
    'w07708': ('тюбик', 'tüp'),
    'w07710': ('безмятежный', 'sakin, huzurlu'),
    'w07713': ('жало', 'iğne, uç'),
    'w07717': ('излишек', 'fazlalık, artık'),
    'w07723': ('шипеть', 'cızırdamak, tıslamak'),
    'w07728': ('бантик', 'fiyonk, küçük kurdele'),
    'w07729': ('конвейер', 'konveyör, taşıma bandı'),
    'w07735': ('объективность', 'nesnellik'),
    'w07741': ('сблизить', 'yakınlaştırmak'),
    'w07746': ('мировоззрение', 'dünya görüşü'),
    'w07756': ('обходительный', 'nazik, kibar'),
    'w07763': ('решительность', 'kararlılık, azim'),
    'w07770': ('авторитетный', 'saygın, güvenilir'),
    'w07777': ('толкование', 'yorum, açıklama'),
    'w07778': ('редактировать', 'düzenlemek, redakte etmek'),
    'w07779': ('маргаритка', 'papatya'),
    'w07782': ('макать', 'batırmak, daldırmak'),
    'w07795': ('диво', 'harika, mucize'),
    'w07812': ('выкачать', 'pompalamak, dışarı çekmek'),
    'w07814': ('сочувствующий', 'duygudaş, şefkatli'),
    'w07818': ('интервенция', 'müdahale'),
    'w07821': ('проронить', 'söylemek, ağzından kaçırmak'),
    'w07826': ('пристройка', 'ek bina'),
    'w07827': ('повергнуть', 'düşürmek, şoka sokmak'),
    'w07829': ('окорок', 'jambon, but eti'),
    'w07839': ('расценить', 'nitelendirmek, değerlendirmek'),
    'w07848': ('извилина', 'kıvrım (beyin), dönemeç'),
    'w07859': ('беспомощность', 'çaresizlik, güçsüzlük'),
    'w07866': ('многократный', 'tekrarlanan, defalarca olan'),
    'w07867': ('мироздание', 'evren, kâinat'),
    'w07868': ('товарищество', 'yoldaşlık, ortaklık'),
    'w07882': ('драматург', 'oyun yazarı'),
    'w07883': ('следование', 'izleme, bağlılık'),
    'w07884': ('свисать', 'sarkmak'),
    'w07895': ('плеть', 'kamçı, kırbaç'),
    'w07898': ('разовый', 'tek kullanımlık, bir kereye mahsus'),
    'w07901': ('отечь', 'şişmek'),
    'w07902': ('хоровой', 'koroya ait'),
    'w07904': ('кондуктор', 'kondüktör, biletçi'),
    'w07906': ('снадобье', 'ilaç, iksir'),
    'w07913': ('выявлять', 'ortaya çıkarmak, tespit etmek'),
    'w07917': ('заведующий', 'müdür, yönetici'),
    'w07927': ('известия', 'haberler'),
    'w07936': ('лысина', 'kellik, dazlak yer'),
    'w07938': ('продлевать', 'uzatmak, sürdürmek'),
    'w07944': ('писательство', 'yazarlık'),
    'w07949': ('язвительный', 'alaycı, iğneleyici'),
    'w07953': ('совокупность', 'bütün, toplam'),
    'w07954': ('арбитр', 'hakem'),
    'w07978': ('закрасить', 'boyamak, üzerini boyamak'),
    'w07982': ('белоснежный', 'karbeyaz, bembeyaz'),
    'w07983': ('рефери', 'hakem'),
    'w07987': ('приверженность', 'bağlılık, sadakat'),
    'w07992': ('изумление', 'hayret, şaşkınlık'),
    'w08016': ('саркастичный', 'alaycı, iğneleyici'),
    'w08020': ('детонация', 'infilak (etme), patlama'),
    'w08021': ('дознание', 'soruşturma'),
    'w08027': ('разгон', 'hızlanma, ivme'),
    'w08030': ('ударяться', 'çarpmak, vurmak'),
    'w08046': ('неумелый', 'beceriksiz'),
    'w08056': ('археология', 'arkeoloji'),
    'w08068': ('разгонять', 'dağıtmak, hızlandırmak'),
    'w08075': ('скандировать', 'slogan atmak'),
    'w08078': ('шлёпать', 'şaplak atmak, çırpmak'),
    'w08084': ('представительство', 'temsilcilik, temsil'),
    'w08089': ('опечатать', 'mühürlemek'),
    'w08091': ('сходный', 'benzer'),
    'w08094': ('ассортимент', 'çeşit, ürün yelpazesi'),
    'w08097': ('угнетение', 'zulüm, baskı'),
    'w08103': ('притеснять', 'baskı yapmak, ezmek'),
    'w08104': ('столетний', 'yüz yıllık, asırlık'),
    'w08105': ('компактный', 'küçük, derli toplu'),
    'w08106': ('чопорный', 'resmi, aşırı kurallara bağlı'),
    'w08109': ('каркас', 'çerçeve, iskelet (yapı)'),
    'w08112': ('зевака', 'meraklı seyirci, aylak'),
    'w08113': ('ценитель', 'hayran, uzman, değerbilir'),
    'w08116': ('раздражаться', 'sinirlenmek, tahriş olmak'),
    'w08120': ('гармоничный', 'uyumlu, ahenkli'),
    'w08124': ('уточнение', 'açıklama, netleştirme'),
    'w08146': ('эмигрировать', 'göç etmek, yurt dışına göç etmek'),
    'w08148': ('обрекать', 'mahkum etmek, mahvetmek'),
    'w08150': ('сладостный', 'tatlı, hoş, lezzetli'),
    'w08154': ('упорствовать', 'ısrar etmek, inat etmek'),
    'w08169': ('пляс', 'dans, oyun'),
    'w08172': ('суслик', 'yer sincabı'),
    'w08174': ('маскировать', 'gizlemek, kamufle etmek'),
    'w08179': ('зенит', 'başucu, doruk noktası'),
    'w08181': ('сваха', 'çöpçatan'),
    'w08196': ('лилипут', 'cüce'),
    'w08203': ('веснушка', 'çil'),
    'w08206': ('зубрить', 'ezberlemek'),
    'w08210': ('скатываться', 'yuvarlanmak, kaymak'),
    'w08218': ('кардинальный', 'temel, köklü, esaslı'),
    'w08220': ('коммутатор', 'santral, telefon santrali'),
    'w08226': ('вольность', 'özgürlük, serbestlik'),
    'w08241': ('изготовитель', 'üretici, yapımcı'),
    'w08244': ('конфигурация', 'yapılandırma, konfigürasyon'),
    'w08251': ('геройство', 'kahramanlık'),
    'w08253': ('пополнять', 'doldurmak, yenilemek'),
    'w08259': ('ластик', 'silgi'),
    'w08278': ('волчок', 'topaç'),
    'w08296': ('попрошайничать', 'dilenmek, dilencilik yapmak'),
    'w08304': ('осуществимый', 'gerçekleştirilebilir, mümkün'),
    'w08309': ('бронирование', 'rezervasyon'),
    'w08311': ('искалечить', 'sakatlamak, sakat bırakmak'),
    'w08318': ('навеселе', 'çakırkeyf, hafif sarhoş'),
    'w08329': ('клещи', 'pense; kene, akar'),
    'w08342': ('вставка', 'ekleme, ilave'),
    'w08343': ('стеречь', 'korumak, bekçilik yapmak, gözetmek'),
    'w08350': ('змейка', 'küçük yılan, fermuar'),
    'w08356': ('изгнанник', 'sürgün'),
    'w08357': ('стезя', 'yol (mecazi)'),
    'w08369': ('вразрез', 'aykırı, ters'),
    'w08374': ('буржуа', 'burjuva'),
    'w08375': ('бранить', 'azarlamak, paylamak'),
    'w08410': ('несметный', 'hesapsız, sayısız'),
    'w08420': ('атрибут', 'özellik, nitelik'),
    'w08430': ('резкость', 'netlik, keskinlik'),
    'w08447': ('комбайн', 'biçerdöver'),
    'w08453': ('трактат', 'inceleme, risale'),
    'w08461': ('ремесленник', 'zanaatçı, usta'),
    'w08500': ('хворост', 'çalı çırpı, dal'),
    'w08512': ('борщ', 'borş (çorba)'),
    'w08516': ('докладчик', 'konuşmacı, sunucu'),
    'w08528': ('застой', 'durgunluk, duraklama'),
    'w08529': ('агрегат', 'agregat, kitle'),
    'w08531': ('ёмкость', 'kap, kutu; kapasite'),
    'w08537': ('быстрота', 'hız, çabukluk'),
    'w08541': ('мять', 'buruşturmak, yoğurmak'),
    'w08556': ('прикарманить', 'cebe indirmek, aşırmak'),
    'w08559': ('осмысленный', 'anlamlı, bilinçli'),
    'w08567': ('плаха', 'kütük, cellat kütüğü (idam kütüğü)'),
    'w08568': ('остолоп', 'ahmak, budala, mankafa'),
    'w08593': ('гонение', 'zulüm, baskı, takibat'),
    'w08598': ('головокружительный', 'baş döndürücü'),
    'w08607': ('багет', 'baget, uzun ince ekmek (baguette)'),
    'w08610': ('вульгарно', 'kaba, bayağı'),
    'w08612': ('обогатить', 'zenginleştirmek'),
    'w08613': ('драгун', 'süvari askeri, dragon (asker)'),
    'w08616': ('штанина', 'pantolon paçası'),
    'w08617': ('основывать', 'kurmak, temellendirmek'),
    'w08629': ('кликать', 'tıklamak, seslenmek'),
    'w08643': ('цветение', 'çiçeklenme'),
    'w08644': ('акушерство', 'ebelik, doğum bilimi'),
    'w08645': ('бурундук', '(bir tür) sincap, çipmank'),
    'w08647': ('выборный', 'seçimle ilgili, seçilmiş'),
    'w08649': ('намазывать', 'sürmek'),
    'w08663': ('пианистка', 'piyanist (kadın piyanist)'),
    'w08670': ('посягательство', 'ihlal, saldırı, el atma'),
    'w08671': ('бессрочный', 'süresiz'),
    'w08680': ('уклад', 'yaşam düzeni, yapı'),
    'w08681': ('маринад', 'salamura, marine sosu'),
    'w08690': ('фольксваген', 'Volkswagen (marka)'),
    'w08697': ('предприимчивый', 'girişken, girişimci'),
    'w08712': ('адаптировать', 'adapte etmek'),
    'w08719': ('грохотать', 'gümbürdemek, gürlemek'),
    'w08725': ('дурман', 'tatula, sersemlik verici madde'),
    'w08728': ('лексика', 'kelime hazinesi, söz dağarcığı'),
    'w08732': ('логически', 'mantıklı bir şekilde, mantıksal olarak'),
    'w08734': ('порицать', 'kınamak, ayıplamak'),
    'w08738': ('смутьян', 'fesatçı, kışkırtıcı, arabozucu'),
    'w08744': ('отображать', 'yansıtmak, göstermek'),
    'w08757': ('амуниция', 'cephane, mühimmat'),
    'w08758': ('вздорный', 'saçma, mantıksız (ayrıca huysuz)'),
    'w08761': ('колодка', 'kalıp (ayakkabı kalıbı), fren pabucu'),
    'w08762': ('бесстрастный', 'ifadesiz, sakin'),
    'w08769': ('инсинуация', 'ima, kinaye'),
    'w08771': ('приклад', 'dipçik'),
    'w08793': ('хлопотать', 'uğraşmak, çabalamak'),
    'w08803': ('гуманист', 'hümanist'),
    'w08807': ('циркулировать', 'dolaşmak, devretmek'),
    'w08808': ('наследить', 'iz bırakmak'),
    'w08809': ('почерпнуть', 'edinmek, elde etmek'),
    'w08820': ('распутье', 'yol ayrımı, kavşak, dönüm noktası'),
    'w08821': ('глубь', 'derinlik'),
    'w08832': ('сведущий', 'bilgili, usta'),
    'w08834': ('терзаться', 'üzülmek, acı çekmek, kıvranmak'),
    'w08852': ('вязкий', 'yapışkan, koyu kıvamlı'),
    'w08856': ('бельмо', 'göz lekesi, göz perdesi'),
    'w08859': ('виток', 'tur, sarım, bobin turu'),
    'w08871': ('тучный', 'şişman, iri yapılı'),
    'w08895': ('аллегория', 'alegori, mecaz'),
    'w08896': ('окрестный', 'civar, çevredeki'),
    'w08899': ('обременительный', 'yük getiren, ağır'),
    'w08902': ('скреплять', 'birleştirmek, bağlamak'),
    'w08905': ('воспротивиться', 'karşı çıkmak, karşı koymak'),
    'w08910': ('зачеркнуть', 'üzerini çizmek, çizip iptal etmek'),
    'w08917': ('пион', 'şakayık (çiçek)'),
    'w08920': ('энергоснабжение', 'enerji tedariki, enerji temini'),
    'w08921': ('заглатывать', 'yutmak'),
    'w08928': ('корявый', 'çarpık, düzensiz (el yazısı)'),
    'w08929': ('изувечить', 'sakatlamak, organını bozmak'),
    'w08933': ('святотатство', 'kutsala saygısızlık, dinsizlik'),
    'w08934': ('раздражительность', 'sinirlilik, tahammülsüzlük'),
    'w08938': ('сглаз', 'nazar, kem göz'),
    'w08954': ('писарь', 'kâtip'),
    'w08961': ('константа', 'sabit'),
    'w08965': ('пересказ', 'yeniden anlatım, özet'),
    'w08966': ('обмундирование', 'üniforma, teçhizat'),
    'w08975': ('несговорчивый', 'uzlaşmaz, inatçı'),
    'w08976': ('окутать', 'sarmak, bürümek'),
    'w08982': ('полынь', 'pelin otu (yavşan otu)'),
    'w08984': ('вереск', 'funda'),
    'w08988': ('многообразие', 'çeşitlilik, çoğulluk'),
    'w08995': ('онемелый', 'hissiz, uyuşmuş'),
    'w08996': ('тягостный', 'ağır, acı verici'),
    'w08998': ('рьяный', 'gayretli, ateşli, hararetli'),
    'w08999': ('дуда', 'gayda, kaval (nefesli çalgı)'),
}

# Raporun aciklama ile ic ice yazdigi, otomatik ayiklanamayan
# satirlar. Ceviri kismi elle cikarildi.
REPORT5_MANUAL = {
    'w01839': ('столкнуться', 'çarpışmak, karşılaşmak'),
    'w03658': ('заблуждение', 'yanılgı, yanlış kanı'),
    'w04508': ('нехватка', 'eksiklik, yetersizlik'),
    'w04934': ('ласка', 'sevgi, okşama'),
    'w05374': ('неполный', 'eksik, tam olmayan'),
    'w05944': ('олива', 'zeytin ağacı'),
    'w06639': ('хозяйственный', 'ev işleriyle ilgili'),
    'w06652': ('сена', 'saman, kuru ot'),
    'w06750': ('забрасывать', 'doldurmak, yağdırmak'),
    'w06840': ('разбросать', 'dağıtmak, saçmak'),
    'w06918': ('артериальный', 'atardamarla ilgili'),
    'w07028': ('погодный', 'hava ile ilgili'),
    'w07075': ('подгонять', 'uydurmak, ayarlamak'),
    'w07240': ('пространственный', 'mekânsal, uzaysal'),
    'w07372': ('светло', 'açık (renk)'),
    'w07709': ('патриотический', 'yurtsever, vatansever'),
    'w08072': ('живчик', 'sperm hücresi, canlı kişi'),
    'w08294': ('реконструировать', 'yeniden inşa etmek'),
    'w08574': ('маневровый', 'manevra ile ilgili'),
    'w08626': ('агитировать', 'kışkırtmak, propaganda yapmak'),
    'w08668': ('худощавый', 'zayıf, ince yapılı'),
    'w08773': ('воспитанник', 'yetiştirilen kişi, öğrenci'),
    'w08880': ('истощать', 'tüketmek, güçten düşürmek'),
}

# Tur etiketi duzeltmesi. Raporun bes 'sifat olmali' iddiasi
# yanlisti (zaten adj); yalnizca bu biri gercekti.
REPORT5_POS = {
    'w02355': 'adj',
}

# BOLUM 2 yalnizca kimlik listesi verdi, duzeltme metni vermedi.
# Raporun somut olarak tarif ettigi dort vaka burada; geri kalan 563
# kayit icin duzeltilmis cumleler gerekiyor.
REPORT5_EXAMPLE = {
    'w00852': (
        'Прежде всего хочу выразить свою особую благодарность профессору Анне Коста.',
        "Başlamadan önce Profesör Anna Costa'ya en içten teşekkürlerimi sunmak istiyorum.",
    ),
    'w05856': (
        'Он умеет метать копьё.',
        'Mızrak atmayı biliyor.',
    ),
    'w07918': (
        'Дорога вывела нас на широкое плато.',
        'Yol bizi geniş bir platoya çıkardı.',
    ),
    'w08917': (
        'В саду расцвёл большой розовый пион.',
        'Bahçede büyük pembe bir şakayık açtı.',
    ),
}
