# -*- coding: utf-8 -*-
"""Sekizinci tur: dosya 5 (w04017-w04999) ve dosya 6 (w05022-w06026)
denetimi (2026-08-29). Onceki turlardaki gibi: kurtarilamayan ornekler
bos birakildi, supheli/sozluk-disi kayitlar cikarildi, dogru karsiligi
belirsiz tema hatalari temizlendi. Kaynak raporlarda yine ID kaymalari
vardi; yalnizca icerigi dogrulanabilen maddeler uygulandi, dogrulanamayan
(orn. w04924, w04373, w04419, w04439, w04306, w04309, w04322, w04346,
w04363, w04374, w04422, w04436, w04442) atlandi.
"""

# id -> (ru, yeni tr)
REPORT8_TR = {
    # Dosya 5, A (baslikla ilgisiz ornek -> baslik anlami degismedi)
    'w04036': ('косяк', 'balık sürüsü'),
    # Dosya 5, B
    'w04211': ('механик', 'tamirci, makinist'),
    'w04223': ('флора', 'bitki örtüsü'),
    'w04296': ('подмога', 'yardım'),
    'w04349': ('шкатулка', 'mücevher kutusu'),
    'w04654': ('нечистый', 'kirli, murdar'),
    'w04787': ('седой', 'beyaz saçlı'),
    'w04885': ('ломбард', 'rehinci dükkânı'),
    'w04934': ('ласка', 'şefkat, okşama'),
    'w04713': ('шип', 'diken'),
    'w04159': ('магнитный', 'manyetik'),
    'w04064': ('хлопать', '(kapıyı) çarpmak'),
    'w04367': ('курорт', 'tatil beldesi, kaplıca'),
    'w04595': ('восхищение', 'göğe alınma (dini terim)'),
    # Dosya 6, A
    'w05522': ('колода', 'deste'),
    'w05303': ('дворецкий', 'uşak'),
    'w05340': ('липовый', 'sahte, uydurma'),
    'w05474': ('опустошить', 'harap etmek'),
    'w05659': ('компетенция', 'yetki, yetkinlik'),
    'w05685': ('заурядный', 'sıradan, vasat'),
    'w05090': ('строение', 'yapı, bina'),
    'w05076': ('грубость', 'kabalık'),
    'w05373': ('банкрот', 'müflis, iflas etmiş'),
    'w05324': ('предрассудок', 'önyargı, batıl inanç'),
    'w05555': ('кривой', 'eğri, çarpık'),
    'w05897': ('грызть', 'kemirmek'),
    'w05936': ('хлопнуть', 'çarpmak, el çırpmak'),
    'w05955': ('трусость', 'korkaklık'),
    'w05975': ('кровожадный', 'kana susamış'),
    'w05980': ('монарх', 'hükümdar, monark'),
    'w05981': ('дротик', 'dart oku'),
    'w06013': ('череда', 'dizi, silsile'),
    'w05963': ('дробь', 'kesir'),
    'w05880': ('неустойчивый', 'dengesiz'),
    'w05883': ('эскиз', 'eskiz, taslak'),
    'w05965': ('ультразвук', 'ultrases'),
    'w06021': ('гитарист', 'gitarist'),
    'w05912': ('неопровержимый', 'çürütülemez, kesin'),
    'w05951': ('хорёк', 'kokarca (yaban gelinciği)'),
    'w05917': ('улучшать', 'geliştirmek'),
}

# id -> (yeni exRu, yeni exTr)
REPORT8_EXAMPLE = {
    # Dosya 5, C (anlam kaybı/uydurma)
    'w04022': ('С её помощью омлет не сделаешь.', 'Onunla omlet yapamazsın.'),
    'w04054': ('Я заварил щель, но клапан всё равно протекает.',
               'Çatlağı kapattım ama valf hâlâ sızdırıyor.'),
    'w04062': ('Король пытается отступать, но вражеская кавалерия окружает его с фланга.',
               'Kral geri çekilmeye çalışıyor ama düşman süvarisi onu yandan kuşatıyor.'),
    'w04070': ('Т.е. половинка, четвертинка — это просто и понятно.',
               'Yani yarım, çeyrek -- işte bunlar basit ve anlaşılır.'),
    'w04099': ('Мы должны упорно трудиться, чтобы способствовать миру во всём мире.',
               'Dünya barışına katkıda bulunmak için azimle çalışmalıyız.'),
    'w04101': ('Другой — с человеческой алчностью, или жадностью, если хотите.',
               'Diğeri ise insanoğlunun açgözlülüğüyle, ya da hırsıyla ilgili.'),
    'w04118': ('Она – лучшая лошадь в конюшне.', 'O, ahırdaki en iyi at.'),
    'w04128': ('Поэтому им приходится рыться в отбросах.',
               'Bu yüzden çöpleri karıştırmak zorunda kalıyorlar.'),
    'w04138': ('Они сообщают об убийствах, коррупции, болезнях, стихийных бедствиях.',
               'Cinayetler, yolsuzluk, hastalıklar ve doğal afetler hakkında haber veriyorlar.'),
    'w04143': ('Можем ли мы сидеть у костра без опаски?',
               'Korkmadan ateşin başında oturabilir miyiz?'),
    'w04180': ('В ней описывается состояние грешников в Судный день.',
               'Bu, günahkârların kıyamet gününde içinde bulunacağı durumu tasvir ediyor.'),
    'w04190': ('Осторожность не приблизит нас к цели, которую мы хотим достичь.',
               'Dikkatli olmak bizi ulaşmak istediğimiz hedefe yaklaştırmaz.'),
    'w04225': ('Канализация в их доме была внутри или снаружи?',
               'Evlerindeki kanalizasyon içeride mi yoksa dışarıda mıydı?'),
    'w04260': ('Я не разбирал их холодильник.', 'Onların buzdolabını sökmedim.'),
    'w04272': ('Мы наливаем ее в бутыли, замораживаем, а затем используем снова и снова.',
               'Onu şişelere dolduruyoruz, donduruyoruz, sonra tekrar tekrar kullanıyoruz.'),
    'w04369': ('Я не чокнутый. Я читал биографию Стива Джобса.',
               "Ben garip değilim. Steve Jobs'ın biyografisini okudum."),
    'w04473': ('Я называю это принципом Спортивного Внедорожника.',
               'Ben buna Spor Arazi Aracı prensibi diyorum.'),
    'w04488': ('Ярлыки вроде «середняки» и «сливки» звучат отовсюду.',
               '"Vasatlar" ve "kaymak tabaka" gibi etiketler her yerden duyuluyor.'),
    'w04494': ('Дом планировали отдать подрядчику для переделки под строительную площадку.',
               'Ev, inşaat alanına dönüştürülmek üzere bir müteahhide devredilmeyi planlıyordu.'),
    'w04514': ('Поэтому выбрать этот вариант было бы безответственно.',
               'Bu yüzden bu seçeneği tercih etmek sorumsuzca olurdu.'),
    'w04531': ('Герцогиня стала близкой подругой королевы Виктории до конца жизни.',
               "Düşes, ömrünün sonuna kadar Kraliçe Viktorya'nın yakın bir dostu oldu."),
    'w04542': ('Суд приговорил её к шести месяцам условно.',
               'Mahkeme onu altı ay ertelemeli hapis cezasına çarptırdı.'),
    'w04588': ('один из троих бездельников получает по башке — бах!',
               'Üç aylaktan biri kafasına darbe alıyor -- bam!'),
    'w04636': ('Можно заблуждаться и не быть при этом дураком.',
               'İnsan yanılabilir ve bu onu aptal yapmaz.'),
    'w04637': ('Утром было довольно-таки прохладно.', 'Bu sabah hava oldukça serindi.'),
    'w04668': ('Что если взрывающиеся бомбы — это своего рода будильник для нас?',
               'Ya patlayan bombalar bizim için bir tür alarm saatiyse?'),
    'w04679': ('Это интернет, взаимодействие и похвала, взятые вместе.',
               'Bu; internet, işbirliği ve övgünün bir araya gelmesiyle oluşuyor.'),
    'w04700': ('Дверь в моё сознание открывается, врывается поток энергии.',
               'Bilincimin kapısı açılıyor, içeri bir enerji akını doluyor.'),
    'w04701': ('Играли в настольные игры, жарили картошку, сражались в племенных войнах?',
               'Masa oyunları mı oynadılar, patates mi kızarttılar, yoksa kabile savaşları mı yaptılar?'),
    'w04721': ('Кому из присутствующих в зале свистели вслед незнакомцы?',
               'Salondakilerden kaçının arkasından bir yabancı ıslık çaldı?'),
    'w04742': ('Номер люкс в этом отеле - 400 кв.', 'Bu oteldeki süit oda 400 metrekare.'),
    'w04773': ('У ныне покойного мэра Джексона была схожая идея.',
               "Şimdi merhum olan Belediye Başkanı Jackson'ın da benzer bir fikri vardı."),
    'w04795': ('Она — ведущий археолог, работающий сейчас на острове Пасхи.',
               "O, şu anda Paskalya Adası'nda çalışan önde gelen bir arkeolog."),
    'w04797': ('Мартин Лютер назвал печатную прессу «высшей добродетелью Господа».',
               "Martin Luther matbaayı 'Tanrı'nın en yüce erdemi' olarak nitelendirmiştir."),
    'w04800': ('Со мной случилось нечто, чего раньше не бывало.',
               'Daha önce hiç yaşamadığım bir şey başıma geldi.'),
    'w04809': ('Мужские профессии стали важнее: они должны были расчищать землю, валить деревья, пахать.',
               'Erkeklerin işleri daha önemli hale geldi: arazi temizlemek, ağaç devirmek, toprağı sürmek zorundaydılar.'),
    'w04822': ('Кровные связи, предопределённые и упорядоченные.',
               'Kan bağları, önceden belirlenmiş ve düzenlidir.'),
    'w04842': ('Ребят, плохие новости. У нас хилера грохнули.',
               'Çocuklar, kötü haber. Şifacımızı gebertmişler.'),
    'w04863': ('Том — человек передовых взглядов.', 'Tom ileri görüşlü biridir.'),
    'w04871': ('Датой основания завода считается 1885 год, когда из Кизляра в Москву было привезено 236 вёдер коньяка.',
               "Fabrikanın kuruluş tarihi, Kizlyar'dan Moskova'ya 236 kova konyak getirildiği 1885 yılı olarak kabul edilir."),
    'w04928': ('Особенно же были удобны обе королевы: блондинка и брюнетка.',
               'Özellikle iki kraliçe elverişliydi: sarışın ve esmer.'),
    'w04940': ('Нам нужно было отскрести весь этот воск.',
               'Bütün bu balmumunu kazımamız gerekiyordu.'),
    'w04954': ('Так что я спросила внучку: «Ты будешь её носить?»',
               'Bu yüzden torunuma sordum: "Bunu giyecek misin?"'),
    # Dosya 5, E (yazim)
    'w04053': ('Как вам нравится это сочетание цветов?', 'Bu renk kombinasyonunu nasıl buluyorsunuz?'),
    'w04061': ('Заболевание ведет себя коварно.', 'Hastalık sinsice hareket eder.'),
    'w04079': ('Несколько более молодых клонов усеивают ландшафт позади неё.',
               'Arkasındaki alanı benekleyen birkaç daha genç klon var.'),
    'w04092': ('И наконец, этот продукт должен обладать избирательным действием.',
               'Ve son olarak, türe özgü bir etki istiyorsunuz.'),
    'w04104': ('Итак, прежде всего учёные выдвигают своё предположение — гипотезу.',
               'Öncelikle, bilim insanları kendi varsayımlarını -- yani hipotezlerini -- ortaya koyar.'),
    'w04121': ('Кто они? Жестокие убийцы или патриоты - защитники родины? Кто?',
               'Onlar kimdi? Acımasız katiller mi, yoksa vatanı savunan yurtseverler mi?'),
    'w04135': ('Том взял мою книгу с условием возврата вечером.',
               'Tom kitabımı akşam geri vermek üzere aldı.'),
    'w04480': ('Я наконец-то решила, что пора послушаться доктора.',
               'En sonunda doktorumun tavsiyesini dinlemeye karar verdim.'),
    'w04557': ('(Смех) Начальная цена была 99 пенсов, без предварительного заказа.',
               '(Kahkahalar) Açılış fiyatımız, ön sipariş olmaksızın 99 peniydi.'),
    'w04563': ('Они говорят, что наши воззрения создаются колдунами, и их, предположительно, тоже.',
               "Düşüncelerimizin büyücüler tarafından yaratıldığını söylüyorlar, muhtemelen kendilerininki de öyle."),
    'w04642': ('Я люблю творчество АББЫ.', "ABBA'nın yaratıcılığını seviyorum."),
    'w04656': ('Затем четыре лампочки с выключателем и даже предохранителем, собранным после законопроекта об электричестве.',
               'Sonra 4 lamba, anahtar ve hatta bir elektrik sayacı model alınarak yapılmış bir sigorta.'),
    'w04807': ('Мы сумели учредить военный трибунал, который занимался именно такими делами.',
               'Biz daha sonra bu tarz meselelerle ilgilenen bir savaş suçları mahkemesi kurmayı başardık.'),
    'w04855': ('Он пинает меня.', 'O beni tekmeliyor.'),
    'w04972': ('Где-то в Африке примат пошёл по саванне.',
               'Afrika\'da bir yerde bir primat büyük savanada yürümeye başladı.'),
    'w04979': ('Этот сверчок проглотил личинку гордиева червя, или волосатика.',
               'Bu cırcır böceği, at kılı solucanı (gordiyen kurt) larvasını yutmuştu.'),
    'w04987': ('Неаполь — крупнейший город в Южной Италии.', 'Napoli Güney İtalya\'nın en büyük şehridir.'),
    # Dosya 5, tekrarlanan hatalar
    'w04214': ('Кагебешники запретили Илоне открывать шторы во время парада.',
               "KGB yetkilileri İlona'nın geçit töreni sırasında perdeleri açmasını yasakladı."),
    'w04276': ('После посещения туалета Том обыкновенно руки не моет.',
               "Tom'un tuvalete girdikten sonra ellerini yıkama alışkanlığı yoktur."),
    'w04294': ('Чудо - это то, что его участие в авантюре успешно.',
               'Mucize, onun maceradaki katılımının başarılı olmasıdır.'),
    'w04353': ('Максима возбуждают девушки в чулках.', "Maksim'i çorap giyen kızlar tahrik ediyor."),
    'w04479': ('гробница была уничтожена в результате умышленного поджога.',
               'Mezar, kasıtlı bir kundaklama sonucu yok edilmişti.'),
    'w04780': ('После захватывающего убийства зеленоволосой Розы врачи бальзамируют её мазями для покойников.',
               "Yeşil saçlı Rosa'nın çarpıcı cinayetinin ardından, doktorlar onu ölüler için özel merhemlerle korudular."),
    'w04878': ('Пуганая ворона куста боится.', 'Ürkmüş karga çalıdan korkar.'),

    # --- Dosya 6 ---
    'w05650': ('Где экономические права приобретают большую ценность, чем политические.',
               'Ekonomik hakların siyasi haklardan daha değerli hale geldiği yerlerde.'),
    'w05997': ('Наши вопросы привели к необычному решению: налоговые льготы.',
               'Sorularımız bizi vergi indirimleri gibi beklenmedik bir çözüme yönlendirdi.'),
    'w05912': ('Но найти неопровержимые доказательства является очень сложной задачей.',
               'Ancak kesin kanıt bulmak çok zor bir iştir.'),
    'w05895': ('Это вырезка из бумаги длиной в девять ярдов.',
               'Bu, dokuz yarda uzunluğunda bir kağıt kupürü.'),
    'w05952': ('Ей никогда не приходилось прятаться под школьными партами.',
               'Okul sıralarının altına saklanmak zorunda hiç kalmadı.'),
    'w05922': ('Затем начинается следующий этап — толщина стенки клетки увеличивается.',
               'Daha sonra, hücre duvarının kalınlığı artmaya başlar.'),
    'w05956': ('Это было удивительно. Эти гигантские трубы, здоровенные кратеры.',
               'İnanılmazdı. Koca koca bacalar, kocaman kraterler.'),
    'w06025': ('Для сравнения, диаметр человеческих волос составляет около 50 микронов.',
               "Karşılaştırma için, insan saçının çapı yaklaşık 50 mikrondur."),
    'w06001': ('Сейчас я озвучу мысль, которая мне очень нравится.',
               'Şimdi çok sevdiğim bir düşünceyi dile getireceğim.'),
    'w05924': ('Эта клавиатура даёт нам средства для изучения музыкального процесса.',
               'Bu klavye, müzikal süreci araştırmamız için bize bir araç sağlıyor.'),
    'w05903': ('Эти мешочки всплывают на поверхность океана, где они разрываются.',
               'Bu torbacıklar okyanusun yüzeyine çıkar ve orada patlarlar.'),
    'w05917': ('В то же время они улучшают свою экономику.', 'Aynı anda ekonomilerini geliştiriyorlar.'),
    'w05290': ('Он сделал намного больше - попросту не замечал её.',
               'O çok daha fazlasını yaptı -- onu fark bile etmedi.'),
    'w05473': ('Существует множество религиозных верований и суеверий, связанных с духами умерших людей.',
               'Ölmüş insanların ruhlarıyla ilgili pek çok dini inanç ve batıl inanç vardır.'),
    'w05494': ('Посетители аттракциона могут испытать не только прилив адреналина, но также головокружение и укачивание.',
               'Bu atraksiyonun ziyaretçileri yalnızca adrenalin dolu bir deneyim değil, aynı zamanda baş dönmesi ve mide bulantısı da yaşayabilir.'),
    'w05617': ('В 1848 году стал пашой Египта, однако вскоре скончался.',
               '1848 yılında Mısır paşası oldu, ancak kısa süre sonra öldü.'),
    'w05646': ('Специалист в области экспериментальной аэродинамики и баллистики.',
               'Deneysel aerodinamik ve balistik alanında uzman.'),
    'w05669': ('ДжХ: Значит, Вы не властелин этих сил.', 'JH: Yani bu güçlerin efendisi değilsin.'),
    'w05988': ('Первое. Нельзя ставить реакторы на разломах тектонических плит.',
               'Birincisi: Reaktörleri tektonik levha fay hatları üzerine kurmamalıyız.'),
    'w06000': ('Бомбардировщики нанесли прицельный удар по заранее разведанным целям.',
               'Bombardıman uçakları, önceden tespit edilen hedeflere isabetli darbeler indirdi.'),
    # Dosya 6, D (yazim)
    'w05028': ('В наши дни она выдерживает 2000 циклов заряд-разряд.',
               'Günümüz bataryaları 2 bin kez kullanılabiliyor.'),
    'w05041': ('Пример. «Пожалуйста, изложите нам процесс выставления счёта больнице.»',
               'Örnek: Lütfen bize hastaneye fatura keserken izlenen süreci anlatın.'),
    'w05101': ('В результате патентные тролли находят щели для существования.',
               'Sonuç olarak patent trolleri bu boşlukta yaşamlarını sürdürüyorlar.'),
    'w05322': ('Это коммуникация внутри вас нарушилась, в некотором роде.',
               'Vücudunuzdaki bu iletişim bir şekilde karışmış.'),
    'w05368': ('Это были просто маленькие, искусно расположенные пятна краски.',
               'Sadece ustaca ve sanatsal biçimde yerleştirilmiş küçük boya lekeleriydi.'),
    'w05576': ('Эти высказывания были замечены консервативным архиепископом Мексики.',
               'Bu konuşma, Meksika Başpiskoposluğunun dikkatini çekti.'),
    'w05612': ('В конце концов, это было разрушение поверх разрушения.',
               'Sonuçta bu, her biri bir sonrakine bir şeyler ekleyen bir yıkımdı.'),
    'w05716': ('"то еще может есть на завтрак фанатка фастфуда?',
               'Fast food düşkünü bir kadın kahvaltıda başka ne yer?'),
    'w05169': ('Мой тренер ест 6000 калорий в день.', 'Antrenörüm günde 6000 kalori yiyor.'),
    'w05262': ('Я не люблю архитектуру.', 'Mimarlığı sevmiyorum.'),
    'w05893': ('(Смех в зале) Их задача была ассистировать в лаборатории.',
               '(Kahkahalar) Onları işe aldık, ekipler kurduk, laboratuvarda asistanlık yaptık.'),
    'w06011': ('И это был доктор Ватсон, исполняющий песню «Тенистая роща»',
               '"Shady Grove (Gölgeli Koruluk)" adlı parçayı çalıp söyleyen Doc Watson\'dı.'),
    'w06015': ('Несколько лет назад, я ездила в Таиланд медитировать.',
               'Birkaç yıl önce meditasyon yapmak için Tayland\'a gittim.'),
    'w05963': ('Затем мы перешли к внушавшим ужас обычным дробям.',
               'Sonra korkutucu adi kesirlere geçtik.'),
    # Dosya 6, F (Rusca)
    'w05551': ('Аорта — самая крупная артерия человеческого организма.',
               'Aort, insan vücudundaki en büyük arterdir.'),
    'w05964': ('Я не обвешан боеприпасами и не повязываю красную бандану,',
               'Ben göğsüme çaprazlama cephane kemerleri takıp kırmızı bandana giymiyor olabilirim'),
    'w05919': ('Римляне обращались к курам за советом, словно к оракулам.',
               'Romalılar, kâhinlere danışır gibi tavuklara danışırlardı.'),
    'w05985': ('Хитрая колдунья выходила Вяйнямёйнена, но потребовала вознаграждение за возможность вернуться домой.',
               "Kurnaz cadı, Väinämöinen'i tekrar sağlığına kavuşturdu ama karşılığında eve dönme hakkı istedi."),
    # Dosya 6, tekrarlanan hatalar
    'w05561': ('Для меня быть доктором - это не профессия, это призвание.',
               'Benim için doktor olmak bir meslek değil, bir çağrıdır.'),
    'w05663': ('Остальные 99 999 километров приносят питательные вещества и уносят отходы.',
               'Kalan 99.999 kilometre ise besin taşır ve atıkları uzaklaştırır.'),
    'w05719': ('Александр выставил на торги акции своей компании.',
               'Aleksandr, şirketinin hisselerini satışa çıkardı.'),
    'w05705': ('Знаменитая русская балерина Анна Павлова была чувашкой.',
               'Ünlü Rus balerini Anna Pavlova bir Çuvaştı.'),
    'w05191': ('Потому что недостаточно сместить лидера, правителя или диктатора.',
               'Çünkü bir lideri, hükümdarı ya da diktatörü devirmek yeterli değil.'),
    'w05046': ('Это не коммерческая пристань.', 'Bu, ticari bir iskele değil.'),
}

# id -> (ru, yeni ru) -- kucuk harfli ozel isimler
REPORT8_RU = {
    'w05962': ('брюссель', 'Брюссель'),
    'w05974': ('ливия', 'Ливия'),
    'w06002': ('румыния', 'Румыния'),
    'w04987': ('неаполь', 'Неаполь'),
}

# Baslikla ilgisi olmayan / kurtarilamayan ornekler: bos birak.
REPORT8_CLEAR_EXAMPLE = {
    # Dosya 5, A (kelimeyle ilgisiz ornek - ses/yazim benzerligi ya da
    # ozel isimle karisma)
    'w04083', 'w04110', 'w04103', 'w04464', 'w04644', 'w04655', 'w04674',
    'w04247', 'w04917', 'w04154', 'w04102', 'w04476', 'w04754',
    # Dosya 5, D (kirik/parcali cumleler)
    'w04047', 'w04066', 'w04096', 'w04113', 'w04125', 'w04133', 'w04144',
    'w04192', 'w04216', 'w04255', 'w04264', 'w04271', 'w04357', 'w04364',
    'w04468', 'w04486', 'w04506', 'w04553', 'w04555', 'w04575', 'w04593',
    'w04603', 'w04605', 'w04621', 'w04624', 'w04630', 'w04715', 'w04717',
    'w04761', 'w04803', 'w04823', 'w04850', 'w04857', 'w04873', 'w04888',
    'w04892', 'w04912', 'w04916', 'w04927', 'w04932', 'w04944', 'w04966',
    # Dosya 6, B (baslikla ilgisiz ornek)
    'w05060', 'w05508', 'w05564', 'w05565', 'w05681', 'w05629', 'w05977',
    'w05944', 'w05923', 'w05887', 'w05889', 'w05899', 'w05093', 'w05201',
    'w05938', 'w05953', 'w05969',
}

# Sozluk girdisi olarak sorunlu / gurultu: cikar.
REPORT8_DROP = {
    'w04147',  # lya (nota harfi, ornek yok)
    'w04269',  # gud (argo, ornek yok)
    'w04483',  # mu (ses taklidi, ornek yok)
    'w04515',  # ar (birim, ornek yok)
    'w04882',  # om (birim, ornek yok)
    'w04730',  # rey (rey/reya ile ayni anlamin tekrari, ornek yok)
    'w05254',  # l' (soru eki, sozcuk degil, ornek yok)
    'w05277',  # der'movıy (kufurlu sifat, ornek yok)
    'w05707',  # myau (ses taklidi, ornek yok)
}

# Tema yanlis isaretlenen ve halen bos olmayan kayitlar temizlendi.
REPORT8_CLEAR_THEME = {
    'w04027', 'w04102', 'w04157', 'w04177', 'w04188', 'w04259', 'w04315',
    'w04502', 'w04766', 'w04829', 'w04870', 'w04154', 'w04208', 'w04333',
    'w04474', 'w04541', 'w04596', 'w04666', 'w04759', 'w04810', 'w04246',
    'w04326', 'w04552', 'w04641', 'w04721', 'w04120', 'w04132', 'w04827',
    'w04879', 'w04917', 'w04115', 'w04371', 'w04545', 'w04574', 'w04646',
    'w04700', 'w04906', 'w04939', 'w04077', 'w04082', 'w04126', 'w04271',
    'w04777', 'w04898', 'w04098', 'w04139', 'w04671', 'w04955', 'w04542',
    'w04616', 'w04742', 'w04845', 'w04648', 'w04654', 'w04195', 'w04366',
    'w04415', 'w04771', 'w04912', 'w04031', 'w04052', 'w04093', 'w04146',
    'w04194', 'w04236', 'w04257', 'w04534', 'w04618', 'w04626', 'w04710',
    'w04724', 'w04774', 'w04784', 'w04791', 'w04836', 'w04838', 'w04891',
    'w04930', 'w04931', 'w04935', 'w04957', 'w04674', 'w04036',
    'w05902', 'w05898', 'w05926', 'w05933', 'w05938', 'w05943', 'w05946',
    'w05916', 'w06004', 'w05959', 'w05971', 'w05982', 'w05975', 'w05883',
    'w05989', 'w05999', 'w05993', 'w05917', 'w06013', 'w05373', 'w05555',
}
